Repository cupy/cupy, pull requests merged in 2018-02, with the labels that each got.

#943 nestead -> nested
  cupy/cuda/nvtx.pyx
Labels: document, to-be-backported

#934 Use __dealloc__ in memory object
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: enhancement

#947 [backport] nestead -> nested
  cupy/cuda/nvtx.pyx
Labels: backport, document

#899 Support wheel build
  .gitignore
  cupy_setup_build.py
  setup.py
Labels: install

#948 Use https in supported websites
  cupy/__init__.py
  cupy/binary/__init__.py
  cupy/core/core.pyx
  cupy/creation/__init__.py
  cupy/cuda/memory.pyx
  cupy/indexing/__init__.py
  cupy/io/__init__.py
  cupy/linalg/__init__.py
  cupy/linalg/solve.py
  cupy/logic/__init__.py
  cupy/manipulation/__init__.py
  cupy/math/__init__.py
  cupy/padding/__init__.py
  cupy/sorting/__init__.py
  cupy/statistics/__init__.py
  cupy_setup_build.py
  docs/source/conf.py
  docs/source/contribution.rst
  docs/source/install.rst
  docs/source/overview.rst
  docs/source/reference/routines.rst
  docs/source/tutorial/basic.rst
Labels: document

#938 Add forward/backward support for cuDNN clipped ReLU and ELU
  cupy/cuda/cudnn.pxd
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: feature, st:test-and-merge

#936 [backport]Fix scalar broadcast
  cupy/core/core.pyx
  cupy/core/elementwise.pxi
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: backport, bug

#951 Remove unnecessary code in cupy.fft
  cupy/fft/fft.py
Labels: enhancement

#953 add --cupy-long-description option to inject long description for wheels
  cupy_setup_build.py
  setup.py
Labels: install, st:test-and-merge

#825 Implement isclose
  cupy/__init__.py
  cupy/logic/comparison.py
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: feature, st:awaiting-response

#763 Improve cupy.partition performance
  cupy/core/core.pyx
  cupy/sorting/sort.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: enhancement

#724 Simplify __getitem__ and __setitem__
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: enhancement

#958 Simplify chained comparisions
  cupy/cuda/memory_hooks/line_profile.py
  cupy/testing/attr.py
Labels: enhancement, st:test-and-merge

#957 Prefer double quoted docstring to single quoted docstring
  cupy/linalg/decomposition.py
  cupy/linalg/solve.py
  examples/cg/cg.py
  examples/gmm/gmm.py
Labels: st:test-and-merge

#956 Prefer data type objects over character codes
  docs/source/reference/difference.rst
  docs/source/tutorial/kernel.rst
Labels: enhancement, st:test-and-merge, to-be-backported

#954 implement environment check
  cupy/__init__.py
  cupy/_environment_check.pyx
  cupy_setup_build.py
Labels: feature

#963 [backport] Prefer data type objects over character codes
  docs/source/reference/difference.rst
  docs/source/tutorial/kernel.rst
Labels: backport, enhancement

#961 [backport] Simplify chained comparisions
  cupy/cuda/memory_hooks/line_profile.py
  cupy/testing/attr.py
Labels: backport, enhancement

#962 [backport] Prefer double quoted docstring to single quoted docstring
  cupy/linalg/decomposition.py
  cupy/linalg/solve.py
  examples/cg/cg.py
  examples/gmm/gmm.py
Labels: backport, enhancement

#955 add wheels to installation guide
  docs/source/install.rst
Labels: document

#916 Fix multithread bug with CUDA driver API
  cupy/cuda/function.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: bug, to-be-backported

#870 Simplify fp16 code in carray.cuh
  cupy/core/include/cupy/carray.cuh
Labels: enhancement, st:test-and-merge

#972 [backport] Fix multithread bug with CUDA driver API
  cupy/cuda/function.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, bug

#980 fix to use rpath only when wheel libs are specified
  cupy_setup_build.py
Labels: install

#981 Use current stream in array method
  cupy/core/core.pyx
  cupy/cuda/stream.pxd
  cupy/cuda/stream.pyx
Labels: enhancement, to-be-backported

#758 Fix overflow in indices when indexing
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: bug, st:test-and-merge, to-be-backported

#950 Use nogil in FFT
  cupy/cuda/cufft.pyx
Labels: enhancement

#975 Add destroy method to NcclCommunicator
  cupy/cuda/nccl.pyx
Labels: feature

#989 Use default stream in _scatter_op
  cupy/core/core.pyx
Labels: enhancement

#884 add upgrade guide for v2 & v4
  docs/source/index.rst
  docs/source/upgrade.rst
Labels: document, to-be-backported

#990 [backport] add upgrade guide for v2 & v4
  docs/source/index.rst
  docs/source/upgrade.rst
Labels: backport, document, st:test-and-merge

#978 Fix ndarray.diagonal to accept appropriate argument of axis2
  cupy/core/core.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: bug, st:test-and-merge, to-be-backported

#971 Fix slow test
  tests/cupy_tests/core_tests/test_carray.py
  tests/cupy_tests/core_tests/test_core.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: test

#984 [backport] Fix overflow in indices when indexing
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: backport, bug, st:test-and-merge

#995 [backport] Fix sum test to avoid contiguousness difference between CuPy and NumPy
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: backport, test

#992 [backport] Fix ndarray.diagonal to accept appropriate argument of axis2
  cupy/core/core.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: backport, bug

#998 Fix eliminate zeros
  cupy/sparse/coo.py
  cupy/sparse/csr.py
  tests/cupy_tests/sparse_tests/test_coo.py
Labels: bug, to-be-backported

#996 remove unnecessary heading from reference
  docs/source/reference/index.rst
Labels: document

#997 Support CUDA 9.1
  docs/source/install.rst
  install/build.py
Labels: install

#869 [backport] Fix return type of linalg.norm for complex input
  cupy/linalg/norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: backport, bug, st:test-and-merge

#949 Improve concatenate and other functions
  cupy/core/core.pyx
  cupy/core/internal.pyx
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: enhancement
