Repository cupy/cupy, pull requests merged in 2018-08, with the labels that each got.

#1506 Avoid compile error in old GCC (CentOS6)
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
  cupy/core/reduction.pxi
  cupy_setup_build.py
Labels: bug, install, st:test-and-merge, to-be-backported

#1508 [backport] Use CScalar in elementwise and reduction
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
  cupy/core/elementwise.pxi
  cupy/core/reduction.pxi
Labels: backport, enhancement, performance

#1515 Use collections.abc to avoid DeprecationWarning in Python 3.7
  cupy/core/internal.pyx
  cupy/linalg/product.py
  cupy/util.pyx
Labels: enhancement

#1516 [backport] Avoid compile error in old GCC (CentOS6)
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
  cupy/core/reduction.pxi
  cupy_setup_build.py
Labels: backport, bug, install

#1504 Fix cupy.real and cupy.imag
  cupy/core/fusion.py
  cupy/math/arithmetic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: bug, numpy-compat

#1517 [backport] Use collections.abc to avoid DeprecationWarning in Python 3.7
  cupy/core/internal.pyx
  cupy/linalg/product.py
  cupy/util.pyx
Labels: backport, enhancement

#946 Reduce GPU device object
  cupy/core/core.pyx
  cupy/core/dlpack.pyx
  cupy/core/elementwise.pxi
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/cuda_tests/test_pinned_memory.py
Labels: enhancement, st:test-and-merge

#1511 Fix thrust memory allocation problem
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/cupy_thrust.h
  cupy/cuda/thrust.pyx
Labels: bug, to-be-backported

#1519 Fix docstring about free_all_free
  cupy/cuda/memory.pyx
Labels: document

#1521 Update agnostic code tutorial
  docs/source/tutorial/basic.rst
Labels: document

#1526 Add .pytest_cache/ to .gitignore
  .gitignore
Labels: to-be-backported

#1513 Add `cupyx.scipy.get_array_module`
  cupyx/scipy/__init__.py
  docs/source/reference/generic.rst
  docs/source/reference/ndarray.rst
  tests/cupyx_tests/scipy_tests/test_get_array_module.py
Labels: feature, st:test-and-merge

#1144 __cuda_array_interface__ implementation
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: feature, st:awaiting-response

#1501 Support `nonzero` for complex types
  cupy/core/core.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: enhancement

#1514 Fix unit test errors in NumPy 1.15
  cupy/core/core.pyx
  cupy/manipulation/rearrange.py
  cupy/statistics/histogram.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: enhancement, numpy-compat, to-be-backported

#1477 Avoid hacking: Use the same test settings as Chainer
  .flake8.cython
  .travis.yml
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  cupy/linalg/einsum.py
  docs/source/contribution.rst
Labels: enhancement, test, to-be-backported

#1525 [backport] Fix thrust memory allocation problem
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/cupy_thrust.h
  cupy/cuda/thrust.pyx
Labels: backport, bug, st:test-and-merge

#1536 [backport] Avoid hacking: Use the same test settings as Chainer
  .flake8.cython
  .travis.yml
  cupy/__init__.py
  cupy/core/core.pyx
  cupy/cuda/cublas.pyx
  cupy/cuda/cudnn.pyx
  cupy/cuda/cufft.pyx
  cupy/cuda/curand.pyx
  cupy/cuda/cusolver.pyx
  cupy/cuda/cusparse.pyx
  cupy/cuda/function.pyx
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  cupy/cuda/nccl.pyx
  cupy/cuda/nvrtc.pyx
  cupy/cuda/runtime.pyx
  cupy/cuda/thrust.pyx
  cupy/cudnn.pyx
  docs/source/contribution.rst
Labels: backport, enhancement, test

#1537 Support `loop_prep` in ufunc
  cupy/core/elementwise.pxi
Labels: enhancement

#1549 [backport] Fix unit test errors in NumPy 1.15
  cupy/core/core.pyx
  cupy/manipulation/rearrange.py
Labels: backport, enhancement, numpy-compat

#1540 Add _has_memory_hooks to avoid thread local dictionary operation
  cupy/cuda/memory.pyx
  cupy/cuda/memory_hook.pxd
  cupy/cuda/memory_hook.pyx
Labels: performance

#1548 Add cdef and cpdef for better cythonize `core.pyx`
  cupy/core/core.pxd
  cupy/core/core.pyx
Labels: enhancement

#1503 Fix indexing behavior when input is zero-sized array
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: bug, numpy-compat, st:test-and-merge

#1507 Change type checking rules of Fusion ufuncs
  cupy/core/fusion.py
  cupyx/scipy/special/bessel.py
  tests/cupy_tests/core_tests/test_fusion.py
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
Labels: enhancement

#1551 Fix create_comparison
  cupy/core/core.pyx
Labels: bug, to-be-backported

#1546 Use xorshift128 to reduce global memory access
  cupy/random/_kernels.py
  cupy/random/generator.py
Labels: performance

#1522 Implement `cupy.allclose`
  cupy/__init__.py
  cupy/logic/comparison.py
  docs/source/reference/logic.rst
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: feature

#1496 [backport] Add upgrade guide for cupyx namespaces
  docs/source/upgrade.rst
Labels: backport, document

#1552 Raise error when trying to broadcast out_params in ElementwiseKernel
  cupy/core/elementwise.pxi
  tests/cupy_tests/core_tests/test_elementwise.py
Labels: bug, to-be-backported

#1556 [backport] Raise error when trying to broadcast out_params in ElementwiseKernel
  cupy/core/elementwise.pxi
  tests/cupy_tests/core_tests/test_elementwise.py
Labels: backport, bug

#1543 Improve view method performance
  cupy/core/core.pyx
Labels: performance

#1560 Add document to sqrt
  cupy/core/core.pyx
Labels: document

#1544 Improve memory pool performance
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: performance

#1559 Add cbrt
  cupy/__init__.py
  cupy/core/fusion.py
  cupy/math/misc.py
  tests/cupy_tests/core_tests/test_fusion.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: feature, st:test-and-merge

#1562 Add nan_to_num
  cupy/__init__.py
  cupy/core/fusion.py
  cupy/math/misc.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_misc.py
Labels: feature

#1075 Add sparse cholesky decompsition
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
  cupyx/__init__.py
  cupyx/linalg/__init__.py
  cupyx/linalg/sparse/__init__.py
  cupyx/linalg/sparse/solve.py
  setup.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: feature

#1570 Add erf, erfc, and erfcx to cupyx
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/erf.py
  docs/source/reference/special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_erf.py
Labels: feature

#1567 Fix docstring of modified bessel function
  cupyx/scipy/special/bessel.py
Labels: document

#1581 Fix cupy not working in thread other than one imported cupy
  cupy/core/fusion.py
Labels: bug, to-be-backported

#1584 Support cuDNN v7.2
  docs/source/install.rst
Labels: document

#1585 [backport] Fix cupy not working in thread other than one imported cupy
  cupy/core/fusion.py
Labels: backport, bug

#1573 Support SciPy1.0+
  cupy/testing/helper.py
  cupyx/scipy/sparse/compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: enhancement, test

#1577 Fix result dtypes of special functions
  cupyx/scipy/special/bessel.py
  cupyx/scipy/special/erf.py
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_erf.py
Labels: enhancement

#1580 Improve readability of reduction kernel (only python)
  cupy/core/reduction.pxi
Labels: enhancement

#1578 Improve usability of special functions
  cupyx/scipy/special/digamma.py
  cupyx/scipy/special/gamma.py
  cupyx/scipy/special/gammaln.py
  cupyx/scipy/special/zeta.py
Labels: enhancement, st:test-and-merge

#1568 Import scipy.special to use it in test
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_zeta.py
  tests/cupyx_tests/scipy_tests/test_get_array_module.py
Labels: st:test-and-merge, test

#1565 Add interoperability docs
  docs/source/reference/index.rst
  docs/source/reference/interoperability.rst
Labels: document, st:test-and-merge

#1554 Make ElementwiseKernel emit immutable in_params
  cupy/core/elementwise.pxi
  cupy/core/fusion.py
  cupy/core/reduction.pxi
  cupy/random/generator.py
Labels: enhancement, st:test-and-merge

#1591 [hotfix] [backport] Fix cupy not working in thread other than one imported cupy
  cupy/core/fusion.py
Labels: backport, bug

#1592 Reset cuda runtime error
  cupy/cuda/cupy_cuda.h
  cupy/cuda/runtime.pyx
Labels: bug, to-be-backported

#1571 Add ndtr
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/statistics.py
  docs/source/reference/special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: feature

#1589 Add test for thread use case of fusion
  tests/cupy_tests/core_tests/test_fusion.py
Labels: test, to-be-backported

#1555 Use bit operation when the divisor is a power of 2 on GPU
  cupy/core/include/cupy/carray.cuh
Labels: performance
