Repository cupy/cupy, pull requests merged in 2018-10, with the labels that each got.

#1606 Update ndimage to support SciPy 1.0+
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: numpy-compat, to-be-backported

#1632 add `cupy.random.wald`
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1671 [backport] Fix typo in docstring for cupy.linalg.slogdet
  cupy/linalg/norms.py
Labels: backport, document, st:test-and-merge

#1628 add `cupy.random.logseries`
  cupy/random/__init__.py
  cupy/random/_kernels.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1631 add `cupy.random.triangular`
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1665 Fix float16 nextafter
  cupy/core/include/cupy/carray.cuh
Labels: bug, to-be-backported

#1629 add `cupy.random.power`
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1635 add `cupy.random.negative_binomial`
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1637 add `cupy.random.noncentral_chisquare` & `cupy.random.noncentral_f`
  cupy/random/__init__.py
  cupy/random/_kernels.py
  cupy/random/distributions.py
  cupy/random/generator.py
  docs/source/reference/random.rst
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: feature

#1673 Improve floating point tests
  tests/cupy_tests/math_tests/test_floating.py
Labels: test

#1674 add complex support in solve
  cupy/cuda/cublas.pxd
  cupy/cuda/cublas.pyx
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
  cupy/linalg/solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: bug, takeover

#1680 Add licenses of distribution kernels from numpy
  cupy/random/_kernels.py
Labels: document, to-be-backported

#1679 Minor fixes to cupy.random tests
  tests/cupy_tests/random_tests/test_distributions.py
Labels: test, to-be-backported

#1681 Sort distribution kernels
  cupy/random/_kernels.py
Labels: enhancement

#1683 [backport] Add licenses of distribution kernels from numpy
  cupy/random/_kernels.py
Labels: backport, document

#1677 Mark slow `cupy.random` tests
  tests/cupy_tests/random_tests/test_generator.py
Labels: test

#1685 Fix math docs of cupy.random
  cupy/random/distributions.py
Labels: document

#1687 Tentatively skip failing `test_nextafter_combination`
  tests/cupy_tests/math_tests/test_floating.py
Labels: bug, test

#1678 Add more K-S tests
  tests/cupy_tests/random_tests/test_generator.py
Labels: test

#1682 Fix TestRandintDtype was slow
  tests/cupy_tests/random_tests/test_sample.py
Labels: st:test-and-merge, test, to-be-backported

#1693 [backport] Fix TestRandintDtype was slow
  tests/cupy_tests/random_tests/test_sample.py
Labels: backport, test

#1676 [backport] Fix float16 nextafter
  cupy/core/include/cupy/carray.cuh
Labels: backport, bug

#1478 Reorganize setup requirements
  .travis.yml
  appveyor.yml
  docs/source/contribution.rst
  setup.py
Labels: enhancement, test, to-be-backported

#1670 [backport] Update ndimage to support SciPy 1.0+
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: backport, numpy-compat, st:test-and-merge

#1697 Fix `ndarray.__iter__`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_iter.py
Labels: numpy-compat

#1696 [backport] Reorganize setup requirements
  .travis.yml
  appveyor.yml
  docs/source/contribution.rst
  setup.py
Labels: backport, enhancement, test

#1688 Fix cupy.random.hypergeometric
  cupy/random/_kernels.py
Labels: bug

#1700 Add header file generated by Cython to gitignore
  .gitignore
Labels: other, to-be-backported

#1705 [backport] Support `astype` in fused functions
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: backport, feature

#1684 Add float16 support for scatter_add
  cupy/core/core.pyx
  cupy/core/include/cupy/atomics.cuh
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
Labels: feature

#1702 Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15
  setup.cfg
Labels: st:test-and-merge, test, to-be-backported

#1708 [backport] Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15
  setup.cfg
Labels: backport, test

#1701 Use "x mod 1" to generate [0, 1)-uniform random
  cupy/random/generator.py
Labels: bug, st:test-and-merge, to-be-backported

#1710 [backport] Use "x mod 1" to generate [0, 1)-uniform random
  cupy/random/generator.py
Labels: backport, bug

#1704 [backport] Add header file generated by Cython to gitignore
  .gitignore
Labels: backport, other

#1712 [backport] Minor fixes to cupy.random tests
  tests/cupy_tests/random_tests/test_distributions.py
Labels: backport, test

#1718 Update einsum optimization routine
  cupy/linalg/einsum_opt.py
Labels: enhancement

#1709 [backport] Improve reduction code
  cupy/core/reduction.pxi
Labels: backport, bug, enhancement

#1707 Support float64 in scatter_add
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
Labels: feature

#1722 Drop support for CUDA 7.0 / 7.5
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: document, to-be-backported

#1717 Explain that -ftz=true affects nextafter
  cupy/math/floating.py
  tests/cupy_tests/math_tests/test_floating.py
Labels: document, st:test-and-merge, test, to-be-backported

#1727 Add workaround for numpy issue 12142
  cupy/core/core.pyx
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: bug, to-be-backported

#1728 Add support for NumPy 1.15 in docs
  docs/source/install.rst
Labels: document, to-be-backported

#1726 [backport] Drop support for CUDA 7.0 / 7.5
  docs/source/install.rst
  docs/source/upgrade.rst
Labels: backport, install

#1729 [backport] Add support for NumPy 1.15 in docs
  docs/source/install.rst
Labels: backport, document

#1730 [backport] Explain that -ftz=true affects nextafter
  cupy/math/floating.py
Labels: backport, document, test

#1731 [backport] Add workaround for numpy issue 12142
  cupy/core/core.pyx
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: backport, bug

#1739 Add Python 3.7 support to installation docs
  docs/source/install.rst
Labels: document, to-be-backported

#1742 [backport] Add Python 3.7 support to installation docs
  docs/source/install.rst
Labels: backport, document

#1743 Fix test for python 3.7
  cupy/random/generator.py
Labels: test, to-be-backported

#1744 [backport] Fix test for python 3.7
  cupy/random/generator.py
Labels: backport, test

#1740 Bump version to v6.0.0a1
  cupy/_version.py
Labels: install

#1741 Bump version to v5.0.0
  cupy/_version.py
Labels: install

#1749 Update intersphinx mapping of Chainer to stable
  docs/source/conf.py
Labels: document

#1622 Improve `_comparison_generator`
  docs/source/_comparison_generator.py
Labels: document

#1750 [backport] Improve `_comparison_generator`
  docs/source/_comparison_generator.py
Labels: backport, document

#1738 [backport] Workaround for test failure when Python 3.4 + SciPy 0.x + NumPy 0.15
  tests/cupyx_tests/__init__.py
Labels: backport, test

#1735 Add cuDNN pooling interface
  cupy/cudnn.pyx
Labels: enhancement, st:test-and-merge, to-be-backported

#1736 Add cuDNN softmax interface
  cupy/cudnn.pyx
Labels: enhancement, st:test-and-merge, to-be-backported

#1756 [backport] Add float16 support for scatter_add
  cupy/core/core.pyx
  cupy/core/include/cupy/atomics.cuh
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
Labels: backport, feature

#1759 Fix userspace kernel test failure in Windows
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: test, to-be-backported

#1755 Fix PendingDeprecationWarning when running test against NumPy 1.15
  setup.cfg
Labels: test, to-be-backported

#1762 [backport] Fix PendingDeprecationWarning when running test against NumPy 1.15
  setup.cfg
Labels: backport, test

#1761 [backport] Fix userspace kernel test failure in Windows
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: backport, test

#1763 [backport] Support float64 in scatter_add
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
Labels: backport, feature
