Repository cupy/cupy, pull requests merged in 2018-05, with the labels that each got.

#1180 Add cupy.average
  cupy/__init__.py
  cupy/statistics/meanvar.py
  docs/source/reference/statistics.rst
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: feature

#1207 [backport] Support complex constants and functions in fuse
  cupy/__init__.py
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: backport, enhancement, st:test-and-merge

#1227 [backport] Fix gitignore to exclude pyd files
  .gitignore
Labels: backport, other

#1228 Fix hacking version
  .travis.yml
Labels: st:test-and-merge, test, to-be-backported

#1124 fix cupy.diag() fails for array_likes other than CuPy arrays
  cupy/creation/matrix.py
  tests/cupy_tests/creation_tests/test_matrix.py
Labels: enhancement, to-be-backported

#1219 Free pooled memory when cufftMakePlan1d cannot allocate memory
  cupy/cuda/cufft.pyx
  tests/cupy_tests/fft_tests/test_fft.py
Labels: enhancement, to-be-backported

#1140 Implement unique
  cupy/__init__.py
  cupy/manipulation/add_remove.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: feature

#1205 [backport] Add constants
  cupy/__init__.py
Labels: backport, enhancement

#1211 Separate NVTX module for better Windows support
  cupy_setup_build.py
  install/build.py
Labels: install, to-be-backported

#1231 Fix matmul when inputs contain zero-sized array
  cupy/core/core.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: bug, to-be-backported

#875 Fix to preserve dtype of input array in cupy.linalg.norm
  cupy/linalg/norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: numpy-compat, to-be-backported

#1195 Implement triangular array creation routines
  cupy/__init__.py
  cupy/creation/matrix.py
  docs/source/reference/creation.rst
  tests/cupy_tests/creation_tests/test_matrix.py
Labels: feature

#1234 Fix naming of cufft.pyx
  cupy/cuda/cufft.pyx
Labels: enhancement, st:test-and-merge, to-be-backported

#1236 [backport] Free pooled memory when cufftMakePlan1d cannot allocate memory
  cupy/cuda/cufft.pyx
  tests/cupy_tests/fft_tests/test_fft.py
Labels: backport, enhancement

#1249 Fix file permissions
  cupy/__init__.py
  cupy/creation/matrix.py
  docs/source/reference/creation.rst
  tests/cupy_tests/creation_tests/test_matrix.py
Labels: enhancement, to-be-backported

#1241 Fix conversion from float16 to complex
  cupy/core/reduction.pxi
Labels: bug

#1244 [backport] Fix naming of cufft.pyx
  cupy/cuda/cufft.pyx
Labels: backport, enhancement

#1216 Fix 32-bit boundary test to support Windows
  tests/cupy_tests/core_tests/test_carray.py
Labels: test, to-be-backported

#1255 [backport] Fix 32-bit boundary test to support Windows
  tests/cupy_tests/core_tests/test_carray.py
Labels: backport, test

#1252 [backport] Fix conversion from float16 to complex
  cupy/core/reduction.pxi
Labels: backport, bug, st:test-and-merge

#1237 [backport] Separate NVTX module for better Windows support
  cupy_setup_build.py
  install/build.py
Labels: backport, install

#1209 Fix default dtype of full
  cupy/creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: bug, st:awaiting-response, to-be-backported

#1239 Fix dtype option of sum and prod
  cupy/core/core.pyx
  cupy/core/fusion.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: bug, to-be-backported

#1082 Support DLPack
  cupy/__init__.py
  cupy/core/__init__.py
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/dlpack.pxd
  cupy/core/dlpack.pyx
  cupy_setup_build.py
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: feature

#890 Check cuDNN convolution algorithm
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
  cupy/cuda/cupy_cudnn.h
  cupy/cudnn.pyx
Labels: enhancement

#1257 [backport] Fix default dtype of full
  cupy/creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: backport, bug, numpy-compat

#1212 [backport] Fix .coveragerc
  .coveragerc
Labels: backport, test

#1259 [backport] Fix dtype option of sum and prod
  cupy/core/core.pyx
  cupy/core/fusion.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: backport, bug

#1289 catch C++ exceptions from Thrust
  cupy/cuda/thrust.pyx
Labels: bug, to-be-backported

#1287 Fix view of zerodim ndarray
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: bug, to-be-backported

#1217 Fix linalg.matrix_rank casting for Windows
  cupy/linalg/norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: numpy-compat

#1280 Fix real and imag for zero-dim arrays
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
Labels: bug, to-be-backported

#1283 Support expm1, log1p, log2 for complex type
  cupy/core/include/cupy/complex.cuh
  tests/cupy_tests/math_tests/test_explog.py
Labels: bug, to-be-backported

#1292 [backport] Fix real and imag for zero-dim arrays
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
Labels: backport, bug, st:test-and-merge

#1293 [backport] Support expm1, log1p, log2 for complex type
  cupy/core/include/cupy/complex.cuh
  tests/cupy_tests/math_tests/test_explog.py
Labels: backport, bug

#1290 [backport] catch C++ exceptions from Thrust
  cupy/cuda/thrust.pyx
Labels: backport, bug, st:test-and-merge

#1208 Update README to encourage use of wheels
  README.md
Labels: document, to-be-backported

#1284 Fix unary functions in misc for complex
  cupy/math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: bug, to-be-backported

#1285 Fix binary functions in misc to support complex types
  cupy/core/include/cupy/complex.cuh
  cupy/math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: bug, to-be-backported

#1296 [backport] Update README to encourage use of wheels
  README.md
Labels: backport, document

#1297 [backport] Fix unary functions in misc for complex
  cupy/math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: backport, bug

#1256 fix OutOfMemoryError raised even when there are sufficient large freeable chunks
  cupy/cuda/memory.pyx
Labels: bug, to-be-backported

#1301 [backport] fix OutOfMemoryError raised even when there are sufficient large freeable chunks
  cupy/cuda/memory.pyx
Labels: backport, bug, st:test-and-merge

#1279 Fix astype for complex dtypes
  cupy/core/core.pyx
  setup.cfg
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: bug, st:test-and-merge, to-be-backported

#1286 Add divmod function to cupy namespace
  cupy/__init__.py
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: enhancement, to-be-backported

#1302 [backport] Fix astype for complex dtypes
  cupy/core/core.pyx
  setup.cfg
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, bug

#1235 [backport] fix cupy.diag() fails for array_likes other than CuPy arrays
  cupy/creation/matrix.py
  tests/cupy_tests/creation_tests/test_matrix.py
Labels: backport, enhancement

#1213 Improve sparse docs to show conversion from/to SciPy
  docs/source/reference/sparse.rst
Labels: document, st:test-and-merge

#1260 Improve performance of batch normalization
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
  cupy/cuda/cupy_cudnn.h
Labels: feature

#1253 Support bundling dependent DLLs for Windows wheel support
  cupy_setup_build.py
  install/build.py
Labels: install

#1298 [backport] Fix binary functions in misc to support complex types
  cupy/core/include/cupy/complex.cuh
  cupy/math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: backport, bug

#1282 Support rounding for complex types
  cupy/core/include/cupy/complex.cuh
  cupy/math/rounding.py
  cupy/math/ufunc.py
  tests/cupy_tests/math_tests/test_rounding.py
Labels: bug, to-be-backported

#1311 Fix rint syntax error
  cupy/core/include/cupy/complex.cuh
Labels: bug

#1306 [backport] Fix `real`, `imag` of non-contiguous complex arrays
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
Labels: backport, bug, st:test-and-merge

#1305 [backport] Add NumPy 1.14 to supported versions
  docs/source/install.rst
Labels: backport, document
