Repository cupy/cupy, pull requests merged in 2018-11, with the labels that each got.

#1752 [backport] Add cuDNN softmax interface
  cupy/cudnn.pyx
Labels: backport, enhancement

#1753 [backport] Add cuDNN pooling interface
  cupy/cudnn.pyx
Labels: backport, enhancement

#1757 Support skipping tests decorated by condition or parametize
  cupy/testing/condition.py
  cupy/testing/helper.py
  cupy/testing/parameterized.py
  tests/cupy_tests/testing_tests/test_condition.py
  tests/cupy_tests/testing_tests/test_parameterized.py
Labels: test, to-be-backported

#1767 [backport] Support skipping tests decorated by condition or parametize
  cupy/testing/condition.py
  cupy/testing/helper.py
  cupy/testing/parameterized.py
  tests/cupy_tests/testing_tests/test_condition.py
  tests/cupy_tests/testing_tests/test_parameterized.py
Labels: backport, test

#1751 Add requirements to build documentation on RTD
  docs/requirements.txt
Labels: document, st:test-and-merge, to-be-backported

#1768 [backport] Add requirements to build documentation on RTD
  docs/requirements.txt
Labels: backport, document

#1601 Check if ElementwiseKernel doesn't broadcast mutable `in_params`
  cupy/core/_kernel.pyx
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: enhancement

#1754 Add policy on compatibility of random sampling
  docs/source/reference/random.rst
Labels: document, to-be-backported

#1771 [backport] Add policy on compatibility of random sampling
  docs/source/reference/random.rst
Labels: backport, document

#1780 Assume CUDA v8 in cuSPARSE check
  cupy/cuda/__init__.py
  cupy/cuda/cupy_cusparse.h
Labels: enhancement, to-be-backported

#1778 [backport] Drop support for CUDA 7.0 / 7.5 and cuDNN v4
  cupy/core/core.pyx
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cudnn.h
  cupy/cudnn.pyx
  cupy_setup_build.py
  cupyx/scipy/sparse/csr.py
  install/build.py
  tests/cupy_tests/test_cudnn.py
Labels: backport, enhancement

#1737 Implement cuDNN batch normalization interface
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
  cupy/cudnn.pyx
Labels: enhancement, st:awaiting-response, to-be-backported

#1782 [backport] Assume CUDA v8 in cuSPARSE/cuSOLVER check
  cupy/cuda/__init__.py
  cupy/cuda/cupy_cusparse.h
Labels: backport, enhancement, st:test-and-merge

#1783 [backport] Fix description of CUDA_PATH environment variable
  docs/source/reference/environment.rst
Labels: backport, document

#1784 [backport] Implement cuDNN batch normalization interface
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
  cupy/cudnn.pyx
Labels: backport, enhancement

#1791 Indicate alias in comparison table
  docs/source/_comparison_generator.py
Labels: document, to-be-backported

#1794 [backport] Indicate alias in comparison table
  docs/source/_comparison_generator.py
Labels: backport, document, st:test-and-merge

#1797 Fix English in ndarray.nbytes documentation
  cupy/core/core.pyx
Labels: document, to-be-backported

#1799 Fix error in typecast from fp16 to complex dtype in `cupy.fuse`
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: bug, to-be-backported

#1796 [backport] Fix DropoutStates interface to avoid using cuDNN handle
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: backport, enhancement

#1801 [backport] Fix error in typecast from fp16 to complex dtype in `cupy.fuse`
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: backport, bug

#1795 Fix incorrect cast in element-wise op for float array and complex scalar
  cupy/core/_kernel.pyx
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: numpy-compat, test, to-be-backported

#1774 Fix invalid memory access during reduction whose output is large to exceed 32-bit
  cupy/core/reduction.pxi
  tests/cupy_tests/core_tests/test_carray.py
Labels: bug, to-be-backported

#1803 [backport] Fix incorrect cast in element-wise op for float array and complex scalar
  cupy/core/_kernel.pyx
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, numpy-compat, test

#1810 [backport] Fix invalid memory access during reduction whose output is large to exceed 32-bit
  cupy/core/reduction.pxi
  tests/cupy_tests/core_tests/test_carray.py
Labels: backport, bug, st:test-and-merge

#1594 Support compile-time constants in Fusion
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: feature

#1814 [backport] Add note about `cupy.random.{get_set}_state`
  docs/source/reference/random.rst
Labels: backport, document

#1809 Enable intersphinx to cupyx module
  docs/source/reference/ext.rst
Labels: document, st:test-and-merge, to-be-backported

#1816 [backport] Enable intersphinx to cupyx module
  docs/source/reference/ext.rst
Labels: backport, document

#1815 Add `ndarray.item` method
  cupy/core/core.pxd
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_conversion.py
Labels: feature

#1713 Support ndim checking in Fusion
  cupy/__init__.py
  cupy/core/fusion.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: enhancement

#1636 Support comparison operators for complex numbers
  cupy/core/core.pyx
  cupy/core/include/cupy/complex/arithmetic.h
  cupy/logic/ops.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: feature, to-be-backported

#1820 [backport] Support comparison operators for complex numbers
  cupy/core/core.pyx
  cupy/core/include/cupy/complex/arithmetic.h
  cupy/logic/ops.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, feature

#1806 Add docs about conversion from/to cupy ndarray and sparse
  docs/source/reference/sparse.rst
Labels: document, to-be-backported

#1659 RNN high level API
  cupy/cudnn.pyx
Labels: feature, to-be-backported

#1823 Update for cuDNN v7.3 and v7.4
  docs/source/install.rst
  tests/cupy_tests/test_cudnn.py
Labels: test, to-be-backported

#1824 Support CUDA 10.0
  docs/source/install.rst
Labels: document, to-be-backported

#1793 Add code of conduct
  CodeOfConduct.md
Labels: document, to-be-backported

#1821 [backport] RNN high level API
  cupy/cudnn.pyx
Labels: backport, feature

#1760 Support array conversion from numba to cupy w/o memcpy
  cupy/creation/from_data.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: feature

#1838 Rename `_make_rnn_workspace` function
  cupy/cudnn.pyx
Labels: enhancement, to-be-backported

#1841 [backport] Rename `_make_rnn_workspace` function
  cupy/cudnn.pyx
Labels: backport, enhancement

#1839 Make a helper function to get the number of layers in RNN
  cupy/cudnn.pyx
Labels: enhancement, to-be-backported

#1758 Fix test failure of binomial distribution in Windows
  tests/cupy_tests/random_tests/test_distributions.py
Labels: test, to-be-backported
