Repository cupy/cupy, pull requests merged in 2019-03, with the labels that each got.

#2065 Add NCCL v2.4 support to docs
  docs/source/install.rst
Labels: cat:document, to-be-backported

#2060 Fix fp16 issue in batch normalization
  cupy/cudnn.pyx
Labels: cat:enhancement, to-be-backported

#2049 Use single quote
  cupy/core/_kernel.pyx
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_math.pyx
  cupy/core/core.pyx
  cupy/core/internal.pyx
  cupy/creation/matrix.py
  cupy/cuda/compiler.py
  cupy/cuda/cublas.pyx
  cupy/cuda/cudnn.pyx
  cupy/cuda/cufft.pyx
  cupy/cuda/curand.pyx
  cupy/cuda/cusolver.pyx
  cupy/cuda/cusparse.pyx
  cupy/cuda/driver.pyx
  cupy/cuda/nccl.pyx
  cupy/cuda/nvrtc.pyx
  cupy/cuda/nvtx.pyx
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/profiler.pyx
  cupy/cuda/runtime.pyx
  cupy/cuda/thrust.pyx
  cupy/fft/fft.py
  cupy/indexing/insert.py
  cupy/linalg/eigenvalue.py
  cupy/linalg/einsum.py
  cupy/linalg/norms.py
  cupy/linalg/product.py
  cupy/manipulation/rearrange.py
  cupy/padding/pad.py
  cupy/random/_kernels.py
  cupy/random/generator.py
  cupy/sorting/search.py
  cupy/statistics/meanvar.py
  cupy/statistics/order.py
  cupy_setup_build.py
  cupyx/scipy/fftpack/fft.py
  cupyx/scipy/linalg/solve_triangular.py
  cupyx/scipy/ndimage/interpolation.py
  cupyx/scipy/sparse/construct.py
  tests/cupy_tests/core_tests/test_carray.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_conversion.py
  tests/cupy_tests/cuda_tests/test_nvtx.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/sorting_tests/test_search.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
Labels: cat:code-fix

#1983 Support fusion feature of copyto method
  cupy/manipulation/basic.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: cat:feature

#1911 Fix assigning from complex to float
  cupy/core/_ufuncs.py
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
Labels: cat:bug, to-be-backported

#1943 ensure that sparse matrix shapes are always a tuple of int
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2051 Add `lu_factor` and `lu_solve` to `cupyx.scipy.linalg`
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/decomp_lu.py
  docs/source/reference/linalg.rst
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:feature

#2080 Do not fail by warnings when building docs
  .travis.yml
  docs/Makefile
Labels: cat:test, to-be-backported

#2086 [backport] Do not fail by warnings when building docs
  .travis.yml
  docs/Makefile
Labels: backport, cat:test

#2073 Use deep copy in setting up RPATH
  cupy_setup_build.py
Labels: cat:install

#2082 [backport] Ensure that sparse matrix shapes are always a tuple of `int`
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: backport, cat:bug

#2077 Use `assert` in helper.py instead of `self.assertXXX`
  cupy/testing/helper.py
Labels: cat:code-fix

#1979 Document ``__array_function__``
  docs/source/reference/interoperability.rst
Labels: cat:document

#2075 Check array contiguity in `copy`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:bug, to-be-backported

#2089 [backport] Add NCCL v2.4 support to docs
  docs/source/install.rst
Labels: backport, cat:document, st:test-and-merge

#2072 Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training
  cupy/cudnn.pyx
Labels: cat:enhancement, to-be-backported

#2093 [backport] Check array contiguity in `copy`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: backport, cat:bug

#2092 [backport] Fix assigning from complex to float
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
Labels: backport, cat:bug

#2084 Test linalg.cholesky with more stable inputs
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:test

#1609 New RNN API introduced in v7.2
  cupy/cudnn.pyx
Labels: cat:feature, st:test-and-merge

#2038 Improve `_routines_manipulation`
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/core/reduction.pxi
Labels: cat:performance

#2105 Remove unused variable
  cupy/cudnn.pyx
Labels: cat:code-fix, st:test-and-merge

#2096 Add strides to docstring of ndarray
  cupy/core/core.pyx
Labels: cat:document, st:test-and-merge, to-be-backported

#2108 [backport] Remove unused variable
  cupy/cudnn.pyx
Labels: backport, cat:code-fix

#2058 More support `__cuda_array_interface__`
  cupy/core/_kernel.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/reduction.pxi
  cupy/creation/from_data.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:enhancement

#2103 Fix assertion error in _Chunk.split
  cupy/cuda/memory.pyx
Labels: cat:bug, to-be-backported

#2112 [backport] Fix assertion error in _Chunk.split
  cupy/cuda/memory.pyx
Labels: backport, cat:bug

#2094 [backport] Fix fp16 issue in batch normalization + Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training
  cupy/cudnn.pyx
Labels: backport, cat:enhancement

#2109 [backport] Add strides to docstring of ndarray
  cupy/core/core.pyx
Labels: backport, cat:document

#2097 Support dltensor with strides of NULL
  cupy/core/dlpack.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#2119 [backport] Support dltensor with strides of NULL
  cupy/core/dlpack.pyx
Labels: backport, cat:bug

#1933 Add `diff` and `unwrap`
  cupy/__init__.py
  cupy/math/sumprod.py
  cupy/math/trigonometric.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: cat:feature, takeover
