Repository cupy/cupy, pull requests merged in 2019-02, with the labels that each got.

#1993 [backport] Support Python scalars in `iscomplexobj`
  cupy/logic/type_test.py
  tests/cupy_tests/logic_tests/test_type_test.py
Labels: backport, cat:numpy-compat

#1996 [backport] Document NumPy 1.16 support
  docs/source/install.rst
Labels: backport, cat:document

#1995 define __dealloc__ instead of __del__ for cdef-classes to fix memory leak
  cupy/cudnn.pyx
Labels: cat:bug, to-be-backported

#1999 Improve memcpy example
  examples/stream/cupy_memcpy.py
Labels: cat:example

#1787 Implement `cupy.put` and `cupy.place`
  cupy/__init__.py
  cupy/core/_routines_indexing.pxd
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/indexing/insert.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: cat:feature

#1997 Fix test of `assert_array_list_equal`
  tests/cupy_tests/testing_tests/test_array.py
Labels: cat:test, to-be-backported

#1998 Fix test with NumPy 1.16.1
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, to-be-backported

#1947 Support comparing complex-number arrays in `cupy.allclose`
  cupy/logic/comparison.py
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: cat:enhancement

#2003 [backport] Fix test of `assert_array_list_equal`
  tests/cupy_tests/testing_tests/test_array.py
Labels: backport, cat:test

#2004 [backport] Fix test with NumPy 1.16.1
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:test

#1985 Use version interface in NCCL 2.3.4
  cupy/cuda/cupy_nccl.h
  cupy/cuda/nccl.pyx
  cupyx/runtime.py
  install/build.py
Labels: cat:enhancement, to-be-backported

#2006 [backport] Use version interface in NCCL 2.3.4
  cupy/cuda/cupy_nccl.h
  cupy/cuda/nccl.pyx
  cupyx/runtime.py
  install/build.py
Labels: backport, cat:enhancement, st:test-and-merge

#2007 Enhance error messages of elementwise operation in fusion mode
  cupy/core/fusion.pyx
Labels: cat:enhancement

#2001 Do not "accept error" if bad kwarg is passed to test itself
  cupy/testing/helper.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:test, st:test-and-merge

#2009 Fix NCCL version assignment for NCCL < 2.3.4
  cupy/cuda/cupy_nccl.h
Labels: cat:bug, to-be-backported

#2012 [backport] Fix NCCL version assignment for NCCL < 2.3.4
  cupy/cuda/cupy_nccl.h
Labels: backport, cat:bug

#2008 Fix vector handling
  cupy/core/core.pyx
  cupy/cuda/thrust.pyx
Labels: cat:enhancement

#2013 [backport] Fix vector handling
  cupy/core/core.pyx
  cupy/cuda/thrust.pyx
Labels: backport, cat:enhancement

#1770 Eliminate RUNPATH to use correct cuDNN
  cupy_setup_build.py
Labels: cat:install

#2023 Improve _is_fusing performance
  cupy/core/_kernel.pyx
  cupy/core/fusion.pyx
Labels: cat:performance

#2000 [backport] Define `__dealloc__` instead of `__del__` for cdef-classes to fix memory leak
  cupy/cudnn.pyx
Labels: backport, cat:bug, st:test-and-merge

#2017 Improve kind score operation
  cupy/core/_kernel.pyx
Labels: cat:performance

#2010 improve performance of reduction on outer axis
  cupy/core/reduction.pxi
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:performance, st:test-and-merge

#2014 Fix eliminate-runpath
  cupy_setup_build.py
Labels: cat:install

#1942 Add `plan` argument to 2D/3D FFT functions in `cupyx.scipy.fftpack`
  cupy/fft/fft.py
  cupyx/scipy/fftpack/__init__.py
  cupyx/scipy/fftpack/fft.py
  docs/source/reference/fftpack.rst
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:feature

#2015 Reduce vector copy in ndarray initialization
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: cat:performance

#2034 Support cuDNN FP16 batch normalization
  cupy/cudnn.pyx
Labels: cat:enhancement

#2022 Improve performance of broadcasting in elementwise kernels
  cupy/core/_kernel.pyx
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
Labels: cat:performance

#2028 remove duplicate declaration of cudaMalloc
  cupy/cuda/runtime.pyx
Labels: cat:code-fix, to-be-backported

#2018 Improve dictionary operation
  cupy/core/_kernel.pyx
  cupy/util.pyx
Labels: cat:performance, st:test-and-merge

#2019 Improve get_ufunc_kernel
  cupy/core/_kernel.pyx
Labels: cat:performance

#2036 Fix random generator seed type
  cupy/random/_kernels.py
  cupy/random/generator.py
Labels: cat:bug, to-be-backported

#2021 Reduce get_device_id call
  cupy/core/_kernel.pyx
  cupy/core/reduction.pxi
Labels: cat:performance

#2024 Fix __array_function__ bug
  cupy/core/_kernel.pyx
  cupy/core/core.pyx
Labels: cat:bug

#2039 [backport] Improve dictionary operation
  cupy/core/_kernel.pyx
  cupy/util.pyx
Labels: backport, cat:performance

#2041 [backport] Fix random generator seed type
  cupy/random/_kernels.py
  cupy/random/generator.py
Labels: backport, cat:bug, st:test-and-merge

#1789 Add documentation of `cupy.fuse`
  cupy/core/fusion.pyx
  docs/source/reference/kernel.rst
  docs/source/tutorial/kernel.rst
Labels: cat:document

#1992 Add NCCL 2.4 functions
  cupy/cuda/__init__.py
  cupy/cuda/cupy_nccl.h
  cupy/cuda/nccl.pyx
  tests/cupy_tests/cuda_tests/test_nccl.py
Labels: prio:high, to-be-backported

#2052 [backport] Add NCCL 2.4 functions
  cupy/cuda/__init__.py
  cupy/cuda/cupy_nccl.h
  cupy/cuda/nccl.pyx
  tests/cupy_tests/cuda_tests/test_nccl.py
Labels: backport, prio:high

#1379 Remove experimental warning of `cupy.fuse`
  cupy/core/fusion.pyx
Labels: cat:enhancement

#2040 Avoid `import numpy`
  cupy/core/core.pyx
Labels: cat:enhancement, to-be-backported

#2054 [backport] Avoid `import numpy`
  cupy/core/core.pyx
Labels: backport, cat:enhancement

#2037 [backport] Remove duplicate declaration of `cudaMalloc`
  cupy/cuda/runtime.pyx
Labels: backport, cat:code-fix

#2026 Fix usage array function for CuPy modules
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_array_function.py
Labels: cat:bug

#2056 Make `plan` argument in 2D/3D FFT functions experimental
  cupyx/scipy/fftpack/fft.py
Labels: cat:document

#2055 Avoid using pytest attributes during import
  cupy/testing/attr.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2050 fix cupyx.scipy.get_array_module's docstring
  cupyx/scipy/__init__.py
Labels: cat:document

#2033 Add `plan` argument to 1D FFT functions in `cupyx.scipy.fftpack`
  cupy/cuda/cufft.pyx
  cupy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:feature

#2064 Fix RPATH not set correctly
  cupy_setup_build.py
Labels: cat:install

#2067 Bump version in Dockerfiles to v5.3.0
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2057 [backport] Avoid using pytest attributes during import
  cupy/testing/attr.py
Labels: backport, cat:enhancement

#2016 Do exact type comparison instead of `isinstance` for `numpy.dtype`
  cupy/core/_dtype.pyx
Labels: cat:performance, st:test-and-merge
