Repository cupy/cupy, pull requests merged in 2019-06, with the labels that each got.

#2209 Avoid division by zero in tensordot, allowing 0-length arrays
  cupy/linalg/product.py
  tests/cupy_tests/linalg_tests/test_product.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2208 Add setup option to copy include files in wheel
  .gitignore
  cupy_setup_build.py
Labels: cat:install, to-be-backported

#2169 Set current device in `cupy.ndarray.get()`/`set()`
  cupy/core/core.pyx
Labels: cat:enhancement, st:test-and-merge

#2233 Fix: duplicate object description of cupy
  docs/source/overview.rst
  docs/source/reference/index.rst
  docs/source/reference/routines.rst
Labels: cat:document, to-be-backported

#2239 Add `CUDNN_POOLING_MAX_DETERMINISTIC`
  cupy/cuda/cudnn.pxd
Labels: cat:feature, st:test-and-merge

#2240 [backport] Fix: duplicate object description of cupy
  docs/source/overview.rst
  docs/source/reference/index.rst
  docs/source/reference/routines.rst
Labels: backport, cat:document

#2232 [backport] Add setup option to copy include files in wheel
  .gitignore
  cupy_setup_build.py
Labels: backport, cat:install

#2231 [backport] Avoid division by zero in tensordot, allowing 0-length arrays
  cupy/linalg/product.py
  tests/cupy_tests/linalg_tests/test_product.py
Labels: backport, cat:bug, st:test-and-merge

#2250 Make `RandomState.permutation` compatible with `random.permutation`
  cupy/random/generator.py
  cupy/random/permutations.py
  tests/cupy_tests/random_tests/test_permutations.py
Labels: cat:bug, to-be-backported

#2253 [Backport] Make `RandomState.permutation` compatible with `random.permutation`
  cupy/random/generator.py
  cupy/random/permutations.py
  tests/cupy_tests/random_tests/test_permutations.py
Labels: backport, cat:bug

#2256 Fix _preprocess_args to avoid calling hasattr
  cupy/core/_kernel.pyx
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2229 Add fallback_mode
  cupyx/__init__.py
  cupyx/fallback_mode/__init__.py
  cupyx/fallback_mode/data_transfer.py
  cupyx/fallback_mode/fallback.py
  cupyx/fallback_mode/utils.py
  setup.py
  tests/cupyx_tests/fallback_mode_tests/__init__.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:feature

#2254 Simplify _prepare_multiple_array_indexing
  cupy/core/_routines_indexing.pyx
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2257 Add `constant` modification to `vector_equal`
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2269 Update version numbers to v7.0.0b1
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2265 [backport] Add `constant` modification to `vector_equal`
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: backport, cat:enhancement

#2264 [backport] Simplify _prepare_multiple_array_indexing
  cupy/core/_routines_indexing.pyx
Labels: backport, cat:enhancement

#2263 [backport] Fix _preprocess_args to avoid calling hasattr
  cupy/core/_kernel.pyx
Labels: backport, cat:enhancement

#2234 Raise error when no available algorithm found by cudnnFindConvolution*
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: cat:enhancement, st:test-and-merge

#2260 Make `__cuda_array_interface__()['strides']` be `tuple`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2219 [backport] Allow copying in the format `cupy_array[:] = numpy_array`
  cupy/core/core.pyx
  cupy/util.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, cat:feature

#2273 [backport] Make `__cuda_array_interface__()['strides']` be `tuple`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
Labels: backport, cat:bug

#2255 Remove unused code
  cupy/core/_kernel.pyx
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2275 [backport] Remove unused code
  cupy/core/_kernel.pyx
Labels: backport, cat:enhancement, st:test-and-merge
