Repository cupy/cupy, pull requests merged in 2019-04, with the labels that each got.

#2053 Avoid sharing handles between threads
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
  cupy/cuda/device.pxd
  cupy/cuda/device.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: cat:bug, to-be-backported

#2121 Reorganize import in device.pyx
  cupy/cuda/device.pyx
Labels: cat:code-fix, to-be-backported

#2117 Support CUDA 10.1 + cuDNN 7.5 + Turing
  cupy/core/carray.pxi
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp
  cupy/cuda/cudnn.pyx
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cudnn.h
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy_setup_build.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported

#2123 [backport] Support CUDA 10.1 + cuDNN 7.5 + Turing
  cupy/core/carray.pxi
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp
  cupy/cuda/cudnn.pyx
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cudnn.h
  cupy/cuda/memory.pyx
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy_setup_build.py
  docs/source/install.rst
Labels: backport, cat:enhancement, st:test-and-merge

#2122 [backport] Avoid sharing handles between threads
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
  cupy/cuda/device.pxd
  cupy/cuda/device.pyx
Labels: backport, cat:bug

#2133 Bump version in Dockerfiles to v6.0.0rc1
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2129 Fix `__cuda_array_interface__` data pointer for sliced arrays
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#1769 Support cuDNN CTC functions
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
  cupy/cuda/cupy_cudnn.h
  cupy/cudnn.pyx
Labels: cat:feature

#2102 Add `hostRegister` and `hostUnregister`
  cupy/cuda/cupy_cuda.h
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
Labels: cat:feature, st:test-and-merge

#2134 [backport] Fix `__cuda_array_interface__` data pointer for sliced arrays
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
Labels: backport, cat:bug

#2124 Fix testing condition of `diff` and `unwrap`
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2142 [backport] Fix testing condition of `diff` and `unwrap`
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: backport, cat:test

#1885 Support NHWC format in convolution
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: cat:feature, st:test-and-merge

#2113 Implement limit to memory pool
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  docs/source/reference/environment.rst
  docs/source/reference/memory.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:feature, st:test-and-merge

#2150 Add `strides_check` option in array testing functions
  cupy/testing/array.py
  cupy/testing/helper.py
Labels: cat:feature

#1539 Avoid unnecessary weak pointer for null stream
  cupy/cuda/stream.pyx
Labels: cat:code-fix, st:test-and-merge

#2154 [backport] Avoid unnecessary weak pointer for null stream
  cupy/cuda/stream.pyx
Labels: backport, cat:code-fix

#2156 Add a test for `assert_array_equal(strides_check=True)`
  tests/cupy_tests/testing_tests/test_array.py
Labels: cat:test, st:test-and-merge

#1945 Avoid PyThread in `stream.pyx`
  cupy/cuda/stream.pyx
Labels: cat:code-fix

#2147 fix compile error on CUDA 10.1 and GCC 7 or 8
  cupy_setup_build.py
Labels: cat:install, to-be-backported

#2160 [backport] fix compile error on CUDA 10.1 and GCC 7 or 8
  cupy_setup_build.py
Labels: backport, cat:install

#2078 Fix `ascontiguousarray` with 0-dim array input
  cupy/core/__init__.py
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/cudnn.pyx
  cupy/statistics/order.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:numpy-compat

#2145 Make k-means example's custom kernels simpler
  examples/kmeans/kmeans.py
Labels: cat:example

#2151 Emit kernel names with type names
  cupy/core/_kernel.pyx
Labels: cat:enhancement
