Repository cupy/cupy, pull requests merged in 2019-10, with the labels that each got.

#2504 Avoid implicit cast inputs to cupy.ndarray in `cupy.pad`
  cupy/padding/pad.py
  tests/cupy_tests/padding_tests/test_pad.py
Labels: cat:enhancement, no-compat, st:test-and-merge

#1094 [Experimental] Support AMD GPU via HIP (ROCm2.7.0+)
  cupy/core/_routines_math.pyx
  cupy/core/include/cupy/atomics.cuh
  cupy/core/include/cupy/carray.cuh
  cupy/core/include/cupy/complex/complex.h
  cupy/core/reduction.pxi
  cupy/cuda/compiler.py
  cupy/cuda/cupy_cuComplex.h
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cuda_common.h
  cupy/cuda/cupy_cudnn.h
  cupy/cuda/cupy_cufft.h
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cupy_cutensor.h
  cupy/cuda/cupy_hip.h
  cupy/cuda/cupy_hip_common.h
  cupy/cuda/cupy_hiprtc.h
  cupy/cuda/cupy_nvrtc.h
  cupy/cuda/device.pyx
  cupy/cuda/driver.pxd
  cupy/cuda/function.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy/math/misc.py
  cupy_setup_build.py
  docs/source/index.rst
  docs/source/install_rocm.rst
  install/build.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:feature

#2514 Fix error in `test_build.py`
  tests/install_tests/test_build.py
Labels: cat:test, st:test-and-merge

#2342 Improve error message in cupy.linalg.inv
  cupy/linalg/solve.py
Labels: cat:enhancement, st:test-and-merge

#2388 Implement `isin` and `in1d`
  cupy/__init__.py
  cupy/logic/truth.py
  docs/source/reference/logic.rst
  tests/cupy_tests/logic_tests/test_truth.py
Labels: cat:feature

#2491 Update `__cuda_array_interface__` to protocol version 3
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2523 Fix some typo
  cupy/core/_routines_sorting.pyx
  cupy/cuda/cupy_thrust.cu
  cupy/cusparse.py
  cupy_setup_build.py
  docs/source/reference/interoperability.rst
  examples/finance/black_scholes.py
  examples/finance/monte_carlo.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: cat:document, st:test-and-merge, to-be-backported

#2527 [backport] Fix some typo
  cupy/core/_routines_sorting.pyx
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
  docs/source/reference/interoperability.rst
  examples/finance/black_scholes.py
  examples/finance/monte_carlo.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: backport, cat:document

#2511 Enhance shuffle-test of `testing.for_dtypes_combination`
  cupy/testing/helper.py
Labels: cat:enhancement, st:test-and-merge

#2502 [backport] Fix memory pool disabled during tests
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:test

#2341 Support cuTENSOR 0.2
  cupy/cuda/cupy_cutensor.h
  cupy/cuda/cutensor.pyx
  cupy/cutensor.py
  examples/cutensor/reduction.py
Labels: cat:feature

#2509 Cholesky decomposition to support complex values
  cupy/linalg/decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:enhancement

#2517 enable fast CUB-based reductions in more cases (example cupy.linalg.norm)
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cuda/cub.pyx
Labels: cat:enhancement

#2531 Handle PCI bus ID
  cupy/cuda/cupy_cuda.h
  cupy/cuda/device.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: cat:feature, st:test-and-merge

#2533 Move CI requirements to Cupy repository
  setup.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2512 Update install_rocm.rst
  docs/source/install_rocm.rst
Labels: cat:document

#2541 Support `cupyx.fallback_mode` as an experimental feature
  cupyx/__init__.py
  cupyx/fallback_mode/__init__.py
Labels: cat:enhancement, st:test-and-merge

#1941 Adds nvcc as a RawKernel backend
  cupy/core/carray.pxi
  cupy/core/core.pxd
  cupy/core/raw.pxd
  cupy/core/raw.pyx
  cupy/cuda/compiler.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: cat:feature, st:test-and-merge

#2384 Fix dead link to NumPy docs in random functions
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  cupy/random/permutations.py
  cupy/random/sample.py
  docs/source/reference/random.rst
Labels: st:awaiting-author

#2544 Fix for NumPy 1.14.x compatibility
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2545 Workaround bug in NumPy 1.12.x or earlier
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2520 Allow to use `real` and `imag` on cuda kernels
  cupy/core/include/cupy/complex.cuh
  cupy/core/include/cupy/complex/arithmetic.h
  cupy/core/include/cupy/complex/complex.h
Labels: cat:enhancement

#2539 Expand coverage of cuSolverSP APIs
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
Labels: cat:feature

#2546 [backport] Fix for NumPy 1.14.x compatibility
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
Labels: backport, cat:test

#2538 Fix bug in CUB + **Native support** of complex numbers in CUB
  cupy/core/include/cupy/complex/complex.h
  cupy/core/include/cupy/complex/complex_inl.h
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
  install/build.py
Labels: cat:enhancement

#2526 Support complex numbers in `cupy.linalg.qr()`
  cupy/linalg/decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:enhancement

#2529 checks for whether cuSOLVER is enabled aren't needed anymore
  cupy/cuda/__init__.py
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cusparse.pyx
  cupy/cuda/device.pyx
  cupy/linalg/decomposition.py
  cupy/linalg/eigenvalue.py
  cupy/linalg/norms.py
  cupy/linalg/solve.py
  cupyx/linalg/sparse/solve.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/sparse/linalg/solve.py
  tests/cupy_tests/cuda_tests/test_cusolver.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
  tests/cupy_tests/linalg_tests/test_norms.py
  tests/cupy_tests/linalg_tests/test_product.py
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:code-fix, st:test-and-merge

#2542 Add cuSPARSE routines for preconditioners
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cusparse.pxd
  cupy/cuda/cusparse.pyx
Labels: cat:feature

#2201 Fix division by zero in mean/std/var functions for 0-length dimensions
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: cat:numpy-compat

#2555 Support stream in CUB
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
Labels: cat:enhancement

#2554 [backport] Fix dead links in NumPy docs in random functions
  cupy/random/__init__.py
  cupy/random/distributions.py
  cupy/random/generator.py
  cupy/random/permutations.py
  cupy/random/sample.py
  docs/source/reference/random.rst
Labels: backport, cat:document

#2570 Bump Docker version to v7.0.0rc1
  docker/python3/Dockerfile
Labels: cat:other

#2571 Bump Docker version to v6.5.0
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2563 Package the tests
  MANIFEST.in
Labels: cat:install

#2567 [backport] Make exceptions picklable
  cupy/cuda/compiler.py
  cupy/cuda/cublas.pyx
  cupy/cuda/cudnn.pyx
  cupy/cuda/cufft.pyx
  cupy/cuda/curand.pyx
  cupy/cuda/cusolver.pyx
  cupy/cuda/cusparse.pyx
  cupy/cuda/driver.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/nccl.pyx
  cupy/cuda/nvrtc.pyx
  cupy/cuda/runtime.pyx
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupy_tests/cuda_tests/test_cublas.py
  tests/cupy_tests/cuda_tests/test_cudnn.py
  tests/cupy_tests/cuda_tests/test_cufft.py
  tests/cupy_tests/cuda_tests/test_curand.py
  tests/cupy_tests/cuda_tests/test_cusolver.py
  tests/cupy_tests/cuda_tests/test_cusparse.py
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/cuda_tests/test_nccl.py
  tests/cupy_tests/cuda_tests/test_nvrtc.py
  tests/cupy_tests/cuda_tests/test_runtime.pyx
Labels: backport, cat:bug

#2495 Inverse for Hermitian matrix
  cupyx/linalg/__init__.py
  cupyx/linalg/solve.py
  tests/cupyx_tests/linalg_tests/__init__.py
  tests/cupyx_tests/linalg_tests/test_solve.py
Labels: cat:feature

#2556 Reduce compile warnings
  cupy/core/_kernel.pyx
  cupy/core/_routines_indexing.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/texture.pyx
  cupy/cudnn.pyx
  cupy_setup_build.py
  install/build.py
Labels: cat:enhancement

#2557 Add CUDA API runtime API list
  docs/source/reference/cuda.rst
Labels: cat:document, st:test-and-merge

#2577 Include `.git` in ChainerCV compatibility CI
  .pfnci/config.pbtxt
Labels: cat:test, st:test-and-merge

#2573 Remove cuSPARSE APIs dropped in CUDA 10.1 Update 2
  cupy/cuda/cusparse.pyx
Labels: cat:bug

#2561 Use `!=` instead of `is not` for literal
  install/build.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2580 Fix url to use the home page address
  setup.py
Labels: cat:install, st:test-and-merge, to-be-backported
