Repository cupy/cupy, pull requests merged in 2019-09, with the labels that each got.

#2418 [backport] Support for shape argument in *_like functions
  cupy/core/core.pyx
  cupy/creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: backport, cat:enhancement

#2441 Add NumPy 1.17.1 to skip list of 0-length `ifft` test
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:test, to-be-backported

#2443 Remove unnecessary skip in 0-length `ifft` test
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:test

#2445 [backport] Add NumPy 1.17.1 to skip list of 0-length `ifft` test
  tests/cupy_tests/fft_tests/test_fft.py
Labels: backport, cat:test

#2442 Normalize hidden layer strides in cuDNN RNN
  cupy/cudnn.pyx
Labels: cat:enhancement, to-be-backported

#2448 [backport] Normalize hidden layer strides in cuDNN RNN
  cupy/cudnn.pyx
Labels: backport, cat:bug

#2447 [backport] Fix NumPy version in Dockerfile
  docker/python2/Dockerfile
Labels: backport, cat:install

#2427 Add scatter_max and scatter_min
  cupy/core/_routines_indexing.pxd
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pyx
  cupy/core/include/cupy/atomics.cuh
  cupyx/__init__.py
  cupyx/scatter.py
  docs/source/reference/ext.rst
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupyx_tests/test_scatter.py
Labels: cat:enhancement

#2386 Document CUTENSOR_PATH
  docs/source/install.rst
  docs/source/reference/environment.rst
Labels: cat:document

#2339 Simplify `cupy.fuse` tests
  tests/cupy_tests/core_tests/fusion_tests/__init__.py
  tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py
  tests/cupy_tests/core_tests/fusion_tests/test_array.py
  tests/cupy_tests/core_tests/fusion_tests/test_function.py
  tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
  tests/cupy_tests/core_tests/test_fusion.py
Labels: cat:test, st:test-and-merge

#2451 Fixed `TestDLTensorMemory.test_delete`
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:test, to-be-backported

#2473 Fix pytest 5.x version errors
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2470 Fix invalid escape sequence
  cupy/core/raw.pyx
Labels: cat:document, st:test-and-merge

#2475 Remove global state from tests
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: cat:test, st:test-and-merge

#2468 Support complex dtypes in `cupy.linalg.inv()`
  cupy/linalg/solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:enhancement, st:test-and-merge

#2455 Add appropriate pointer types in Cython to the contribute guide
  cupy/core/raw.pyx
  cupy/cuda/cufft.pxd
  cupy/cuda/cufft.pyx
  cupy/cuda/driver.pxd
  cupy/cuda/driver.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/nccl.pyx
  cupy/cuda/nvrtc.pxd
  cupy/cuda/nvrtc.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy/cuda/stream.pxd
  cupy/cuda/stream.pyx
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  docs/source/contribution.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#2411 add complex dtype support to `cupy.std` and `cupy.var`
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: cat:enhancement

#2472 Fix data race in advanced indexing test
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: cat:test, to-be-backported

#2482 [backport] Fix data race in advanced indexing test
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: backport, cat:test

#2479 `cupy.linalg.norm`: update docstring and improve performance for ord=2 cases
  cupy/linalg/norms.py
Labels: cat:performance, st:test-and-merge

#2465 Remove unncecessary `ndarray` private methods
  cupy/core/_routines_math.pxd
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pxd
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/math/sumprod.py
  cupy/sorting/search.py
Labels: cat:code-fix, st:test-and-merge

#2480 [backport] Add appropriate pointer types in Cython to the contribute guide
  docs/source/contribution.rst
Labels: backport, cat:document, st:test-and-merge

#2460 Copy inputs in ufunc if they share the same memory with outputs
  cupy/core/_kernel.pyx
  cupy/core/_memory_range.pxd
  cupy/core/_memory_range.pyx
  cupy/misc/memory_ranges.py
  cupy_setup_build.py
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:bug, st:test-and-merge

#2410 Bug: Fix `coosort`
  cupy/cusparse.py
  tests/cupy_tests/test_cusparse.py
Labels: cat:bug, to-be-backported

#2090 Use CUB to speed up `sum`/`min`/`max`
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cuda/__init__.py
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
  cupy_setup_build.py
  install/build.py
Labels: cat:performance, st:test-and-merge

#2494 Bump version to v6.4.0
  cupy/_version.py
Labels: cat:other

#2493 Bump version to v7.0.0b4
  cupy/_version.py
Labels: cat:other

#2499 Bump versions in Dockerfile
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2489 Added `cupy.cuda.memory.get_allocator` interface
  cupy/cuda/__init__.py
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:feature

#2484 Performance improvement for `cupy.var` complex inputs
  cupy/core/_routines_statistics.pyx
Labels: cat:performance, st:test-and-merge

#2488 Ignore warning caused by fastrlock
  cupy/__init__.py
Labels: cat:other, st:test-and-merge, to-be-backported

#2452 Fix memory pool disabled during tests
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:test, to-be-backported

#2400 Fix `cupy.repeat` error message about `repeats` argument type
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_tiling.py
Labels: cat:enhancement, to-be-backported

#2501 [backport] Ignore warning caused by fastrlock
  cupy/__init__.py
Labels: backport, cat:enhancement

#2487 [backport] Bug: Fix `coosort`
  cupy/cusparse.py
  tests/cupy_tests/test_cusparse.py
Labels: backport, cat:bug, st:test-and-merge

#2399 replace `cupy.pad` with a heavily refactored version from NumPy 1.17
  cupy/padding/pad.py
  tests/cupy_tests/padding_tests/test_pad.py
Labels: cat:enhancement

#2498 Fix `@testing.numpy_cupy_` decorators for skips
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:enhancement

#2483 Support `scipy.ndimage` compatible `convolve` and `correlate`
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:feature, st:test-and-merge

#2503 Skip bool-bool inputs in `cupy.cross` test
  tests/cupy_tests/linalg_tests/test_product.py
Labels: cat:test

#2506 [backport] Fix `cupy.repeat` error message about `repeats` argument type
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_tiling.py
Labels: backport, cat:enhancement

#2496 allow axis=None in concatenate
  cupy/manipulation/join.py
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: cat:enhancement
