Repository cupy/cupy, pull requests merged in 2019-12, with the labels that each got.

#2572 [backport] Package tests in sdist
  MANIFEST.in
Labels: backport, cat:install, st:test-and-merge

#2737 Add a few missing stubs for ROCm/HIP build
  cupy/cuda/cupy_hip.h
  cupy/cuda/cupy_hip_common.h
Labels: cat:enhancement

#2700 Avoid module level lookup in _dtype
  cupy/core/_dtype.pyx
Labels: cat:performance

#2701 Add _ndarray_init to reduce ndarray creation cost
  cupy/core/core.pxd
  cupy/core/core.pyx
Labels: cat:performance

#2671 Avoid __init__ function call overhead in memory allocation
  cupy/cuda/memory.pyx
Labels: cat:performance

#2691 Avoid __init__ call when creating CArray object
  cupy/core/carray.pxi
  cupy/core/core.pyx
Labels: cat:performance

#2694 Improve ndattay.reduced_view
  cupy/core/core.pyx
Labels: cat:enhancement

#2739 Remove `cupy/internal.py`
  cupy/internal.py
  cupy/linalg/einsum.py
  cupy/linalg/product.py
  cupy/linalg/solve.py
  cupy/testing/helper.py
Labels: cat:code-fix, st:test-and-merge

#2693 Improve _reduce_dims
  cupy/core/_kernel.pyx
Labels: cat:performance

#2729 Avoid tricky initialization of block stride
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
  cupy/core/reduction.pxi
Labels: cat:code-fix, st:test-and-merge

#2698 CUB-based CSR sparse matrix vector multiply
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
  cupyx/scipy/sparse/csr.py
Labels: cat:performance, st:test-and-merge

#2355 Add scipy.fft to cupyx
  cupy/fft/fft.py
  cupyx/scipy/fft/__init__.py
  cupyx/scipy/fft/fft.py
  docs/source/reference/fftpack.rst
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_fft.rst
  setup.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/__init__.py
  tests/cupyx_tests/scipy_tests/fft_tests/__init__.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:feature

#2726 Add `searchsorted`
  cupy/__init__.py
  cupy/core/core.pyx
  cupy/sorting/search.py
  cupy/statistics/histogram.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:feature, st:test-and-merge

#2697 Improve reduction core
  cupy/core/reduction.pxi
Labels: cat:code-fix

#2747 Implement `ParameterInfo.__str__`
  cupy/core/_kernel.pyx
Labels: cat:enhancement

#2738 Support Python 3.8 on Windows
  cupy/__init__.py
  cupy/_environment.py
  cupy/cuda/__init__.py
Labels: cat:enhancement, to-be-backported

#2751 [backport] Support Python 3.8 on Windows
  cupy/__init__.py
  cupy/_environment.py
  cupy/cuda/__init__.py
Labels: backport, cat:enhancement

#2756 Update requirements
  docs/source/install.rst
Labels: cat:document

#2755 [v6] Update requirements
  docs/source/install.rst
Labels: cat:document

#2753 Bump version to v7.0.0
  cupy/_version.py
Labels: cat:other

#2754 Bump version to v6.6.0
  cupy/_version.py
Labels: cat:other

#2760 Bump Docker version to v6.6.0
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2761 Bump version number in Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2699 Remove memory copy to improve memory range checking
  cupy/core/_kernel.pyx
  cupy/core/_memory_range.pyx
Labels: cat:performance

#2727 Test cuTENSOR v1.0.0
  .pfnci/py27and35.Dockerfile
  .pfnci/py37.Dockerfile
Labels: cat:test

#2643 Fix docs of options argument in RawKernel and RawModule
  cupy/core/raw.pyx
Labels: cat:document

#2759 Fix slow import of cupy
  cupy/testing/helper.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2732 Merge reduction implementations
  cupy/core/_kernel.pyx
  cupy/core/reduction.pxi
Labels: cat:code-fix

#2765 [backport] Fix slow import of cupy
  cupy/testing/helper.py
Labels: backport, cat:enhancement

#2752 [v6] Fix axes handling in `_fftn`
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:bug

#2770 Remove unused `cuParamSetTexRef()`
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_hip.h
  cupy/cuda/driver.pxd
  cupy/cuda/driver.pyx
Labels: cat:code-fix, to-be-backported

#2745 Support sorting complex arrays
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/thrust.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:enhancement, st:test-and-merge

#2767 Rename and reorder private functions in `reduction.pxi`
  cupy/core/reduction.pxi
Labels: cat:code-fix

#2673 Avoid `numpy.can_cast` call to improve guess routine
  cupy/core/_kernel.pyx
Labels: cat:performance

#2769 Avoid using PyThread API
  cupy/cuda/memory_hook.pyx
  cupy/cuda/runtime.pyx
  cupy/cuda/stream.pyx
Labels: cat:code-fix

#2782 Support loading PTX in `cupy.RawModule`
  cupy/core/raw.pyx
Labels: cat:feature

#2784 Separate code and path arguments in `RawModule`
  cupy/core/raw.pyx
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: cat:bug, no-compat, to-be-backported

#2730 Allow install without thrust
  cupy_setup_build.py
Labels: cat:other, st:test-and-merge

#2704 Avoid `can_cast` calling to reduce overhead
  cupy/core/_kernel.pyx
Labels: cat:performance

#2788 Use more stable input to test `linalg.matrix_power`
  tests/cupy_tests/linalg_tests/test_product.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2791 [backport] Use more stable input to test `linalg.matrix_power`
  tests/cupy_tests/linalg_tests/test_product.py
Labels: backport, cat:test

#2798 Document device synchronization
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pyx
  cupy/indexing/generate.py
  cupy/indexing/insert.py
  cupy/manipulation/add_remove.py
  cupy/random/generator.py
  cupy/sorting/search.py
  cupy/statistics/histogram.py
  cupy/statistics/meanvar.py
  cupy/statistics/order.py
Labels: cat:document, to-be-backported

#2740 Add helpers to measure execution times
  cupyx/__init__.py
  cupyx/time.py
  tests/cupyx_tests/test_time.py
Labels: cat:feature

#2804 fix typo in scipy.fft docs
  docs/source/reference/scipy_fft.rst
Labels: cat:document, to-be-backported

#2803 Drop ChainerCV's test in master branch.
  .pfnci/config.pbtxt
Labels: cat:test

#2801 Refactor reduction code
  cupy/core/reduction.pxi
Labels: cat:code-fix

#2805 fix range used in cupyx.scipy.ndimage filter origin check
  cupyx/scipy/ndimage/filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:bug, to-be-backported

#2809 Detect interpreter shutdown for proper `__del__` behavior
  cupy/cuda/compiler.py
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/stream.pyx
  cupy/cusparse.py
  cupy/cutensor.py
  cupy/random/generator.py
  cupy/util.pyx
Labels: cat:bug, to-be-backported

#2812 [backport] Detect interpreter shutdown for proper `__del__` behavior
  cupy/cuda/compiler.py
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/stream.pyx
  cupy/cusparse.py
  cupy/random/generator.py
  cupy/util.pyx
Labels: backport, cat:bug

#2811 [backport] Detect interpreter shutdown for proper `__del__` behavior
  cupy/cuda/compiler.py
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/stream.pyx
  cupy/cusparse.py
  cupy/cutensor.py
  cupy/random/generator.py
  cupy/util.pyx
Labels: backport, cat:bug

#2810 [backport] fix range used in cupyx.scipy.ndimage filter origin check
  cupyx/scipy/ndimage/filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: backport, cat:bug

#2785 Separate reduction code from `_kernel.pyx`
  cupy/__init__.py
  cupy/core/__init__.py
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
  cupy/core/_routines_logic.pyx
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pyx
  cupy/core/fusion.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/manipulation/rearrange.py
  cupy_setup_build.py
  tests/cupy_tests/core_tests/fusion_tests/test_function.py
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:code-fix

#2735 Use getrfBatched in `linalg.slogdet`
  cupy/linalg/decomposition.py
  cupy/linalg/norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: cat:performance, st:test-and-merge

#2814 Fix split and array_split with indices overrun
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: cat:bug, to-be-backported

#2775 [backport] Test cuTENSOR v1.0.0
  .pfnci/py27and35.Dockerfile
  .pfnci/py37.Dockerfile
Labels: backport, cat:test

#2821 Fix the docstring format of `cupy.asarray`
  cupy/creation/from_data.py
Labels: cat:document, st:test-and-merge, to-be-backported

#2787 Add nogil to CUB
  cupy/cuda/cub.pyx
Labels: cat:enhancement, st:test-and-merge

#2774 [backport] Fix docs of options argument in RawKernel and RawModule
  cupy/core/raw.pyx
Labels: backport, cat:document

#2773 [backport] Fix slow import of cupy
  cupy/testing/helper.py
Labels: backport, cat:enhancement

#2746 reduce overhead in calls to multi-dimensional FFTs.
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:performance

#2826 [backport] Fix the docstring format of `cupy.asarray`
  cupy/creation/from_data.py
Labels: backport, cat:document

#2830 Add f-contiguous reduction tests
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:test, st:test-and-merge

#2076 Fix `true_divide` with dtype argument
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/_routines_math.pyx
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2741 Update thrust::complex headers with a bug fix
  cupy/core/include/cupy/complex.cuh
  cupy/core/include/cupy/complex/arithmetic.h
  cupy/core/include/cupy/complex/catrig.h
  cupy/core/include/cupy/complex/catrigf.h
  cupy/core/include/cupy/complex/ccosh.h
  cupy/core/include/cupy/complex/ccoshf.h
  cupy/core/include/cupy/complex/cexp.h
  cupy/core/include/cupy/complex/cexpf.h
  cupy/core/include/cupy/complex/clog.h
  cupy/core/include/cupy/complex/clogf.h
  cupy/core/include/cupy/complex/complex.h
  cupy/core/include/cupy/complex/complex_inl.h
  cupy/core/include/cupy/complex/cpow.h
  cupy/core/include/cupy/complex/cproj.h
  cupy/core/include/cupy/complex/csinh.h
  cupy/core/include/cupy/complex/csinhf.h
  cupy/core/include/cupy/complex/csqrt.h
  cupy/core/include/cupy/complex/csqrtf.h
  cupy/core/include/cupy/complex/ctanh.h
  cupy/core/include/cupy/complex/ctanhf.h
  cupy/core/include/cupy/complex/math_private.h
Labels: cat:bug, to-be-backported

#2825 [backport] Fix the docstring format of `cupy.asarray`
  cupy/creation/from_data.py
Labels: backport, cat:document

#2833 [backport] Update thrust::complex headers with a bug fix
  cupy/core/include/cupy/complex.cuh
  cupy/core/include/cupy/complex/arithmetic.h
  cupy/core/include/cupy/complex/catrig.h
  cupy/core/include/cupy/complex/catrigf.h
  cupy/core/include/cupy/complex/ccosh.h
  cupy/core/include/cupy/complex/ccoshf.h
  cupy/core/include/cupy/complex/cexp.h
  cupy/core/include/cupy/complex/cexpf.h
  cupy/core/include/cupy/complex/clog.h
  cupy/core/include/cupy/complex/clogf.h
  cupy/core/include/cupy/complex/complex.h
  cupy/core/include/cupy/complex/complex_inl.h
  cupy/core/include/cupy/complex/cpow.h
  cupy/core/include/cupy/complex/cproj.h
  cupy/core/include/cupy/complex/csinh.h
  cupy/core/include/cupy/complex/csinhf.h
  cupy/core/include/cupy/complex/csqrt.h
  cupy/core/include/cupy/complex/csqrtf.h
  cupy/core/include/cupy/complex/ctanh.h
  cupy/core/include/cupy/complex/ctanhf.h
  cupy/core/include/cupy/complex/math_private.h
Labels: backport, cat:bug

#2834 [backport] Fix `true_divide` with dtype argument
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_routines_math.pyx
  cupy/core/reduction.pxi
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: backport, cat:bug

#2813 fix cupyx.scipy.ndimage.map_coordinates for cases with coords > 2d
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:feature, st:test-and-merge

#2799 Avoid device synchronization in `cupy.allclose`
  cupy/logic/comparison.py
Labels: cat:enhancement, no-compat

#2815 Fix split and array_split with unordered indices supplied
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: cat:bug, to-be-backported

#2822 Allow squashing f-contiguous axes for faster reduction
  cupy/core/_reduction.pyx
Labels: cat:performance

#2817 Refactor ops
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/fusion.pyx
Labels: cat:code-fix

#2838 Fix compilation error causes when thrust is enabled
  cupy/core/include/cupy/complex/cpow.h
Labels: cat:bug, st:test-and-merge, to-be-backported

#2839 [backport] Fix compilation error causes when thrust is enabled
  cupy/core/include/cupy/complex/cpow.h
Labels: backport, cat:bug

#2793 [backport] Use more stable input to test `linalg.matrix_power`
  tests/cupy_tests/linalg_tests/test_product.py
Labels: backport, cat:test, st:test-and-merge

#2831 Separate CArray and family from `core.pyx`
  cupy/core/_carray.pxd
  cupy/core/_carray.pyx
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/carray.pxi
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/cuda/function.pyx
  cupy_setup_build.py
Labels: cat:code-fix

#2820 Fix decorator usage in tests
  cupy/testing/helper.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:test, to-be-backported

#2725 keepdims should always preserve all dimensions in CUB-based reductions
  cupy/core/_reduction.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/cuda/cub.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:bug, to-be-backported

#2847 [backport] Fix decorator usage in tests
  cupy/testing/helper.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:test

#2786 [backport] Separate code and path arguments in `RawModule`
  cupy/core/raw.pyx
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: backport, cat:bug, no-compat, st:test-and-merge

#2848 [backport] keepdims should always preserve all dimensions in CUB-based reductions
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/core/reduction.pxi
  cupy/cuda/cub.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: backport, cat:bug

#2837 [backport] Fix split and array_split with indices overrun
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: backport, cat:bug, st:test-and-merge

#2851 [backport] Fix split and array_split with indices overrun
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: backport, cat:bug

#2857 [backport] Fix split and array_split with unordered indices supplied
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: backport, cat:bug

#2856 [backport] Fix split and array_split with unordered indices supplied
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_split.py
Labels: backport, cat:bug

#2828 Improve compatibility of `random.randint`
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
Labels: cat:numpy-compat, st:test-and-merge, to-be-backported

#2850 [backport] Fix decorator usage in tests
  cupy/testing/helper.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_rounding.py
Labels: backport, cat:test, st:test-and-merge

#2835 [backport] Fix `true_divide` with dtype argument
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_routines_math.pyx
  cupy/core/reduction.pxi
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: backport, cat:bug

#2854 [backport] Support 64 bit extent `randint`
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: backport, cat:numpy-compat

#2855 [backport] Support 64 bit extent `randint`
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: backport, cat:numpy-compat

#2862 [backport] Improve compatibility of `random.randint`
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
Labels: backport, cat:numpy-compat

#2802 Avoid looking up null pointers' attributes
  cupy/core/core.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:bug, to-be-backported

#2794 Reomve Python 3.4 matrix from Travis CI
  .travis.yml
Labels: cat:test, to-be-backported

#2807 [backport] fix typo in scipy.fft docs
  docs/source/reference/scipy_fft.rst
Labels: backport, cat:document

#2758 Add `digitize`
  cupy/__init__.py
  cupy/sorting/search.py
  cupy/statistics/histogram.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: cat:feature, st:test-and-merge

#2867 [backport] Remove Python 3.4 matrix from Travis CI
  .travis.yml
Labels: backport, cat:test

#2818 Refactor array testing decorators
  cupy/testing/helper.py
  tests/cupy_tests/manipulation_tests/test_shape.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: cat:test, to-be-backported

#2852 Test `ifloordiv` with numpy 1.18
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:test, to-be-backported

#2879 [backport] Test `ifloordiv` with numpy 1.18
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, cat:test

#2880 [backport] Test `ifloordiv` with numpy 1.18
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, cat:test

#2875 Remove `dtype` argument from `min`/`max`
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/statistics/order.py
Labels: cat:numpy-compat

#2881 Sort type map in `_kernel.pyx`
  cupy/core/_kernel.pyx
Labels: cat:enhancement

#2866 [backport] Avoid looking up null pointers' attributes
  cupy/core/core.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: backport, cat:bug

#2868 [backport] Avoid looking up null pointers' attributes
  cupy/core/core.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: backport, cat:bug

#2877 [backport] Refactor array testing decorators
  cupy/testing/helper.py
  tests/cupy_tests/manipulation_tests/test_shape.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: backport, cat:test

#2860 Add CUB reduction support to `mean`
  cupy/core/_routines_statistics.pyx
Labels: cat:enhancement

#2887 Add missing blank lines
  cupy/core/_routines_statistics.pyx
Labels: cat:code-fix, st:test-and-merge

#2870 Fix `testing.shaped_random` for shape `()`
  cupy/testing/helper.py
  tests/cupy_tests/random_tests/test_permutations.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:bug, to-be-backported

#2819 Detect synchronization
  cupy/core/core.pyx
  cupy/core/syncdetect.py
  cupy/cuda/device.pyx
  cupyx/__init__.py
  docs/source/reference/prof.rst
  tests/cupy_tests/core_tests/test_syncdetect.py
Labels: cat:feature, st:test-and-merge

#2872 Fix `argmin`/`argmax` `dtype` argument
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pyx
  cupy/sorting/search.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, st:blocked-by-another-pr, to-be-backported

#2889 [backport] Fix `testing.shaped_random` for shape `()`
  cupy/testing/helper.py
  tests/cupy_tests/random_tests/test_permutations.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:bug

#2892 [backport] Fix `@testing.numpy_cupy_` decorators for skips
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:enhancement, st:test-and-merge

#2878 [backport] Refactor array testing decorators
  cupy/testing/helper.py
  tests/cupy_tests/manipulation_tests/test_shape.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: backport, cat:test, st:test-and-merge
