Repository cupy/cupy, pull requests merged in 2019-01, with the labels that each got.

#1909 Use LF instead of CR+LF
  cupy/core/include/cupy/complex/complex.h
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#1746 add PlanNd class for faster 2D and 3D FFTs
  cupy/cuda/cufft.pyx
  cupy/cuda/cupy_cufft.h
  cupy/fft/__init__.py
  cupy/fft/config.py
  cupy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:feature

#1920 [backport] Use LF instead of CR+LF
  cupy/core/include/cupy/complex/complex.h
Labels: backport, cat:enhancement

#1904 CuPy external memory pool with memory pool and function pointers
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
Labels: cat:feature

#1650 Implement __array_function__ interface
  cupy/core/core.pyx
Labels: cat:feature

#1922 [backport] fix RecursionError bug in conj method of sparse matrix classes
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/data.py
  cupyx/scipy/sparse/dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: backport, cat:bug

#1881 Support NumPy 1.16
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:enhancement, to-be-backported

#1843 Add the `order` kwarg to `cupy.reshape` and the underlying `ndarray` method
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/manipulation/shape.py
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:feature, st:test-and-merge

#1923 [backport] Support NumPy 1.16
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: backport, cat:enhancement

#1926 Set size attribute of externally allocated memory
  cupy/cuda/memory.pyx
Labels: cat:bug

#1907 Fix ndarray initialization bug
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:bug, to-be-backported

#1929 [backport] Fix ufunc performance degradation
  cupy/core/_kernel.pyx
  cupy/core/fusion.py
Labels: backport, cat:enhancement, cat:performance

#1547 Improve matmul perfomance (x3 faster)
  cupy/core/core.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:performance

#1792 Use language level 3 in cythonize
  cupy/core/_kernel.pyx
  cupy/core/_scalar.pyx
  cupy/core/core.pyx
  cupy/core/raw.pyx
  cupy/core/reduction.pxi
  cupy/cuda/compiler.py
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
  cupy/cuda/nvtx.pyx
  cupy/cudnn.pyx
  cupy_setup_build.py
Labels: cat:enhancement, to-be-backported

#1620 Refactor manipulation routines from `core.pyx`
  cupy/core/__init__.py
  cupy/core/_errors.py
  cupy/core/_kernel.pyx
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/core/_ufuncs.py
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/fusion.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/core/reduction.pxi
  cupy/cudnn.pyx
  cupy/manipulation/join.py
  cupy/manipulation/rearrange.py
  cupy/math/sumprod.py
  cupy_setup_build.py
  tests/cupy_tests/core_tests/test_core.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/manipulation_tests/test_dims.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:code-fix

#1939 [backport] Fix `ndim` not using `cdef`
  cupy/core/core.pyx
Labels: backport, cat:code-fix

#1949 Refactor math and indexing routines from `core.pyx`
  cupy/core/__init__.py
  cupy/core/_routines_indexing.pxd
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_math.pxd
  cupy/core/_routines_math.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/math/misc.py
  cupy/math/sumprod.py
  cupy_setup_build.py
  tests/cupy_tests/core_tests/test_scan.py
Labels: cat:code-fix

#1957 [backport] Ignore W503 and W504
  .flake8.cython
Labels: backport, cat:other, st:test-and-merge

#1958 Rename External* to CFunction*
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
Labels: cat:code-fix

#1951 Clean up `internal.pyx` (`prod`)
  cupy/core/_routines_manipulation.pyx
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: cat:code-fix, st:test-and-merge

#1960 [backport] Clean up `internal.pyx` (`prod`)
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: backport, cat:code-fix, st:test-and-merge

#1959 Refactor logic, sorting and statistics routines from `core.pyx`
  cupy/core/__init__.py
  cupy/core/_routines_logic.pxd
  cupy/core/_routines_logic.pyx
  cupy/core/_routines_sorting.pxd
  cupy/core/_routines_sorting.pyx
  cupy/core/_routines_statistics.pxd
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pyx
  cupy/logic/truth.py
  cupy/statistics/order.py
  cupy_setup_build.py
Labels: cat:code-fix, st:test-and-merge

#1944 ensure the input to the CUFFT Plan1D class is C contiguous
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:bug, to-be-backported

#1952 Fix int types
  cupy/cuda/driver.pxd
  cupy/cuda/driver.pyx
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  cupy/cuda/pinned_memory.pxd
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
Labels: cat:code-fix

#1964 [backport] ensure the input to the CUFFT Plan1D class is C contiguous
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: backport, cat:bug

#1963 [backport] Rename Code of Conduct filename
  CODE_OF_CONDUCT.md
Labels: backport, cat:document

#1965 Allow passing `None` as parameters of `Fusion.__call__`
  cupy/core/fusion.pyx
  tests/cupy_tests/core_tests/test_fusion.py
Labels: cat:enhancement

#1968 Fix test to support SciPy 1.12
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
Labels: cat:test, to-be-backported

#1978 Add cupy-cuda100 to README
  README.md
Labels: cat:document, to-be-backported

#1967 Fix `cupy.random.randint` fail with size zero
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#1980 [backport] Add cupy-cuda100 to README
  README.md
Labels: backport, cat:document

#1981 [backport] Fix `cupy.random.randint` fail with size zero
  cupy/random/generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: backport, cat:bug, st:test-and-merge

#1971 [backport] Fix test to support SciPy 1.12
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
Labels: backport, cat:test, st:test-and-merge

#1982 [backport] Fix README image to use URL
  README.md
Labels: backport, cat:document

#1970 Add `out` argument to `ndarray.get` for asynchronous device-to-host copy
  cupy/core/core.pxd
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_get.py
Labels: cat:feature, st:test-and-merge, takeover

#1984 Call free_all_blocks to free CUDA memory
  cupy/cuda/memory.pyx
Labels: cat:bug, to-be-backported

#1987 [backport] Call free_all_blocks to free CUDA memory
  cupy/cuda/memory.pyx
Labels: backport, cat:bug
