Repository cupy/cupy, pull requests merged in 2020-08, with the labels that each got.

#3593 Add `cupy.polysub`
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/polynomial.pyx
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3698 [backport] Fix broken message format
  cupy/cusparse.py
Labels: backport, cat:bug

#3704 Refactor `cupy.poly1d` tests
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:code-fix

#3708 Rename `cupy.creation` submodule to `cupy._creation`
  cupy/__init__.py
  cupy/_creation/__init__.py
  cupy/_creation/basic.py
  cupy/_creation/from_data.py
  cupy/_creation/matrix.py
  cupy/_creation/ranges.py
  cupy/creation/__init__.py
  cupy/cuda/cub.pyx
  cupy/indexing/generate.py
  cupy/random/sample.py
  cupyx/scipy/sparse/compressed.py
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:code-fix

#3722 Fix wrong test file name
  tests/cupy_tests/cuda_tests/test_runtime.py
Labels: cat:test, to-be-backported

#3583 Mark `nonzero` parameters experimental in sparse min/max
  cupyx/scipy/sparse/data.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement, st:test-and-merge

#3679 Work around a known CUB SpMV bug
  cupyx/scipy/sparse/csr.py
Labels: cat:bug

#3726 Rename `cupy.misc` submodule to `cupy._misc`
  cupy/__init__.py
  cupy/_misc/__init__.py
  cupy/_misc/memory_ranges.py
  cupy/_misc/who.py
  cupy/misc/__init__.py
Labels: cat:code-fix

#3590 Add `cupy.polymul`
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/polynomial.pyx
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3595 Add `cupy_backends/cuda/libs/cutensor.pxd`
  cupy/cutensor.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_setup_build.py
Labels: cat:code-fix, st:test-and-merge

#3729 Support `__cuda_array_interface__` in `cupy.poly1d`
  cupy/lib/polynomial.pyx
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3645 Adding scipy.signal functions that are simple wrappers of ndimage functions
  cupyx/__init__.py
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/bsplines.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature

#3697 Refactor `_make_decorator` in helper.py
  cupy/testing/helper.py
Labels: cat:code-fix

#3703 Add `cupy.roots` for Hermitian or symmetric matrix
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/polynomial.pyx
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3721 [backport] Support cuSparse generic API
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cusparse.pxd
  cupy/cuda/cusparse.pyx
  cupy/cusparse.py
  tests/cupy_tests/test_cusparse.py
Labels: backport, blocking, cat:feature, st:test-and-merge

#3654 add cupyx.scipy.ndimage.fourier_shift, fourier_gaussian, fourier_uniform
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/fourier.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
Labels: cat:feature, st:test-and-merge

#3678 Speed up `cupy.vdot`
  cupy/core/core.pyx
Labels: cat:performance

#3743 Fix circular imports
  cupy/math/misc.py
  cupyx/scipy/signal/signaltools.py
Labels: cat:bug, st:test-and-merge

#3754 [backport] Fix wrong test file name
  tests/cupy_tests/cuda_tests/test_runtime.py
Labels: backport, cat:test

#3735 Fix test to run without NCCL
  tests/cupy_tests/cuda_tests/test_nccl.py
Labels: cat:test, st:test-and-merge

#3711 Rename `cupy.indexing` submodule to `cupy._indexing`
  cupy/__init__.py
  cupy/_indexing/__init__.py
  cupy/_indexing/generate.py
  cupy/_indexing/indexing.py
  cupy/_indexing/insert.py
  cupy/_indexing/iterate.py
  cupy/indexing/__init__.py
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:code-fix

#3727 Rename `cupy.padding` submodule to `cupy._padding`
  cupy/__init__.py
  cupy/_padding/__init__.py
  cupy/_padding/pad.py
Labels: cat:code-fix

#3758 Relax tolerance in `TestArrayElementwiseOp::test_doubly_broadcasted_pow`
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:test, to-be-backported

#3752 Correct format of docstrings in creation routines
  cupy/_creation/basic.py
  cupy/_creation/from_data.py
  cupy/_creation/matrix.py
  cupy/_creation/ranges.py
Labels: cat:document, st:test-and-merge, to-be-backported

#3749 Avoid mutation of `os.environ`
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test

#3733 Bump version in Docker images
  docker/python3/Dockerfile
  docs/source/upgrade.rst
Labels: blocking, cat:install, no-compat, st:test-and-merge

#3762 [backport] Relax tolerance in `TestArrayElementwiseOp::test_doubly_broadcasted_pow`
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, blocking, cat:test

#3767 [backport] Correct format of docstrings in creation routines
  cupy/creation/basic.py
  cupy/creation/from_data.py
  cupy/creation/matrix.py
  cupy/creation/ranges.py
Labels: backport, cat:document

#3707 Rename `cupy.binary` submodule to `cupy._binary`
  cupy/__init__.py
  cupy/_binary/__init__.py
  cupy/_binary/elementwise.py
  cupy/_binary/packing.py
  cupy/binary/__init__.py
Labels: cat:code-fix, st:test-and-merge

#3771 [backport] Allow `MatDescriptor` to be pickle-able
  cupy/cusparse.py
  tests/cupy_tests/test_cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: backport, cat:bug, st:test-and-merge

#3763 Skip FFT input checks for some CUDA >= 10.1 cases
  cupy/fft/fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:bug, to-be-backported

#3742 add multi-axis support to cupy.flip
  cupy/manipulation/rearrange.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
Labels: cat:numpy-compat, st:test-and-merge

#3710 Rename `cupy.functional` submodule to `cupy._functional`
  cupy/__init__.py
  cupy/_functional/__init__.py
  cupy/_functional/piecewise.py
  cupy/functional/__init__.py
Labels: cat:code-fix, st:test-and-merge

#3761 [backport] Fix sparse matrix related test failures on CUDA11
  cupyx/scipy/sparse/csr.py
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#3657 [REVIEW] 2D Sparse Slicing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:feature

#3725 Add `cupy.polyval`
  cupy/__init__.py
  cupy/core/_kernel.pyx
  cupy/lib/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/polynomial.pyx
  cupyx/__init__.py
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3775 Fix CUDA 11 multi-GPU FFT bug
  cupy/testing/parameterized.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: blocking, cat:bug, to-be-backported

#3772 Rename submodules under `cupy.random` package
  cupy/random/__init__.py
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupy/random/_permutations.py
  cupy/random/_sample.py
  cupy/testing/random.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
Labels: cat:code-fix

#3790 Temporary fixes for cudnn v8
  tests/cupy_tests/test_cudnn.py
Labels: cat:bug, to-be-backported

#3792 [backport] Skip FFT input checks for some CUDA >= 10.1 cases
  cupy/fft/fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: backport, cat:bug, st:test-and-merge

#3791 More on using `unittest.mock`
  tests/cupy_tests/core_tests/fusion_tests/test_kernel_cache.py
  tests/cupy_tests/core_tests/fusion_tests/test_optimization.py
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test

#3797 [v7] Avoid testing exception type match on NumPy 1.19+
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: blocking, cat:test, st:test-and-merge

#3699 [backport] support order argument in cupy.ones, cupy.full and cupy.eye
  cupy/creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: backport, cat:bug

#3794 [backport] Temporary fixes for cudnn v8
  tests/cupy_tests/test_cudnn.py
Labels: backport, cat:bug

#3798 [backport] Improve cudnn performance when using deterministic mode
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: backport, cat:performance, st:test-and-merge

#3719 Use cublasGemmEx in tensordot_core when CUDA11
  cupy/core/_dtype.pxd
  cupy/core/_dtype.pyx
  cupy/core/core.pyx
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
Labels: cat:enhancement

#3720 [backport] Support CUDA 11.0
  cupy/core/carray.pxi
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupy/cuda/cupy_cuda_common.h
  cupy/cuda/cupy_cudnn.h
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cusparse.pxd
  cupy/cuda/cusparse.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy/cudnn.pyx
  cupy/cusparse.py
  cupy_setup_build.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  install/build.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupy_tests/test_cudnn.py
  tests/cupy_tests/test_cusparse.py
Labels: backport, blocking, cat:feature, st:test-and-merge

#3800 [backport] Fix error message broken
  cupy/cusparse.py
Labels: backport, cat:bug, st:test-and-merge

#3799 [backport] Update CUDA 11.0 FP16 header to production release version (11.0.2)
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
Labels: backport, blocking, cat:code-fix, cat:enhancement, st:test-and-merge

#3803 [v7] Update requirements for CuPy v7.8.0
  docs/source/install.rst
Labels: blocking, cat:document, st:test-and-merge

#3809 [v7] Fix cuSparse build failure on Windows (backport #3690)
  cupy/cuda/cupy_cusparse.h
Labels: cat:bug, st:test-and-merge

#3806 [v7] Install doc: source devtoolset needed in CentOS
  docs/source/install.rst
Labels: blocking, cat:document, st:test-and-merge

#3802 Update docs for v8
  docs/source/contribution.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/reference/environment.rst
  docs/source/reference/index.rst
Labels: blocking, cat:document, st:test-and-merge

#3805 [v7] Skip TestDiaMatrixScipyComparison failing with scipy>=1.5.0
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: blocking, cat:test, st:test-and-merge

#3812 Bump version to v7.8.0
  cupy/_version.py
Labels: cat:other

#3804 Refactor logical routines from `core.pyx`
  cupy/core/__init__.py
  cupy/core/_routines_logic.pxd
  cupy/core/_routines_logic.pyx
  cupy/core/core.pyx
  cupy/logic/ops.py
Labels: cat:code-fix, st:test-and-merge

#3815 Bump Dockerfile version to v7.8.0
  docker/python3/Dockerfile
Labels: cat:other

#3817 Add cupy-cuda110 package to README
  README.md
Labels: cat:document, st:test-and-merge

#3782 Improve 2D sparse row slicing
  cupyx/scipy/sparse/_index.py
Labels: cat:performance, st:test-and-merge

#3807 Fix a broken document
  cupyx/scipy/linalg/solve_triangular.py
Labels: cat:document, st:test-and-merge

#3641 Adding most of scipy.linalg.special_matrices.
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/special_matrices.py
  docs/source/reference/linalg.rst
  tests/cupyx_tests/scipy_tests/linalg_tests/test_special_matrices.py
Labels: cat:feature

#3658 [REVIEW] 2D Sparse Slicing + Row Indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:feature

#3748 Adding scipy.signal.convolve and correlate functions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, st:test-and-merge

#3497 Support negative `axis` in sparse min/max/argmin/argmax
  cupyx/scipy/sparse/data.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement

#3659 [REVIEW] 2D Sparse Slicing + Row & Column Indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:feature

#3700 Improve `cupy.cutensor`
  cupy/core/_reduction.pxd
  cupy/cutensor.pyx
Labels: cat:performance, st:test-and-merge

#3486 [REVIEW] Compressed Sparse Inner Indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:feature

#3818 Fix documents to reflect `CUPY_ACCELERATORS`
  docs/source/install.rst
  docs/source/reference/environment.rst
  docs/source/reference/routines.rst
Labels: blocking, cat:document, st:test-and-merge

#3813 Improve median_filter, rank_filter and percentile_filter
  cupyx/scipy/ndimage/filters.py
Labels: cat:performance, st:test-and-merge

#3786 Fix build and import errors for ROCm
  .pfnci/config.pbtxt
  .pfnci/script.sh
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
  cupy_setup_build.py
  docs/source/install_rocm.rst
  docs/source/reference/cuda.rst
  install/build.py
Labels: cat:hip, st:test-and-merge

#3731 Implement library preloading for wheels
  cupy/__init__.py
  cupy/_environment.py
  cupy/cuda/cudnn.py
  cupyx/tools/__init__.py
  cupyx/tools/install_library.py
  tests/cupyx_tests/tools_tests/__init__.py
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: blocking, cat:feature, st:test-and-merge

#3810 Support TF32
  cupy/core/__init__.py
  cupy/core/core.pxd
  cupy/core/core.pyx
  docs/source/reference/environment.rst
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:enhancement

#3282 Bug: Add check for method in Randomstate seed
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:enhancement, st:test-and-merge

#3706 Remove unnecessary imports in `cupy._sorting`
  cupy/__init__.py
  cupy/_sorting/__init__.py
Labels: cat:code-fix

#3237 Make nvrtc `getPTX` use `bytes` instead of `unicode`
  cupy/cuda/compiler.py
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
  cupy_backends/cuda/libs/nvrtc.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: cat:hip

#3850 Fix typo
  cupyx/scipy/sparse/data.py
Labels: cat:code-fix, st:test-and-merge

#3839 Deprecate `cupy.sparse` package
  cupy/__init__.py
  cupy/sparse/__init__.py
  cupyx/linalg/sparse/solve.py
  cupyx/scipy/sparse/construct.py
  examples/stream/cusparse.py
  tests/cupy_tests/test_numpy_interop.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: blocking, cat:enhancement, no-compat

#3846 Fix test to run without cuDNN
  tests/cupy_tests/test_cudnn.py
Labels: blocking, cat:test, st:test-and-merge

#3844 Install scipy and optuna to Docker image
  docker/python3/Dockerfile
Labels: blocking, cat:install

#3854 Resolve circular imports between `cupy` and `cupyx.scipy`
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/measurements.py
Labels: cat:code-fix, prio:high, st:test-and-merge

#3851 Improve CSR matrix `getrow`, `getcol` and some slicing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
Labels: cat:performance, prio:high, st:test-and-merge

#3644 Add a `compile` method for `RawKernel` and `RawModule`
  cupy/core/raw.pyx
  tests/cupy_tests/core_tests/test_raw.py
Labels: blocking, st:awaiting-author

#3848 Copy input by default for C2R transform
  cupy/fft/fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: blocking, cat:bug

#3617 Fix float16 ndarray input in histogram with CUB
  cupy/statistics/histogram.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: cat:bug

#3842 Support Optuna v2 (install docs)
  docs/source/install.rst
Labels: blocking, cat:document, st:test-and-merge

#3845 Add `path` and `readonly` options to `cupyx.optimizing.optimize`
  cupy/core/_optimize_config.pxd
  cupy/core/_optimize_config.pyx
  cupyx/optimizing/_optimize.py
  tests/cupyx_tests/test_optimize.py
Labels: blocking, cat:enhancement, st:test-and-merge

#3238 Add hiprtc support
  cupy/cuda/compiler.py
  cupy_backends/cuda/libs/cupy_rtc.h
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: cat:hip

#3744 More improvement of `cupy.cutensor`
  cupy/cutensor.pyx
  examples/cutensor/contraction.py
  examples/cutensor/elementwise_binary.py
  examples/cutensor/elementwise_trinary.py
  examples/cutensor/reduction.py
  tests/cupy_tests/test_cutensor.py
Labels: cat:performance, no-compat

#3856 Fix `cupy.sparse.*` deprecation
  cupy/sparse/__init__.py
  cupy/sparse/linalg/__init__.py
Labels: blocking, no-compat, st:test-and-merge

#3126 Add `PythonFunctionAllocator`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: blocking

#3060 add cupy.ndim
  cupy/__init__.py
  tests/cupy_tests/test_ndim.py
Labels: cat:feature, st:awaiting-author

#3732 Deprecate `*_enabled` flags under `cupy.cuda`
  cupy/_sorting/sort.py
  cupy/core/_routines_math.pyx
  cupy/core/_routines_sorting.pyx
  cupy/cuda/__init__.py
  cupy/cuda/cub.pyx
  cupy/cuda/nccl.pyx
  cupy/cuda/nvtx.pyx
  cupy/cuda/thrust.pyx
  cupy/linalg/einsum.py
  cupy/prof/time_range.py
  cupy/statistics/histogram.py
  cupy_backends/cuda/libs/cutensor.pyx
  cupyx/runtime.py
  cupyx/scipy/sparse/csr.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/cuda_tests/test_cusolver.py
  tests/cupy_tests/cuda_tests/test_cutensor.py
  tests/cupy_tests/cuda_tests/test_nccl.py
  tests/cupy_tests/cuda_tests/test_nvtx.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/prof_tests/test_range.py
  tests/cupy_tests/sorting_tests/test_search.py
  tests/cupy_tests/statics_tests/test_histogram.py
  tests/cupy_tests/test_cutensor.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/test_runtime.py
Labels: cat:enhancement, no-compat, st:test-and-merge

#3864 Fix broken link in the installation guide
  docs/source/install.rst
Labels: blocking, cat:document, st:test-and-merge

#3863 Add upgrade guide for v8
  docs/source/upgrade.rst
Labels: blocking, cat:document, st:test-and-merge

#3879 Fix cub not bundled in wheels
  MANIFEST.in
  cupy/core/include/cupy/README.md
  setup.py
Labels: blocking, st:test-and-merge

#3880 [WIP] Fix wheel not loading bundled cuDNN on Windows
  cupy/_environment.py
  cupy_setup_build.py
Labels: blocking

#3882 Bump version to v8.0.0rc1
  cupy/_version.py
Labels: cat:other

#3883 Fix not to use cupy.cuda.* from cupy codebase
  cupy/cuda/cudnn.py
  cupyx/runtime.py
  tests/cupyx_tests/test_runtime.py
Labels: blocking

#3881 Add option to include wheel metadata
  cupy/_environment.py
  cupy_setup_build.py
Labels: blocking

#3889 Bump Dockerfile version to v8.0.0rc1
  docker/python3/Dockerfile
Labels: blocking, cat:other

#3852 Use `_csr_row_index` for CSR matrix major-axis slicing with step
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: cat:performance, prio:high, to-be-backported
