Repository cupy/cupy, pull requests merged in 2020-11, with the labels that each got.

#4203 Add equal_nan toggle for NaN values in array_equal
  cupy/_logic/comparison.py
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: cat:numpy-compat, prio:medium, st:test-and-merge

#4196 Add a note in `free_all_blocks` reference
  cupy/cuda/memory.pyx
Labels: cat:document, prio:medium, st:test-and-merge

#4202 [backport] Rename submodules under `cupyx.linalg` package
  cupyx/linalg/__init__.py
  cupyx/linalg/_solve.py
  cupyx/linalg/sparse/__init__.py
  cupyx/linalg/sparse/_solve.py
  tests/cupyx_tests/linalg_tests/test_solve.py
Labels: backport, cat:code-fix, prio:medium

#4204 [backport] fix broadcasting behavior in ndimage.measurements functions
  cupyx/scipy/ndimage/measurements.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: backport, cat:bug, prio:high

#4225 Remove `cupy.testing.NumpyError`
  cupy/testing/__init__.py
  cupy/testing/helper.py
  tests/cupy_tests/core_tests/fusion_tests/test_routines.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_explog.py
Labels: cat:enhancement, prio:medium

#4178 Remove unused features in `testing.parameterized`
  cupy/testing/__init__.py
  cupy/testing/_bundle.py
  cupy/testing/parameterized.py
  tests/cupy_tests/testing_tests/test_parameterized.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:test, prio:medium

#4227 Fix output dtype of `linalg.norm`
  cupy/linalg/_norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: cat:numpy-compat, prio:medium, st:test-and-merge, to-be-backported

#4230 [backport] Fix output dtype of `linalg.norm`
  cupy/linalg/_norms.py
  tests/cupy_tests/linalg_tests/test_norms.py
Labels: backport, cat:numpy-compat, prio:medium, st:test-and-merge

#4231 Fix an issue in `cupyx.scipy.sparse.linalg.eigsh` with CUDA 9.2
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:enhancement, st:test-and-merge

#4205 Improve coverage of cuBLAS L1 functions
  cupy/cublas.py
  cupy_backends/cuda/hip/cupy_hipblas.h
  cupy_backends/cuda/hip/cupy_hipsolver.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/stub/cupy_cublas.h
  tests/cupy_tests/test_cublas.py
Labels: cat:feature, no-compat, prio:medium

#4155 Add cupyx.scipy.sparse.linalg.svds
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_eigen.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4135 Add `cupy.vectorize`
  cupy/__init__.py
  cupy/_functional/vectorize.py
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
  cupyx/jit/_typerules.py
  cupyx/jit/_types.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:feature, prio:medium

#4211 Add repr of parameterized test and stop adding error message
  cupy/testing/parameterized.py
Labels: cat:test, prio:medium

#4235 Create `cupyx.lapack`
  cupy/cusolver.py
  cupy/linalg/_solve.py
  cupyx/__init__.py
  cupyx/lapack.py
  tests/cupy_tests/test_cusolver.py
  tests/cupyx_tests/test_lapack.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4248 Improve convolve/correlate
  cupy/_math/misc.py
Labels: cat:performance, st:test-and-merge

#4240 Add parallel build feature
  cupy_setup_build.py
Labels: cat:enhancement, prio:medium

#4222 Add cupyx.scipy.sparse.linalg.cg
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_iterative.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4242 Detect the CC of the device when building
  cupy_setup_build.py
  install/build.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4188 [backport] Record Cython build version
  cupy/_util.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
Labels: backport, cat:enhancement, st:test-and-merge

#4250 Add description of env vars for parallel build and auto cc detection
  docs/source/reference/environment.rst
Labels: cat:document, st:test-and-merge

#4233 Refactor `AssertFunctionIsCalled`
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:bug, prio:high, to-be-backported

#4252 Fix tests of `__bytes__`
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:test, to-be-backported

#4253 [backport] Refactor `AssertFunctionIsCalled`
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:bug, prio:high

#4255 [backport] Fix tests of `__bytes__`
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: backport, cat:test, st:test-and-merge

#4215 DOC: add missing functions to the API reference
  cupy/_indexing/insert.py
  cupyx/scipy/ndimage/morphology.py
  docs/source/reference/binary.rst
  docs/source/reference/indexing.rst
  docs/source/reference/logic.rst
  docs/source/reference/manipulation.rst
  docs/source/reference/misc.rst
  docs/source/reference/ndimage.rst
  docs/source/reference/sparse.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#4244 Fix `numpy_cupy_equal` for case that both numpy cupy raise errors
  cupy/testing/helper.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:test, prio:high, to-be-backported

#4257 [backport] DOC: add missing functions to the API reference
  cupy/_indexing/insert.py
  docs/source/reference/binary.rst
  docs/source/reference/indexing.rst
  docs/source/reference/logic.rst
  docs/source/reference/manipulation.rst
  docs/source/reference/misc.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#4145 add spline_filter1d and spline_filter to cupyx.scipy.ndimage.interpolation
  cupy/_misc/memory_ranges.py
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/_spline_prefilter_core.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4261 Use GitHub Actions
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported

#4141 Support cuFFT callbacks
  MANIFEST.in
  cupy/cuda/cufft.pxd
  cupy/cuda/cufft.pyx
  cupy/cuda/cupy_cufftXt.cu
  cupy/cuda/cupy_cufftXt.h
  cupy/fft/__init__.pxd
  cupy/fft/_cache.pyx
  cupy/fft/_callback.pyx
  cupy/fft/_fft.py
  cupy/fft/config.py
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_setup_build.py
  cupyx/scipy/fftpack/_fft.py
  docs/source/reference/fft.rst
  setup.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4265 add spline_filter functions to ndimage docs
  docs/source/reference/ndimage.rst
Labels: cat:document, st:test-and-merge

#4214 Improve performance of `cupyx.scipy.sparse.linalg.eigsh`
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:performance, prio:medium, st:test-and-merge

#4267 Reduce the file size of cuFFT callback modules
  cupy/fft/_callback.pyx
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4273 [backport] Add parallel build feature
  cupy_setup_build.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#4276 Fix possible redefinition of "-ccbin" in `cupy.fft._callback`
  cupy/fft/_callback.pyx
Labels: cat:bug, st:test-and-merge

#4221 Change the wrapper arguments for cuBLAS L2 functions
  cupy/cublas.py
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  tests/cupy_tests/test_cublas.py
Labels: cat:feature, no-compat, prio:medium, st:test-and-merge

#4283 Fix undefined symbols in `cupy.fft._callback`
  cupy/fft/_callback.pyx
Labels: cat:bug, st:test-and-merge

#4260 [backport] Fix `numpy_cupy_equal` for case that both numpy cupy raise errors
  cupy/testing/helper.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: backport, cat:test, prio:high

#4245 Warn non-tuple sequence for multidimensional indexing
  cupy/_creation/ranges.py
  cupy/_indexing/indexing.py
  cupy/core/_routines_indexing.pyx
  cupy/fft/_fft.py
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:numpy-compat, prio:medium, to-be-backported

#4192 Add pytest backend implementation of `testing.parameterize`
  cupy/testing/_pytest_impl.py
  cupy/testing/helper.py
  cupy/testing/parameterized.py
  tests/conftest.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/testing_tests/test_parameterized.py
Labels: cat:test, prio:medium

#4285 [backport] Warn non-tuple sequence for multidimensional indexing
  cupy/_creation/ranges.py
  cupy/_indexing/indexing.py
  cupy/core/_routines_indexing.pyx
  cupy/fft/_fft.py
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: backport, cat:numpy-compat, prio:medium

#4286 [backport] Use GitHub Actions
  .github/workflows/pretest.yml
Labels: backport, cat:test

#4241 Support compile-time constants in CuPy JIT
  cupyx/jit/_compile.py
  cupyx/jit/_typerules.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4234 Use `.imag = 0` at hipFFT workaround
  cupy/fft/_fft.py
Labels: cat:code-fix, prio:low, st:test-and-merge

#4160 Improve cupy.random.randint
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
Labels: cat:performance, prio:medium, st:test-and-merge

#4271 ROCm: Fix filters in `cupyx.scipy.ndimage`
  cupy/core/core.pyx
  cupy/core/include/cupy/math_constants.h
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/special/_convex_analysis.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4073 Add cupy.cusolver.gels that uses cusolverDn<t1><t2>gels
  cupy/cusolver.py
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/hip/cupy_hipsolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/stub/cupy_cusolver.h
  tests/cupy_tests/test_cusolver.py
Labels: cat:feature, prio:medium

#4301 ROCm: fix ndimage interpolation
  cupyx/scipy/ndimage/_interp_kernels.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4308 `DeprecationWaring` on truth value on empty array
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
Labels: cat:numpy-compat, prio:medium, st:test-and-merge

#4303 Bump cuDNN to v8.0.5
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#3917 Add cupy.cusolver.gesv that uses cusolverDn<t1><t2>gesv
  cupy/cusolver.py
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/hip/cupy_hipsolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/stub/cupy_cusolver.h
  tests/cupy_tests/test_cusolver.py
Labels: cat:feature, prio:medium

#4306 Detect Jitify version
  cupy/cuda/__init__.py
  cupy/cuda/cupy_jitify.h
  cupy/cuda/jitify.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
  install/build.py
Labels: cat:enhancement, prio:medium

#4295 Fix issues when coo sparse matrix is created from dense matrix
  cupyx/scipy/sparse/coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:bug, prio:high, st:test-and-merge

#4313 [backport] Bump cuDNN to v8.0.5
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:medium

#4310 Assert the results are bool
  tests/cupy_tests/core_tests/test_ndarray_contiguity.py
  tests/cupy_tests/core_tests/test_ndarray_owndata.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:test

#4318 Fix `cupy.random.bytes` not working
  cupy/random/__init__.py
  tests/cupy_tests/random_tests/test_init.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4299 Skip some failing tests for fp16 + CUDA 9.0
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:test, to-be-backported

#4324 [backport] Skip some failing tests for fp16 + CUDA 9.0
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:test, st:test-and-merge

#4327 [backport] ROCm: Support hipCUB/rocPRIM
  .pfnci/script.sh
  cupy/_environment.py
  cupy/_statistics/histogram.py
  cupy/core/_cub_reduction.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cuda/__init__.py
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
  cupy_setup_build.py
  docs/source/install_rocm.rst
  install/build.py
  tests/cupy_tests/core_tests/test_cub_reduction.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/core_tests/test_raw.py
Labels: backport, cat:hip, prio:medium

#4329 [backport] Defer import in `cupy/_environment.py`
  cupy/_environment.py
Labels: backport, blocking, cat:enhancement, st:test-and-merge

#4332 Bump version to v8.2.0
  cupy/_version.py
Labels: blocking, cat:other

#4331 Bump version to v9.0.0a2
  cupy/_version.py
Labels: blocking, cat:other

#4326 Add import test for ROCm
  .pfnci/script.sh
Labels: cat:test, to-be-backported

#4333 cupy-cuda111 package now on PyPI
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported

#4334 [backport] Add import test for ROCm
  .pfnci/script.sh
  cupy_setup_build.py
Labels: backport, cat:test

#4335 [backport] cupy-cuda111 package now on PyPI
  README.md
  docs/source/install.rst
Labels: backport, cat:document

#4336 Reset extra_compile_args for each module
  cupy_setup_build.py
Labels: cat:install, st:test-and-merge, to-be-backported

#4339 Tentatively hide CUPY_NUM_BUILD_JOBS option
  cupy_setup_build.py
  docs/source/reference/environment.rst
Labels: blocking, cat:install, to-be-backported

#4342 Bump Docker version to v9.0.0a2
  docker/python3/Dockerfile
Labels: cat:other

#4343 Bump Docker version to v8.2.0
  docker/python3/Dockerfile
Labels: cat:other

#4345 Update links to forums in README
  README.md
Labels: cat:document, to-be-backported

#4346 [backport] Update links to forums in README
  README.md
Labels: backport, cat:document

#4269 `testing.numpy_cupy_allclose` with per-dtype tolerance
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, prio:medium

#4348 Fix parallel build
  cupy_setup_build.py
  docs/source/reference/environment.rst
Labels: cat:install, st:test-and-merge, to-be-backported

#4349 [backport] Fix parallel build
  cupy_setup_build.py
Labels: backport, cat:install, st:test-and-merge

#3713 Rename submodules under `cupy.lib`
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_polynomial.pyx
  cupy/lib/_shape_base.py
  cupy/lib/stride_tricks.py
  cupy_setup_build.py
Labels: cat:code-fix, to-be-backported

#4353 [backport] Rename submodules under `cupy.lib`
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_polynomial.pyx
  cupy/lib/stride_tricks.py
  cupy_setup_build.py
Labels: backport, cat:code-fix

#4340 Drop support for Python 3.5 in CuPy v9
  README.md
  docs/source/install.rst
  docs/source/reference/environment.rst
  docs/source/upgrade.rst
  setup.py
Labels: cat:other, no-compat, prio:medium, st:test-and-merge

#4275 Refactor `cupyx.scipy.sparse.linalg.eigsh`
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:code-fix, prio:medium, st:test-and-merge

#4236 Add `cupyx.scipy.sparse.linalg.gmres`
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_iterative.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4341 Add broadcast test for `cupy.vectorize`
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:test, prio:medium, st:test-and-merge

#4304 Fix `testing.helper` to work without `unittest`
  cupy/testing/helper.py
Labels: cat:test, prio:medium, st:test-and-merge

#4293 Simplify `cupy.linalg.inv`
  cupy/linalg/_solve.py
  cupyx/lapack.py
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupyx_tests/test_lapack.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#4355 Apply fixes to the FFT callback module
  cupy/fft/_callback.pyx
  cupy/fft/config.py
  cupy_setup_build.py
Labels: cat:bug, st:test-and-merge

#4287 Refactor `fft_tests`: unittest -> pytest
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:test, prio:medium, st:test-and-merge

#4364 Bump version to v9.0.0a3
  cupy/_version.py
Labels: cat:other, st:test-and-merge
