Repository cupy/cupy, pull requests merged in 2020-10, with the labels that each got.

#4047 Update README and docs for unified tagline
  README.md
  docs/source/index.rst
  setup.py
Labels: cat:document, prio:medium, to-be-backported

#4053 fix typo
  cupy/_sorting/search.py
  cupy/core/_fusion_variable.pyx
  cupy/core/new_fusion.pyx
  cupy/cuda/nvtx.pyx
  cupy/cudnn.pyx
  cupyx/scipy/ndimage/measurements.py
  docs/source/reference/interoperability.rst
  tests/cupy_tests/fft_tests/test_cache.py
Labels: cat:document, prio:medium, to-be-backported

#4008 Add `apply_along_axis`
  cupy/__init__.py
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/lib/shape_base.py
  cupy/manipulation/transpose.py
  docs/source/reference/functional.rst
  tests/cupy_tests/lib_tests/test_shape_base.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
Labels: cat:feature, prio:medium

#4056 [backport] fix typo
  cupy/_sorting/search.py
  cupy/core/_fusion_variable.pyx
  cupy/core/new_fusion.pyx
  cupy/cuda/nvtx.pyx
  cupy/cudnn.pyx
  cupyx/scipy/ndimage/measurements.py
  docs/source/reference/interoperability.rst
  tests/cupy_tests/fft_tests/test_cache.py
Labels: backport, cat:document, prio:medium

#3835 ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 2
  cupy/core/include/cupy/complex/complex.h
  cupy/core/include/cupy/complex/complex_inl.h
  cupy/core/include/cupy/type_dispatcher.cuh
  cupy/cuda/__init__.py
  cupy/cuda/common.pxd
  cupy/cuda/common.pyx
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/runtime.pyx
  tests/cupy_tests/core_tests/test_array_function.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/cuda_tests/test_stream.py
  tests/cupy_tests/test_init.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4035 [backport] Add `CUDA_VERSION` define for Cython compilation
  cupy_setup_build.py
Labels: backport, cat:install, prio:high, st:test-and-merge

#4041 [backport] Require SciPy 1.2 for sparse comparison
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#3870 Rename submodule under `cupy.fft` package
  cupy/_math/misc.py
  cupy/fft/__init__.py
  cupy/fft/_fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/cuda_tests/test_cufft.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: prio:medium, to-be-backported

#3994 Add a kernel for integer GEMM
  cupy/core/core.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:bug, prio:high, to-be-backported

#3616 Split cupy cuda header
  cupy/cuda/cupy_cufft.h
  cupy/cuda/cupy_nvtx.h
  cupy/cuda/nvtx.pyx
  cupy/cuda/texture.pyx
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cublas.h
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/cupy_cuda_runtime.h
  cupy_backends/cuda/cupy_cudnn.h
  cupy_backends/cuda/cupy_curand.h
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/cupy_cusparse.h
  cupy_backends/cuda/cupy_cutensor.h
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_nvrtc.h
  cupy_backends/cuda/cupy_profiler.h
  cupy_backends/cuda/cupy_rtc.h
  cupy_backends/cuda/hip/cupy_common.h
  cupy_backends/cuda/hip/cupy_cuda.h
  cupy_backends/cuda/hip/cupy_hipblas.h
  cupy_backends/cuda/hip/cupy_hiprand.h
  cupy_backends/cuda/hip/cupy_hiprtc.h
  cupy_backends/cuda/hip/cupy_hipsolver.h
  cupy_backends/cuda/hip/cupy_profiler.h
  cupy_backends/cuda/hip/cupy_roctx.h
  cupy_backends/cuda/hip/cupy_runtime.h
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/cupy_cusolver.h
  cupy_backends/cuda/libs/curand.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/cuda/libs/profiler.pyx
  cupy_backends/cuda/stub/cupy_cublas.h
  cupy_backends/cuda/stub/cupy_cuda.h
  cupy_backends/cuda/stub/cupy_cuda_runtime.h
  cupy_backends/cuda/stub/cupy_cudnn.h
  cupy_backends/cuda/stub/cupy_curand.h
  cupy_backends/cuda/stub/cupy_cusolver.h
  cupy_backends/cuda/stub/cupy_cusparse.h
  cupy_backends/cuda/stub/cupy_cutensor.h
  cupy_backends/cuda/stub/cupy_nvrtc.h
  cupy_backends/cuda/stub/cupy_profiler.h
  cupy_setup_build.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#4024 Fix potential segfault when reduction axis is empty
  cupy/core/_cub_reduction.pyx
  cupy/core/_reduction.pyx
  cupy/core/internal.pyx
  cupy/cuda/cub.pxd
  cupy/cuda/cub.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:bug, prio:high, to-be-backported

#4067 [backport] Add a kernel for integer GEMM
  cupy/core/core.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4066 [backport] Rename submodule under `cupy.fft` package
  cupy/_math/misc.py
  cupy/fft/__init__.py
  cupy/fft/_fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: backport, prio:medium

#4065 Bump cuDNN to v8.0.4
  cupyx/tools/install_library.py
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#4060 Move `matmul` from `core.pyx` to `_routine_linalg.pyx`
  cupy/core/__init__.py
  cupy/core/_routines_linalg.pxd
  cupy/core/_routines_linalg.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/cutensor.pyx
  cupy/linalg/decomposition.py
  cupy/linalg/solve.py
  cupy_setup_build.py
  cupyx/linalg/solve.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupy_tests/test_cutensor.py
Labels: cat:code-fix, prio:medium, st:test-and-merge

#4069 [backport] Bump cuDNN to v8.0.4
  cupyx/tools/install_library.py
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: backport, cat:enhancement, prio:medium

#4052 Add missing sparse matrix constructors
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4068 [backport] Fix potential segfault when reduction axis is empty
  cupy/core/_cub_reduction.pyx
  cupy/core/_reduction.pyx
  cupy/core/internal.pyx
  cupy/cuda/cub.pxd
  cupy/cuda/cub.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#3858 Add `cudaGetDeviceProperties`
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cuda_common.h
  cupy_backends/cuda/hip/cupy_common.h
  cupy_backends/cuda/hip/cupy_runtime.h
  cupy_backends/cuda/stub/cupy_cuda_runtime.h
Labels: cat:feature, prio:high, to-be-backported

#4074 [backport] Update README and docs for unified tagline
  README.md
  docs/source/index.rst
  setup.py
Labels: backport, cat:document, prio:medium

#4063 [backport] ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 2
  cupy/core/include/cupy/complex/complex.h
  cupy/core/include/cupy/complex/complex_inl.h
  cupy/core/include/cupy/type_dispatcher.cuh
  cupy/cuda/__init__.py
  cupy/cuda/common.pxd
  cupy/cuda/common.pyx
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/runtime.pyx
  tests/cupy_tests/core_tests/test_array_function.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/cuda_tests/test_stream.py
  tests/cupy_tests/test_init.py
Labels: backport, cat:hip, prio:medium

#3967 Hide private names in `cupy.cusolver`
  cupy/cusolver.py
Labels: cat:code-fix, prio:medium, to-be-backported

#4027 ROCm: Support hipCUB/rocPRIM
  .pfnci/script.sh
  cupy/_environment.py
  cupy/_statistics/histogram.py
  cupy/core/_cub_reduction.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cuda/__init__.py
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
  cupy_setup_build.py
  docs/source/install_rocm.rst
  install/build.py
  tests/cupy_tests/core_tests/test_cub_reduction.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:hip, prio:medium, st:test-and-merge

#3768 Show numpy and scipy versions in `show_config`
  cupyx/_runtime.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#3936 Support cublasXgetrsBatched and add cupy.cublas.batched_gesv
  cupy/cublas.py
  cupy/linalg/solve.py
  cupy_backends/cuda/hip/cupy_hipblas.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/stub/cupy_cublas.h
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupy_tests/test_cublas.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4070 Add `generate_matrix` to `cupy.testing`
  cupy/testing/__init__.py
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, prio:medium

#4071 Add `*svdjBatched` prototypes
  cupy_backends/cuda/libs/cusolver.pxd
Labels: cat:enhancement, prio:medium

#4076 [backport] Hide private names in `cupy.cusolver`
  cupy/cusolver.py
Labels: backport, cat:code-fix, prio:medium

#4075 Add @ operator support to cupyx.scipy.sparse
  cupyx/scipy/sparse/base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, prio:medium

#4057 Move `_normalize_axis_index` to `cupy/core/internal.pyx`
  cupy/_math/sumprod.py
  cupy/_util.pyx
  cupy/core/_fusion_trace.pyx
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_math.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/lib/shape_base.py
  cupy/linalg/product.py
  cupy/manipulation/rearrange.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/fourier.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:code-fix, prio:medium, to-be-backported

#3426 Code fix on tests for `cupyx.scipy.ndiamge` stats functions
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:test, st:test-and-merge, to-be-backported

#4031 Add cython bindings to cuSPARSE csrsv2/csrsm2 related functions
  cupy_backends/cuda/cupy_cusparse.h
  cupy_backends/cuda/libs/cusparse.pxd
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4085 Workaround cudaPointerGetAttributes error in CUDA 10.2+
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4089 [backport] Workaround cudaPointerGetAttributes error in CUDA 10.2+
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: backport, cat:bug, prio:high

#4086 [backport] Move `_normalize_axis_index` to `cupy/core/internal.pyx`
  cupy/_math/sumprod.py
  cupy/_util.pyx
  cupy/core/_fusion_trace.pyx
  cupy/core/_routines_math.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/linalg/product.py
  cupy/manipulation/rearrange.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/fourier.py
Labels: backport, cat:code-fix, prio:medium

#4081 Add work-around for issue in cutensorReduction of cuTENSOR 1.2.1
  cupy/cutensor.pyx
Labels: cat:bug, prio:high, to-be-backported

#4091 Add `order` option in `cupy.testing.shaped_random`
  cupy/testing/helper.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4098 [backport] Add work-around for issue in cutensorReduction of cuTENSOR 1.2.1
  cupy/cutensor.pyx
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4103 [backport] Add `cudaGetDeviceProperties`
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/cupy_cuda_common.h
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
Labels: backport, cat:feature, prio:high

#4097 Add complex dtype support in cupy.nanmin and cupy.nanmax
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:feature

#4084 Fix `argmax` and `argmin` for F-order inputs
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: cat:bug, prio:high, st:blocked-by-another-pr, st:test-and-merge, to-be-backported

#4079 [backport] Show numpy and scipy versions in `show_config`
  cupyx/_runtime.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4104 [backport] Add `order` option in `cupy.testing.shaped_random`
  cupy/testing/helper.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: backport, cat:feature, prio:medium

#4018 Improve `cupy.in1d`
  cupy/_logic/truth.py
Labels: cat:performance, prio:medium

#4106 [backport] Fix `argmax` and `argmin` for F-order inputs
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: backport, cat:bug, prio:high

#4062 Fix CUB block reduction for F-order arrays with ndim > 2
  cupy/core/_cub_reduction.pyx
  cupy/core/_reduction.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:bug, prio:high, to-be-backported

#4109 [backport] Fix CUB block reduction for F-order arrays with ndim > 2
  cupy/core/_cub_reduction.pyx
  cupy/core/_reduction.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4108 ROCm: Fix `getDeviceProperties` for HIP
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupyx/_runtime.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#4112 Add `cupy.append` and `cupy.resize`
  cupy/__init__.py
  cupy/manipulation/add_remove.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4087 [backport] Improve the plan cache documentation
  cupy/fft/_cache.pyx
  docs/source/reference/fft.rst
  docs/source/reference/plan_cache.rst
Labels: backport, cat:document, prio:medium

#4114 Add compute capability checking for cublasGemmEx()
  cupy/core/_routines_linalg.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#4092 Add cupy.nanmedian
  cupy/__init__.py
  cupy/_statistics/meanvar.py
  cupy/core/_routines_statistics.pyx
  docs/source/reference/statistics.rst
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4096 Fix `argmax`/`argmin` in CUB block reduction for F-order arrays with ndim > 1
  cupy/core/_cub_reduction.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, prio:high, to-be-backported

#3902 Rename submodules under `cupyx.scipy.special`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_convex_analysis.py
  cupyx/scipy/special/_digamma.py
  cupyx/scipy/special/_erf.py
  cupyx/scipy/special/_gamma.py
  cupyx/scipy/special/_gammaln.py
  cupyx/scipy/special/_polygamma.py
  cupyx/scipy/special/_statistics.py
  cupyx/scipy/special/_zeta.py
Labels: cat:code-fix, prio:medium, to-be-backported

#4116 [backport] Rename `cupyx.rsqrt` submodule
  cupyx/__init__.py
  cupyx/_rsqrt.py
Labels: backport, cat:code-fix, prio:medium

#4119 [backport] Rename submodules under `cupyx.scipy.special`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_convex_analysis.py
  cupyx/scipy/special/_digamma.py
  cupyx/scipy/special/_erf.py
  cupyx/scipy/special/_gamma.py
  cupyx/scipy/special/_gammaln.py
  cupyx/scipy/special/_polygamma.py
  cupyx/scipy/special/_statistics.py
  cupyx/scipy/special/_zeta.py
Labels: backport, cat:code-fix, prio:medium

#4055 Support pickling `cupy.RawKernel`
  cupy/core/raw.pxd
  cupy/core/raw.pyx
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:enhancement, prio:high, to-be-backported

#4117 [backport] Fix typos in `cupy.cuda.cufft`
  cupy/cuda/cufft.pyx
Labels: backport, cat:bug, prio:high

#4110 ROCm: Build on latest ROCm
  .pfnci/script.sh
  cupy_setup_build.py
Labels: cat:bug, cat:hip, prio:medium, st:test-and-merge, to-be-backported

#4115 [backport] Fix `argmax`/`argmin` in CUB block reduction for F-order arrays with ndim > 1
  cupy/core/_cub_reduction.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4077 Add cupy.nancumsum and cupy.nancumprod
  cupy/__init__.py
  cupy/_math/sumprod.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:feature, prio:medium, st:test-and-merge

#3716 Rename `cupy.manipulation` submodule to `cupy._manipulation`
  cupy/__init__.py
  cupy/_indexing/generate.py
  cupy/_manipulation/__init__.py
  cupy/_manipulation/add_remove.py
  cupy/_manipulation/basic.py
  cupy/_manipulation/dims.py
  cupy/_manipulation/join.py
  cupy/_manipulation/kind.py
  cupy/_manipulation/rearrange.py
  cupy/_manipulation/shape.py
  cupy/_manipulation/split.py
  cupy/_manipulation/tiling.py
  cupy/_manipulation/transpose.py
  cupy/_misc/memory_ranges.py
  cupy/manipulation/__init__.py
  cupy/polynomial/polyutils.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#4113 [backport] ROCm: Fix `getDeviceProperties` for HIP
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
Labels: backport, cat:bug

#4058 allow non-contiguous array input to binary morphology functions
  cupyx/scipy/ndimage/morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4048 Simplify ROCm install guide
  docs/source/install_rocm.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#4099 ROCm: Support RCCL
  .pfnci/script.sh
  cupy/cuda/cupy_nccl.h
  cupy_setup_build.py
  docs/source/install_rocm.rst
  install/build.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4059 improve performance of binary morphology for fully nonzero structuring elements
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/morphology.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4083 handle np.nan and np.inf constant values properly in ndimage functions
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4128 [backport] Simplify ROCm install guide
  docs/source/install_rocm.rst
Labels: backport, cat:document, prio:medium

#4124 Fix 64-bit int types in `type_dispatcher.cuh`
  cupy/core/include/cupy/type_dispatcher.cuh
Labels: cat:bug, prio:high, to-be-backported

#4123 [backport] Move `matmul` from `core.pyx` to `_routine_linalg.pyx`
  cupy/core/__init__.py
  cupy/core/_routines_linalg.pxd
  cupy/core/_routines_linalg.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/cutensor.pyx
  cupy/linalg/decomposition.py
  cupy/linalg/solve.py
  cupy_setup_build.py
  cupyx/linalg/solve.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupy_tests/test_cutensor.py
Labels: backport, cat:code-fix, prio:medium

#4134 [backport] Fix 64-bit int types in `type_dispatcher.cuh`
  cupy/core/include/cupy/type_dispatcher.cuh
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4133 [backport] handle np.nan and np.inf constant values properly in ndimage functions
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: backport, cat:bug, prio:high

#4064 Add cupy.cusolver.gels
  cupy/cusolver.py
  tests/cupy_tests/test_cusolver.py
Labels: cat:feature, prio:medium

#4137 Add `compute_35` for CUDA 11.0+
  cupy_setup_build.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4142 Fix device properties for cuda 9.2
  cupy_backends/cuda/api/runtime.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#3979 add several functions to cupyx.scipy.ndimage.measurements
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/measurements.py
  docs/source/reference/ndimage.rst
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:feature, prio:medium

#3969 Hide private names in `cupy.cutensor`
  cupy/cutensor.pyx
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#4140 [backport] Add `compute_35` for CUDA 11.0+
  cupy_setup_build.py
Labels: backport, cat:bug, prio:high

#4144 DOC: Add note about starting nvprof with profiling off
  cupy/cuda/__init__.py
Labels: cat:document, st:test-and-merge

#4147 [backport] Hide private names in `cupy.cutensor`
  cupy/cutensor.pyx
Labels: backport, cat:code-fix, prio:medium

#4146 Fix docstrings of `cupyx.scipy.ndimage.{minimum,maximum}_position`
  cupyx/scipy/ndimage/measurements.py
Labels: cat:document

#4126 [backport] ROCm: Build on latest ROCm
  .pfnci/script.sh
  cupy_setup_build.py
Labels: backport, cat:bug, cat:hip, prio:medium

#4130 fix mode='opencv' case in cupyx.scipy.ndimage.affine_transform
  cupyx/scipy/ndimage/interpolation.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4151 fix broadcasting behavior in ndimage.measurements functions
  cupyx/scipy/ndimage/measurements.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4159 Fix `polyfit` tests tolerance
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:test, prio:medium, to-be-backported

#4154 [backport] Support pickling `cupy.RawKernel`
  cupy/core/raw.pxd
  cupy/core/raw.pyx
  tests/cupy_tests/core_tests/test_raw.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4158 [backport] fix mode='opencv' case in cupyx.scipy.ndimage.affine_transform
  cupyx/scipy/ndimage/interpolation.py
Labels: backport, cat:bug, prio:high

#4162 Defer import in `cupy/_environment.py`
  cupy/_environment.py
Labels: cat:enhancement, st:test-and-merge

#4169 Use `testing.assert_warns`
  tests/cupy_tests/polynomial_tests/test_polynomial.py
Labels: cat:test, prio:medium

#4167 Fix `argwhere` for 0d inputs
  cupy/_sorting/search.py
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, prio:high, to-be-backported

#4173 Fix to use current stream properly with CUDA-related libraries
  cupy_backends/cuda/stream.pyx
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#4175 [backport] Fix to use current stream properly with CUDA-related libraries
  cupy_backends/cuda/stream.pyx
Labels: backport, blocking, cat:bug, prio:high

#4174 [backport] Fix `argwhere` for 0d inputs
  cupy/_sorting/search.py
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:bug, prio:high

#4161 Improve `cupy.cuda.cub.device_segmented_reduce()`
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
Labels: cat:performance, prio:medium

#4152 [backport] Fix device properties for cuda 9.2
  cupy_backends/cuda/api/runtime.pyx
Labels: backport, cat:bug, st:test-and-merge

#4094 Make parameterized dtype test skip by `pytest.skip`
  cupy/testing/helper.py
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/indexing_tests/test_iterate.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, prio:medium, to-be-backported

#3712 Rename `cupy.io` submodule to `cupy._io`
  cupy/__init__.py
  cupy/_io/__init__.py
  cupy/_io/formatting.py
  cupy/_io/npz.py
  cupy/_io/text.py
  cupy/io/__init__.py
Labels: cat:code-fix, to-be-backported

#4149 Fix tests that have side effects
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:test, prio:medium, to-be-backported

#4182 [backport] Code fix on tests for `cupyx.scipy.ndiamge` stats functions
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: backport, cat:test

#4183 [backport] Rename `cupy.io` submodule to `cupy._io`
  cupy/__init__.py
  cupy/_io/__init__.py
  cupy/_io/formatting.py
  cupy/_io/npz.py
  cupy/_io/text.py
  cupy/io/__init__.py
Labels: backport, cat:code-fix

#4181 [backport] Rename `cupy.manipulation` submodule to `cupy._manipulation`
  cupy/__init__.py
  cupy/_indexing/generate.py
  cupy/_manipulation/__init__.py
  cupy/_manipulation/add_remove.py
  cupy/_manipulation/basic.py
  cupy/_manipulation/dims.py
  cupy/_manipulation/join.py
  cupy/_manipulation/kind.py
  cupy/_manipulation/rearrange.py
  cupy/_manipulation/shape.py
  cupy/_manipulation/split.py
  cupy/_manipulation/tiling.py
  cupy/_manipulation/transpose.py
  cupy/_misc/memory_ranges.py
  cupy/manipulation/__init__.py
  cupy/polynomial/polyutils.py
Labels: backport, cat:code-fix

#4179 [backport] Make parameterized dtype test skip by `pytest.skip`
  cupy/testing/helper.py
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/indexing_tests/test_iterate.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:test, prio:medium

#3899 Rename submodule under `cupyx.scipy.fft`
  cupyx/scipy/fft/__init__.py
  cupyx/scipy/fft/_fft.py
Labels: cat:code-fix, prio:medium, to-be-backported

#3741 Rename submodules under `cupy.linalg` package
  cupy/__init__.py
  cupy/cublas.py
  cupy/cusolver.py
  cupy/linalg/__init__.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_eigenvalue.py
  cupy/linalg/_einsum.py
  cupy/linalg/_einsum_opt.py
  cupy/linalg/_norms.py
  cupy/linalg/_product.py
  cupy/linalg/_solve.py
  cupy/linalg/_util.py
  cupyx/linalg/solve.py
  cupyx/linalg/sparse/solve.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/linalg/solve_triangular.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: to-be-backported

#4185 [backport] Fix tests that have side effects
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: backport, cat:test, prio:medium

#4164 Record Cython build and runtime versions
  cupy/_util.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#4156 Enhance dtype error message in testing helpers
  cupy/testing/helper.py
Labels: cat:test, prio:medium, st:test-and-merge

#3784 Rename submodules under `cupyx.linalg` package
  cupyx/linalg/__init__.py
  cupyx/linalg/_solve.py
  cupyx/linalg/sparse/__init__.py
  cupyx/linalg/sparse/_solve.py
  tests/cupyx_tests/linalg_tests/test_solve.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#4187 [backport] Rename submodules under `cupy.linalg` package
  cupy/__init__.py
  cupy/cusolver.py
  cupy/linalg/__init__.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_eigenvalue.py
  cupy/linalg/_einsum.py
  cupy/linalg/_einsum_opt.py
  cupy/linalg/_norms.py
  cupy/linalg/_product.py
  cupy/linalg/_solve.py
  cupy/linalg/_util.py
  cupyx/linalg/solve.py
  cupyx/linalg/sparse/solve.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/linalg/solve_triangular.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: backport

#4186 [backport] Rename submodule under `cupyx.scipy.fft`
  cupyx/scipy/fft/__init__.py
  cupyx/scipy/fft/_fft.py
Labels: backport, cat:code-fix, prio:medium

#4150 Fix cupyx.seterr() when `linalg` not supplied
  cupyx/_ufunc_config.py
  tests/cupyx_tests/test_cupyx.py
Labels: cat:bug, prio:high, to-be-backported

#4168 Fix `nonzero` for 0d inputs
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, prio:high, to-be-backported

#4189 [backport] Fix cupyx.seterr() when `linalg` not supplied
  cupyx/_ufunc_config.py
  tests/cupyx_tests/test_cupyx.py
Labels: backport, cat:bug, prio:high

#4190 [backport] Fix `nonzero` for 0d inputs
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4138 Add cupyx.scipy.sparse.linalg.eigsh
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium

#4184 Add support for CUDA 11.1
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:feature, st:test-and-merge

#4180 [backport] Add compute capability checking for cublasGemmEx()
  cupy/core/_routines_linalg.pyx
Labels: backport, cat:bug

#4191 [backport] Add support for CUDA 11.1
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: backport, cat:feature

#4194 Bump version to v9.0.0a1
  cupy/_version.py
Labels: cat:other

#4195 Bump version to v8.1.0
  cupy/_version.py
Labels: cat:other

#4207 Bump Docker version to v9.0.0a1
  docker/python3/Dockerfile
Labels: cat:other

#4208 Bump Docker version to v8.1.0
  docker/python3/Dockerfile
Labels: cat:other

#4210 Add cupy-cuda111 to README
  README.md
  docs/source/install.rst
Labels: cat:document

#4206 Use Python 3.6 in Travis CI
  .travis.yml
Labels: cat:test, st:test-and-merge

#4212 [backport] Add cupy-cuda111 to README
  README.md
  docs/source/install.rst
Labels: backport, cat:document

#4157 fix: respect user-supplied output array in all binary morphology functions
  cupyx/scipy/ndimage/morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported
