Repository cupy/cupy, pull requests merged in 2020-12, with the labels that each got.

#4289 Support CUB-backed `cupy.ReductionKernel` and `@cupy.fuse`
  cupy/core/_cub_reduction.pxd
  cupy/core/_cub_reduction.pyx
  cupy/core/_fusion_op.py
  cupy/core/_reduction.pyx
  cupy/core/fusion.pyx
Labels: cat:feature, prio:medium, st:test-and-merge

#4320 Make names of test classes start with `Test`
  tests/cupy_tests/core_tests/fusion_tests/test_example.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/testing_tests/test_parameterized.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:code-fix, prio:medium, to-be-backported

#4307 Refactor ndimage_tests
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:test, prio:medium, st:test-and-merge

#4373 Remove travis
  .github/workflows/pretest.yml
  .travis.yml
  README.md
  docs/source/contribution.rst
  setup.py
Labels: cat:test, to-be-backported

#4372 [backport] Make names of test classes start with `Test`
  tests/cupy_tests/core_tests/fusion_tests/test_example.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/testing_tests/test_parameterized.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: backport, cat:code-fix, prio:medium, st:test-and-merge

#4370 add cupy.quantile
  cupy/__init__.py
  cupy/_statistics/order.py
  docs/source/reference/statistics.rst
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4377 Fix cufft callback manager error in Windows
  cupy/fft/config.py
Labels: cat:bug, st:test-and-merge

#4378 Configure Mergify to check GitHub Actions instead of Travis
  .mergify.yml
Labels: st:test-and-merge, to-be-backported

#4379 [backport] Fix cufft callback manager error in Windows
  cupy/fft/config.py
Labels: backport, cat:bug

#4381 [backport] Configure Mergify to check GitHub Actions instead of Travis
  .mergify.yml
Labels: backport, cat:other, st:test-and-merge

#4376 [backport] Remove travis
  .github/workflows/pretest.yml
  .travis.yml
  README.md
  docs/source/contribution.rst
  setup.py
Labels: backport, cat:test, st:test-and-merge

#4384 [backport] Reset extra_compile_args for each module
  cupy_setup_build.py
Labels: backport, cat:install, st:test-and-merge

#4278 add scipy.fft module to the API comparison table
  docs/requirements.txt
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported

#4391 [backport] add scipy.fft module to the API comparison table
  docs/requirements.txt
  docs/source/_comparison_generator.py
Labels: backport, cat:document, st:test-and-merge

#4394 Require SciPy >= 1.4 in `TestGmres`
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test

#4263 Change the wrapper arguments for cuBLAS L3 functions
  cupy/core/_routines_linalg.pyx
  cupy/core/core.pyx
  cupy/cublas.py
  cupy/linalg/_solve.py
  cupy_backends/cuda/hip/cupy_hipblas.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/stub/cupy_cublas.h
  cupyx/lapack.py
  cupyx/scipy/linalg/solve_triangular.py
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupy_tests/test_cublas.py
Labels: cat:enhancement, no-compat

#4385 Fix some FFT test issues
  cupy/testing/attr.py
  tests/cupy_tests/fft_tests/test_callback.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:test, prio:high, st:test-and-merge

#4338 Add `cudaLaunchHostFunc`
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/hip/cupy_common.h
  cupy_backends/cuda/hip/cupy_runtime.h
  cupy_backends/cuda/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:feature, prio:medium

#4284 Add `cupyx.scipy.sparse.csr_matrix.diagonal` and `cupyx.scipy.sparse.csr_matrix.setdiag`
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, prio:medium

#4291 add batched cholesky solver
  cupyx/lapack.py
  cupyx/linalg/_solve.py
  tests/cupyx_tests/linalg_tests/test_solve.py
  tests/cupyx_tests/test_lapack.py
Labels: cat:feature, prio:medium

#4365 Fix `rcond` arg of `linalg.lstsq`
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:bug, prio:medium, st:test-and-merge, to-be-backported

#4368 Parameterize sparse matrix tests
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, prio:medium

#4404 Add support for cuTENSOR 1.2.2
  cupy_setup_build.py
Labels: cat:install, st:test-and-merge

#4388 Refactor test of `linalg.lstsq`
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:test, prio:medium, st:test-and-merge, to-be-backported

#4399 Fix `poly1d`
  cupy/lib/_polynomial.pyx
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:enhancement, prio:medium

#4258 [REVIEW] Add `cupyx.scipy.sparse.linalg.interface` that exposes LinearOperator Feature
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_interface.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium

#4411 Run FFT callback test only on Linux
  tests/cupy_tests/fft_tests/test_callback.py
Labels: cat:test, prio:high, st:test-and-merge

#4410 DOC: Incorrect environment variable description
  docs/source/reference/environment.rst
Labels: cat:document, st:test-and-merge

#4408 [backport] Fix `rcond` arg of `linalg.lstsq`
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: backport, cat:bug, prio:medium, st:test-and-merge

#4397 Inherit environment variable and detect cl.exe automatically
  cupy/cuda/compiler.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#4417 [backport] Inherit environment variable and detect cl.exe automatically
  cupy/cuda/compiler.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#4413 Refactor `TestLinearOperator`
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, prio:medium, st:test-and-merge

#4420 Require SciPy 1.4 in `TestLinearOperator`
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test

#4390 Fix `linalg.lstsq` for complex types
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:bug, to-be-backported

#4425 [backport] Refactor test of `linalg.lstsq`
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#4426 [backport] Fix `linalg.lstsq` for complex types
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: backport, cat:bug, st:test-and-merge

#4314 revise dtype handling in cupyx.scipy.ndimage.spline_filter
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:enhancement, st:test-and-merge

#4311 cupyx.ndimage.measurements: add center_of_mass, histogram, labeled_comprehension
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/measurements.py
  docs/source/reference/ndimage.rst
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4316 Improve `scan_core` in cupy/core/_routines_math.pyx
  cupy/core/_routines_math.pyx
Labels: cat:performance, prio:medium, st:test-and-merge

#4264 Replace stubs in ndimage by Jitify
  cupy/cuda/jitify.pyx
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
Labels: cat:code-fix, prio:medium, st:test-and-merge

#4422 Add support for `LinearOperator` to `cg` and `gmres` in `cupyx.scipy.sparse.linalg`.
  cupyx/scipy/sparse/linalg/_iterative.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium

#4418 Add `cupy.interp`
  cupy/__init__.py
  cupy/_math/misc.py
  cupy/_sorting/search.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:feature, prio:medium

#4366 Improve `scan` in cupy/core/_routines_math.pyx.
  cupy/core/_routines_math.pyx
Labels: cat:performance, prio:medium, st:test-and-merge

#4416 Disentangle HIP from CUDA in the build script
  .pfnci/script.sh
  cupy_setup_build.py
  install/build.py
Labels: cat:install, prio:medium, st:test-and-merge, to-be-backported

#4198 Fix ndarray binary operations with non-CuPy arrays to return `NotImplemented`
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
  cupy/core/core.pyx
  tests/cupy_tests/test_numpy_interop.py
Labels: cat:enhancement, prio:high

#4361 add cupyx.scipy.ndimage.fourier_ellipsoid
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/fourier.py
  docs/source/reference/ndimage.rst
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4356 Add `cupyx.scipy.sparse.linalg.spsolve_triangular`
  cupy/cusparse.py
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupy_tests/test_cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4382 Add `tril`, `triu` and `find` to `cupyx.scipy.sparse`
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/extract.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_extract.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4438 Add `spsolve_triangular` to the reference
  docs/source/reference/sparse.rst
Labels: cat:document, st:test-and-merge

#4357 Update CUDA Array Interface to v3 - Part 1
  cupy/_util.pyx
  cupy/core/core.pyx
  cupy/cuda/stream.pyx
  docs/source/reference/environment.rst
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:enhancement, to-be-backported

#4437 Fix `cupy.searchsorted` on HIP
  cupy/_sorting/search.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4439 Fix out-of-bound access in ndimage rank filters
  cupyx/scipy/ndimage/filters.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4446 [backport] Update CUDA Array Interface to v3 - Part 1
  cupy/_util.pyx
  cupy/core/core.pyx
  cupy/cuda/stream.pyx
  docs/source/reference/environment.rst
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: backport, cat:enhancement, st:test-and-merge

#4447 [backport] Fix `cupy.searchsorted` on HIP
  cupy/_sorting/search.py
Labels: backport, cat:bug, prio:high

#4449 [backport] Fix out-of-bound access in ndimage rank filters
  cupyx/scipy/ndimage/filters.py
Labels: backport, cat:bug, prio:high

#4375 Add `cupyx.scipy.sparse.linalg.spsolve`
  cupy/cusolver.py
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  docs/source/reference/sparse.rst
  tests/cupy_tests/test_cusolver.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4428 Add support for `LinearOperator` to `eigsh` and `svds` in `cupyx.scipy.sparse.linalg`
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, prio:medium

#4441 Fix doc of `LinearOperator`
  cupyx/scipy/sparse/linalg/_interface.py
Labels: cat:document, prio:medium

#4452 Support complex types in `solve_triangular`
  cupyx/scipy/linalg/solve_triangular.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#4386 [backport] Fix comment in docs/source/reference/statistics.rst
  docs/source/reference/statistics.rst
Labels: backport, cat:document

#4323 [backport] Fix `cupy.random.bytes` not working
  cupy/random/__init__.py
  tests/cupy_tests/random_tests/test_init.py
Labels: backport, cat:bug, prio:high

#4325 Update `[jenkins]` requirement
  setup.py
Labels: cat:test, prio:medium, to-be-backported

#4458 Fix `__cuda_array_interface__` for HIP
  cupy/core/core.pyx
Labels: cat:bug, prio:high, st:test-and-merge

#4319 Fix docs of `cupy.random` functions/methods
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupy/random/_permutations.py
  cupy/random/_sample.py
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#4442 Refactor traceback in testing.helper
  cupy/testing/helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:code-fix, prio:medium

#3683 Adding C++ constructors for CArray and CIndexer
  cupy/core/include/cupy/carray.cuh
Labels: cat:enhancement, st:test-and-merge

#4460 Fix overwritten issue in `cumsum` and `cumprod`
  cupy/core/_routines_math.pyx
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:bug, st:test-and-merge

#4462 [backport] Add support for cuTENSOR 1.2.2
  cupy_setup_build.py
Labels: backport, cat:install, st:test-and-merge

#4464 Fixing minor TODO in scan.
  cupy/core/_routines_math.pyx
Labels: cat:performance, prio:medium, st:test-and-merge

#4400 ndimage: support all interpolation boundary modes
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_spline_prefilter_core.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4459 [backport] Support complex types in `solve_triangular`
  cupyx/scipy/linalg/solve_triangular.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4457 cupy.random.normal: fix broadcasting of scale and loc arguments
  cupy/random/_distributions.py
  tests/cupy_tests/random_tests/test_distributions.py
Labels: cat:bug, prio:high, st:test-and-merge

#3828 Adding cupyx.scipy.signal.fftconvolve
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium, st:awaiting-author

#4473 [backport] Update `[jenkins]` requirement
  setup.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#4474 [backport] Fix docs of `cupy.random` functions/methods
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupy/random/_permutations.py
  cupy/random/_sample.py
Labels: backport, cat:document, prio:medium, st:test-and-merge

#3857 Remove broken support for macOS
  cupy_setup_build.py
  docs/source/contribution.rst
  install/build.py
Labels: cat:install, prio:medium, st:test-and-merge, to-be-backported

#4239 Set `__module__` attr to parameterized class
  cupy/testing/_bundle.py
  cupy/testing/_pytest_impl.py
Labels: cat:test, prio:medium, st:test-and-merge

#4477 Exclude unsupported dtypes for TestOrderFilter
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test

#4463 Update to use the new CArray and CIndexer constructors
  cupyx/scipy/ndimage/_filters_generic.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4453 Eliminate read past end of array in percentile_weightnening
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:bug, prio:high, st:test-and-merge

#4461 Skip large size test for hip
  tests/cupy_tests/core_tests/test_carray.py
Labels: cat:hip, prio:medium

#4480 [backport] Exclude unsupported dtypes for TestOrderFilter
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: backport, cat:test, st:test-and-merge

#4481 Fix TestEntropy: Requires scipy>=1.4.0 for `axis` parameter
  tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py
Labels: cat:test, st:test-and-merge

#4482 Disable `__cuda_array_interface__` for HIP
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
Labels: cat:enhancement, prio:medium

#4479 Deprecations for v9
  cupy/core/core.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_setup_build.py
  cupyx/tools/install_library.py
  docs/source/install.rst
  docs/source/upgrade.rst
  install/build.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: cat:enhancement, no-compat, prio:high

#4472 Fix raw kernel test
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test, prio:medium

#4491 fix dev info allocation
  cupy/cusolver.py
Labels: cat:bug, prio:high

#4500 Bump version to v8.3.0
  cupy/_version.py
Labels: cat:other

#4499 Bump version to v9.0.0b1
  cupy/_version.py
Labels: cat:other

#4470 Use `--device-c` for RDC compile
  cupy/cuda/compiler.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4501 [backport] Fix dev info allocation
  cupy/cusolver.py
Labels: backport, cat:bug, prio:high

#4403 Show type of error in `numpy_cupy_*` decorators
  cupy/testing/helper.py
Labels: cat:test, prio:medium

#4505 [backport] Use `--device-c` for RDC compile
  cupy/cuda/compiler.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4367 Improve `cupy.argwhere` and `cupy.nonzero`
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_math.pxd
  cupy/core/_routines_math.pyx
Labels: cat:performance, prio:medium, st:test-and-merge

#4226 Test FutureWarning
  setup.cfg
  tests/cupy_tests/test_cusolver.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
  tests/cupyx_tests/test_lapack.py
Labels: prio:medium, to-be-backported

#4510 [backport] Test FutureWarning
  setup.cfg
Labels: backport, cat:test, prio:medium, st:test-and-merge

#4488 Refactor axis errors
  cupy/_indexing/indexing.py
  cupy/_manipulation/join.py
  cupy/core/_reduction.pyx
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_sorting.pyx
  cupy/core/fusion.pyx
  cupy/core/internal.pyx
Labels: cat:code-fix, prio:medium

#4507 Update PyTest
  setup.py
Labels: cat:test, st:test-and-merge

#4402 ndimage: implement higher order spline interpolation
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_spline_kernel_weights.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:enhancement, no-compat, prio:medium, st:test-and-merge
