Repository cupy/cupy, pull requests merged in 2020-05, with the labels that each got.

#3321 Ensure runtime context on a per-device basis
  cupy/cuda/runtime.pyx
Labels: cat:bug, st:test-and-merge

#3315 Use `shape_t` instead of `tuple`
  cupy/core/_carray.pxd
  cupy/core/_carray.pyx
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
Labels: cat:code-fix, st:test-and-merge

#3307 Add cupy.bartlett
  cupy/__init__.py
  cupy/math/window.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_window.py
Labels: cat:feature, st:test-and-merge

#3312 Enhancement: Performance Improvements to blackman, hanning and hamming methods
  cupy/math/window.py
Labels: cat:enhancement, st:test-and-merge

#3328 Fix `put` when using scalars
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: cat:bug, to-be-backported

#3335 `cupy.around` behaves differently from NumPy for EVEN_NUMBER+0.5
  cupy/core/core.pyx
  cupy/math/rounding.py
  tests/cupy_tests/core_tests/test_ndarray_math.py
Labels: cat:numpy-compat, st:test-and-merge, takeover

#3338 [backport] Remove upper restrictions for numpy and scipy in doc build
  docs/requirements.txt
Labels: backport, cat:document

#3333 Add mean for sparse matrices
  cupyx/scipy/sparse/data.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, takeover

#3332 [backport] Fix `put` when using scalars
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: backport, cat:bug, st:test-and-merge

#3336 [backport] Support sorting complex arrays
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/thrust.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: backport, cat:enhancement, st:test-and-merge

#3330 Support multiple architectures in `CUPY_NVCC_GENERATE_CODE`
  cupy_setup_build.py
  docs/source/reference/environment.rst
Labels: cat:enhancement, st:test-and-merge

#3311 Fix scipy version check in cupyx.scipy.fft
  cupyx/scipy/fft/fft.py
Labels: cat:bug, st:test-and-merge

#3271 Show versions of cub and cutensor on `cupy.show_config`
  cupy/cuda/cupy_cutensor.h
  cupy/cuda/cutensor.pyx
  cupyx/runtime.py
Labels: cat:feature, st:test-and-merge, to-be-backported

#3276 Add PFN to the README
  README.md
Labels: cat:document, to-be-backported

#3227 [backport] Fix byte buffer handling to support PyPy
  cupy/cuda/nvrtc.pyx
Labels: backport, cat:bug, st:test-and-merge

#3352 [backport] Add PFN to the README
  README.md
Labels: backport, cat:document, st:test-and-merge

#3353 [backport] Show versions of cub and cutensor on `cupy.show_config`
  cupy/cuda/cupy_cutensor.h
  cupy/cuda/cutensor.pyx
  cupyx/runtime.py
Labels: backport, cat:feature, st:test-and-merge

#3354 Fix `linalg.svd` for 0-sized matrices
  cupy/linalg/decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:bug, to-be-backported

#3250 Implement `flatiter.base` property
  cupy/indexing/iterate.py
  docs/source/conf.py
  tests/cupy_tests/indexing_tests/test_iterate.py
Labels: cat:feature

#3331 Assign a workpace to `ormqr` functions in `_solve`
  cupy/linalg/solve.py
Labels: cat:bug, to-be-backported

#3251 Implement `flatiter.__len__()` special method.
  cupy/indexing/iterate.py
  tests/cupy_tests/indexing_tests/test_iterate.py
Labels: cat:feature, st:test-and-merge

#3356 [backport] Assign a workpace to `ormqr` functions in `_solve`
  cupy/linalg/solve.py
Labels: backport, cat:bug, st:test-and-merge

#3252 Implement `flatiter.__next__()` special method
  cupy/indexing/iterate.py
  tests/cupy_tests/indexing_tests/test_iterate.py
Labels: cat:feature, st:test-and-merge

#3357 Support `max_duration` argument in `cupyx.time.repeat`
  cupyx/time.py
  tests/cupyx_tests/test_time.py
Labels: cat:feature, st:test-and-merge

#3347 Reduce memory usage of `cupy.linalg.svd`
  cupy/linalg/decomposition.py
Labels: cat:performance, st:test-and-merge, takeover

#3355 [backport] Fix `linalg.svd` for 0-sized matrices
  cupy/linalg/decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: backport, cat:bug, st:test-and-merge

#3341 Use local cache in `cupy.RawKernel`
  cupy/core/raw.pxd
  cupy/core/raw.pyx
Labels: cat:performance, st:test-and-merge

#2731 Optimize kernel launch parameters
  cupy/core/_optimize_config.pxd
  cupy/core/_optimize_config.pyx
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy_setup_build.py
  cupyx/__init__.py
  cupyx/optimizing/__init__.py
  cupyx/optimizing/_optimize.py
Labels: cat:feature, st:test-and-merge

#3345 [backport] Remove some xfails in sorting tests
  cupy/core/_routines_sorting.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: backport, cat:bug

#2606 Support primitive complex scalar in `RawKernel`
  cupy/cuda/function.pyx
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:enhancement, st:test-and-merge

#3242 Support cuSparse generic API
  cupy/cuda/cupy_cusparse.h
  cupy/cuda/cusparse.pxd
  cupy/cuda/cusparse.pyx
  cupy/cusparse.py
  cupyx/scipy/sparse/coo.py
  tests/cupy_tests/test_cusparse.py
Labels: cat:feature

#3363 Add tests for optimizer for kernel launch parameters
  cupy/core/_optimize_config.pyx
  cupy/core/_reduction.pyx
  tests/cupyx_tests/test_optimize.py
Labels: cat:test, st:test-and-merge

#3365 Fix too small `max_total_time_per_trial`
  cupy/core/_optimize_config.pyx
Labels: cat:enhancement, st:test-and-merge

#3367 Support OptimizeContext serialization
  cupy/core/_optimize_config.pxd
  cupy/core/_optimize_config.pyx
  cupy/core/_reduction.pyx
  tests/cupyx_tests/test_optimize.py
Labels: cat:feature, st:test-and-merge

#3260 Fix the internal streams in multi-GPU Plan1d
  cupy/cuda/cufft.pyx
Labels: cat:enhancement

#3376 Bump version to v8.0.0b3
  cupy/_version.py
Labels: cat:other

#3377 Bump version to v7.5.0
  cupy/_version.py
Labels: cat:other

#3379 Fix windows
  cupy_setup_build.py
Labels: cat:bug, st:test-and-merge

#3361 Add `cupy.who`
  cupy/__init__.py
  cupy/misc/__init__.py
  cupy/misc/who.py
  docs/source/reference/index.rst
  docs/source/reference/misc.rst
  tests/cupy_tests/misc_tests/test_who.py
Labels: cat:feature, takeover
