Repository cupy/cupy, pull requests merged in 2020-01, with the labels that each got.

#2883 Fix `test_helper.py` for NumPy 1.18
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, to-be-backported

#2890 [backport] Fix `argmin`/`argmax` `dtype` argument
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pyx
  cupy/sorting/search.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: backport, cat:bug

#2895 [backport] Fix `testing.shaped_random` for shape `()`
  cupy/testing/helper.py
  tests/cupy_tests/random_tests/test_permutations.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:bug

#2899 Readability fix in `memory.pyx`
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
Labels: cat:code-fix

#2901 Ignore error when peer access is already enabled
  cupy/cuda/cupy_cuda_common.h
  cupy/cuda/memory.pyx
  cupy/cuda/runtime.pxd
Labels: cat:enhancement, st:test-and-merge

#2776 update slicing of CSR and CSC matrices for compatibility with SciPy 1.4.0
  cupyx/scipy/sparse/compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement, no-compat

#2923 Fix complex type checks in `_correlate_or_convolve`
  cupyx/scipy/ndimage/filters.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2897 Make `cupyx.time.repeat` experimental
  cupyx/time.py
Labels: cat:other, st:test-and-merge

#2913 [backport] Fix `test_helper.py` for NumPy 1.18
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:test, st:test-and-merge

#2912 [backport] Fix `test_helper.py` for NumPy 1.18
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:test, st:test-and-merge

#2846 skip zero valued coefficients in cupyx.scipy.ndimage.convolve
  cupyx/scipy/ndimage/filters.py
Labels: cat:enhancement, st:test-and-merge

#2924 [backport] Fix complex type checks in `_correlate_or_convolve`
  cupyx/scipy/ndimage/filters.py
Labels: backport, cat:bug, st:test-and-merge

#2888 Make test helper decorators pdb-friendly
  cupy/testing/helper.py
Labels: cat:enhancement, st:test-and-merge

#2909 Fix logic to check explicit `size` argument in `ElementwiseKernel`
  cupy/core/_kernel.pyx
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: cat:bug, st:test-and-merge

#2917 Clean up `_scalar.pyx`
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/_scalar.pxd
  cupy/core/_scalar.pyx
Labels: cat:code-fix

#2927 Avoid 0s in the diagonal of `TestSolveTriangular` inputs
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2929 [backport] Avoid 0s in the diagonal of `TestSolveTriangular` inputs
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: backport, cat:test

#2930 [backport] Avoid 0s in the diagonal of `TestSolveTriangular` inputs
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: backport, cat:test

#2921 Fix `cupy.cuda.cub.device_segmented_reduce()` not being used
  cupy/cuda/cub.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#2894 Add Mergify configuration file
  .mergify.yml
Labels: cat:other, to-be-backported

#2934 [backport] Add Mergify configuration file
  .mergify.yml
Labels: backport, cat:other

#2933 [backport] Add Mergify configuration file
  .mergify.yml
Labels: backport, cat:other

#2931 Add tests for size argument with no input
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: cat:test, st:test-and-merge

#2936 [backport] Fix `cupy.cuda.cub.device_segmented_reduce()` not being used
  cupy/cuda/cub.pyx
Labels: backport, cat:bug

#2688 Improve caching in `ElementwiseKernel`
  cupy/core/_kernel.pyx
Labels: cat:performance, st:test-and-merge

#2915 Sets the default value for `thread_local.linalg` if not defined
  cupy/linalg/util.py
  cupyx/_ufunc_config.py
Labels: cat:bug, to-be-backported

#2937 [backport] Sets the default value for `thread_local.linalg` if not defined
  cupy/linalg/util.py
  cupyx/_ufunc_config.py
Labels: backport, cat:bug

#2914 Allow `ElementwiseKernel` to set the block_size
  cupy/core/_kernel.pyx
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: cat:feature, st:test-and-merge

#2932 Improve error message for wrong number of arguments in elementwise kernels
  cupy/core/_kernel.pyx
Labels: cat:enhancement, st:test-and-merge

#2940 Enhance type and argument manipulation in elementwise and reduction kernels
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pxd
  cupy/core/_reduction.pyx
Labels: cat:code-fix, st:test-and-merge

#2925 Support grid synchronization in `RawKernel` and `RawModule`
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/raw.pxd
  cupy/core/raw.pyx
  cupy/cuda/compiler.py
  cupy/cuda/cupy_cuda.h
  cupy/cuda/driver.pxd
  cupy/cuda/driver.pyx
  cupy/cuda/function.pyx
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:feature, st:test-and-merge

#2948 Update cuTENSOR version in docs
  docs/source/install.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#2953 Document `get_allocator` function
  docs/source/reference/cuda.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#2942 Use asynchronous copy in `cupy.copyto`
  cupy/manipulation/basic.py
Labels: cat:enhancement

#2955 [backport] Update cuTENSOR version in docs
  docs/source/install.rst
Labels: backport, cat:document

#2922 Skip some tests for irfftn
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:test, to-be-backported

#2928 Use cuTensor for einsum
  cupy/linalg/einsum.py
Labels: cat:enhancement

#2949 silence sign comparison warnings
  cupy/core/_routines_manipulation.pyx
Labels: cat:code-fix

#2957 [backport] Document device synchronization
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pyx
  cupy/indexing/generate.py
  cupy/indexing/insert.py
  cupy/manipulation/add_remove.py
  cupy/random/generator.py
  cupy/sorting/search.py
  cupy/statistics/histogram.py
  cupy/statistics/meanvar.py
  cupy/statistics/order.py
Labels: backport, cat:document

#2954 [backport] Document `get_allocator` function
  docs/source/reference/cuda.rst
Labels: backport, cat:document

#2943 Avoid invalid in-place division in CUB-based mean
  cupy/core/_routines_statistics.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#2941 Fix `ParameterInfo` as a cache key
  cupy/core/_kernel.pyx
Labels: cat:bug

#2959 [backport] Show warning for cuFFT bug in irfftn
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: backport, cat:test

#2962 [backport] Show warning for cuFFT bug in irfftn
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: backport, cat:test

#2963 Bump version to v7.1.0
  cupy/_version.py
Labels: cat:other

#2964 Bump version to v6.7.0
  cupy/_version.py
Labels: cat:other

#2968 Bump Docker version to v6.7.0
  docker/python2/Dockerfile
  docker/python3/Dockerfile
Labels: cat:other

#2961 [backport] Fix `ParameterInfo` as a cache key
  cupy/core/_kernel.pyx
Labels: backport, cat:bug, st:test-and-merge

#2874 Disallow boolean subtraction
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_routines_math.pyx
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:numpy-compat, st:test-and-merge

#2947 Make `cupyx.allow_synchronize` experimental
  cupy/core/syncdetect.py
Labels: cat:other, st:test-and-merge, to-be-backported

#2972 Fix import of `_get_axis`
  cupy/cuda/cub.pyx
Labels: cat:bug, st:test-and-merge, to-be-backported

#2981 `MemoryPointer.__repr__`
  cupy/cuda/memory.pyx
Labels: cat:enhancement, st:test-and-merge

#2974 Rename arg of `isscalar`
  cupy/__init__.py
  tests/cupy_tests/logic_tests/test_type_test.py
Labels: cat:numpy-compat, no-compat, st:test-and-merge

#2975 Fix `linspace(..., num=1, endpoint=False, retstep=True)`
  cupy/creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: cat:numpy-compat, st:test-and-merge, to-be-backported

#2990 [backport] Fix `linspace(..., num=1, endpoint=False, retstep=True)`
  cupy/creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: backport, cat:numpy-compat

#2980 Remove dependency to six
  .pfnci/py27and35.Dockerfile
  .pfnci/py37.Dockerfile
  cupy/__init__.py
  cupy/core/_dtype.pyx
  cupy/core/_kernel.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_scalar.pyx
  cupy/core/core.pyx
  cupy/core/fusion.pyx
  cupy/core/raw.pyx
  cupy/cuda/compiler.py
  cupy/cuda/function.pyx
  cupy/cuda/memory.pyx
  cupy/fft/fft.py
  cupy/indexing/generate.py
  cupy/linalg/einsum.py
  cupy/linalg/product.py
  cupy/linalg/solve.py
  cupy/manipulation/basic.py
  cupy/manipulation/dims.py
  cupy/math/sumprod.py
  cupy/random/generator.py
  cupy/random/sample.py
  cupy/testing/condition.py
  cupy/testing/helper.py
  cupy/testing/parameterized.py
  cupy/util.pyx
  cupyx/runtime.py
  cupyx/scipy/ndimage/interpolation.py
  cupyx/scipy/sparse/base.py
  docs/source/conf.py
  examples/cg/cg.py
  examples/gmm/gmm.py
  examples/kmeans/kmeans.py
  setup.py
  tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py
  tests/cupy_tests/core_tests/fusion_tests/test_array.py
  tests/cupy_tests/core_tests/fusion_tests/test_function.py
  tests/cupy_tests/core_tests/test_array_function.py
  tests/cupy_tests/core_tests/test_elementwise.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/cuda_tests/memory_hooks_tests/test_debug_print.py
  tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupy_tests/cuda_tests/test_device.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/io_tests/test_npz.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
  tests/cupy_tests/sorting_tests/test_count.py
  tests/cupy_tests/testing_tests/test_array.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/example_tests/test_finance.py
  tests/example_tests/test_gmm.py
  tests/example_tests/test_kmeans.py
Labels: cat:code-fix

#2988 A nit-picking code fix
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:code-fix

#2992 Allow multiple axes in `expand_dims`
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/manipulation/dims.py
  tests/cupy_tests/manipulation_tests/test_dims.py
Labels: cat:enhancement, st:test-and-merge

#2960 Improve performance of element-wise `einsum` where no contraction is necessary
  cupy/linalg/einsum.py
Labels: cat:performance, st:test-and-merge

#2859 Add `ptp` ndarray method and function
  cupy/__init__.py
  cupy/core/_routines_statistics.pxd
  cupy/core/_routines_statistics.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/statistics/order.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/statics_tests/test_order.py
Labels: cat:feature, st:test-and-merge

#3000 [backport] Add nogil to CUB
  cupy/cuda/cub.pyx
Labels: backport, cat:enhancement

#3001 [backport] Fix an issue using non-existing attribute in cub.pyx
  cupy/cuda/cub.pyx
Labels: backport, cat:bug

#3002 Rename `_op` variable in cub.pyx
  cupy/cuda/cub.pyx
Labels: cat:code-fix, st:test-and-merge

#3004 Remove code paths for unsupported Python versions
  cupy/__init__.py
  cupy/core/core.pyx
  cupyx/fallback_mode/fallback.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupyx_tests/__init__.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:code-fix, st:test-and-merge
