Repository cupy/cupy, pull requests merged in 2020-09, with the labels that each got.

#3906 Fix test fail when cudnn is unavailable
  tests/cupy_tests/cuda_tests/test_cudnn.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#3859 Fix 32-bit boundary test to run on Windows
  tests/cupy_tests/core_tests/test_carray.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#3888 Update FP16 header to CUDA 11.0 Update 1 (11.0.3)
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#3911 Add v8 to list of known branch in FlexCI script
  .pfnci/script.sh
Labels: cat:test, prio:high, to-be-backported

#3747 Add `cupy.polyfit`
  cupy/__init__.py
  cupy/lib/__init__.py
  cupy/lib/_routines_poly.py
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature

#3914 [backport] Add v8 to list of known branch in FlexCI script
  .pfnci/script.sh
Labels: backport, cat:test, prio:high

#3898 [backport] Use `_csr_row_index` for CSR matrix major-axis slicing with step
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: backport, cat:performance, prio:high

#3875 Rename `cupyx.scatter` submodule
  cupyx/__init__.py
  cupyx/_scatter.py
Labels: cat:code-fix, prio:medium, to-be-backported

#3910 [backport] Fix test fail when cudnn is unavailable
  tests/cupy_tests/cuda_tests/test_cudnn.py
Labels: backport, cat:test, prio:high, st:test-and-merge

#3542 Support list bins with histogram
  cupy/statistics/histogram.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: cat:enhancement

#3913 [backport] Fix 32-bit boundary test to run on Windows
  tests/cupy_tests/core_tests/test_carray.py
Labels: backport, cat:test, prio:high

#3886 Improve CSR matrix column fancy indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:performance, to-be-backported

#3894 Fix cooperative kernel launch
  cupy/cuda/function.pyx
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:bug, prio:high

#3919 Fix `csr2csc` for zero-size matrix
  cupy/cusparse.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3904 Improve accuracy of cupy.around
  cupy/core/core.pyx
Labels: cat:enhancement, prio:medium

#3912 Hide private names in `cupyx/scipy/__init__.py`
  cupyx/scipy/__init__.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3905 Fix dtype in CSR matrix division
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:bug, prio:high, to-be-backported

#3924 [backport] Fix dtype in CSR matrix division
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#3908 Add `cupy.searchsorted` to doc
  docs/source/reference/sorting.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#3922 [backport] Fix `csr2csc` for zero-size matrix
  cupy/cusparse.py
Labels: backport, cat:bug

#3900 Rename submodule under `cupyx.scipy.fftpack`
  cupyx/scipy/fftpack/__init__.py
  cupyx/scipy/fftpack/_fft.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3766 Proposal: Support transforming NumPy arrays with multi-GPU `Plan1d`
  cupy/cuda/cufft.pyx
  cupy/fft/fft.py
  tests/cupy_tests/cuda_tests/test_cufft.py
Labels: cat:enhancement, st:test-and-merge

#3823 ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 1
  cupy/core/core.pyx
  cupy/core/raw.pyx
  cupy/cuda/compiler.py
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
  cupy_backends/cuda/libs/cublas.pyx
  tests/cupy_tests/core_tests/test_cub_reduction.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/test_cusparse.py
Labels: cat:bug, cat:hip, prio:medium, to-be-backported

#3925 [backport] Add `cupy.searchsorted` to doc
  docs/source/reference/sorting.rst
Labels: backport, cat:document, prio:medium

#3838 Support sparse pointwise division by vectors or matrices
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, prio:medium, st:test-and-merge

#3929 [backport] ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 1
  cupy/core/core.pyx
  cupy/core/raw.pyx
  cupy/cuda/compiler.py
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
  cupy_backends/cuda/libs/cublas.pyx
  tests/cupy_tests/core_tests/test_cub_reduction.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/test_cusparse.py
Labels: backport, cat:bug, cat:hip, prio:medium

#3865 Refactor CSR sparse matrix row fancy indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3930 [backport] Refactor CSR sparse matrix row fancy indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: backport, cat:code-fix, prio:medium

#3921 [backport] Rename `cupyx.scatter` submodule
  cupyx/__init__.py
  cupyx/_scatter.py
Labels: backport, cat:code-fix, prio:medium

#3923 [backport] Hide private names in `cupyx/scipy/__init__.py`
  cupyx/scipy/__init__.py
Labels: backport, cat:code-fix, prio:medium

#3926 [backport] Rename submodule under `cupyx.scipy.fftpack`
  cupyx/scipy/fftpack/__init__.py
  cupyx/scipy/fftpack/_fft.py
Labels: backport, cat:code-fix, prio:medium

#3897 Check format of sparse matrix in `numpy_cupy_array_equal`
  cupy/testing/helper.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#3901 Rename submodules under `cupyx.scipy.sparse`
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/_util.py
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/dia.py
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:code-fix, prio:medium, to-be-backported

#3874 Rename `cupyx.runtime` submodule
  cupyx/__init__.py
  cupyx/_runtime.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3843 ROCm: Support rocTX
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
  cupy_setup_build.py
  install/build.py
Labels: cat:hip, prio:medium, st:test-and-merge

#3779 Rename `cupy.util` submodule to `cupy._util`
  cupy/__init__.py
  cupy/_sorting/search.py
  cupy/_util.pyx
  cupy/core/_cub_reduction.pyx
  cupy/core/_fusion_kernel.pyx
  cupy/core/_fusion_trace.pyx
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_sorting.pyx
  cupy/core/core.pyx
  cupy/core/raw.pyx
  cupy/core/syncdetect.py
  cupy/cuda/compiler.py
  cupy/cuda/device.pyx
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/stream.pyx
  cupy/cudnn.pyx
  cupy/cusolver.py
  cupy/cusparse.py
  cupy/fft/config.py
  cupy/fft/fft.py
  cupy/linalg/einsum.py
  cupy/linalg/product.py
  cupy/logic/truth.py
  cupy/manipulation/rearrange.py
  cupy/math/sumprod.py
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupy_setup_build.py
  cupyx/fallback_mode/__init__.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/fourier.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/data.py
  cupyx/time.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#3774 Rename `cupy.statistics` submodule to `cupy._statistics`
  cupy/__init__.py
  cupy/_statistics/__init__.py
  cupy/_statistics/correlation.py
  cupy/_statistics/histogram.py
  cupy/_statistics/meanvar.py
  cupy/_statistics/order.py
  cupy/statistics/__init__.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#3869 Rename submodule under `cupy.prof` package
  cupy/prof/__init__.py
  cupy/prof/_time_range.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3860 Support sparse pointwise maximum and minimum
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: prio:medium, st:test-and-merge, to-be-backported

#3940 [backport] Rename submodule under `cupy.prof` package
  cupy/prof/__init__.py
  cupy/prof/_time_range.py
Labels: backport, cat:code-fix, prio:medium

#3939 [backport] Rename `cupy.statistics` submodule to `cupy._statistics`
  cupy/__init__.py
  cupy/_statistics/__init__.py
  cupy/_statistics/correlation.py
  cupy/_statistics/histogram.py
  cupy/_statistics/meanvar.py
  cupy/_statistics/order.py
  cupy/statistics/__init__.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: backport, cat:code-fix

#3938 [backport] Rename `cupy.util` submodule to `cupy._util`
  cupy/__init__.py
  cupy/_sorting/search.py
  cupy/_util.pyx
  cupy/core/_cub_reduction.pyx
  cupy/core/_fusion_kernel.pyx
  cupy/core/_fusion_trace.pyx
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/_routines_math.pyx
  cupy/core/_routines_sorting.pyx
  cupy/core/core.pyx
  cupy/core/raw.pyx
  cupy/core/syncdetect.py
  cupy/cuda/compiler.py
  cupy/cuda/device.pyx
  cupy/cuda/pinned_memory.pyx
  cupy/cuda/stream.pyx
  cupy/cudnn.pyx
  cupy/cusolver.py
  cupy/cusparse.py
  cupy/fft/config.py
  cupy/fft/fft.py
  cupy/linalg/einsum.py
  cupy/linalg/product.py
  cupy/logic/truth.py
  cupy/manipulation/rearrange.py
  cupy/math/sumprod.py
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupy_setup_build.py
  cupyx/fallback_mode/__init__.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/fourier.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/data.py
  cupyx/time.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: backport, cat:code-fix

#3937 [backport] Rename `cupyx.runtime` submodule
  cupyx/__init__.py
  cupyx/_runtime.py
Labels: backport, cat:code-fix, prio:medium

#3840 Fix wrong curand enum names
  cupy/random/_generator.py
Labels: cat:document, prio:medium

#3948 Fix `_compressed_sparse_matrix._minor_slice` for step > 1 case
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3934 Fix side effects in some tests
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:test, st:test-and-merge, to-be-backported

#3952 [backport] Fix `_compressed_sparse_matrix._minor_slice` for step > 1 case
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:bug

#3953 [backport] Fix side effects in some tests
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: backport, cat:test

#3955 Fix some test to check compatibility with scipy's behavior
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:test, st:test-and-merge, to-be-backported

#3951 Fix `csr_matrix._get_intXslice` for step < 0 case
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3956 [backport] Fix some test to check compatibility with scipy's behavior
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:test

#3957 [backport] Fix `csr_matrix._get_intXslice` for step < 0 case
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:bug

#3928 Handle transfer to cupy view
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#3959 [backport] Rename submodules under `cupyx.scipy.sparse`
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/_util.py
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/dia.py
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: backport, cat:code-fix, prio:medium

#3942 Use LU-decomposition based solver in cupy.linalg.solver
  cupy/cusolver.py
  cupy/linalg/solve.py
  tests/cupy_tests/test_cusolver.py
Labels: cat:performance, prio:medium, st:test-and-merge

#3962 [backport] Handle transfer to cupy view
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, cat:bug, prio:high

#3964 [backport] Support sparse pointwise division by vectors or matrices
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, cat:feature, prio:medium, st:test-and-merge

#3944 Add `cupy.testing.shaped_sparse_random`
  cupy/testing/__init__.py
  cupy/testing/helper.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:feature, prio:high, st:test-and-merge

#3943 [backport] Support sparse pointwise maximum and minimum
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, prio:medium

#3884 Add cuTENSOR 1.2 support
  cupy/core/__init__.py
  cupy/core/core.pyx
  cupy/cutensor.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  tests/cupy_tests/test_cutensor.py
Labels: cat:enhancement, prio:high, to-be-backported

#3965 Hide private names in `cupyx.time`
  cupyx/time.py
Labels: cat:code-fix, prio:medium, to-be-backported

#3963 ENH: add cupy.gradient
  cupy/__init__.py
  cupy/math/sumprod.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:feature, prio:medium

#3958 Refactor sparse indexing tests
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:test, prio:high, st:blocked-by-another-pr, st:test-and-merge, to-be-backported

#3976 [backport] Add `cupy.testing.shaped_sparse_random`
  cupy/testing/__init__.py
  cupy/testing/helper.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:feature, prio:high

#3977 [backport] Refactor sparse indexing tests
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:test, prio:high

#3978 [v7] Post release 1 for v7.8.0
  cupy/_version.py
Labels: cat:other

#3970 [backport] Add cuTENSOR 1.2 support
  cupy/core/__init__.py
  cupy/core/core.pyx
  cupy/cutensor.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  tests/cupy_tests/test_cutensor.py
Labels: backport, cat:enhancement, prio:high

#3986 [backport] Update FP16 header to CUDA 11.0 Update 1 (11.0.3)
  cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#3950 ROCm: Support more hipBLAS/rocBLAS and rocSOLVER functions
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/cupy_hip_common.h
  cupy_backends/cuda/libs/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_setup_build.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:hip, prio:high, st:test-and-merge

#3960 [backport] Improve CSR matrix column fancy indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
Labels: backport, cat:performance, prio:high, st:test-and-merge

#3947 Add histogram2d and histogramdd
  cupy/__init__.py
  cupy/_statistics/histogram.py
  docs/source/reference/statistics.rst
  tests/cupy_tests/statistics_tests/__init__.py
  tests/cupy_tests/statistics_tests/test_correlation.py
  tests/cupy_tests/statistics_tests/test_histogram.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: prio:medium, st:test-and-merge

#3990 [backport] Hide private names in `cupyx.time`
  cupyx/time.py
Labels: backport, cat:code-fix, prio:medium

#3975 Fix `sparse.__getitem__` not to return view of input
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#3993 [backport] Fix `sparse.__getitem__` not to return view of input
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#3985 Bump cuDNN version to v8.0.3
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, to-be-backported

#3907 add all binary morphology functions to cupyx.scipy.ndimage
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:feature, prio:medium

#3988 ROCm: fix rocBLAS and rocSOLVER version displays
  cupy_backends/cuda/cupy_hip.h
  cupy_backends/cuda/libs/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
Labels: cat:bug, prio:high, st:test-and-merge

#3954 DOC: update cupyx.scipy API documentation
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/signal/signaltools.py
  docs/source/reference/ndimage.rst
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_linalg.rst
  docs/source/reference/signal.rst
  docs/source/reference/special.rst
Labels: prio:medium, st:test-and-merge, to-be-backported

#3533 [REVIEW] Compressed Sparse __setitem__
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: blocking, cat:feature, to-be-backported

#3997 [backport] DOC: update cupyx.scipy API documentation
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/signal/signaltools.py
  docs/source/reference/ndimage.rst
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_linalg.rst
  docs/source/reference/signal.rst
  docs/source/reference/special.rst
Labels: backport, prio:medium

#3981 Improve cupyx.scipy.sparse int x int indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: cat:performance, prio:high, st:test-and-merge, to-be-backported

#3945 Add sparse pointwise equality & inequality functions
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: prio:medium, to-be-backported

#3968 Hide private names in `cupy.cusparse`
  cupy/cusparse.py
Labels: cat:code-fix, prio:medium, to-be-backported

#4003 [backport] Improve cupyx.scipy.sparse int x int indexing
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
Labels: backport, cat:performance, prio:high, st:test-and-merge

#3618 Add different dtype input test in histogram
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:bug, to-be-backported

#3946 Add remaining greyscale morphology operations to `cupyx.scipy.ndimage`
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4002 Add complex dtype support to cupyx.scipy.linalg.lu_factor/solve
  cupyx/scipy/linalg/decomp_lu.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:enhancement

#3998 [backport] Add compressed sparse `__setitem__`
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, blocking, cat:feature, st:test-and-merge

#4004 [backport] Add sparse pointwise equality & inequality functions
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, blocking, prio:medium, st:test-and-merge

#3730 Add a cuFFT plan cache
  cupy/cuda/cufft.pyx
  cupy/fft/_cache.pyx
  cupy/fft/config.py
  cupy/fft/fft.py
  cupy_setup_build.py
  cupyx/scipy/fftpack/_fft.py
  docs/source/reference/fft.rst
  tests/cupy_tests/fft_tests/test_cache.py
Labels: cat:enhancement, to-be-backported

#3995 Add `cupyx.scipy.linalg.lu`
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/decomp_lu.py
  docs/source/reference/scipy_linalg.rst
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:feature, prio:medium

#4011 Fix docs of cupyx.scipy.linalg.lu_factor
  cupyx/scipy/linalg/decomp_lu.py
Labels: cat:document, prio:medium, st:test-and-merge

#4005 [backport] Hide private names in `cupy.cusparse`
  cupy/cusparse.py
Labels: backport, cat:code-fix, prio:medium

#3992 Avoid using CUlinkState unless absolutely necessary
  cupy/cuda/compiler.py
Labels: cat:performance, prio:high, to-be-backported

#4010 [backport] Add a cuFFT plan cache
  cupy/cuda/cufft.pyx
  cupy/fft/_cache.pyx
  cupy/fft/config.py
  cupy/fft/fft.py
  cupy_setup_build.py
  cupyx/scipy/fftpack/_fft.py
  docs/source/reference/fft.rst
  tests/cupy_tests/fft_tests/test_cache.py
Labels: backport, cat:enhancement, st:test-and-merge

#4016 [backport] Avoid using CUlinkState unless absolutely necessary
  cupy/cuda/compiler.py
Labels: backport, cat:performance, prio:high

#3896 ROCm: Support rocFFT/hipFFT
  .pfnci/script.sh
  cupy/cuda/cufft.pxd
  cupy/cuda/cufft.pyx
  cupy/cuda/cupy_cufft.h
  cupy/fft/fft.py
  cupy_setup_build.py
  cupyx/scipy/fftpack/_fft.py
  docs/source/install_rocm.rst
  tests/cupy_tests/fft_tests/test_cache.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4020 Disable github checks annotations of Codecov
  codecov.yml
Labels: cat:other, prio:high, to-be-backported

#4022 [backport] Disable github checks annotations of Codecov
  codecov.yml
Labels: backport, cat:other, prio:high, st:test-and-merge

#3717 Rename `cupy.math` submodule to `cupy._math`
  cupy/__init__.py
  cupy/_math/__init__.py
  cupy/_math/arithmetic.py
  cupy/_math/explog.py
  cupy/_math/floating.py
  cupy/_math/hyperbolic.py
  cupy/_math/misc.py
  cupy/_math/rational.py
  cupy/_math/rounding.py
  cupy/_math/special.py
  cupy/_math/sumprod.py
  cupy/_math/trigonometric.py
  cupy/_math/ufunc.py
  cupy/_math/window.py
  cupy/_statistics/correlation.py
  cupy/math/__init__.py
  cupyx/scipy/signal/signaltools.py
Labels: cat:code-fix, to-be-backported

#3966 Hide private names in `cupy.cudnn`
  cupy/cudnn.pyx
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#3715 Rename `cupy.logic` submodule to `cupy._logic`
  cupy/__init__.py
  cupy/_logic/__init__.py
  cupy/_logic/comparison.py
  cupy/_logic/content.py
  cupy/_logic/ops.py
  cupy/_logic/truth.py
  cupy/_logic/type_test.py
  cupy/_statistics/order.py
  cupy/logic/__init__.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#4013 Improve the plan cache documentation
  cupy/fft/_cache.pyx
  docs/source/reference/fft.rst
  docs/source/reference/plan_cache.rst
Labels: cat:document, prio:medium

#3996 [backport] Bump cuDNN version to v8.0.3
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:high

#4015 Fix managed memory leak
  cupy/cuda/memory.pyx
Labels: cat:bug, prio:high, to-be-backported

#3890 Fix `cupy.ndim` test style
  tests/cupy_tests/test_ndim.py
Labels: cat:test, prio:medium, to-be-backported

#3873 Rename `cupyx.rsqrt` submodule
  cupyx/__init__.py
  cupyx/_rsqrt.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#4014 Fix typos in `cupy.cuda.cufft`
  cupy/cuda/cufft.pyx
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4032 [backport] Fix managed memory leak
  cupy/cuda/memory.pyx
Labels: backport, cat:bug, prio:high

#3877 Add `CUDA_VERSION` define for Cython compilation
  cupy_setup_build.py
Labels: cat:install, prio:high, to-be-backported

#4034 [backport] Fix `cupy.ndim` test style
  tests/cupy_tests/test_ndim.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#4036 Use `__dealloc__` instead of `__del__` for cdef class
  cupy_backends/cuda/libs/cutensor.pyx
Labels: blocking, cat:bug, prio:high, to-be-backported

#4037 [backport] Use `__dealloc__` instead of `__del__` for cdef class
  cupy_backends/cuda/libs/cutensor.pyx
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#3871 Hide private names in `cupy/__init__.py`
  cupy/__init__.py
Labels: prio:medium, to-be-backported

#4038 Fix typo in `_binary_erosion`
  cupyx/scipy/ndimage/morphology.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4039 [backport] Hide private names in `cupy/__init__.py`
  cupy/__init__.py
Labels: backport, prio:medium

#4017 Add `sparse.linalg.norm`
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_norm.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: blocking, cat:feature, prio:high, takeover, to-be-backported

#4028 [backport] Rename `cupy.math` submodule to `cupy._math`
  cupy/__init__.py
  cupy/_math/__init__.py
  cupy/_math/arithmetic.py
  cupy/_math/explog.py
  cupy/_math/floating.py
  cupy/_math/hyperbolic.py
  cupy/_math/misc.py
  cupy/_math/rational.py
  cupy/_math/rounding.py
  cupy/_math/special.py
  cupy/_math/sumprod.py
  cupy/_math/trigonometric.py
  cupy/_math/ufunc.py
  cupy/_math/window.py
  cupy/_statistics/correlation.py
  cupy/math/__init__.py
  cupyx/scipy/signal/signaltools.py
Labels: backport, cat:code-fix

#4029 [backport] Hide private names in `cupy.cudnn`
  cupy/cudnn.pyx
Labels: backport, cat:code-fix, prio:medium

#4040 [backport] Add `sparse.linalg.norm`
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_norm.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: backport, blocking, cat:feature, prio:high, takeover

#4030 [backport] Rename `cupy.logic` submodule to `cupy._logic`
  cupy/__init__.py
  cupy/_logic/__init__.py
  cupy/_logic/comparison.py
  cupy/_logic/content.py
  cupy/_logic/ops.py
  cupy/_logic/truth.py
  cupy/_logic/type_test.py
  cupy/_statistics/order.py
  cupy/logic/__init__.py
Labels: backport, cat:code-fix

#4033 Require SciPy 1.2 for sparse comparison
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:test, prio:medium, st:test-and-merge, to-be-backported

#3765 Use cuTENSOR in `cupy.prod`, `cupy.max`, `cupy.min`, `cupy.ptp` and `cupy.mean`
  cupy/_statistics/order.py
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: blocking, cat:performance, to-be-backported

#4046 [backport] Use cuTENSOR in `cupy.prod`, `cupy.max`, `cupy.min`, `cupy.ptp` and `cupy.mean`
  cupy/_statistics/order.py
  cupy/core/_routines_math.pyx
  cupy/core/_routines_statistics.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/statics_tests/test_order.py
Labels: backport, blocking, cat:performance
