Repository cupy/cupy, pull requests merged in 2020-02, with the labels that each got.

#3012 Fix typo in note
  cupy/linalg/eigenvalue.py
Labels: cat:document, st:test-and-merge

#3015 [backport] Use `size_t nbytes` in `__cuda_array_interface__`
  cupy/core/core.pyx
Labels: backport, cat:bug

#3020 Fix empty vector access
  cupy/cuda/nvrtc.pyx
Labels: cat:bug, to-be-backported

#3021 [backport] Fix empty vector access
  cupy/cuda/nvrtc.pyx
Labels: backport, cat:bug

#3019 [backport] Fix typo in note
  cupy/linalg/eigenvalue.py
Labels: backport, cat:document

#3025 Check size before accesing empty vectors data ptr
  cupy/cuda/nvrtc.pyx
Labels: cat:enhancement, st:test-and-merge

#3024 Make `testing.parameterize` pdb-friendly
  cupy/testing/helper.py
  cupy/testing/parameterized.py
Labels: cat:test

#3026 Use `cupy.random` in kmeans example
  examples/kmeans/kmeans.py
Labels: cat:example

#2998 Add a keyword-only `plan` argument to `cupyx.scipy.fft.*`
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  docs/source/reference/fftpack.rst
  docs/source/reference/scipy_fft.rst
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:feature

#2982 Add `cupy.conjugate` and make `cupy.conj` its alias
  cupy/__init__.py
  cupy/core/__init__.py
  cupy/core/_routines_math.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/math/arithmetic.py
  tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/test_init.py
Labels: cat:feature, st:test-and-merge

#2886 Fix imag for 0-size array
  cupy/core/_routines_math.pyx
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:bug, to-be-backported

#3031 [backport] Fix `get_fft_plan()` and some FFT tests
  cupyx/scipy/fftpack/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: backport, cat:bug

#2979 Print installed packages in pytest
  tests/conftest.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2978 Fix typos in comments
  cupy/core/_kernel.pxd
Labels: cat:code-fix, st:test-and-merge

#2718 Use `intptr_t` for cuSOLVER handles
  cupy/cuda/cusolver.pxd
  cupy/cuda/cusolver.pyx
Labels: cat:code-fix, st:test-and-merge

#3028 Fix nvcc command lookup
  cupy/cuda/_environment.py
  cupy/cuda/compiler.py
Labels: cat:bug, to-be-backported

#3039 [backport] Fix imag for 0-size array
  cupy/core/_routines_math.pyx
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: backport, cat:bug, st:test-and-merge

#3005 Add NumPy 1.18 to installation guide
  docs/source/install.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#2984 Fix an issue that cuComplex_bridge.h is not installed
  setup.py
Labels: cat:install, st:test-and-merge, to-be-backported

#3040 [backport] Fix nvcc command lookup
  cupy/cuda/_environment.py
  cupy/cuda/compiler.py
Labels: backport, cat:bug

#2910 Add CUDA 10.2 support
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.hpp
Labels: cat:enhancement, st:test-and-merge, to-be-backported

#2996 Fix GMM example for matplotlib 3
  examples/gmm/gmm.py
Labels: cat:example

#3042 [backport] Add NumPy 1.18 to installation guide
  docs/source/install.rst
Labels: backport, cat:document

#3043 [backport] Fix an issue that cuComplex_bridge.h is not installed
  setup.py
Labels: backport, cat:install

#3045 [backport] Remove code paths for unsupported Python versions
  cupy/__init__.py
  cupy/core/core.pyx
  cupyx/fallback_mode/fallback.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupyx_tests/__init__.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: backport, cat:code-fix

#3044 [backport] Do not let Python 2 users build CuPy v7+
  setup.py
Labels: backport, cat:install

#3041 Some fixes to `.pfnci/script.sh`
  .pfnci/script.sh
Labels: cat:other, to-be-backported

#2973 Disallow boolean `negative`
  cupy/core/_kernel.pyx
  cupy/core/_routines_math.pyx
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:numpy-compat, st:test-and-merge

#3048 Require `scipy` in `test_gmm`
  tests/example_tests/test_gmm.py
Labels: cat:test

#3050 [backport] Require `scipy` in `test_gmm`
  tests/example_tests/test_gmm.py
Labels: backport, cat:test

#3065 [backport] Print installed packages in pytest
  tests/conftest.py
Labels: backport, cat:test, st:test-and-merge

#3066 [backport] Set CUPY_CI environment variable in Travis CI and AppVeyor
  .travis.yml
  appveyor.yml
Labels: backport, cat:test, st:test-and-merge

#3057 Add cupy-cuda102
  README.md
  docs/source/install.rst
Labels: cat:feature

#3071 Fix ROCm build errors
  cupy/cuda/cupy_hip.h
  cupy/cuda/cupy_hip_common.h
  cupy_setup_build.py
Labels: cat:install

#3072 Bump version to v7.2.0
  cupy/_version.py
Labels: cat:other, st:test-and-merge

#3070 Bump Docker version to v8.0.0a1
  docker/python3/Dockerfile
Labels: cat:other

#3073 [backport] Add cupy-cuda102
  README.md
  docs/source/install.rst
Labels: backport, cat:document, st:test-and-merge

#3084 Skip `irfft` tests for compute capability != 7
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:test

#2907 Improve performance of `cumsum` and `cumprod`
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_math.pxd
  cupy/core/_routines_math.pyx
  cupy/math/sumprod.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:performance

#2461 support array-like start/stop and add axis argument to linspace
  cupy/creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: cat:enhancement

#3074 Remove deprecated `cupy.scatter_add`
  cupy/__init__.py
  cupy/ext/__init__.py
  cupy/ext/scatter.py
  setup.py
  tests/cupy_tests/ext_tests/__init__.py
  tests/cupy_tests/ext_tests/test_scatter.py
Labels: no-compat, st:test-and-merge

#3051 Added a compute capability check for testing grid sync
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2600 Add fp16 support of CUB
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
Labels: cat:enhancement, st:test-and-merge

#3003 Remove custom tempdir context manager
  cupy/cuda/compiler.py
  install/build.py
Labels: cat:code-fix, st:test-and-merge

#2510 Add `get_global()` to `cupy.RawModule`
  cupy/core/raw.pyx
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:feature

#2951 Import `using_allocator` in `cupy.cuda`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:enhancement, no-compat, st:test-and-merge, to-be-backported

#3086 Include `UnownedMemory` in the API docs
  docs/source/reference/cuda.rst
Labels: cat:document, to-be-backported

#3047 [backport] Some fixes to `.pfnci/script.sh`
  .pfnci/script.sh
Labels: backport, cat:other

#3068 Properly decrement total bytes in memory pool
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2983 Added `out` parameter to `cupy.concatenate` and `cupy.stack`
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/manipulation/join.py
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: cat:numpy-compat

#3081 Use `intptr_t` instead of `size_t` for cuSPARSE and cuBLAS handles
  cupy/cuda/cublas.pxd
  cupy/cuda/cublas.pyx
  cupy/cuda/cusparse.pxd
  cupy/cuda/cusparse.pyx
Labels: cat:code-fix, st:test-and-merge

#1950 Clean up `internal.pyx` (`get_contiguous_strides`)
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  tests/cupy_tests/core_tests/test_internal.py
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:code-fix, st:test-and-merge

#3087 [backport] Import `using_allocator` in `cupy.cuda`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:enhancement

#3082 Use `intptr_t` for cuDNN handles
  cupy/cuda/cudnn.pxd
  cupy/cuda/cudnn.pyx
Labels: cat:code-fix, st:test-and-merge

#3096 Remove `IndexOrValueError`
  cupy/core/__init__.py
  cupy/core/_errors.py
  cupy/core/_reduction.pyx
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_manipulation.pyx
  cupy/core/_routines_sorting.pyx
  cupy/core/core.pyx
  cupy/core/fusion.pyx
  cupy/cuda/cub.pyx
  cupy/indexing/indexing.py
  cupy/manipulation/join.py
  cupy/manipulation/rearrange.py
  cupy/testing/helper.py
  cupy/util.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/manipulation_tests/test_dims.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:code-fix, st:test-and-merge

#3046 [backport] Fix GMM example for matplotlib 3
  examples/gmm/gmm.py
Labels: backport, cat:example, st:test-and-merge

#3100 Fix `cub_reduction` for `CUPY_CUB_MIN` and float16 arrays
  cupy/cuda/cupy_cub.cu
Labels: cat:bug, st:test-and-merge

#3101 cupy.pad: update to use cupy.linspace instead of numpy.linspace internally
  cupy/padding/pad.py
  tests/cupy_tests/padding_tests/test_pad.py
Labels: cat:enhancement, st:test-and-merge

#3094 Minor fix to `using_allocator`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
Labels: cat:code-fix, st:test-and-merge

#3056 Fix atol of fft tests
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:test, st:test-and-merge, to-be-backported

#2795 Raise errors instead of assertion on array type checks
  cupy/_sorting/search.py
  cupy/logic/truth.py
  cupy/util.pyx
Labels: cat:enhancement, st:test-and-merge

#3105 [backport] Fix atol of fft tests
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: backport, cat:test, st:test-and-merge

#3054 Use Python scalar as random seed
  cupy/random/generator.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3089 Fix compiler bug when building `cupy.cuda.cub` with CUDA < 9.2
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
Labels: cat:bug, st:test-and-merge, to-be-backported

#3106 [backport] Use Python scalar as random seed
  cupy/random/generator.py
Labels: backport, cat:bug, st:test-and-merge

#3093 [backport] Properly decrement total bytes in memory pool
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:bug

#3099 Rewrite tests not to use `numpy_cupy_raises` cupyx.* tests
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, st:test-and-merge

#3104 add ravel_multi_index
  cupy/__init__.py
  cupy/indexing/generate.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:feature, st:test-and-merge

#3107 Add copyright notice for Random Kit
  cupy/random/_kernels.py
Labels: cat:other, st:test-and-merge, to-be-backported

#3103 Add `compress`
  cupy/__init__.py
  cupy/core/_routines_indexing.pxd
  cupy/core/_routines_indexing.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/indexing/indexing.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:feature, st:test-and-merge

#3121 [backport] Add copyright notice for Random Kit
  cupy/random/_kernels.py
Labels: backport, cat:other, st:test-and-merge

#3123 Fix `reshape` to raise `ValueError` for order 'K'
  cupy/core/internal.pyx
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:numpy-compat, st:test-and-merge

#2391 Add `ndarray` variants AND inplace support in `fallback_mode`
  cupyx/fallback_mode/fallback.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:enhancement, st:awaiting-author

#3120 Add `bitwise_not` as alias to `invert`
  cupy/__init__.py
  cupy/binary/elementwise.py
  cupy/core/core.pyx
  tests/cupy_tests/test_init.py
Labels: cat:feature, st:test-and-merge

#3083 Feature - implementation of np.require in Cupy
  cupy/__init__.py
  cupy/manipulation/kind.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_kind.py
Labels: cat:feature, st:test-and-merge

#1380 Improve cudnn performance when using deterministic mode
  cupy/cudnn.pyx
  tests/cupy_tests/test_cudnn.py
Labels: cat:performance

#3109 Add `extract`
  cupy/__init__.py
  cupy/indexing/indexing.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:feature

#3122 Rewrite manipulation tests not to use `numpy_cupy_raises`
  tests/cupy_tests/manipulation_tests/test_dims.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
  tests/cupy_tests/manipulation_tests/test_shape.py
  tests/cupy_tests/manipulation_tests/test_tiling.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
Labels: cat:test, st:test-and-merge

#3011 Fix `fill_diagonal`
  cupy/indexing/insert.py
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#2644 Support multi-GPU `cupy.cuda.cufft.Plan1d`
  cupy/cuda/cufft.pyx
  cupy/cuda/cupy_cufft.h
  cupy/fft/config.py
  cupy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  docs/source/reference/fft.rst
  docs/source/reference/fftpack.rst
  docs/source/reference/scipy_fft.rst
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:feature

#3049 Add mpi4py examples
  examples/interoperability/mpi4py_multiple_devices.py
Labels: cat:example, st:test-and-merge

#3128 use `time.process_time` instead of `time.clock`
  cupy/random/generator.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3132 [backport] use `time.process_time` instead of `time.clock`
  cupy/random/generator.py
Labels: backport, cat:bug
