Repository cupy/cupy, pull requests merged in 2020-04, with the labels that each got.

#2403 Fix overfow in `matmul` test
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:test, to-be-backported

#3243 Small typo/spelling fixes
  docs/source/reference/difference.rst
Labels: cat:document, to-be-backported

#3034 Fix: n-dimensional FFTs must preserve array contiguity when copying a view
  cupy/fft/fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3207 Fix `cupy.fill_diagonal` to implement with `cupy.flatiter`
  cupy/indexing/insert.py
Labels: cat:code-fix, st:test-and-merge

#3249 [backport] Fix: n-dimensional FFTs must preserve array contiguity when copying a view
  cupy/fft/fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: backport, cat:bug

#3256 Rewrite tests not use `numpy_cupy_raises`
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/creation_tests/test_matrix.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/linalg_tests/test_norms.py
  tests/cupy_tests/linalg_tests/test_product.py
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupy_tests/math_tests/test_matmul.py
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/padding_tests/test_pad.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/statics_tests/test_correlation.py
  tests/cupy_tests/statics_tests/test_histogram.py
  tests/cupy_tests/statics_tests/test_order.py
Labels: cat:test

#3253 Remove unnecessary `Arg` instantiation in `cuda/function.pyx`
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
Labels: cat:performance, st:test-and-merge

#3262 Fix `_reduce_dims` call in reduction
  cupy/core/_reduction.pyx
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:bug, st:test-and-merge

#3248 [backport] Small typo/spelling fixes
  docs/source/reference/difference.rst
Labels: backport, cat:document

#3217 implement `diag_indices` and `diag_indices_from`
  cupy/__init__.py
  cupy/indexing/insert.py
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: cat:feature, st:test-and-merge

#3118 Use larger type to represent index range in `cupy.take`
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3265 [backport] Use larger type to represent index range in `cupy.take`
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: backport, cat:bug

#3239 Add four functions in scipy.ndimage
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/filters.py
  cupyx/scipy/ndimage/morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:feature, st:test-and-merge

#3270 Reduce arg creation cost in `Arg.from_obj`
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
Labels: cat:performance, st:test-and-merge

#3264 Raise `IndexError` for R2C/C2R FFT with `axes=()`
  cupy/fft/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#3037 Add cuTENSOR test
  tests/cupy_tests/test_cutensor.py
Labels: blocking, cat:test

#3272 Use sphinx 2.x on Read the Docs
  docs/requirements.txt
Labels: cat:document, st:test-and-merge

#3245 [backport] Fix overfow in `matmul` test
  tests/cupy_tests/math_tests/test_matmul.py
Labels: backport, cat:test

#3134 Add `cupy.median`
  cupy/__init__.py
  cupy/core/_routines_statistics.pxd
  cupy/core/_routines_statistics.pyx
  cupy/statistics/meanvar.py
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: cat:feature, st:test-and-merge

#3247 Support cusolverDn<t>gesvdjBatched
  cupy/cuda/cupy_cusolver.h
  cupy/cuda/cusolver.pyx
  cupy/cusolver.py
  tests/cupy_tests/test_cusolver.py
Labels: cat:feature, st:test-and-merge

#3278 Improve `norm`
  cupy/linalg/norms.py
Labels: cat:performance

#3288 Simplify `TestEigenvalue`
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:code-fix, st:test-and-merge

#3268 Implementation of `cupy.kaiser`
  cupy/__init__.py
  cupy/math/window.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_window.py
Labels: cat:feature, st:test-and-merge

#3286 Support all dtypes in every sorting function in `cupy.cuda.thrust`
  cupy/core/_routines_sorting.pyx
  cupy/cuda/common.pxd
  cupy/cuda/cupy_common.h
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/cupy_thrust.h
  cupy/cuda/thrust.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:feature

#3291 Code fix + bug fix for `cupy.cuda.thrust`
  cupy/_sorting/sort.py
  cupy/cuda/cupy_thrust.cu
  cupy/cuda/cupy_thrust.h
  cupy/cuda/thrust.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:bug

#3281 improve efficiency of cupy.pad for some simple cases
  cupy/padding/pad.py
Labels: cat:enhancement, st:test-and-merge

#3102 Add R2C/C2R support to `cupy.cuda.cufft.PlanNd`
  cupy/cuda/cufft.pyx
  cupy/fft/fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
Labels: cat:enhancement

#2279 Add notification support for fallback_mode
  cupyx/_ufunc_config.py
  cupyx/fallback_mode/fallback.py
  cupyx/fallback_mode/notification.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:feature

#3299 Bump version to v8.0.0b2
  cupy/_version.py
Labels: cat:other

#3304 Bump version in Dockerfile to v7.4.0
  docker/python3/Dockerfile
Labels: cat:other

#3298 Improve `ElementwiseKernel` cpu time
  cupy/core/_kernel.pyx
Labels: cat:performance

#3294 Support surface memory in `RawKernel`
  cupy/cuda/cupy_cuda.h
  cupy/cuda/cupy_cuda_common.h
  cupy/cuda/cupy_hip_common.h
  cupy/cuda/function.pyx
  cupy/cuda/runtime.pxd
  cupy/cuda/runtime.pyx
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  docs/source/reference/cuda.rst
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: cat:feature, st:test-and-merge

#3280 ENH: support additional dtypes and axis sequences in cupy.median
  cupy/core/_routines_statistics.pyx
  tests/cupy_tests/statics_tests/test_meanvar.py
Labels: cat:enhancement, st:test-and-merge

#3166 rewrite cupyx.scipy.ndimage.interpolation using ElementwiseKernel
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:performance

#3293 Enable getting R2C/C2R FFT plans from `get_fft_plan()`
  cupy/fft/fft.py
  cupyx/scipy/fft/fft.py
  cupyx/scipy/fftpack/fft.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Labels: cat:feature

#3261 implement putmask function
  cupy/__init__.py
  cupy/indexing/insert.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_insert.py
Labels: cat:feature, st:test-and-merge

#3310 Alias of shape type
  cupy/core/_carray.pxd
  cupy/core/_carray.pyx
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_reduction.pyx
  cupy/core/_routines_indexing.pyx
  cupy/core/_routines_manipulation.pxd
  cupy/core/_routines_manipulation.pyx
  cupy/core/core.pxd
  cupy/core/core.pyx
  cupy/core/internal.pxd
  cupy/core/internal.pyx
  cupy/cudnn.pyx
Labels: cat:code-fix, st:test-and-merge
