Repository cupy/cupy, pull requests merged in 2021-07, with the labels that each got.

#5337 Add tests for num_to_num's optional parameters
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:test, prio:medium, st:test-and-merge

#5423 [backport] Enable strict xfail in pytest
  setup.cfg
Labels: backport, cat:test, prio:high, st:test-and-merge

#5387 JIT: Support all atomic intrinsics
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#5405 [backport] JIT: Fix supported dtype of `atomic_add` on HIP
  cupyx/jit/_builtin_funcs.py
Labels: backport, cat:bug, prio:medium

#5278 Add upgrade guide for v10
  docs/source/upgrade.rst
Labels: cat:document, prio:medium

#5426 Fix `unwrap` tests for v9
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: cat:test, prio:high

#5362 Add HIP symbol redefinitions
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pyx
  cupy/_core/include/cupy/hip_workaround.cuh
  cupyx/jit/_builtin_funcs.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:code-fix, st:test-and-merge, to-be-backported

#5422 [backport] JIT: Fix `__call__()` for built-in functions
  cupyx/jit/_builtin_funcs.py
Labels: backport, cat:code-fix

#5432 Fix typo in `apply_along_axis`
  cupy/lib/_shape_base.py
Labels: cat:document, prio:medium, to-be-backported

#5428 Fix compatibility issues of `ndarray.view`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5171 [WIP] Texture memory 2D/3D affine transformations
  cupyx/_texture.py
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5440 Fix preloading slow tests
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: cat:test, prio:high, to-be-backported

#5442 [backport] Fix compatibility issues of `ndarray.view`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, cat:bug, prio:high

#5441 [backport] Fix typo in `apply_along_axis`
  cupy/lib/_shape_base.py
Labels: backport, cat:document, prio:medium

#5425 [v9] Add missing DLPack test for complex numbers
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:test, prio:medium

#5326 Do not call cudnnGetVersion on import
  cupy/cudnn.pyx
Labels: cat:code-fix, prio:medium, to-be-backported

#5445 [backport] Fix preloading slow tests
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: backport, cat:test, prio:high

#5416 [backport] Fix cupy.nanmedian's axis parameter to accept a sequence other than a tuple
  cupy/_core/_routines_statistics.pyx
  cupy/_statistics/meanvar.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5446 [backport] Do not call cudnnGetVersion on import
  cupy/cudnn.pyx
Labels: backport, cat:code-fix, prio:medium

#5433 Fix indent of `Returns` section
  cupy/_core/core.pyx
  cupy/_core/dlpack.pyx
  cupy/_functional/piecewise.py
  cupy/_indexing/generate.py
  cupy/_indexing/indexing.py
  cupy/_logic/comparison.py
  cupy/_manipulation/add_remove.py
  cupy/_manipulation/dims.py
  cupy/_manipulation/kind.py
  cupy/_math/sumprod.py
  cupy/_sorting/count.py
  cupy/_sorting/search.py
  cupy/_statistics/histogram.py
  cupy/_statistics/meanvar.py
  cupy/cuda/memory.pyx
  cupy/cusparse.py
  cupy/cutensor.pyx
  cupy/lib/_routines_poly.py
  cupy/lib/_shape_base.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_einsum.py
  cupy/linalg/_solve.py
  cupy/polynomial/polyutils.py
  cupy/random/_generator_api.pyx
  cupy/random/_sample.py
  cupy/testing/_helper.py
  cupy_backends/cuda/libs/cutensor.pyx
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/ndimage/morphology.py
  cupyx/scipy/signal/signaltools.py
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/data.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5444 Use `dtype.name` instead `dtype.char`
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_cuda_types.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:code-fix, prio:medium

#5452 [backport] Fix indent of `Returns` section
  cupy/_core/core.pyx
  cupy/_functional/piecewise.py
  cupy/_indexing/generate.py
  cupy/_indexing/indexing.py
  cupy/_logic/comparison.py
  cupy/_manipulation/add_remove.py
  cupy/_manipulation/dims.py
  cupy/_manipulation/kind.py
  cupy/_math/sumprod.py
  cupy/_sorting/count.py
  cupy/_sorting/search.py
  cupy/_statistics/histogram.py
  cupy/_statistics/meanvar.py
  cupy/cuda/memory.pyx
  cupy/cusparse.py
  cupy/cutensor.pyx
  cupy/lib/_routines_poly.py
  cupy/lib/_shape_base.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_einsum.py
  cupy/linalg/_solve.py
  cupy/polynomial/polyutils.py
  cupy/random/_generator_api.pyx
  cupy/random/_sample.py
  cupy/testing/_helper.py
  cupy_backends/cuda/libs/cutensor.pyx
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/ndimage/morphology.py
  cupyx/scipy/signal/signaltools.py
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/data.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5448 Fix `types` attribute of ufunc
  cupy/_core/_kernel.pyx
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:bug, prio:high, to-be-backported

#5435 docs: user_guide/basic.rst: impr. device agnostic section
  docs/source/user_guide/basic.rst
Labels: cat:document, prio:medium, to-be-backported

#5449 Fix new DLPack protocol error messages and tests
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:bug, prio:high

#5455 [backport] Fix `types` attribute of ufunc
  cupy/_core/_kernel.pyx
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: backport, cat:bug, prio:high

#5456 [backport] docs: user_guide/basic.rst: impr. device agnostic section
  docs/source/user_guide/basic.rst
Labels: backport, cat:document, prio:medium

#5378 Add script for ROCm CI on Jenkins
  .pfnci/BRANCH
  .pfnci/config.pbtxt
  .pfnci/docker/devel/Dockerfile
  .pfnci/hint.pbtxt
  .pfnci/linux/README.md
  .pfnci/linux/run.sh
  .pfnci/linux/tests/_environment.sh
  .pfnci/linux/tests/rocm-4-0.Dockerfile
  .pfnci/linux/tests/rocm-4-0.sh
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/linux/tests/rocm-4-2.sh
  .pfnci/linux/tests/rocm.sh
  .pfnci/py27and35.Dockerfile
  .pfnci/py37.Dockerfile
  .pfnci/run.sh
  .pfnci/wheel_nightly.sh
Labels: cat:test, prio:high, to-be-backported

#5468 [backport] Add script for ROCm CI on Jenkins
  .pfnci/BRANCH
  .pfnci/config.pbtxt
  .pfnci/docker/devel/Dockerfile
  .pfnci/hint.pbtxt
  .pfnci/linux/README.md
  .pfnci/linux/run.sh
  .pfnci/linux/tests/_environment.sh
  .pfnci/linux/tests/rocm-4-0.Dockerfile
  .pfnci/linux/tests/rocm-4-0.sh
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/linux/tests/rocm-4-2.sh
  .pfnci/linux/tests/rocm.sh
  .pfnci/py27and35.Dockerfile
  .pfnci/py37.Dockerfile
  .pfnci/run.sh
  .pfnci/wheel_nightly.sh
Labels: backport, cat:test, prio:high

#5453 Update setup.py numpy/scipy pinning
  setup.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5454 Update install guide with new numpy versions
  docs/requirements.txt
  docs/source/install.rst
Labels: cat:document, prio:medium

#5464 `texture_memory` option in `affine_transform` not supported by HIP
  cupyx/scipy/ndimage/interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, prio:high

#5471 [backport] Update setup.py numpy/scipy pinning
  setup.py
Labels: backport, cat:enhancement, prio:medium

#5477 Increase memory for CUDA 11.4 tests
  .pfnci/config.pbtxt
Labels: cat:test, to-be-backported

#5480 [backport] Increase memory for CUDA 11.4 tests
  .pfnci/config.pbtxt
Labels: backport, cat:test

#5482 Import numpy before Cython
  cupy_setup_build.py
Labels: cat:install, prio:high, to-be-backported

#5443 Add geometric distribution to new Generator
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5483 [backport] Import numpy before Cython
  cupy_setup_build.py
Labels: backport, cat:install, prio:high, st:test-and-merge

#5479 Fix random `integers`
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:bug, prio:high, to-be-backported

#5478 Fix random generator output not being raveled
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
Labels: cat:bug, prio:high, to-be-backported

#5461 Support Numba-like `jit.gridsize()` syntax in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#5487 [backport] Fix random generator output not being raveled
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
Labels: backport, cat:bug, prio:high

#5410 Fix astype from boolean
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:bug, prio:high, to-be-backported

#5485 Fix DLPack test for ROCm/HIP
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:test, hip, prio:high

#5465 [backport] Update install guide with new NumPy/SciPy versions
  docs/source/install.rst
Labels: backport, cat:document, prio:medium

#5491 Bump ReadTheDocs configuration to version 2
  .readthedocs.yaml
  readthedocs.yml
Labels: cat:document, to-be-backported

#5494 Fix docs of eigh and eigvalsh
  cupy/linalg/_eigenvalue.py
Labels: cat:document, to-be-backported

#5489 Use Sphinx 4.1.0
  docs/requirements.txt
Labels: cat:document, prio:medium, to-be-backported

#5497 [backport] Bump ReadTheDocs configuration to version 2
  .readthedocs.yaml
  readthedocs.yml
Labels: backport, cat:document

#5499 [backport] Fix docs of eigh and eigvalsh
  cupy/linalg/_eigenvalue.py
Labels: backport, cat:document

#5490 [backport] Fix astype from boolean
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, cat:bug, prio:high

#5488 Use `from_dlpack` instead of fromDlpack
  docs/source/user_guide/interoperability.rst
Labels: cat:document, prio:medium

#5486 Try to use `-I` in hipRTC
  cupy/cuda/compiler.py
Labels: cat:code-fix, hip, to-be-backported

#5470 Fix reshape
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:bug, prio:high, to-be-backported

#5504 [backport] Fix reshape
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: backport, cat:bug, prio:high

#5500 [backport] Use Sphinx 4.1.0
  docs/requirements.txt
Labels: backport, cat:document, prio:medium

#5467 Fix `linalg.lstsq` for empty matrix
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:bug, to-be-backported

#5495 Add `cudaDeviceDisablePeerAccess` wrapper
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_runtime.h
Labels: cat:enhancement, prio:medium

#5506 [backport] Fix `linalg.lstsq` for empty matrix
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: backport, cat:bug

#5472 Support hipSPARSE
  cupy/cusparse.py
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cupy_sparse.h
  cupy_backends/hip/cupy_hipsparse.h
  cupy_backends/stub/cupy_cusparse.h
  cupy_setup_build.py
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/dia.py
  cupyx/scipy/sparse/linalg/_solve.py
  cupyx/tools/_hipsparse_stub_mapper.py
  tests/cupy_tests/cuda_tests/test_device.py
  tests/cupy_tests/test_cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/__init__.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, prio:high, st:test-and-merge

#5439 Fix mergify to only comment when pull-request is open
  .mergify.yml
Labels: cat:other, prio:high, to-be-backported

#5513 Fix mergify condition
  .mergify.yml
Labels: cat:other, prio:high

#5510 [backport] Fix mergify to only comment when pull-request is open
  .mergify.yml
Labels: backport, cat:other, prio:high

#5517 [backport] Fix mergify condition
  .mergify.yml
Labels: backport, cat:other, prio:high

#5498 Fix "Revert test decorators order"
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5434 Support CUDA 11.4 and support `compute_86`
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupy_setup_build.py
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, to-be-backported

#5519 [backport] Support CUDA 11.4 and support `compute_86`
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupy_setup_build.py
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:high

#5505 Fix FlexCI Linux tests
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
  .pfnci/linux/tests/_environment.sh
Labels: cat:test, prio:high, to-be-backported

#5475 [backport] Add HIP symbol redefinitions
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pyx
  cupy/_core/include/cupy/hip_workaround.cuh
Labels: cat:code-fix, prio:medium, st:test-and-merge

#5447 Support CUDA 11.4 on documents
  README.md
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#5516 cuDNN v8.2.2
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, to-be-backported

#5507 [v9] Add missing checks and `_setStream()`
  cupy_backends/cuda/libs/cusparse.pyx
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:bug, prio:high, st:test-and-merge

#5515 Add missing hipSPARSE include to builder
  cupy_setup_build.py
Labels: cat:bug, prio:high, st:test-and-merge

#5458 Make `matrix_power` support stacked matrices
  cupy/linalg/_product.py
  tests/cupy_tests/linalg_tests/test_product.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5525 [backport] Make `matrix_power` support stacked matrices
  cupy/linalg/_product.py
  tests/cupy_tests/linalg_tests/test_product.py
Labels: backport, cat:enhancement, prio:medium

#5523 [backport] cuDNN v8.2.2
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:high

#5509 Add a lingering doc page for `fromDlpack()`
  cupy/_core/dlpack.pyx
  docs/source/reference/_deprecated.rst
Labels: cat:document, prio:high

#5520 [backport] Fix FlexCI Linux tests
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
  .pfnci/linux/tests/_environment.sh
Labels: backport, cat:test, prio:high

#5521 NCCL v2.10.3 for library installer and document
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, prio:high, to-be-backported

#5526 [backport] NCCL v2.10.3 for library installer and document
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: backport, cat:enhancement, prio:high

#5514 Document `scipy.fft` backend usage
  docs/source/reference/scipy_fft.rst
  docs/source/user_guide/fft.rst
Labels: cat:document, prio:medium, to-be-backported

#5522 Hide modules from public APIs
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cuda/stream.pyx
Labels: cat:code-fix, prio:medium, to-be-backported

#5502 [backport] Try to use `-I` in hipRTC
  cupy/cuda/compiler.py
Labels: backport, cat:code-fix, hip

#5533 [backport] Hide modules from public APIs
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cuda/stream.pyx
Labels: backport, cat:code-fix, prio:medium

#5492 Fix availability tests in cuSOLVER and cuSPARSE
  cupy/cusolver.pyx
  cupy/cusparse.py
Labels: blocking, cat:bug, prio:high, to-be-backported

#5531 prune cufft static lib by major cc ver
  cupy/fft/_callback.pyx
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5462 Support Numba-like `jit.laneid()` and `jit.warpsize` syntax in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_interface.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5532 [backport] Document `scipy.fft` backend usage
  docs/source/reference/scipy_fft.rst
  docs/source/user_guide/fft.rst
Labels: backport, cat:document, prio:medium

#5534 [backport] Fix availability tests in cuSOLVER and cuSPARSE
  cupy/cusolver.pyx
  cupy/cusparse.py
Labels: backport, blocking, cat:bug, prio:high

#5538 Add auto notify bot for `hip` label
  .github/workflows/auto-cc.yml
Labels: cat:other, to-be-backported

#5540 [backport] Add auto notify bot for `hip` label
  .github/workflows/auto-cc.yml
Labels: backport, cat:other

#5542 [backport] Use `pull_request_target` instead for auto notify bot
  .github/workflows/auto-cc.yml
Labels: backport, cat:other

#5535 [backport] Support CUDA 11.4 on documents
  README.md
  docs/source/install.rst
Labels: backport, cat:document, prio:high, st:test-and-merge

#5528 Add CUDA 11.4 for FlexCI helper script
  .pfnci/windows/_flexci.ps1
Labels: cat:test, prio:medium, to-be-backported

#5536 [backport] prune cufft static lib by major cc ver
  cupy/fft/_callback.pyx
Labels: backport, cat:bug, prio:high

#5543 [backport] Add CUDA 11.4 for FlexCI helper script
  .pfnci/windows/_flexci.ps1
Labels: backport, cat:test, prio:medium

#5547 [backport] Fix auto notify bot for issues
  .github/workflows/auto-cc.yml
Labels: backport, cat:other

#5539 Fix casts from bool in ufunc inputs
  cupy/_core/_kernel.pyx
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:bug, prio:high, to-be-backported

#5524 Add cupyx.scipy.sparse.linalg.cgs
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_iterative.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium

#5549 [backport] Fix casts from bool in ufunc inputs
  cupy/_core/_kernel.pyx
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: backport, cat:bug, prio:high

#5548 Replaced the links for NumPy docs as per issue #3418
  cupy/__init__.py
  cupy/_binary/__init__.py
  cupy/_core/core.pyx
  cupy/_creation/__init__.py
  cupy/_indexing/__init__.py
  cupy/_io/__init__.py
  cupy/_logic/__init__.py
  cupy/_manipulation/__init__.py
  cupy/_math/__init__.py
  cupy/_padding/__init__.py
  cupy/_sorting/__init__.py
  cupy/_statistics/__init__.py
  cupy/cuda/cupy_thrust.cu
  cupy/linalg/__init__.py
  docs/source/overview.rst
  docs/source/reference/ndarray.rst
  docs/source/reference/random.rst
  docs/source/user_guide/basic.rst
Labels: cat:document, prio:medium, to-be-backported

#5553 [backport] Replaced the links for NumPy docs as per issue #3418
  cupy/__init__.py
  cupy/_binary/__init__.py
  cupy/_core/core.pyx
  cupy/_creation/__init__.py
  cupy/_indexing/__init__.py
  cupy/_io/__init__.py
  cupy/_logic/__init__.py
  cupy/_manipulation/__init__.py
  cupy/_math/__init__.py
  cupy/_padding/__init__.py
  cupy/_sorting/__init__.py
  cupy/_statistics/__init__.py
  cupy/cuda/cupy_thrust.cu
  cupy/linalg/__init__.py
  docs/source/overview.rst
  docs/source/reference/ndarray.rst
  docs/source/reference/random.rst
  docs/source/user_guide/basic.rst
Labels: backport, cat:document, prio:medium

#5556 Disable Mergify's auto-merge
  .mergify.yml
Labels: cat:other, prio:medium, to-be-backported

#5562 [backport] Disable Mergify's auto-merge
  .mergify.yml
Labels: backport, cat:other, prio:medium

#5563 [v9] Fix scipy requirement
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, prio:high

#5554 Use the new macro `__HIP_PLATFORM_AMD__` at build time
  cupy_setup_build.py
Labels: cat:code-fix, hip, prio:medium, to-be-backported

#5558 Code fix for {cu, roc}SOLVER
  cupy/cusolver.pyx
  cupy_backends/hip/cupy_rocsolver.h
Labels: cat:bug, hip, prio:high, to-be-backported

#5565 [backport] Use the new macro `__HIP_PLATFORM_AMD__` at build time
  cupy_setup_build.py
Labels: backport, cat:code-fix, hip, prio:medium

#5518 [backport] Fix "Revert test decorators order"
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: backport, cat:test, prio:high

#5566 [backport] Code fix for {cu, roc}SOLVER
  cupy/cusolver.pyx
  cupy_backends/hip/cupy_rocsolver.h
Labels: backport, cat:bug, hip, prio:high

#5561 Fix CUDA API call on module initialization
  cupy/cuda/memory.pyx
Labels: cat:bug, prio:high, to-be-backported

#5097 Compile with SASS for CUDA versions >= 11.1
  cupy/cuda/compiler.py
  tests/cupy_tests/core_tests/test_raw.py
Labels: blocking, cat:enhancement, no-compat, prio:high

#5569 Fix the RTC call path for HIP
  cupy/cuda/compiler.py
Labels: cat:bug, prio:high

#5544 Access `cudaMemoryType` in the pointer attributes and fix for HIP
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_runtime.h
Labels: cat:bug, prio:high, to-be-backported

#5551 consistent kernel names
  cupy/_binary/packing.py
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pyx
  cupy/_creation/matrix.py
  cupy/_functional/piecewise.py
  cupy/_functional/vectorize.py
  cupy/_indexing/insert.py
  cupy/_manipulation/add_remove.py
  cupy/_misc/memory_ranges.py
  cupy/_sorting/search.py
  cupy/_statistics/histogram.py
  cupy/_statistics/order.py
  cupy/linalg/_util.py
  cupy/random/_generator.py
  cupy/random/_kernels.py
  cupyx/_texture.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_spline_prefilter_core.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/dia.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_convex_analysis.py
  cupyx/scipy/special/_digamma.py
  cupyx/scipy/special/_erf.py
  cupyx/scipy/special/_gammaln.py
  cupyx/scipy/special/_statistics.py
  cupyx/scipy/special/_zeta.py
Labels: cat:code-fix, prio:medium, to-be-backported

#5575 Increase timeout for CUDA 11.4 tests
  .pfnci/config.pbtxt
Labels: cat:test, prio:high

#5501 Fix some tests for HIP
  cupyx/scipy/linalg/decomp_lu.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/indexing_tests/test_generate.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupyx_tests/test_scatter.py
Labels: cat:test, prio:high, to-be-backported

#5560 Add hypergeometric distribution to new Generator
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5331 Add cupyx.scipy.sparse.linalg.lsmr
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5571 [backport] Access `cudaMemoryType` in the pointer attributes and fix for HIP
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_runtime.h
Labels: backport, cat:bug, prio:high

#5578 [backport] Fix some tests for HIP
  cupyx/scipy/linalg/decomp_lu.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/indexing_tests/test_generate.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupyx_tests/test_scatter.py
Labels: backport, cat:test, prio:high

#5576 Update tests to install all requirements and add PATH
  .pfnci/linux/tests/_build_and_test.sh
  .pfnci/linux/tests/_environment.sh
Labels: cat:test, prio:high, to-be-backported

#5582 [backport] Add Cython to `all` requirements
  setup.py
Labels: backport, cat:test, prio:high

#5581 [backport] Update tests to install all requirements and add PATH
  .pfnci/linux/tests/_build_and_test.sh
  .pfnci/linux/tests/_environment.sh
Labels: backport, cat:test, prio:high

#5579 Fix broadcast error messages
  cupy/_core/internal.pyx
Labels: cat:bug, prio:high, to-be-backported
