Repository cupy/cupy, pull requests merged in 2021-05, with the labels that each got.

#5160 [backport] Cosmetic change in cuSPARSELt stub header
  cupy_backends/stub/cupy_cusparselt.h
Labels: backport, cat:code-fix, prio:medium

#5173 Fix integer `scatter_add` failure on Windows
  cupy/_core/_routines_indexing.pyx
  tests/cupyx_tests/test_scatter.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5162 [backport] Cosmetic changes of CuPy JIT implementation
  cupy/_functional/vectorize.py
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_interface.py
  cupyx/jit/_internal_types.py
Labels: backport, cat:code-fix, prio:medium, st:test-and-merge

#5168 Properly handle non-contiguous RHS in cupyx.scipy.sparse.linalg.spsolve
  cupy/cusolver.pyx
  tests/cupy_tests/test_cusolver.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5169 Add `cupyx.jit.atomic_add`
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  examples/jit/reduction_atomic.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium, st:test-and-merge, to-be-backported

#5087 Fix poisson to support lam array
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/test_distributions.py
Labels: cat:bug, prio:high, to-be-backported

#5180 [backport] Properly handle non-contiguous RHS in cupyx.scipy.sparse.linalg.spsolve
  cupy/cusolver.pyx
  tests/cupy_tests/test_cusolver.py
Labels: backport, cat:bug, prio:high

#5182 [backport] Fix poisson to support lam array
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/test_distributions.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5096 Xfail tests for random distribution generator under HIP/ROCm
  tests/cupy_tests/random_tests/test_distributions.py
Labels: hip, prio:medium, st:test-and-merge, to-be-backported

#5161 [backport] Fix TypeError in `svds`
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: backport, cat:bug, prio:medium, st:test-and-merge

#5177 CUDA 11.2/11.3: Support `MemoryAsyncPool` statistics and limits
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_common.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/user_guide/memory.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:feature, prio:medium

#5188 Use Sphinx 4
  docs/requirements.txt
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5198 [backport] Use Sphinx 4
  docs/requirements.txt
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5155 Add a new argument `out` to `cupy.asnumpy()`
  cupy/__init__.py
  cupy/_core/core.pyx
  tests/cupy_tests/test_numpy_interop.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#5209 Fix thrust compilation for ROCm 4.2.0
  .pfnci/script.sh
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: cat:enhancement, hip, prio:high, st:test-and-merge

#5146 cuDNN v8.2.0 for library installer
  cupyx/tools/install_library.py
Labels: cat:install, prio:high, st:test-and-merge, to-be-backported

#5200 add sum_labels to cupyx.scipy.ndimage.measure
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/measurements.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5158 Support cuSPARSELt v0.1.0
  cupy_backends/cuda/cupy_cusparselt.h
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cupy_cusparselt.h
  cupy_backends/stub/cupy_cusparselt.h
  examples/cusparselt/matmul.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5222 [backport] Add `sum_labels` to `cupyx.scipy.ndimage.measure`
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/measurements.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: backport, cat:enhancement, prio:medium

#5212 [backport] Fix thrust compilation for ROCm 4.2.0
  .pfnci/script.sh
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: backport, cat:enhancement, hip, prio:high

#5216 [backport] cuDNN v8.2.0 for library installer
  cupyx/tools/install_library.py
Labels: backport, cat:install, prio:high

#5217 [backport] cuDNN v8.2 on documentation
  docs/source/install.rst
Labels: backport, cat:document, prio:medium

#5172 Per device stream
  cupy/cuda/stream.pyx
  cupy_backends/cuda/stream.pxd
  cupy_backends/cuda/stream.pyx
  docs/source/user_guide/basic.rst
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:enhancement, no-compat, prio:high, to-be-backported

#5201 NCCL v2.9.8
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5215 Add NVCC path and Python version to `show_config`
  cupyx/_runtime.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5221 Fix cusparseLt not covered in docs
  docs/source/install.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5228 [v9] Fix Stream destructor not taking care of PTDS
  cupy/cuda/stream.pyx
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#5229 [backport] NCCL v2.9.8
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5230 [backport] Add NVCC path and Python version to `show_config`
  cupyx/_runtime.py
Labels: backport, cat:enhancement, prio:medium

#5218 Add CUDA 11.3 headers
  .pfnci/windows/_flexci.ps1
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.hpp
  docs/source/install.rst
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#5191 `MemoryAsyncPool`: Use the "current" mempool instead of the "default" one
  cupy/cuda/memory.pyx
Labels: cat:bug, no-compat, st:test-and-merge, to-be-backported

#5192 cuTENSOR v1.3.0 for library installer
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, to-be-backported

#5219 Add libraries for CUDA 11.3
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, to-be-backported

#5235 [backport] Add libraries for CUDA 11.3
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:high

#5226 Remove syncdetect APIs
  cupy/_core/syncdetect.py
  docs/source/reference/prof.rst
Labels: cat:enhancement, no-compat, prio:medium, st:test-and-merge

#5196 cuTENSOR v1.3 on documentation
  docs/source/install.rst
Labels: blocking, cat:document, st:test-and-merge, to-be-backported

#5224 Test build for ROCm 4.0 and latest
  .pfnci/config.pbtxt
  .pfnci/script.sh
Labels: blocking, cat:test, prio:high, to-be-backported

#5205 Fix matmul for input with relaxed strides
  cupy/_core/_routines_linalg.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5239 [backport] Test build for ROCm 4.0 and latest
  .pfnci/config.pbtxt
  .pfnci/script.sh
Labels: backport, blocking, cat:test, prio:high

#5032 Add warnings for duplicate installation
  cupy/__init__.py
  cupy/_environment.py
Labels: cat:install, prio:medium

#4970 Avoid using `pip install -e` on Windows CI for performance
  .pfnci/windows/test.ps1
  install/build.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5206 Add check_availability for cuTensor routines
  cupy/cutensor.pyx
  cupy/linalg/_einsum.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5223 Add `cupyx.scipy.ndimage.sum_labels` to docs
  docs/source/reference/ndimage.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5242 [backport] Avoid using `pip install -e` on Windows CI for performance
  .pfnci/windows/test.ps1
  install/build.py
Labels: backport, cat:test, prio:high

#5244 [backport] Add check_availability for cuTensor routines
  cupy/cutensor.pyx
  cupy/linalg/_einsum.py
Labels: backport, cat:bug, prio:high

#5248 Fix mergify configuration
  .mergify.yml
Labels: cat:test, prio:high, to-be-backported

#5233 Fix windows constexpr
  cupy/cuda/cupy_thrust.cu
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#5249 [backport] Fix mergify configuration
  .mergify.yml
Labels: backport, cat:test, prio:high

#5245 [backport] Add `cupyx.scipy.ndimage.sum_labels` to docs
  docs/source/reference/ndimage.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5250 [backport] Fix windows constexpr
  cupy/cuda/cupy_thrust.cu
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#5234 [backport] cuTENSOR v1.3.0 for library installer
  cupyx/tools/install_library.py
Labels: backport, blocking, cat:enhancement, prio:high

#5238 [backport] cuTENSOR v1.3 on documentation
  docs/source/install.rst
Labels: backport, cat:document, st:test-and-merge

#5227 [backport] Support cuSPARSELt v0.1.0
  cupy_backends/cuda/cupy_cusparselt.h
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cupy_cusparselt.h
  cupy_backends/stub/cupy_cusparselt.h
  examples/cusparselt/matmul.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5231 [backport] Fix cusparseLt not covered in docs
  docs/source/install.rst
Labels: backport, cat:document, prio:medium

#5255 Update logo image
  docs/image/cupy_logo_1000px.png
Labels: cat:document, prio:medium, to-be-backported

#5257 [backport] Update logo image
  docs/image/cupy_logo_1000px.png
Labels: backport, cat:document, prio:medium

#5254 Improve README
  README.md
Labels: cat:document, prio:medium, to-be-backported

#5259 [backport] Improve README
  README.md
Labels: backport, cat:document, prio:medium

#5240 [backport] Fix matmul for input with relaxed strides
  cupy/_core/_routines_linalg.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: backport, cat:bug, prio:high

#5256 Tentatively remove CUDA 11.3 from support list
  docs/source/install.rst
Labels: blocking, cat:document, prio:high, to-be-backported

#5247 Remove duplicated subtraction in `cupy.random.Generator.integers`
  cupy/random/_generator_api.pyx
Labels: cat:bug, prio:high, to-be-backported

#5261 [backport] Remove duplicated subtraction in `cupy.random.Generator.integers`
  cupy/random/_generator_api.pyx
Labels: backport, cat:bug, prio:high

#5276 Bump Dockerfile version to v9.1.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#5274 Use cdef instead of cpdef where appropraite
  cupy/_core/internal.pyx
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#5243 Code and comment fixes for stream
  cupy/cuda/stream.pyx
Labels: cat:code-fix, prio:low, st:test-and-merge

#5174 Fix `matmul` docstring
  cupy/_core/__init__.py
  cupy/_core/_gufuncs.py
  cupy/_core/_routines_linalg.pxd
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
Labels: cat:document, prio:medium, to-be-backported

#5279 [backport] Use cdef instead of cpdef where appropraite
  cupy/_core/internal.pyx
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cusparse.pyx
Labels: backport, cat:code-fix, prio:medium

#5281 [backport] Fix `matmul` docstring
  cupy/_core/__init__.py
  cupy/_core/_gufuncs.py
  cupy/_core/_routines_linalg.pxd
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5251 Fix to allow sharing a Stream instance between threads
  cupy/cuda/stream.pyx
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:enhancement, no-compat, prio:medium, st:test-and-merge

#5272 Add user guide for FFT
  docs/source/reference/fft.rst
  docs/source/reference/scipy_fft.rst
  docs/source/user_guide/fft.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/memory.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5284 [backport] Update list of wheels in README
  README.md
Labels: backport, cat:document, prio:high

#5236 Fix cub repository url
  .gitmodules
Labels: cat:code-fix, prio:medium, to-be-backported

#5286 [backport] Add user guide for FFT
  docs/source/reference/fft.rst
  docs/source/reference/scipy_fft.rst
  docs/source/user_guide/fft.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/memory.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5273 Exclude Cython 3 from setup_requires
  setup.py
Labels: cat:install, prio:medium, st:test-and-merge, to-be-backported

#5285 [backport] Do not use handles unless requested
  cupy/__init__.py
  cupyx/_runtime.py
  tests/cupy_tests/test_init.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5287 Fix deadlink to tutorial and reorder in README
  README.md
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#5271 [backport] `MemoryAsyncPool`: Use the "current" mempool instead of the "default" one
  cupy/cuda/memory.pyx
Labels: cat:bug, no-compat, prio:high, st:test-and-merge

#5288 [backport] Fix cub repository url
  .gitmodules
Labels: backport, cat:code-fix, prio:medium, st:test-and-merge

#5291 [backport] Fix deadlink to tutorial and reorder in README
  README.md
Labels: backport, cat:document, prio:high

#5290 [backport] Exclude Cython 3 from setup_requires
  setup.py
Labels: backport, cat:install, prio:medium

#5283 Add user guide for streams & events
  docs/source/user_guide/cuda_api.rst
Labels: cat:document, prio:medium, to-be-backported

#5302 [backport] Add user guide for streams & events
  docs/source/user_guide/cuda_api.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge
