Repository cupy/cupy, pull requests merged in 2021-02, with the labels that each got.

#4585 Fix test import failure in ROCm
  tests/cupy_tests/random_tests/test_bit_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:test, st:test-and-merge

#4586 Remove use of `numpy.bool`
  cupy/cuda/common.pyx
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/csr.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:code-fix, prio:high, to-be-backported

#4558 CUDA 11.1: Wrap the new `nvrtcGetCUBIN` API
  cupy/cuda/compiler.py
  cupy_backends/cuda/cupy_nvrtc.h
  cupy_backends/cuda/libs/nvrtc.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/cupy_rtc.h
  cupy_backends/hip/cupy_hiprtc.h
  cupy_backends/stub/cupy_nvrtc.h
Labels: cat:enhancement, prio:medium, st:test-and-merge

#3853 Use `cupy.core._dtype.to_cuda_dtype` whenever possible
  cupy/cusparse.py
  cupy/cutensor.pyx
  cupyx/scipy/sparse/linalg/_eigen.py
  cupyx/scipy/sparse/linalg/_iterative.py
Labels: cat:code-fix, prio:low

#4589 [backport] Remove use of `numpy.bool`
  cupy/cuda/common.pyx
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/csr.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, cat:code-fix, prio:high

#4538 CUDA 11.2: Fix empty NVRTC program name
  cupy/cuda/compiler.py
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: cat:bug, prio:high, to-be-backported

#4560 Add cuTENSOR to library download tool
  cupy/_environment.py
  cupyx/tools/install_library.py
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: cat:feature, prio:medium

#4594 Fix device property default name
  cupy_backends/cuda/api/runtime.pyx
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4598 Avoid test discovery failure in NumPy 1.20
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/logic_tests/test_type_test.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:code-fix, prio:high, st:test-and-merge, to-be-backported

#4603 [backport] Avoid test discovery failure in NumPy 1.20
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/logic_tests/test_type_test.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: backport, cat:code-fix, prio:high

#4605 Stop using deprecated type aliases
  cupy/_statistics/histogram.py
  cupy/core/core.pyx
  cupyx/scipy/ndimage/measurements.py
  tests/cupy_tests/indexing_tests/test_insert.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: cat:numpy-compat, prio:high, to-be-backported

#4611 Fix `poly1d` return types for NumPy 1.20
  cupy/lib/_polynomial.pyx
  cupy/lib/_routines_poly.py
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:numpy-compat

#4612 [backport] Stop using deprecated type aliases
  cupy/_statistics/histogram.py
  cupy/core/core.pyx
  tests/cupy_tests/indexing_tests/test_insert.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Labels: backport, cat:numpy-compat, prio:high

#4616 Deprecate passing shape=None to mean shape=()
  cupy/core/internal.pyx
  cupy/random/_generator.py
  tests/cupy_tests/core_tests/test_internal.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:numpy-compat, prio:high, to-be-backported

#4514 Fix Jitify version detection on CUDA 11.0+
  install/build.py
Labels: cat:bug, prio:high

#4622 [backport] Deprecate passing shape=None to mean shape=()
  cupy/core/internal.pyx
  cupy/random/_generator.py
  tests/cupy_tests/core_tests/test_internal.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: backport, cat:numpy-compat, prio:high

#4620 Stop using deprecated `numpy.complex`
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:code-fix, prio:high, st:test-and-merge, to-be-backported

#4623 Backport: Fix `poly1d` return types for NumPy 1.20
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: backport, cat:numpy-compat

#4604 Update spec of `linspace` to NumPy 1.20
  cupy/_creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: cat:numpy-compat, prio:high, st:test-and-merge, to-be-backported

#4537 CUDA 11.2: Support the built-in Stream Ordered Memory Allocator
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cuda_runtime.h
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_common.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  docs/source/reference/environment.rst
  docs/source/reference/index.rst
  docs/source/tutorial/index.rst
  docs/source/tutorial/memory.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4624 [backport] Stop using deprecated `numpy.complex`
  cupyx/scipy/fftpack/_fft.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/statics_tests/test_histogram.py
Labels: backport, cat:code-fix, prio:high

#4392 Add `splu`, `spilu` and `factorized` to `cupyx.scipy.sparse.linalg`
  cupy/cusparse.py
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupy_tests/test_cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4504 Slight code improvements for the CUB reduction kernel
  cupy/core/_cub_reduction.pyx
Labels: cat:hip, st:test-and-merge

#4561 Update doctest of `cupyx.scipy.linalg.lu_factor`
  cupyx/scipy/linalg/decomp_lu.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#4492 Use NVRTC for grid synchronization in `cupy.fuse`
  cupy/core/_fusion_kernel.pyx
  cupy/cuda/compiler.py
Labels: cat:enhancement, prio:medium, to-be-backported

#4615 Make `normal` and `lognormal` support array args
  cupy/random/_distributions.py
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_distributions.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4602 [backport] Fix device property default name
  cupy_backends/cuda/api/runtime.pyx
Labels: backport, cat:bug, prio:high

#4347 Support ufunc call in CuPy JIT
  cupyx/jit/_compile.py
  cupyx/jit/_types.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4213 Add `SparseEfficiencyWarning` and warn inefficient comparison
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4614 Update installation guide for cuTENSOR on Conda-Forge
  docs/source/install.rst
Labels: cat:document, prio:medium, to-be-backported

#4625 [backport] Fix tests for incompatible behavior of NumPy 1.20 `linspace`
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: backport, cat:numpy-compat, prio:high, st:test-and-merge

#4581 [backport] Test `numpy.VisibleDeprecationWarning`
  setup.cfg
  tests/cupy_tests/random_tests/test_generator.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#4322 Support for Per Thread Default Stream (PTDS)
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/curand.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/stream.pxd
  cupy_backends/cuda/stream.pyx
  docs/source/reference/environment.rst
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4595 Support explicit typecast in CuPy JIT
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4630 Update documentation requirements
  .github/workflows/pretest.yml
  docs/requirements.txt
  setup.py
Labels: cat:document, prio:medium, to-be-backported

#4631 Update install requirements
  setup.py
Labels: cat:install, prio:medium

#4626 [backport] Make `normal` and `lognormal` support array args
  cupy/random/_distributions.py
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_distributions.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4637 [backport] Update documentation requirements
  .github/workflows/pretest.yml
  docs/requirements.txt
  setup.py
Labels: backport, cat:document, prio:medium

#4639 [backport] Use NVRTC for grid synchronization in `cupy.fuse`
  cupy/core/_fusion_kernel.pyx
  cupy/cuda/compiler.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#4599 [backport] CUDA 11.2: Fix empty NVRTC program name
  cupy/cuda/compiler.py
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: backport, cat:bug, prio:high

#4362 Add FlexCI for Windows
  .pfnci/config.pbtxt
  .pfnci/trim_cupy_kernel_cache.py
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/run.bat
  .pfnci/windows/test.ps1
  setup.cfg
Labels: cat:test, prio:high, to-be-backported

#4641 [backport] Remove broken support for macOS
  cupy_setup_build.py
  docs/source/contribution.rst
  install/build.py
Labels: backport, cat:install, prio:medium

#4651 ROCm: disable PTDS
  cupy/cuda/stream.pyx
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:bug, prio:high, st:test-and-merge

#4617 Improve floating point accuracy in percentile
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:numpy-compat, prio:high

#4564 Fix return type of `has_sorted_indices` of sparse array
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:bug, prio:high, st:test-and-merge

#4648 Fix typecast from complex to bool in JIT
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug

#4633 Use `CodeBlock` to generate human-readable code in JIT
  cupy/core/_fusion_interface.py
  cupy/core/_fusion_kernel.pyx
  cupy/core/_fusion_op.py
  cupy/core/_fusion_variable.pyx
  cupy/core/fusion.pyx
  cupyx/jit/_codeblock.py
  cupyx/jit/_compile.py
  cupyx/jit/_types.py
Labels: cat:code-fix, prio:medium

#4661 Xfail tests for eigenvalue under HIP/ROCm
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:hip, prio:high

#4556 ROCm: Fix device attributes; Record HIP_VERSION; Add more device properties; etc
  cupy/cuda/compiler.py
  cupy/cuda/cufft.pxd
  cupy/cuda/device.pyx
  cupy/cusolver.py
  cupy/fft/_callback.pyx
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4632 Bump fastrlock requirement
  cupy/__init__.py
  setup.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4638 Make `uniform`-based random distributions support array args
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_distributions.py
Labels: cat:bug, prio:high, to-be-backported

#4656 Skip `TestPoly1dMathArithmetic` under HIP/ROCm
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:hip, prio:high

#4668 Xfail tests for `convolve` under HIP/ROCm
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:hip, prio:high

#4588 Fix/skip some tests for HIP
  tests/cupy_tests/core_tests/test_cub_reduction.py
  tests/cupy_tests/cuda_tests/test_cufft.py
  tests/cupy_tests/cuda_tests/test_texture.py
  tests/cupy_tests/test_cusparse.py
  tests/cupyx_tests/linalg_tests/sparse_tests/__init__.py
  tests/cupyx_tests/scipy_tests/sparse_tests/__init__.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4634 [backport] Update installation guide for cuTENSOR on Conda-Forge
  docs/source/install.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#4646 Support if-statement in CuPy JIT
  cupyx/jit/_compile.py
  cupyx/jit/_typerules.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4636 Bump cuDNN to v8.1.0
  cupyx/tools/install_library.py
  install/build.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#4419 Fix cuSPARSE module build failure with CUDA 10.1 on Windows
  cupy_backends/cuda/cupy_cusparse.h
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4645 [backport] Add FlexCI for Windows
  .pfnci/config.pbtxt
  .pfnci/trim_cupy_kernel_cache.py
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/run.bat
  .pfnci/windows/test.ps1
  setup.cfg
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: backport, cat:test, prio:high

#4640 [backport] Fix DLPack header version
  cupy/core/dlpack.pyx
  cupy/core/include/cupy/dlpack/README.md
  cupy/core/include/cupy/dlpack/dlpack.h
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#4642 [backport] ROCm: Fix filters in `cupyx.scipy.ndimage` - Part 1
  cupy/core/core.pyx
  cupy/core/include/cupy/math_constants.h
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/special/_convex_analysis.py
Labels: backport, cat:hip, prio:medium, st:test-and-merge

#4652 Skip failing tests for `cupy.cublas` under HIP
  tests/cupy_tests/test_cublas.py
Labels: cat:hip, prio:high, st:test-and-merge

#4669 Fix definition order in preamble
  cupy/_math/rational.py
Labels: cat:hip, prio:high, st:test-and-merge

#4678 Support cuTENSOR download tool on Windows
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported

#4667 Fix files not closed
  cupy/_environment.py
  setup.py
Labels: cat:bug, prio:medium, st:test-and-merge, to-be-backported

#4654 Xfail test for cupy._indexing.generate under HIP
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:hip, prio:high, st:test-and-merge

#4672 Support assignment of compile-time constants in CuPy JIT
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:high, st:test-and-merge

#4671 [backport] Make `uniform`-based random distributions support array args
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_distributions.py
Labels: backport, cat:bug, prio:high

#4628 Support batched SVD
  cupy/cusolver.pyx
  cupy/linalg/_decomposition.py
  cupy/linalg/_util.py
  cupy/testing/helper.py
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cupy_lapack.h
  cupy_backends/hip/cupy_rocsolver.h
  cupy_backends/stub/cupy_cusolver.h
  cupy_setup_build.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:feature, prio:medium

#4680 Add cudnn and cutensor for CUDA 11.2 in `install_library`
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4681 [backport] Fix files not closed
  cupy/_environment.py
  setup.py
Labels: backport, cat:bug, prio:medium

#4679 [backport] Remove dependency on CUDA's math_constants.h
  cupy/core/include/cupy/math_constants.h
Labels: backport, cat:bug, prio:high

#4659 Update CUDA Array Interface to v3 - Part 2
  cupy/core/core.pyx
  cupy_backends/cuda/stream.pxd
  cupy_backends/cuda/stream.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4674 [backport] Bump cuDNN to v8.1.0
  cupyx/tools/install_library.py
  install/build.py
Labels: backport, cat:enhancement, prio:medium

#4682 Revert `_get_arch`
  cupy/cuda/compiler.py
Labels: cat:bug, prio:high, st:test-and-merge

#4685 Support building docs against pip installed cupy
  docs/source/conf.py
Labels: cat:document, prio:high, to-be-backported

#4688 [backport] Support building docs against pip installed cupy
  docs/source/conf.py
Labels: backport, cat:document, prio:high, st:test-and-merge

#4650 Fix Windows CI test script to avoid caching kernel when in pull-request test
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4683 Remove maximum cuDNN version check
  install/build.py
Labels: cat:install, prio:medium, to-be-backported

#4690 Fix random errors in batched SVD
  cupy/cusolver.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cupy_lapack.h
  cupy_setup_build.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: blocking, cat:bug, prio:high, st:test-and-merge

#4689 Fix tests for cuDNN 8.1
  tests/cupy_tests/test_cudnn.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4677 Support while/for-statement in CuPy JIT
  cupyx/jit/_compile.py
  cupyx/jit/_types.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:feature, st:test-and-merge

#4643 Update document for cuDNN 8.1
  docs/source/install.rst
Labels: cat:document, prio:medium, to-be-backported

#4698 Use MSVC 14.0 with CUDA 11.2
  cupy_setup_build.py
Labels: cat:enhancement, prio:high, to-be-backported

#4699 [backport] Fix tests for cuDNN 8.1
  tests/cupy_tests/test_cudnn.py
Labels: backport, cat:enhancement, prio:high

#4697 [backport] Remove maximum cuDNN version check
  install/build.py
Labels: backport, cat:install, prio:medium

#4702 Support CUDA 11.2
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.hpp
  cupy/cuda/compiler.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4708 [backport] Support CUDA 11.2
  cupy/core/core.pyx
  cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.h
  cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.hpp
  cupy/cuda/compiler.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4703 [backport] Add cudnn and cutensor for CUDA 11.2 in `install_library`
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4707 [backport] Fix Windows CI test script to avoid caching kernel when in pull-request test
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4709 Bump CUDA version for Docker images
  docker/python3/Dockerfile
Labels: cat:install, no-compat

#4701 [backport] Use MSVC 14.0 with CUDA 11.2
  cupy_setup_build.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#4705 Add CUDA 11.2 to docs
  README.md
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#4716 [backport] Add CUDA 11.2 to docs
  README.md
  docs/source/install.rst
Labels: backport, cat:document, prio:high, st:test-and-merge

#4714 Publish results even if build failed in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#4720 Remove unneeded environment variable from ROCm install guide
  docs/source/install_rocm.rst
Labels: cat:document, prio:medium, to-be-backported

#4721 Document that only x86_64 wheels are provided
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported

#4723 [backport] Remove unneeded environment variable from ROCm install guide
  docs/source/install_rocm.rst
Labels: backport, cat:document, prio:medium

#4724 [backport] Document that only x86_64 wheels are provided
  README.md
  docs/source/install.rst
Labels: backport, cat:document

#4700 [backport] Update document for cuDNN 8.1
  docs/source/install.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#4619 Always run cythonize on sdist installation
  MANIFEST.in
  cupy_setup_build.py
  pyproject.toml
  readthedocs.yml
  setup.py
Labels: cat:bug, no-compat, prio:high, st:test-and-merge

#4710 Add NCCL 2.8 to supported version
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#4726 [backport] Add NCCL 2.8 to supported version
  docs/source/install.rst
Labels: backport, cat:document, prio:high

#4713 Fix thrust compilation in MSVC 14 for CUDA 11.2
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: blocking, cat:bug, prio:high, to-be-backported

#4711 Update Python / NumPy / SciPy requirements
  docs/source/install.rst
  setup.py
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#4725 [backport] Always run cythonize on sdist installation
  MANIFEST.in
  cupy_setup_build.py
  pyproject.toml
  readthedocs.yml
  setup.py
Labels: backport, cat:bug, no-compat, prio:high

#4722 [backport] Publish results even if build failed in Windows CI
  .pfnci/windows/test.ps1
Labels: backport, cat:test, prio:high

#4728 [backport] Fix thrust compilation in MSVC 14 for CUDA 11.2
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#4712 [backport] Update Python / NumPy / SciPy requirements
  docs/source/install.rst
  setup.py
Labels: backport, cat:document, prio:high

#4706 Bump Cython version requirement for Python 3.9
  cupy_setup_build.py
  docs/source/install.rst
Labels: cat:install, prio:high, st:test-and-merge, to-be-backported

#4730 Missing `constexpr` in `cupy_thrust.cu`
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: blocking, prio:high, to-be-backported

#4715 [backport] Fix cuSPARSE module build failure with CUDA 10.1 on Windows
  cupy_backends/cuda/libs/cupy_cusparse.h
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4717 Fix invalid command line generated when rpath is empty
  cupy_setup_build.py
Labels: cat:hip, prio:high, st:test-and-merge

#4735 Disable some `constexpr` only for windows
  cupy/cuda/cupy_thrust.cu
Labels: blocking, cat:bug, prio:high, to-be-backported

#4732 [backport] Missing `constexpr` in `cupy_thrust.cu`
  cupy/cuda/cupy_thrust.cu
  cupy_setup_build.py
Labels: backport, blocking, prio:high, st:test-and-merge

#4736 Fix dead link to issue
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#4739 Add missing attrs
  cupy_backends/cuda/api/runtime.pxd
Labels: blocking, cat:bug, prio:high

#4744 [backport] Fix dead link to issue
  docs/source/install.rst
Labels: backport, cat:document, prio:high

#4740 [backport] Disable some `constexpr` only for windows
  cupy/cuda/cupy_thrust.cu
Labels: backport, blocking, cat:bug, prio:high

#4741 Fix Cython setup requirement out of sync
  setup.py
Labels: blocking, prio:high, to-be-backported

#4734 Remove `pyproject.toml`
  pyproject.toml
  setup.py
Labels: blocking, cat:install, st:test-and-merge, to-be-backported

#4745 Skip callback tests for this release
  tests/cupy_tests/fft_tests/test_callback.py
Labels: blocking, cat:test, prio:high, st:test-and-merge

#4751 Bump version to v9.0.0b3
  cupy/_version.py
Labels: cat:other

#4752 Bump version to v8.5.0
  cupy/_version.py
Labels: cat:other

#4733 [backport] Bump Cython version requirement for Python 3.9
  cupy_setup_build.py
  docs/source/install.rst
Labels: backport, blocking, cat:install, prio:high, st:test-and-merge

#4748 [backport] Remove `pyproject.toml`
  pyproject.toml
  setup.py
Labels: backport, blocking, cat:install, st:test-and-merge

#4742 [backport] Eliminate read past end of array in percentile_weightnening
  cupy/_statistics/order.py
  tests/cupy_tests/statics_tests/test_order.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4747 [backport] Fix `_gesvdj_batched` info array size
  cupy/cusolver.py
Labels: cat:bug, prio:high, st:test-and-merge

#4754 [backport] Fix Cython setup requirement out of sync
  setup.py
Labels: backport, blocking, cat:install, prio:high, st:test-and-merge

#4738 Update Docker image for v9.0.0b3 (use CUDA 11.2)
  docker/python3/Dockerfile
Labels: cat:install, no-compat, st:test-and-merge

#4761 Remove `cupy-cuda112` support from documentation
  README.md
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#4753 Bump Dockerfile version to v8.5.0
  docker/python3/Dockerfile
Labels: cat:other, prio:high

#4737 Add Docker image for ROCm and documentation
  docker/rocm/Dockerfile
  docker/rocm/README.md
  docs/source/install_rocm.rst
Labels: cat:install, prio:high

#4762 [backport] Remove `cupy-cuda112` support from documentation
  README.md
  docs/source/install.rst
Labels: backport, cat:document, prio:high
