Repository cupy/cupy, pull requests merged in 2021-06, with the labels that each got.

#5264 Fix MemoryAsync to keep a weakref to stream
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:bug, no-compat, prio:high, to-be-backported

#5307 [backport] Fix MemoryAsync to keep a weakref to stream
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:bug, no-compat, prio:high, st:test-and-merge

#5301 Add reshape method for COO, CSR and CSC matrices
  cupyx/scipy/sparse/base.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/sputils.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5305 Document `ExternalStream`
  docs/source/user_guide/cuda_api.rst
  docs/source/user_guide/interoperability.rst
Labels: cat:document, prio:medium, st:test-and-merge

#5308 Temporarily remove the async pool test from `TestAllocator`
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5310 Fix Windows CI kernel cache
  .pfnci/windows/test.ps1
Labels: cat:test, prio:medium, to-be-backported

#5317 [backport] Fix Windows CI kernel cache
  .pfnci/windows/test.ps1
Labels: backport, cat:test, prio:medium, st:test-and-merge

#5295 Support `nan`, `posinf`, `neginf` in `cupy.nan_to_num`
  cupy/_math/misc.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#5203 Make cuTENSOR available in cupy.einsum
  cupy/linalg/_einsum.py
Labels: cat:performance, prio:medium, st:test-and-merge

#5277 Bump CuPy version in docs
  docs/source/install.rst
Labels: cat:document, prio:medium

#5312 [backport] Document `ExternalStream`
  docs/source/user_guide/cuda_api.rst
  docs/source/user_guide/interoperability.rst
Labels: cat:document, prio:medium, st:test-and-merge

#5225 Add upper restrictions to NumPy/SciPy versions
  setup.py
Labels: cat:install, prio:medium, to-be-backported

#5321 [backport] Add upper restrictions to NumPy/SciPy versions
  setup.py
Labels: backport, cat:install, prio:medium

#5304 Fix cuFFT callback for sm_61 etc
  cupy/fft/_callback.pyx
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5325 [backport] Fix cuFFT callback for sm_61 etc
  cupy/fft/_callback.pyx
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5319 Support `len`, `min`, `max`, `.ndim`, `.size` in jit
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#5330 Fix large arrays assignment
  cupy/_core/include/cupy/carray.cuh
  tests/cupy_tests/core_tests/test_carray.py
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#5332 Support nested tuple unpack in CuPy JIT
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:feature, prio:medium, st:test-and-merge

#5333 [backport] Fix large arrays assignment
  cupy/_core/include/cupy/carray.cuh
  tests/cupy_tests/core_tests/test_carray.py
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#5207 Fix `check_availablity` for `cupy.cusolver`
  cupy/cusolver.pyx
Labels: cat:bug, prio:high, to-be-backported

#5334 Support Numba-like `jit.grid()` syntax in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#5336 [backport] Fix `check_availablity` for `cupy.cusolver`
  cupy/cusolver.pyx
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5318 Use independent version of hipFFT for ROCm 4.1 and later
  .pfnci/config.pbtxt
  .pfnci/script.sh
  cupy_setup_build.py
Labels: blocking, cat:enhancement, hip, prio:high, to-be-backported

#5350 Tentatively skip unstable `MemoryPoolAsync` tests
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: blocking, prio:high, to-be-backported

#5351 [backport] Use independent version of hipFFT for ROCm 4.1 and later
  .pfnci/config.pbtxt
  .pfnci/script.sh
  cupy_setup_build.py
Labels: backport, blocking, cat:enhancement, hip, prio:high

#5214 Drop support for CUDA 9.2 & NCCL 2.4
  README.md
  docs/source/install.rst
  install/build.py
Labels: blocking, cat:install, prio:high

#5356 docs: user_guide/basic.rst: various improvements
  docs/source/user_guide/basic.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5358 [backport] docs: user_guide/basic.rst: various improvements
  docs/source/user_guide/basic.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5355 Xfail random generator tests for HIP
  tests/cupy_tests/random_tests/test_distributions.py
Labels: cat:test, prio:medium, st:test-and-merge, to-be-backported

#5354 Add ROCm 4.2 support to install docs
  docs/source/install.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5359 [backport] Xfail random generator tests for HIP
  tests/cupy_tests/random_tests/test_distributions.py
Labels: backport, cat:test, prio:medium

#5335 Support warp shuffle and sync functions in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_cuda_types.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#5327 Fix cuDNN preloading
  cupy/_environment.py
  cupyx/tools/install_library.py
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#5366 Tentatively pin to SciPy 1.6 in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, prio:high, to-be-backported

#5260 Adding GUFunc order, dtype and casting kwarg support
  cupy/_core/_gufuncs.py
  tests/cupy_tests/core_tests/test_gufuncs.py
Labels: cat:enhancement, prio:medium

#5338 cuTENSOR v1.3.1
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5369 [backport] Tentatively pin to SciPy 1.6 in Windows CI
  .pfnci/windows/test.ps1
Labels: backport, cat:test, prio:high

#5360 [backport] Add ROCm 4.2 support to install docs
  docs/source/install.rst
Labels: backport, blocking, cat:document, prio:medium

#5365 [backport] Fix cuDNN preloading
  cupy/_environment.py
  cupyx/tools/install_library.py
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#5357 cuDNN v8.2.1
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5372 [backport] cuDNN v8.2.1
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5370 [backport] cuTENSOR v1.3.1
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5342 Ensure source array is C-contiguous before copying to `CUDAArray`
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5374 Remove unnecessary print
  cupy/cusparse.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5375 [backport] Ensure source array is C-contiguous before copying to `CUDAArray`
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5232 [backport] Add CUDA 11.3 headers
  .pfnci/windows/_flexci.ps1
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.hpp
  docs/source/install.rst
Labels: backport, blocking, cat:enhancement, prio:high, st:test-and-merge

#5377 [backport] Remove unnecessary print
  cupy/cusparse.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5344 Increase test coverage for Generalized Universal Functions
  cupy/_core/_gufuncs.py
  tests/cupy_tests/core_tests/test_gufuncs.py
Labels: cat:bug, prio:high, st:test-and-merge

#5380 Bump version to v10.0.0a2
  cupy/_version.py
Labels: cat:other

#5381 Bump version to v9.2.0
  cupy/_version.py
Labels: cat:other

#5391 Add `cupy-cuda113` and `cupy-rocm-4-2` to README and docs
  README.md
  docs/source/install.rst
Labels: cat:document, prio:high, to-be-backported

#5394 [backport] Add `cupy-cuda113` and `cupy-rocm-4-2` to README and docs
  README.md
Labels: backport, cat:document, prio:high

#5396 [backport] Fix typo in README
  README.md
Labels: backport, cat:document

#5268 NCCL v2.9.9
  cupyx/tools/install_library.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5402 [backport] NCCL v2.9.9
  cupyx/tools/install_library.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5388 Fix deprecated `numpy.typeDict` utilization
  cupyx/scipy/ndimage/_util.py
Labels: cat:numpy-compat, prio:high, to-be-backported

#5383 JIT: Fix supported dtype of `atomic_add` on HIP
  cupyx/jit/_builtin_funcs.py
Labels: cat:bug, prio:medium, to-be-backported

#5403 [backport] Fix deprecated `numpy.typeDict` utilization
  cupyx/scipy/ndimage/_util.py
Labels: backport, cat:numpy-compat, prio:high

#5406 Fix `license_file` option in `setup.cfg`
  setup.cfg
Labels: cat:install, prio:medium, to-be-backported

#5384 Skip unwrap tests for `numpy<1.21`
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5368 Fix signal tests for scipy 1.7.0
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:numpy-compat, prio:high

#5376 Remove the data member `use_32bit_indexing` from `CArray`
  cupy/_core/include/cupy/carray.cuh
Labels: cat:code-fix, prio:medium, to-be-backported

#5399 Update tag lines in package description and docs index
  docs/source/index.rst
  setup.py
Labels: cat:document, prio:medium, to-be-backported

#5389 Fix cupy.nanmedian's axis parameter to accept a sequence other than a tuple
  cupy/_core/_routines_statistics.pyx
  cupy/_statistics/meanvar.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: cat:bug, prio:high, to-be-backported

#5412 [backport] Skip unwrap tests for `numpy<1.21`
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: backport, cat:test, prio:high, st:test-and-merge

#5411 [backport] Fix `license_file` option in `setup.cfg`
  setup.cfg
Labels: backport, cat:install, prio:medium, st:test-and-merge

#5415 [backport] Update tag lines in package description and docs index
  docs/source/index.rst
  setup.py
Labels: backport, cat:document, prio:medium

#5413 [backport] Fix signal tests for scipy 1.7.0
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: backport, cat:numpy-compat, prio:high, st:test-and-merge

#5414 [backport] Remove the data member `use_32bit_indexing` from `CArray`
  cupy/_core/include/cupy/carray.cuh
Labels: backport, cat:code-fix, prio:medium

#5409 Remove xfail in windows jitify test
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:test, prio:medium, to-be-backported

#5408 Expose `_GUFunc` through `cupyx`
  cupyx/__init__.py
  cupyx/_gufunc.py
  docs/source/reference/ufunc.rst
Labels: cat:feature, prio:medium

#5371 Notify conflict by mergify
  .mergify.yml
Labels: cat:other, prio:medium, to-be-backported

#5419 [backport] Notify conflict by mergify
  .mergify.yml
Labels: backport, cat:other, prio:medium

#5385 Fix `numpy.unwrap` for NumPy 1.21
  cupy/_math/trigonometric.py
  tests/cupy_tests/math_tests/test_trigonometric.py
Labels: cat:numpy-compat, prio:high, st:test-and-merge

#5361 JIT: Fix `__call__()` for built-in functions
  cupyx/jit/_builtin_funcs.py
Labels: cat:code-fix, to-be-backported

#5306 Support the new DLPack exchange protocol
  cupy/__init__.py
  cupy/_core/__init__.py
  cupy/_core/core.pyx
  cupy/_core/dlpack.pxd
  cupy/_core/dlpack.pyx
  docs/source/reference/ext.rst
  docs/source/user_guide/interoperability.rst
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: array-api, cat:feature, no-compat, prio:medium, st:test-and-merge

#5407 Enable strict xfail in pytest
  setup.cfg
Labels: cat:test, prio:high, to-be-backported

#5418 [backport] Remove xfail in windows jitify test
  tests/cupy_tests/core_tests/test_raw.py
Labels: backport, cat:test, prio:medium
