Repository cupy/cupy, pull requests merged in 2021-08, with the labels that each got.

#5584 [backport] Fix broadcast error messages
  cupy/_core/internal.pyx
Labels: backport, cat:bug, prio:high

#5570 Use Sphinx's `envvar` construct
  docs/source/reference/environment.rst
Labels: cat:document, prio:medium, to-be-backported

#5587 Fix intersphinx for SciPy 1.7.1 docs
  docs/source/conf.py
Labels: blocking, cat:document, prio:high, to-be-backported

#5588 [backport] Fix intersphinx for SciPy 1.7.1 docs
  docs/source/conf.py
Labels: backport, blocking, cat:document, prio:high

#5550 Fix casts in ufunc outputs
  cupy/_core/__init__.py
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_math.pxd
  cupy/_core/_routines_math.pyx
  cupy/_core/_ufuncs.py
  cupy/_core/core.pyx
  cupy/_manipulation/basic.py
  cupy/_math/arithmetic.py
  cupy/testing/_helper.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:bug, prio:medium, to-be-backported

#5586 [backport] Use Sphinx's `envvar` construct
  docs/source/reference/environment.rst
Labels: backport, cat:document, prio:medium

#5589 [backport] Fix casts in ufunc outputs
  cupy/_core/__init__.py
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_math.pxd
  cupy/_core/_routines_math.pyx
  cupy/_core/_ufuncs.py
  cupy/_core/core.pyx
  cupy/_manipulation/basic.py
  cupy/_math/arithmetic.py
  cupy/testing/_helper.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: backport, cat:bug, prio:medium

#5595 Bump version to v10.0.0b1
  cupy/_version.py
Labels: cat:other, prio:high

#5596 Bump version to v9.3.0
  cupy/_version.py
Labels: cat:other, prio:high

#5598 [v9] Fix broken build on CUDA 9.2
  cupy_backends/cuda/api/runtime.pyx
Labels: blocking, cat:bug, prio:high

#5604 Bump dockerfile to v10.0.0b1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#5605 Bump Dockerfile to v9.3.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#5607 Reload GPG key for Docker images
  docker/rocm/Dockerfile
Labels: blocking, cat:install, prio:high

#5608 [backport] Reload GPG key for Docker images
  docker/rocm/Dockerfile
Labels: backport, blocking, cat:install, prio:high

#5574 Release the GIL for several NCCL ops
  cupy_backends/cuda/libs/nccl.pyx
Labels: cat:enhancement, prio:medium

#5573 Add support for array input in beta distribution of Generator
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/common_distributions.py
Labels: cat:enhancement, st:test-and-merge, prio:medium

#5597 Mark `lsmr` tests xfail for CSR matrices on HIP
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, prio:medium, hip

#5611 [backport] Compile with SASS for CUDA versions >= 11.1
  cupy/cuda/compiler.py
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:enhancement, no-compat, backport, blocking, prio:high

#5585 Add cupyx.scipy.sparse.linalg.minres
  cupyx/scipy/sparse/linalg/__init__.py
  cupyx/scipy/sparse/linalg/_solve.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:feature, prio:medium

#5609 Fix FFT convolve for shapes containing 1
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:bug, to-be-backported, prio:high

#5583 Support batched QR solver
  cupy/cusolver.pyx
  cupy/linalg/_decomposition.py
  cupy/linalg/_util.py
  cupy_backends/cupy_lapack.h
  cupy_backends/stub/cupy_cusolver.h
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:feature, prio:medium

#5601 Increase test timeout
  .pfnci/linux/tests/_build_and_test.sh
Labels: cat:test, to-be-backported, prio:high

#5612 Update sphinx to 4.1.2
  docs/requirements.txt
Labels: cat:document, to-be-backported, prio:high

#5617 [backport] Increase timeout for CUDA 11.4 tests
  .pfnci/config.pbtxt
Labels: cat:test, backport, prio:high

#5616 [backport] Update sphinx to 4.1.2
  docs/requirements.txt
Labels: cat:document, backport, prio:high

#5615 [backport] Increase test timeout
  .pfnci/linux/tests/_build_and_test.sh
Labels: cat:test, backport, prio:high

#5621 Add cupy-cuda114 to duplicate detection
  cupy/_environment.py
Labels: cat:other, to-be-backported

#5620 [backport] Fix the RTC call path for HIP
  cupy/cuda/compiler.py
Labels: cat:bug, backport, prio:high

#5613 [backport] Fix FFT convolve for shapes containing 1
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:bug, backport, prio:high

#5618 Add Log Series distribution to Generator
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, st:test-and-merge, prio:high

#5630 [WIP] Add CI for ROCm 4.3
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-4-3.sh
Labels: cat:test, to-be-backported, blocking, prio:high, hip

#5632 [backport] Add CI for ROCm 4.3
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-4-3.sh
Labels: cat:test, backport, blocking, prio:high, hip

#5622 Allow to compile using PTX with an envvar
  cupy/cuda/compiler.py
  docs/source/reference/environment.rst
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:enhancement, to-be-backported, prio:medium

#5635 [backport] Remove unnecessary comments
  cupy/cuda/__init__.pxd
Labels: backport, prio:medium, cat:code-fix

#5634 [backport] Allow to compile using PTX with an envvar
  cupy/cuda/compiler.py
  docs/source/reference/environment.rst
  tests/cupy_tests/core_tests/test_raw.py
Labels: cat:enhancement, backport, prio:medium

#5636 Reload GPG key for ROCm 4.2 test
  .pfnci/linux/tests/rocm-4-2.Dockerfile
Labels: cat:test, to-be-backported, prio:high

#5637 [backport] Reload GPG key for ROCm 4.2 test
  .pfnci/linux/tests/rocm-4-2.Dockerfile
Labels: cat:test, backport, prio:high

#5629 Fix cubic `for_all_dtypes_combination` tests
  .pfnci/linux/tests/_build_and_test.sh
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:test, to-be-backported, prio:high

#5628 Fix random docstring
  cupy/random/_generator_api.pyx
Labels: cat:document, to-be-backported, prio:high

#5625 [backport] Fix kernel names to be consistent
  cupy/_binary/packing.py
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pyx
  cupy/_creation/matrix.py
  cupy/_functional/piecewise.py
  cupy/_functional/vectorize.py
  cupy/_indexing/insert.py
  cupy/_manipulation/add_remove.py
  cupy/_misc/memory_ranges.py
  cupy/_sorting/search.py
  cupy/_statistics/histogram.py
  cupy/_statistics/order.py
  cupy/linalg/_util.py
  cupy/random/_generator.py
  cupy/random/_kernels.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_spline_prefilter_core.py
  cupyx/scipy/ndimage/measurements.py
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/compressed.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csr.py
  cupyx/scipy/sparse/dia.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_convex_analysis.py
  cupyx/scipy/special/_digamma.py
  cupyx/scipy/special/_erf.py
  cupyx/scipy/special/_gammaln.py
  cupyx/scipy/special/_statistics.py
  cupyx/scipy/special/_zeta.py
Labels: backport, prio:medium, cat:code-fix

#5639 [backport] Fix cubic `for_all_dtypes_combination` tests
  .pfnci/linux/tests/_build_and_test.sh
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:test, backport, prio:high

#5555 [HIP] Add new eigensolvers from rocSOLVER
  cupy/cusolver.pyx
  cupy/linalg/_eigenvalue.py
  cupy_backends/hip/cupy_rocsolver.h
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, prio:high, hip

#5638 Add support for CUDA Python
  .pfnci/config.pbtxt
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.sh
  cupy/cuda/cub.pyx
  cupy_backends/cuda/api/_driver_enum.pxd
  cupy_backends/cuda/api/_driver_enum.pyx
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_driver_typedef.pxi
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupy_backends/cuda/api/_runtime_enum.pyx
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/curand.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/nvrtc.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/cuda/libs/profiler.pyx
  cupy_setup_build.py
  cupyx/_runtime.py
  docs/source/reference/environment.rst
Labels: cat:feature, prio:high

#5624 Add Power distribution to Generator
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:high

#5600 Fix compute capability check
  install/build.py
Labels: cat:bug, to-be-backported, prio:medium

#5645 Add Chi-square distribution to Generator
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:high

#5646 [backport] Fix compute capability check
  install/build.py
Labels: cat:bug, backport, prio:medium

#5650 Fix branch name of cuda-python
  .pfnci/linux/tests/cuda11x-cuda-python.sh
Labels: cat:test, to-be-backported, prio:high

#5642 Fix squareness checks
  cupy/cublas.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_eigenvalue.py
  cupy/linalg/_norms.py
  cupy/linalg/_product.py
  cupy/linalg/_solve.py
  cupy/linalg/_util.py
  cupyx/lapack.py
  cupyx/linalg/_solve.py
  cupyx/linalg/sparse/_solve.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/sparse/csgraph/_traversal.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:bug, to-be-backported, prio:high

#5644 `__array_function__` feature by default
  docs/source/user_guide/interoperability.rst
Labels: to-be-backported, cat:numpy-compat, prio:medium

#5651 Show CUDA Python version
  cupyx/_runtime.py
Labels: cat:enhancement, prio:medium

#5653 [backport] `__array_function__` feature by default
  docs/source/user_guide/interoperability.rst
Labels: cat:document, backport, prio:medium

#5652 [backport] Fix squareness checks
  cupy/cublas.py
  cupy/linalg/_decomposition.py
  cupy/linalg/_eigenvalue.py
  cupy/linalg/_norms.py
  cupy/linalg/_product.py
  cupy/linalg/_solve.py
  cupy/linalg/_util.py
  cupyx/lapack.py
  cupyx/linalg/_solve.py
  cupyx/linalg/sparse/_solve.py
  cupyx/scipy/linalg/decomp_lu.py
  cupyx/scipy/sparse/csgraph/_traversal.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:bug, backport, prio:high

#5545 Add ncclAvg and ncclBfloat16 for NCCL
  cupy_backends/cuda/libs/nccl.pxd
Labels: cat:enhancement, to-be-backported, prio:medium

#5654 Fix `unique` for empty array
  cupy/_manipulation/add_remove.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: cat:bug, to-be-backported, prio:high

#5658 [backport] Fix `unique` for empty array
  cupy/_manipulation/add_remove.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: cat:bug, backport, prio:high

#5657 Fix version check for new ROCm version definition
  cupy/_core/_routines_linalg.pyx
Labels: cat:enhancement, blocking, prio:high

#5656 [backport] Add ncclAvg and ncclBfloat16 for NCCL
  cupy_backends/cuda/libs/nccl.pxd
Labels: cat:enhancement, backport, prio:medium

#5661 [backport] Fix version check for new ROCm version definition
  cupy/_core/_routines_linalg.pyx
Labels: cat:enhancement, backport, blocking, prio:high

#5662 Add a workaround for ROCm 4.3.0 for testing
  .pfnci/linux/tests/rocm-4-3.Dockerfile
Labels: cat:test, blocking, prio:high

#5663 [backport] Add a workaround for ROCm 4.3.0 for testing
  .pfnci/linux/tests/rocm-4-3.Dockerfile
Labels: cat:test, backport, blocking, prio:high

#5648 Add Dirichlet distribution to Generator
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:high

#5614 Add `batch_identity` helper
  cupy/linalg/_decomposition.py
  cupy/linalg/_product.py
  cupy/linalg/_util.py
  cupyx/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: prio:medium, cat:code-fix

#5655 Add F distribution to Generator
  cupy/random/_generator_api.pyx
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:high

#5660 Rest of version check fix for new ROCm version definition
  cupy/fft/_fft.py
  tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_compiler.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#5670 [backport] Rest of version check fix for new ROCm version definition
  cupy/fft/_fft.py
  tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: cat:enhancement, backport, blocking, prio:high

#5669 Add ROCm 4.3 in duplicate detection
  cupy/_environment.py
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#5593 Fix `skipTest` in `test_decomp_lu`
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:test, to-be-backported, prio:medium

#5672 [backport] Fix `skipTest` in `test_decomp_lu`
  tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Labels: cat:test, backport, prio:medium

#5633 Support ROCm v4.3 in document
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#5674 [backport] Support ROCm v4.3 in document
  README.md
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:high

#5680 Bump version to v9.4.0
  cupy/_version.py
Labels: cat:other

#5679 Bump version to v10.0.0b2
  cupy/_version.py
Labels: cat:other

#5686 [backport] Fix spline filter with large array
  cupyx/scipy/ndimage/_spline_prefilter_core.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, backport, prio:high
