Repository cupy/cupy, pull requests merged in 2021-01, with the labels that each got.

#4509 Document `random.uniform` may return high
  cupy/random/_distributions.py
Labels: cat:document, prio:medium

#4508 Fix potential race when compiling cuFFT callbacks
  cupy/fft/_callback.pyx
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4468 Implementing cupyx.scipy.signal.oaconvolve
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/signaltools.py
  docs/source/reference/signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#4444 ndimage: complex dtype support in filters and interpolation
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/ndimage/filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:enhancement, prio:medium

#4519 Remove unnecessary `return` statements
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:test, st:test-and-merge

#4102 ROCm: Improve compiler
  cupy/core/core.pyx
  cupy/cuda/__init__.py
  cupy/cuda/compiler.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4177 Add NumPy v1.17 new random API with `Generator`
  cupy/random/LICENSE
  cupy/random/__init__.py
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  cupy_setup_build.py
  docs/source/reference/random.rst
  install/build.py
  setup.py
  tests/cupy_tests/random_tests/test_bit_generator.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:medium

#4517 Add DLPack as submodule & Fix multiple issues
  cupy/core/core.pyx
  cupy/core/dlpack.pxd
  cupy/core/dlpack.pyx
  cupy/core/include/cupy/README.md
  cupy/core/include/cupy/dlpack/README.md
  cupy/core/include/cupy/dlpack/dlpack.h
  cupy_setup_build.py
  docs/source/reference/interoperability.rst
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4407 Add `cufftXtMakePlanMany` and `cufftXtExec`
  cupy/core/_dtype.pyx
  cupy/cuda/cufft.pxd
  cupy/cuda/cufft.pyx
  cupy/cuda/cupy_cufft.h
  tests/cupy_tests/cuda_tests/test_cufft.py
Labels: cat:feature, prio:medium

#4527 Fix `cupy.concatenate` typecheck for out with different dtype
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4525 Add complex support to `cupyx.scipy.signal` functions
  cupyx/scipy/signal/_signaltools_core.py
  cupyx/scipy/signal/bsplines.py
  cupyx/scipy/signal/signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:enhancement, prio:medium

#4528 [backport] Fix `cupy.concatenate` typecheck for out with different dtype
  cupy/core/_routines_manipulation.pyx
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: backport, cat:bug, prio:high

#4217 ROCm: Cover more new BLAS/SOLVER functions
  cupy/core/_routines_linalg.pyx
  cupy/cusolver.py
  cupy/linalg/_decomposition.py
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/hip/cupy_rocsolver.h
  tests/cupy_tests/linalg_tests/test_decomposition.py
  tests/cupy_tests/test_cublas.py
  tests/cupy_tests/test_cusolver.py
  tests/cupyx_tests/test_lapack.py
Labels: cat:hip, prio:medium, st:test-and-merge

#4530 Fix `cupy.take` from an empty array
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: cat:bug, st:test-and-merge, to-be-backported

#4524 Fix bug on bad interaction between `__cuda_array_interface__` and `__array_ufunc__` on HIP
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:bug, prio:high, st:test-and-merge

#4542 [backport] Fix `cupy.take` from an empty array
  cupy/core/_routines_indexing.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: backport, cat:bug, st:test-and-merge

#4536 Fix sparse format of `kron`
  cupyx/scipy/sparse/construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
Labels: cat:numpy-compat, prio:high, st:blocked-by-another-pr, st:test-and-merge, to-be-backported

#4512 Fix integer GEMM
  cupy/core/_routines_linalg.pyx
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#4547 [backport] Fix sparse format of `kron`
  cupyx/scipy/sparse/construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
Labels: backport, cat:numpy-compat, prio:high, st:test-and-merge

#4551 [backport] Fix integer GEMM
  cupy/core/_routines_linalg.pyx
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4544 Fix `__format__`
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4523 Fix `axis` of `cupy.gradient`
  cupy/_math/sumprod.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:bug, prio:high

#4543 Fix windows build of random module
  cupy/random/cupy_distributions.cu
Labels: cat:bug, prio:high, st:test-and-merge

#4545 Remove deprecated stubs for CUDA<9.2
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/cupy_cusparse.h
Labels: cat:code-fix, prio:medium, st:test-and-merge

#4553 ROCm: skip multi-GPU FFT tests
  tests/cupy_tests/fft_tests/test_cache.py
Labels: cat:hip, st:test-and-merge

#4554 Fix return type of `polynomial.__eq__`
  cupy/lib/_polynomial.pyx
Labels: cat:numpy-compat, st:test-and-merge, to-be-backported

#4555 [backport] Fix return type of `polynomial.__eq__`
  cupy/lib/_polynomial.pyx
Labels: backport, cat:numpy-compat

#4539 Add cupy.round
  cupy/__init__.py
  tests/cupy_tests/core_tests/fusion_tests/test_routines.py
  tests/cupy_tests/math_tests/test_rounding.py
Labels: cat:feature, prio:medium

#4518 Remove experimental warnings from cupyx.scipy.ndimage
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/ndimage/interpolation.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4485 Fixes a bunch of AMD issues
  cupy/core/_cub_reduction.pyx
  cupy/core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:hip, prio:high

#4535 [backport] Import DLPack header file & Fix multiple issues
  cupy/core/core.pyx
  cupy/core/dlpack.pxd
  cupy/core/dlpack.pyx
  cupy/core/include/cupy/README.md
  cupy/core/include/cupy/dlpack/README.md
  cupy/core/include/cupy/dlpack/dlpack.h
  cupy_setup_build.py
  docs/source/reference/interoperability.rst
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#4562 Support passing pointers as integers in memory copy routines
  cupy/core/core.pyx
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#4433 Support texture object in `cupy.ElementwiseKernel`
  cupy/core/_kernel.pxd
  cupy/core/_kernel.pyx
  cupy/core/_scalar.pyx
  cupy/cuda/texture.pyx
  docs/source/tutorial/kernel.rst
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: cat:feature, prio:medium, st:test-and-merge

#4563 Fix return type of `polynomial.__eq__` to `numpy.bool_`
  cupy/lib/_polynomial.pyx
Labels: cat:bug, prio:high, st:test-and-merge

#4552 ndimage: coordinate rounding fix for order=0 interpolation
  cupyx/scipy/ndimage/_interp_kernels.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, prio:high, st:test-and-merge

#4559 Fix DLPack header version
  cupy/core/dlpack.pyx
  cupy/core/include/cupy/dlpack/README.md
  cupy/core/include/cupy/dlpack/dlpack.h
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#4566 Check if the accepted_error was not raised from test code
  cupy/testing/helper.py
Labels: cat:test, prio:medium, st:test-and-merge

#4521 Fix fusion tests for HIP
  cupy/_math/floating.py
  cupy/core/_fusion_kernel.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_example.py
Labels: cat:hip, prio:medium, st:blocked-by-another-pr

#4565 Remove dependency on CUDA's math_constants.h
  cupy/core/include/cupy/math_constants.h
Labels: cat:bug, prio:high

#4569 Fix `cupy.array` from nested list of zero-dim ndarray
  cupy/core/core.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:bug, prio:high, to-be-backported

#4572 Bump version to v9.0.0b2
  cupy/_version.py
Labels: cat:install, prio:high

#4575 Bump version to v8.4.0
  cupy/_version.py
Labels: cat:install, prio:high, st:test-and-merge

#4574 Fix windows build
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
Labels: cat:bug, prio:high, st:test-and-merge

#4578 Bump Dockerfile version to v9.0.0b2
  docker/python3/Dockerfile
Labels: cat:install

#4579 Bump Dockerfile version to v8.4.0
  docker/python3/Dockerfile
Labels: cat:install

#4487 Fix warning message on cuDNN version
  install/build.py
Labels: cat:bug, prio:medium, st:test-and-merge, to-be-backported

#4498 Test `numpy.VisibleDeprecationWarning`
  setup.cfg
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:test, prio:medium, st:test-and-merge, to-be-backported

#4580 [backport] Fix warning message on cuDNN version
  install/build.py
Labels: backport, cat:bug, prio:medium, st:test-and-merge

#4571 [backport] Fix `cupy.array` from nested list of zero-dim ndarray
  cupy/core/core.pyx
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: backport, cat:bug, prio:high

#4570 [backport] ndimage: coordinate rounding fix for order=0 interpolation
  cupyx/scipy/ndimage/_interp_kernels.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: backport, cat:bug, prio:high
