Repository cupy/cupy, pull requests merged in 2021-11, with the labels that each got.

#5955 CI: Do not run full combination test even for branch tests for ROCm
  .pfnci/generate.py
  .pfnci/linux/tests/actions/_environment.sh
  .pfnci/linux/tests/rocm-4-0.sh
  .pfnci/linux/tests/rocm-4-2.sh
  .pfnci/linux/tests/rocm-4-3.sh
Labels: to-be-backported, cat:numpy-compat, blocking, prio:high

#5974 [backport] CI: Do not run full combination test even for branch tests for ROCm
  .pfnci/linux/tests/_environment.sh
  .pfnci/linux/tests/rocm.sh
Labels: backport, cat:numpy-compat, blocking, prio:high

#5963 Dont use `with device` in code base
  cupy/_core/core.pyx
  cupy/_core/dlpack.pyx
  cupy/_manipulation/basic.py
  cupy/array_api/_array_object.py
  cupy/array_api/_creation_functions.py
  cupy/cuda/cufft.pyx
  cupy/cuda/device.pyx
  cupy/cuda/memory.pyx
  cupy/fft/_cache.pyx
  cupyx/profiler/_time.py
Labels: cat:bug, blocking, prio:high

#5976 Add `sphinx-copybutton`
  docs/requirements.txt
  docs/source/conf.py
Labels: cat:document, prio:medium

#5977 Fix `cupyx.tools.install_library` for windows
  cupyx/tools/install_library.py
Labels: cat:bug, prio:high

#5939 Update the Array API module
  cupy/array_api/_array_object.py
  cupy/array_api/_typing.py
  tests/cupy_tests/array_api_tests/test_creation_functions.py
Labels: cat:enhancement, prio:medium

#5902 Support using cuTENSOR in elementwise ufuncs
  cupy/_core/__init__.py
  cupy/_core/_accelerator.pxd
  cupy/_core/_accelerator.pyx
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_math.pyx
  cupy/_math/misc.py
  cupy/cutensor.pyx
Labels: cat:enhancement, prio:medium

#5895 Enable new random api in ROCm 4.3
  cupy/random/__init__.py
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  docs/source/install.rst
  install/cupy_builder/_modules.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:enhancement, prio:medium

#5975 [backport] Document `CUPY_ACCELERATORS`
  docs/source/reference/routines.rst
  docs/source/upgrade.rst
  docs/source/user_guide/performance.rst
Labels: cat:document, backport, prio:medium

#5980 Add favicon to docs
  docs/source/_static/favicon.ico
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:medium

#5973 Add PyTorch with RawKernel example to docs
  docs/source/user_guide/interoperability.rst
Labels: cat:document, prio:medium

#5983 [backport] Add favicon to docs
  docs/source/_static/favicon.ico
  docs/source/conf.py
Labels: cat:document, backport, prio:medium

#5982 Make `CUPY_DLPACK_EXPORT_VERSION` consistent
  cupy/_core/core.pyx
  cupy/_util.pyx
Labels: prio:low, cat:code-fix

#5966 Mention `np.matrix` in the difference section
  docs/source/user_guide/difference.rst
Labels: cat:document, prio:medium

#5967 Split loop testing helpers into `_loops`
  cupy/testing/__init__.py
  cupy/testing/_helper.py
  cupy/testing/_loops.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/cupy_tests/testing_tests/test_loops.py
  tests/cupyx_tests/test_pinned_array.py
Labels: prio:medium, cat:code-fix

#5984 Fix comment in device switching
  cupy/cuda/device.pyx
Labels: prio:medium, cat:code-fix

#5953 Fix error type/message for duplicate value in axis
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
Labels: to-be-backported, cat:numpy-compat, prio:low

#5732 Support cuTENSOR 1.3.3
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:medium

#5707 Fix import failure when pytest namespace is available (#5703)
  cupy/testing/_attr.py
  cupy/testing/_helper.py
  cupy/testing/_loops.py
  cupy/testing/_pytest_impl.py
Labels: cat:enhancement, to-be-backported, st:awaiting-author, prio:medium

#5987 [backport] Fix error type/message for duplicate value in axis
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
Labels: backport, cat:numpy-compat, prio:low

#5978 Fix `ravel` for strides 0
  cupy/_core/core.pyx
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:bug, to-be-backported, prio:high

#5985 Avoid using with context for streams
  cupy/cuda/stream.pyx
  cupy/cuda/texture.pyx
Labels: cat:bug, prio:medium

#5925 Implement simple array creation / serialization methods
  cupy/__init__.py
  cupy/_creation/from_data.py
  cupy/_io/formatting.py
  cupy/_io/text.py
  docs/source/reference/creation.rst
  docs/source/reference/io.rst
  tests/cupy_tests/creation_tests/test_from_data.py
  tests/cupy_tests/io_tests/test_formatting.py
  tests/cupy_tests/io_tests/test_text.py
Labels: cat:feature, prio:medium, hacktoberfest-accepted

#5981 Use index_t for faster address calculation
  cupy/_core/include/cupy/carray.cuh
Labels: cat:performance, prio:medium

#5996 Support CUDA 11.5 for library installer
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:high

#5999 Add cupy-cuda115 to duplicate detection
  cupy/_environment.py
Labels: cat:enhancement, blocking, prio:high

#5995 Cover a bit more of cuTENSOR in perf guide
  docs/source/user_guide/performance.rst
Labels: cat:document, prio:medium

#5993 Merge fp16 headers for CUDA 11.2+
  .pfnci/config.pbtxt
  .pfnci/coverage.md
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.hpp
Labels: cat:enhancement, to-be-backported, prio:high

#6002 [backport] Improve handling of FlexCI test runs
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:high

#6003 [backport] Upload cache even when test failed in FlexCI
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:high

#5988 Use SHA1 hash for kernel cache key to support Linux in FIPS-compliant mode
  cupy/cuda/compiler.py
Labels: cat:enhancement, prio:medium

#5997 Support CUDA 11.5 on documents
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#5986 Replace favicon with high resolution one
  docs/source/_static/favicon.ico
Labels: cat:document, to-be-backported, prio:medium

#6008 [backport] Replace favicon with high resolution one
  docs/source/_static/favicon.ico
Labels: cat:document, backport, prio:medium

#6006 [backport] Support CUDA 11.5 on documents
  README.md
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:high

#6005 [backport] Support cuTENSOR 1.3.3
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:medium

#6010 [backport] Support CUDA 11.5 for library installer
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:high

#5994 Update upgrade guide for v10
  docs/source/upgrade.rst
Labels: cat:document, blocking, prio:high

#6007 Fix cuTENSOR installation on Windows
  cupyx/tools/install_library.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#5779 Fix: Allow generating cubins for the max known CC
  cupy/cuda/compiler.py
Labels: cat:bug, to-be-backported, prio:medium

#6004 [backport] Merge fp16 headers for CUDA 11.2+
  .pfnci/config.pbtxt
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.sh
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.3/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.hpp
Labels: cat:enhancement, backport, blocking, prio:high

#6027 CI: Use `ccache` in Pre-review Test
  .github/workflows/pretest.yml
Labels: cat:test, prio:medium

#6023 Fix hash length for SHA1
  cupy/cuda/compiler.py
Labels: cat:bug, blocking, prio:high

#6022 [backport] Fix cuTENSOR installation on Windows
  cupyx/tools/install_library.py
Labels: cat:bug, backport, blocking, prio:high

#6024 [backport] Fix: Allow generating cubins for the max known CC
  cupy/cuda/compiler.py
Labels: cat:bug, backport, prio:high

#6030 Doc: Fix typo in copyright line
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:medium

#5899 FlexCI test against Python 3.10
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  setup.cfg
Labels: cat:test, prio:high

#6028 Suggest using binary packages when build failed
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, prio:medium

#6035 [backport] Doc: Fix typo in copyright line
  docs/source/conf.py
Labels: cat:document, backport, prio:medium

#5998 [backport] Fix `ravel` for strides 0
  cupy/_core/core.pyx
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:bug, backport, prio:high

#6016 CI: Fix ccache not working
  .pfnci/linux/tests/actions/_environment.sh
Labels: cat:test

#6034 CI: Migrate ROCm build test from FlexCI to GitHub Actions (using ROCm docker image)
  .github/workflows/pretest-rocm-test.sh
  .github/workflows/pretest.yml
  .pfnci/config.pbtxt
  .pfnci/linux/main-flexci-rocm-build.sh
Labels: cat:test, prio:medium

#6032 Display license terms when downloading libraries
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:high

#6041 [backport] Display license terms when downloading libraries
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:high

#6042 Bump version to v10.0.0rc1
  cupy/_version.py
Labels: cat:other

#6043 Bump version to v9.6.0
  cupy/_version.py
Labels: cat:other

#6038 Add Python 3.10.0 to support list
  docs/source/install.rst
  setup.py
Labels: cat:document, blocking, prio:high

#5914 Add Slack/Gitter notification when branch test fail
  .pfnci/flexci_notify.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, prio:medium

#6029 Improve import error message
  cupy/__init__.py
  cupy/_environment.py
Labels: cat:enhancement, prio:medium

#5677 Lazy-preload cuDNN
  cupy/__init__.py
  cupy/_environment.py
  cupy/cuda/cudnn.py
  cupy/cudnn.pyx
  cupyx/_runtime.py
Labels: cat:enhancement, blocking, prio:high

#5970 Fix `__dlpack__` protocol
  cupy/_core/core.pyx
Labels: cat:bug, blocking, prio:high

#6039 CI: allow running tests selectively
  .pfnci/config.pbtxt
  .pfnci/flexci_test_tag.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, prio:high

#5590 Add `cupyx.distributed`
  cupy_backends/cuda/libs/nccl.pyx
  cupyx/distributed/__init__.py
  cupyx/distributed/_comm.py
  cupyx/distributed/_init.py
  cupyx/distributed/_klv_utils.py
  cupyx/distributed/_nccl_comm.py
  cupyx/distributed/_store.py
  cupyx/distributed/_store_actions.py
  docs/source/reference/distributed.rst
  docs/source/reference/index.rst
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
  tests/cupyx_tests/distributed_tests/test_store.py
Labels: cat:feature, prio:medium

#6046 Fix: Add missing output dtype check for direct correlate/convolve
  cupyx/scipy/signal/_signaltools_core.py
Labels: cat:bug, prio:high

#6036 CI: Merge doctest to example test in FlexCI
  .pfnci/config.pbtxt
  .pfnci/coverage.md
  .pfnci/generate.py
  .pfnci/linux/tests/actions/doctest.sh
  .pfnci/linux/tests/actions/example.sh
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, prio:high

#6056 Fix notifier to work on Python 3.6
  .pfnci/flexci_notify.py
Labels: cat:test

#6054 Fix cuDNN version not displayed in wheel installation
  cupyx/_runtime.py
Labels: cat:bug, prio:high

#6063 Bump cupy version in Dockerfile to v10.0.0rc1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6064 Bump cupy version in Dockerfile to v9.6.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6065 [v10] Update stable branch
  .pfnci/BRANCH
  docs/source/upgrade.rst
Labels: cat:document

#6073 Doc: Add more footnotes to comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported

#6075 Add more aliases for compatibility with NumPy
  cupy/__init__.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:enhancement, to-be-backported

#6067 Add v11 to compatibility matrix
  docs/source/upgrade.rst
Labels: cat:document, prio:medium

#6071 Fix `__all__` in `cupyx.scipy.fft`
  cupyx/scipy/fft/__init__.py
Labels: cat:bug, to-be-backported, prio:medium

#6080 [backport] Add more aliases for compatibility with NumPy
  cupy/__init__.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:enhancement, backport, prio:medium

#6079 [backport] Doc: Add more footnotes to comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, backport, prio:medium

#6084 Fix CI cannot override cuSPARSELt/cuTENSOR version preinstalled
  .pfnci/generate.py
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
Labels: cat:test, to-be-backported, prio:high

#6087 [backport] Fix CI cannot override cuSPARSELt/cuTENSOR version preinstalled
  .pfnci/generate.py
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
Labels: cat:test, backport, prio:high

#6072 Exclude `kernel_version` from comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported, prio:medium

#6090 [backport] Exclude `kernel_version` from comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, backport, prio:medium

#6095 [backport] Workaround DeprecationWarning raised from pkg_resources
  setup.cfg
Labels: cat:test, backport

#6015 Fix `testing.multi_gpu` to add pytest marker
  cupy/testing/_attr.py
Labels: cat:test, to-be-backported, prio:medium

#6051 Raise better message when importing CPU array via DLPack
  cupy/_core/dlpack.pyx
Labels: cat:enhancement, to-be-backported, prio:medium

#6096 [backport] Fix `testing.multi_gpu` to add pytest marker
  cupy/testing/_attr.py
Labels: cat:test, backport, prio:medium

#6098 Fix missing `multi_gpu` annotation in tests
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:test, to-be-backported, prio:medium

#6093 Remove LLVM_PATH note on document
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:medium

#6083 [backport] Fix `__all__` in `cupyx.scipy.fft`
  cupyx/scipy/fft/__init__.py
Labels: cat:bug, backport, prio:medium

#6097 [backport] Raise better message when importing CPU array via DLPack
  cupy/_core/dlpack.pyx
Labels: cat:enhancement, backport, prio:medium

#6019 Avoid 64bit division for reduce register consumption
  cupy/_core/_carray.pxd
  cupy/_core/_carray.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/include/cupy/carray.cuh
Labels: to-be-backported, cat:performance, prio:medium

#5964 Detect repeated axis in reduction
  cupy/_core/_reduction.pyx
  cupy/_manipulation/rearrange.py
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:bug, to-be-backported, prio:medium

#6100 [backport] Fix missing `multi_gpu` annotation in tests
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:test, backport, prio:medium

#6101 [backport] Remove LLVM_PATH note on document
  docs/source/install.rst
Labels: cat:document, backport, prio:medium

#6102 [backport] Avoid 64bit division for reduce register consumption
  cupy/_core/_carray.pxd
  cupy/_core/_carray.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/include/cupy/carray.cuh
Labels: backport, cat:performance, prio:medium

#6086 Apply upstream patch to `cupy.array_api`
  cupy/array_api/__init__.py
  cupy/array_api/_array_object.py
  cupy/array_api/_creation_functions.py
  cupy/array_api/_data_type_functions.py
  cupy/array_api/_searching_functions.py
  cupy/array_api/_set_functions.py
  tests/cupy_tests/array_api_tests/test_array_object.py
  tests/cupy_tests/array_api_tests/test_creation_functions.py
Labels: cat:enhancement, to-be-backported, prio:high

#6103 [backport] Detect repeated axis in reduction
  cupy/_core/_reduction.pyx
  cupy/_manipulation/rearrange.py
  tests/cupy_tests/core_tests/test_reduction.py
Labels: cat:bug, backport, prio:medium

#6068 [v10] Update labels of Docs column
  docs/source/upgrade.rst
Labels: cat:document, prio:medium

#6074 Borrow more non-GPU APIs from NumPy
  cupy/__init__.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6076 Import more dtype aliases from NumPy
  cupy/__init__.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6077 Borrow indexing APIs from NumPy
  cupy/__init__.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6109 [backport] Borrow more non-GPU APIs from NumPy
  cupy/__init__.py
Labels: cat:enhancement, backport, prio:medium

#6111 [backport] Borrow indexing APIs from NumPy
  cupy/__init__.py
Labels: cat:enhancement, backport, prio:medium

#6110 [backport] Import more dtype aliases from NumPy
  cupy/__init__.py
Labels: cat:enhancement, backport, prio:medium

#6081 Fix `__getitem__` on Ellipsis and advanced indexing dimension
  cupy/_core/_routines_indexing.pxd
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: cat:bug, to-be-backported, prio:high

#6114 Fix exception handling in cupyx.distributed
  cupyx/distributed/_store.py
  tests/cupyx_tests/distributed_tests/test_comm.py
  tests/cupyx_tests/distributed_tests/test_store.py
Labels: cat:test, to-be-backported, prio:high

#6113 [backport] Fix `__getitem__` on Ellipsis and advanced indexing dimension
  cupy/_core/_routines_indexing.pxd
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/internal.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Labels: cat:bug, backport, prio:high

#6116 [backport] Fix exception handling in cupyx.distributed
  cupyx/distributed/_store.py
  tests/cupyx_tests/distributed_tests/test_comm.py
  tests/cupyx_tests/distributed_tests/test_store.py
Labels: cat:test, backport, prio:high

#6117 Improve FlexCI test scripts
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
Labels: cat:test, to-be-backported, prio:medium

#6105 [backport] Apply upstream patch to `cupy.array_api`
  cupy/array_api/__init__.py
  cupy/array_api/_array_object.py
  cupy/array_api/_creation_functions.py
  cupy/array_api/_data_type_functions.py
  cupy/array_api/_searching_functions.py
  cupy/array_api/_set_functions.py
  tests/cupy_tests/array_api_tests/test_array_object.py
  tests/cupy_tests/array_api_tests/test_creation_functions.py
Labels: cat:enhancement, backport, prio:high

#6082 Add polynomial modules to comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported, prio:medium

#6045 Support cuSPARSELt 0.2.0
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda-doctest.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/cupy_cusparselt.h
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cupy_cusparselt.h
  cupy_backends/stub/cupy_cusparselt.h
  docs/source/install.rst
  examples/cusparselt/matmul.py
Labels: cat:enhancement, to-be-backported, prio:high

#6066 Fix CI result notification message format
  .pfnci/flexci_notify.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:medium

#6122 [backport] Add polynomial modules to comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, backport, prio:medium

#6124 [backport] Fix CI result notification message format
  .pfnci/flexci_notify.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:medium

#6120 CI: Add timeout to show_config
  .pfnci/linux/tests/actions/unittest.sh
Labels: cat:test, to-be-backported

#6132 [backport] CI: Add timeout to show_config
  .pfnci/linux/tests/actions/unittest.sh
Labels: cat:test, backport

#6055 Add link to compatibility matrix
  docs/source/upgrade.rst
Labels: cat:document, to-be-backported, prio:medium

#6135 [backport] Add link to compatibility matrix
  docs/source/upgrade.rst
Labels: cat:document, backport, prio:medium

#6119 [backport] Improve FlexCI test scripts
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
Labels: cat:test, backport, prio:medium

#6025 Replace `distutils` with `setuptools` in Windows `cl.exe` detection
  cupy/cuda/compiler.py
Labels: cat:install, to-be-backported, takeover, prio:high

#6106 compile cub/thrust with no unique symbol
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, to-be-backported, prio:high

#6037 CI: add link to ROCm projects in CI coverage matrix
  .pfnci/coverage.md
  .pfnci/generate.py
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, prio:low

#6138 [backport] Replace `distutils` with `setuptools` in Windows `cl.exe` detection
  cupy/cuda/compiler.py
Labels: cat:install, backport, takeover, prio:high

#6136 Revert cuSPARSELt 0.2.0 support (#6045 and #6129)
  .pfnci/coverage.md
  .pfnci/linux/tests/array-api.Dockerfile
  .pfnci/linux/tests/cuda-doctest.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/cupy_cusparselt.h
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cupy_cusparselt.h
  cupy_backends/stub/cupy_cusparselt.h
  docs/source/install.rst
  examples/cusparselt/matmul.py
Labels: cat:test, prio:high

#6140 [backport] Compile cub/thrust with no unique symbol
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, backport, prio:high

#6142 Update footnotes in comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported, prio:medium

#6143 [backport] Update footnotes in comparison table
  docs/source/_comparison_generator.py
Labels: cat:document, backport, prio:medium

#6141 CI: Fix package override sometimes fails in CentOS
  .pfnci/generate.py
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
Labels: cat:test, to-be-backported, prio:high

#6146 [backport] CI: Need to update CUDA driver in cuda115.multi
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:high

#6108 Support cuDNN 8.3.0
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#6150 [backport] Support cuDNN 8.3.0
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#6148 [backport] CI: add link to ROCm projects in CI coverage matrix
  .pfnci/coverage.md
  .pfnci/generate.py
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/matrix.yaml
Labels: cat:test, backport, prio:low

#6118 Allow leading unit dimensions in copy source
  cupy/_core/_routines_indexing.pyx
  cupy/_manipulation/basic.py
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:bug, to-be-backported

#6153 [backport] Allow leading unit dimensions in copy source
  cupy/_core/_routines_indexing.pyx
  cupy/_manipulation/basic.py
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:bug, backport

#6121 Always test broadcast in `copyto`
  cupy/_manipulation/basic.py
  tests/cupy_tests/core_tests/fusion_tests/test_routines.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:bug, to-be-backported, prio:high

#6152 delete from os import path
  install/cupy_builder/cupy_setup_build.py
Labels: to-be-backported, prio:medium, cat:code-fix

#6165 [backport] delete from os import path
  install/cupy_builder/cupy_setup_build.py
Labels: backport, prio:medium, cat:code-fix

#6155 [backport] Always test broadcast in `copyto`
  cupy/_manipulation/basic.py
  tests/cupy_tests/core_tests/fusion_tests/test_routines.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:bug, backport, prio:high

#6172 Handles infinities of the same sign in `logaddexp` and `logaddexp2`
  cupy/_math/explog.py
  tests/cupy_tests/math_tests/test_explog.py
Labels: cat:bug, to-be-backported, prio:high

#6175 CI: Fix unquoted specifiers
  .pfnci/generate.py
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-0.Dockerfile
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
Labels: cat:test, to-be-backported, prio:medium

#6167 Fix empty `solve`
  cupy/cublas.py
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:bug, to-be-backported

#6164 Fix empty Cholesky
  cupy/linalg/_decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:bug, to-be-backported

#6176 [backport] Handles infinities of the same sign in `logaddexp` and `logaddexp2`
  cupy/_math/explog.py
  tests/cupy_tests/math_tests/test_explog.py
Labels: cat:bug, backport, prio:high
