Repository cupy/cupy, pull requests merged in 2021-12, with the labels that each got.

#6184 [backport] Fix empty Cholesky
  cupy/linalg/_decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:bug, backport

#6183 [backport] Fix empty `solve`
  cupy/cublas.py
  cupy/linalg/_solve.py
  tests/cupy_tests/linalg_tests/test_solve.py
Labels: cat:bug, backport

#6174 CI: Update limits to reduce cache size
  .github/workflows/pretest.yml
  .pfnci/linux/tests/actions/cleanup.sh
Labels: cat:test, to-be-backported, prio:medium

#6179 Remove memory copy in matmul
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:performance, prio:medium

#6182 [backport] CI: Fix unquoted specifiers
  .pfnci/generate.py
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-0.Dockerfile
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
Labels: cat:test, backport, prio:medium

#6185 [backport] CI: Update limits to reduce cache size
  .github/workflows/pretest.yml
  .pfnci/linux/tests/actions/cleanup.sh
Labels: cat:test, backport, prio:medium

#6188 Deprecate MachAr (support NumPy 1.22)
  cupy/__init__.py
Labels: to-be-backported, cat:numpy-compat

#6130 Trigger FlexCI from GitHub Actions
  .github/workflows/flexci.yml
  .github/workflows/flexci_dispatcher.py
  .github/workflows/pretest.yml
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/flexci_test_tag.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:medium

#6189 [backport] Deprecate MachAr (support NumPy 1.22)
  cupy/__init__.py
Labels: backport, cat:numpy-compat

#6178 Support eigenvalue solver 64bit API
  cupy/linalg/_eigenvalue.py
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/hip/cupy_rocsolver.h
  cupy_backends/stub/cupy_cusolver.h
Labels: cat:enhancement, to-be-backported, prio:high

#6191 [backport] Trigger FlexCI from GitHub Actions
  .github/workflows/flexci.yml
  .github/workflows/flexci_dispatcher.py
  .github/workflows/pretest.yml
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/flexci_test_tag.py
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:medium

#6190 Support pre-release NumPy version in tests
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:test, to-be-backported

#6171 Add tests for `convolve2d`
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, to-be-backported, prio:medium

#6193 [backport] Support pre-release NumPy version in tests
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:test, backport

#6127 Support all advanced indexing
  cupy/_core/_routines_indexing.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6156 Add `cupy.mask_indices`
  cupy/__init__.py
  cupy/_indexing/generate.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:feature, prio:medium

#6131 Add `cupy.array_api.linalg`
  cupy/array_api/__init__.py
  cupy/array_api/_array_object.py
  cupy/array_api/_linear_algebra_functions.py
  cupy/array_api/_statistical_functions.py
  cupy/array_api/linalg.py
Labels: cat:feature, to-be-backported, blocking, prio:high

#6186 Update conda-forge installation guide
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:medium

#6199 [backport] Add `cupy.array_api.linalg`
  cupy/array_api/__init__.py
  cupy/array_api/_array_object.py
  cupy/array_api/_linear_algebra_functions.py
  cupy/array_api/_statistical_functions.py
  cupy/array_api/linalg.py
Labels: cat:feature, backport, blocking, prio:high

#6200 [backport] Update conda-forge installation guide
  docs/source/install.rst
Labels: cat:document, backport, prio:medium

#6196 [backport] Support all advanced indexing
  cupy/_core/_routines_indexing.pyx
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:enhancement, backport, prio:medium

#6058 Update upgrade guide
  docs/source/upgrade.rst
Labels: cat:document, to-be-backported, blocking, prio:medium

#6197 Fix #4675 on resolving TODO in #4198
  cupy/_core/core.pyx
Labels: cat:bug, to-be-backported, prio:high

#6204 [backport] Fix #4675 on resolving TODO in #4198
  cupy/_core/core.pyx
Labels: cat:bug, backport, prio:high

#6085 Add cupy.asfarray
  cupy/__init__.py
  cupy/_manipulation/kind.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_kind.py
Labels: cat:feature, prio:medium

#6201 Eigenvalue solver 64bit API on CUDA 11.1
  cupy/linalg/_eigenvalue.py
Labels: cat:bug, to-be-backported, prio:high

#6126 Docs: Update linkcode implementation
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:medium

#6203 [backport] Update upgrade guide
  docs/source/upgrade.rst
Labels: cat:document, backport, blocking, prio:medium

#6206 [backport] Docs: Update linkcode implementation
  docs/source/conf.py
Labels: cat:document, backport, prio:medium

#6195 Make `matmul` support ufunc kwargs
  cupy/_core/_gufuncs.py
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:enhancement, prio:medium

#6208 Fix edge case compatibility in `cupy.eye()`
  cupy/_creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: cat:bug, to-be-backported, prio:high

#6209 Revise Overview for CuPy v10
  docs/source/overview.rst
  docs/source/reference/environment.rst
  docs/source/user_guide/performance.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#6215 [backport] Revise Overview for CuPy v10
  docs/source/overview.rst
  docs/source/reference/environment.rst
  docs/source/user_guide/performance.rst
Labels: cat:document, backport, blocking, prio:high

#6170 Support lambda function in `cupy.vectorize`
  cupy/_functional/vectorize.py
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, to-be-backported, prio:high

#6192 [backport] Support eigenvalue solver 64bit API
  cupy/linalg/_eigenvalue.py
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/hip/cupy_rocsolver.h
  cupy_backends/stub/cupy_cusolver.h
Labels: cat:enhancement, backport, blocking, prio:high

#6220 [backport] Eigenvalue solver 64bit API on CUDA 11.1
  cupy/linalg/_eigenvalue.py
Labels: cat:bug, backport, blocking, prio:high

#6217 [backport] Support lambda function in `cupy.vectorize`
  cupy/_functional/vectorize.py
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, backport, blocking, prio:high

#6227 Bump versions in Dockerfiles for CuPy v10.0.0 release
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6218 Docs: CentOS installation from source
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:medium

#6230 [backport] Docs: CentOS installation from source
  docs/source/install.rst
Labels: cat:document, backport, prio:medium

#6216 Fix overlapping `out` in `matmul` and `(tensor)dot`
  cupy/_core/_routines_linalg.pyx
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:bug, to-be-backported, prio:high

#6161 Remove legacy `cp.linalg.solve()` implementation
  cupy/linalg/_solve.py
Labels: to-be-backported, prio:medium, cat:code-fix

#6232 Fix `compile_with_cache` returning None
  cupy/cuda/compiler.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: cat:bug, to-be-backported, prio:high

#6169 Allow `flip` ()-shaped array
  cupy/_manipulation/rearrange.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
Labels: cat:bug, to-be-backported

#6210 Fix `linalg.eigh` and `linalg.eigvalsh` on empty inputs
  cupy/linalg/_eigenvalue.py
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:bug, to-be-backported, prio:high

#6213 [backport] Fix edge case compatibility in `cupy.eye()`
  cupy/_creation/basic.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: cat:bug, backport, prio:high

#6236 [backport] Fix `compile_with_cache` returning None
  cupy/cuda/compiler.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: cat:bug, backport, prio:high

#6237 [backport] Allow `flip` ()-shaped array
  cupy/_manipulation/rearrange.py
  tests/cupy_tests/manipulation_tests/test_rearrange.py
Labels: cat:bug, backport

#6239 Fix `cupy.trapz` docstring
  cupy/_math/sumprod.py
Labels: cat:document

#6238 [backport] Fix `linalg.eigh` and `linalg.eigvalsh` on empty inputs
  cupy/linalg/_eigenvalue.py
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:bug, backport, prio:high

#6194 [backport] Add tests for `convolve2d`
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, backport, prio:medium

#6149 Remove `__all__` from `cupyx/scipy/*`
  cupyx/scipy/fft/__init__.py
  cupyx/scipy/fft/_fft.py
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/special_matrices.py
  cupyx/scipy/sparse/linalg/_norm.py
Labels: st:awaiting-author, prio:medium, cat:code-fix

#6228 Change a parameter name in `percentile` and `quantile` to support NumPy 1.22
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:numpy-compat, prio:medium

#6235 [backport] Remove legacy `cp.linalg.solve()` implementation
  cupy/linalg/_solve.py
Labels: backport, prio:medium, cat:code-fix

#6162 Fix overloading ambiguity in ndimage filters
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_util.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:bug, to-be-backported, prio:high

#6222 Support comparison to `None` and `Ellipsis`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:enhancement

#6241 [backport] Remove memory copy in matmul
  cupy/_core/_gufuncs.py
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
  tests/cupy_tests/math_tests/test_matmul.py
Labels: backport

#6247 [backport] Change a parameter name in `percentile` and `quantile` to support NumPy 1.22
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:test, backport

#6260 Tentatively pin to `setuptools<60` in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, prio:high

#6225 Fix `cupy.linalg.qr` to align with NumPy 1.22
  cupy/cusolver.pyx
  cupy/linalg/_decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: to-be-backported, cat:numpy-compat, prio:medium

#6242 [backport] Fix overloading ambiguity in ndimage filters
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_util.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:bug, backport, prio:high

#6270 [backport] Tentatively pin to `setuptools<60` in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#6274 Add `cupy.positive` in API Reference
  docs/source/reference/math.rst
  docs/source/reference/ufunc.rst
Labels: cat:document, to-be-backported

#6276 [backport] Add `cupy.positive` in API Reference
  docs/source/reference/math.rst
  docs/source/reference/ufunc.rst
Labels: cat:document, backport

#6263 [backport] Fix `cupy.linalg.qr` to align with NumPy 1.22
  cupy/linalg/_decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: backport, cat:numpy-compat, prio:medium
