Repository cupy/cupy, pull requests merged in 2021-09, with the labels that each got.

#5693 Improve performance of `TestSplineFilter1dLargeArray`
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:test, to-be-backported, prio:high

#5694 [backport] Improve performance of `TestSplineFilter1dLargeArray`
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:test, backport, prio:high

#5643 [v9] Update `test_eigenvalue.py`
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:test, backport, prio:medium

#5599 Stop inheriting `unittest.TestCase` for performance
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/cuda_tests/test_texture.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/statistics_tests/test_histogram.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
  tests/cupy_tests/test_cublas.py
  tests/cupy_tests/test_cudnn.py
  tests/cupy_tests/test_cusolver.py
  tests/cupy_tests/test_cusparse.py
  tests/cupy_tests/test_cutensor.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, to-be-backported, prio:medium

#5708 [backport] Fix random docstring
  cupy/random/_generator_api.pyx
Labels: cat:document, backport, prio:high

#5710 [backport] Stop inheriting `unittest.TestCase` for performance
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/cuda_tests/test_texture.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/statistics_tests/test_histogram.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
  tests/cupy_tests/test_cublas.py
  tests/cupy_tests/test_cudnn.py
  tests/cupy_tests/test_cusolver.py
  tests/cupy_tests/test_cusparse.py
  tests/cupy_tests/test_cutensor.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, backport, prio:medium

#5724 `TestSplineFilter1dLargeArray` marked slow and reduced memory usage
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:test, to-be-backported, prio:medium

#5594 Make testing helpers support non-methods
  cupy/testing/_helper.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:test, to-be-backported, prio:medium

#5731 [backport] Make testing helpers support non-methods
  cupy/testing/_helper.py
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:test, backport, prio:medium

#5729 [backport] `TestSplineFilter1dLargeArray` marked slow and reduced memory usage
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:test, backport, prio:medium

#5727 Make test parameter names static
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:test, to-be-backported, prio:medium

#5733 [backport] Make test parameter names static
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:test, backport, prio:medium

#5735 Update pip and setuptools in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported

#5718 Fix exception for indexing with multiple ellipses
  cupy/_core/internal.pyx
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
Labels: cat:bug, to-be-backported, prio:high

#5738 [backport] Update pip and setuptools in Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:medium

#5730 Reorganize build scripts, part 1
  MANIFEST.in
  install/__init__.py
  install/cupy_builder/__init__.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  install/cupy_builder/install_utils.py
  setup.py
  tests/install_tests/__init__.py
  tests/install_tests/test_build.py
  tests/install_tests/test_utils.py
Labels: cat:install, prio:medium

#5739 [backport] Fix exception for indexing with multiple ellipses
  cupy/_core/internal.pyx
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
Labels: cat:bug, backport, prio:high

#5741 Fix backport trigger
  .github/workflows/backport.yml
Labels: cat:other, prio:medium

#5728 Fix docstring for fallback modules
  cupyx/fallback_mode/fallback.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:bug, to-be-backported, prio:medium

#5742 [backport] Fix docstring for fallback modules
  cupyx/fallback_mode/fallback.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Labels: cat:bug, backport, prio:medium

#5726 Support cuDNN 8.2.4
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:medium

#5744 [backport] Support cuDNN 8.2.4
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:medium

#5734 Support NCCL 2.11.4
  .pfnci/linux/tests/cuda114.Dockerfile
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#5747 [backport] Support NCCL 2.11.4
  .pfnci/linux/tests/cuda114.Dockerfile
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#5706 Improve stream mismatch error message
  cupy/cuda/stream.pyx
Labels: cat:enhancement, prio:medium

#5743 Reorganize build scripts, part 2: separate modules
  install/cupy_builder/__init__.py
  install/cupy_builder/_context.py
  install/cupy_builder/_modules.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  setup.py
  tests/install_tests/__init__.py
  tests/install_tests/test_cupy_builder/test_context.py
Labels: cat:install, prio:medium

#5746 Add workflow to test/build/push docker images on pull-request/release
  .github/workflows/docker.yml
Labels: cat:other, prio:medium

#5745 Reorganize build scripts, part 3: simplify `setup.py`
  install/cupy_builder/__init__.py
  install/cupy_builder/_preflight.py
  setup.py
Labels: cat:install, prio:medium

#5752 [backport] Add workflow to test/build/push docker images on pull-request/release
  .github/workflows/docker.yml
Labels: cat:other, backport, prio:medium

#5754 Reorganize build scripts, part 4: remove global `cupy_setup_options`
  install/cupy_builder/_context.py
  install/cupy_builder/cupy_setup_build.py
  setup.py
  tests/install_tests/__init__.py
  tests/install_tests/test_cupy_builder/__init__.py
  tests/install_tests/test_cupy_builder/test_context.py
Labels: cat:install, prio:medium

#5756 Add maintainers in `setup.py`
  setup.py
Labels: cat:install, to-be-backported, prio:medium

#5429 Add binomial distribution to new Generator
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:medium

#5755 Reorganize build scripts, part 5: remove Cython version check
  install/cupy_builder/cupy_setup_build.py
Labels: cat:install, prio:medium

#5758 [backport] Add maintainers in `setup.py`
  setup.py
Labels: cat:install, backport, prio:medium

#5757 Fix `cupyx.optimize` to save file when no optimization ran
  cupyx/optimizing/_optimize.py
  tests/cupyx_tests/test_optimize.py
Labels: cat:enhancement, to-be-backported

#5760 [backport] Fix `cupyx.optimize` to save file when no optimization ran
  cupyx/optimizing/_optimize.py
  tests/cupyx_tests/test_optimize.py
Labels: cat:enhancement, backport

#5769 Include `stdexcept` in hip headers
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/hip/cupy_hipsparse.h
  cupy_backends/hip/cupy_rocsolver.h
Labels: cat:bug, to-be-backported, prio:high

#5765 Adding 'bitorder' support to `cupy.unpackbits`
  cupy/_binary/packing.py
  tests/cupy_tests/binary_tests/test_packing.py
Labels: cat:enhancement, prio:medium

#5777 [backport] Include `stdexcept` in hip headers
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/hip/cupy_rocsolver.h
Labels: cat:bug, backport, prio:high

#5698 Adopt the `numpy.array_api` module as `cupy.array_api`
  .github/workflows/pretest.yml
  cupy/array_api/__init__.py
  cupy/array_api/_array_object.py
  cupy/array_api/_constants.py
  cupy/array_api/_creation_functions.py
  cupy/array_api/_data_type_functions.py
  cupy/array_api/_dtypes.py
  cupy/array_api/_elementwise_functions.py
  cupy/array_api/_linear_algebra_functions.py
  cupy/array_api/_manipulation_functions.py
  cupy/array_api/_searching_functions.py
  cupy/array_api/_set_functions.py
  cupy/array_api/_sorting_functions.py
  cupy/array_api/_statistical_functions.py
  cupy/array_api/_typing.py
  cupy/array_api/_utility_functions.py
  docs/source/_comparison_generator.py
  docs/source/conf.py
  docs/source/reference/array_api.rst
  docs/source/reference/array_api_array.rst
  docs/source/reference/array_api_functions.rst
  docs/source/reference/cuda.rst
  docs/source/reference/index.rst
  setup.cfg
  tests/cupy_tests/array_api_tests/__init__.py
  tests/cupy_tests/array_api_tests/test_array_object.py
  tests/cupy_tests/array_api_tests/test_creation_functions.py
  tests/cupy_tests/array_api_tests/test_elementwise_functions.py
Labels: cat:feature, prio:medium, array-api

#5773 Remove `--pre` from ROCm source build instructions
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:medium

#5767 Fixed typo in error message in sparse.csr_matrix
  cupyx/scipy/sparse/csr.py
Labels: cat:bug, to-be-backported, prio:high

#5788 [backport] Fixed typo in error message in sparse.csr_matrix
  cupyx/scipy/sparse/csr.py
Labels: cat:bug, backport, prio:high

#5725 Update auto-notify bot for array-api label
  .github/workflows/auto-cc.yml
Labels: cat:other, prio:medium

#5772 Use custom index for pre-release wheels
  README.md
  docs/source/install.rst
Labels: cat:document, no-compat, to-be-backported, blocking, prio:high

#5793 [backport] Use custom index for pre-release wheels
  README.md
  docs/source/install.rst
Labels: cat:document, no-compat, backport, blocking, prio:high

#5786 Improve FlexCI output
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:medium

#5749 Fix `MAX_NDIM` and add guards/tests
  cupy/_core/_carray.pxd
  cupy/_core/_carray.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:bug, to-be-backported, prio:high

#5659 Eliminate random test ids
  .pfnci/config.pbtxt
  .pfnci/linux/tests/_build_and_test.sh
  cupy/testing/_parameterized.py
  cupy/testing/_pytest_impl.py
  tests/conftest.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupy_tests/linalg_tests/test_einsum.py
  tests/cupy_tests/logic_tests/test_type_test.py
  tests/cupy_tests/sorting_tests/test_search.py
  tests/cupy_tests/testing_tests/test_parameterized.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:test, prio:medium

#5791 Skip tests for bug cases (FFT on CUDA 10.2 + Pascal)
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: to-be-backported, blocking, prio:high

#5796 [backport] Improve FlexCI output
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:medium

#5782 [backport] Remove `--pre` from ROCm source build instructions
  docs/source/install.rst
Labels: cat:document, backport, prio:medium

#5798 [backport] Fix `MAX_NDIM` and add guards/tests
  cupy/_core/_carray.pxd
  cupy/_core/_carray.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:bug, backport, prio:high

#5771 Drop support for Python 3.6
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, no-compat, blocking, prio:high

#5770 Drop support for CUDA 10.1 or earlier
  .pfnci/config.pbtxt
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-10.0/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-10.0/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-10.1/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-9.2/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-9.2/cuda_fp16.hpp
  cupy/cuda/compiler.py
  cupyx/tools/install_library.py
  docs/source/install.rst
  install/cupy_builder/install_build.py
Labels: cat:enhancement, no-compat, blocking, prio:high

#5802 Disable spmm on Windows CUDA 10.2
  cupy/cusparse.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#5805 [backport] Disable spmm on Windows CUDA 10.2
  cupy/cusparse.py
Labels: cat:bug, backport, blocking, prio:high

#5799 Fix error message comparison
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:test, to-be-backported, blocking, prio:high

#5801 Fix test skip issue
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:test, blocking, prio:high

#5806 [backport] Fix error message comparison
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:test, backport, blocking, prio:high

#5817 Bump cupy version in Dockerfile to v9.5.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#5816 Bump cupy version in Dockerfile to v10.0.0b3
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#5819 Bump ROCm Dockerfile Python to 3.7
  docker/rocm/Dockerfile
Labels: cat:install
