Repository cupy/cupy, pull requests merged in 2021-04, with the labels that each got.

#5002 Use THRUST_OPTIONAL_CPP11_CONSTEXPR
  cupy/cuda/cupy_thrust.cu
Labels: cat:bug, prio:high, to-be-backported

#5011 [backport] Use THRUST_OPTIONAL_CPP11_CONSTEXPR
  cupy/cuda/cupy_thrust.cu
Labels: backport, cat:bug, prio:high

#4930 Move the NVTX module to `cupy_backends.cuda.libs`
  cupy/cuda/__init__.py
  cupy/cuda/nvtx.py
  cupy_backends/cuda/libs/nvtx.pyx
  cupy_backends/cupy_tx.h
  cupy_backends/stub/cupy_nvtx.h
  cupy_setup_build.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5015 Document `cupyx.time.repeat`
  cupyx/time.py
  docs/source/reference/prof.rst
Labels: cat:document, prio:high, to-be-backported

#5016 Document `cupy.cuda.runtime.getDeviceProperties`
  docs/source/reference/cuda.rst
Labels: cat:document, prio:medium, to-be-backported

#5020 Doc: Add links to Anaconda, Gitter, StackOverflow
  README.md
  docs/source/contribution.rst
Labels: cat:document, prio:medium, to-be-backported

#5014 [backport] Move the NVTX module to `cupy_backends.cuda.libs`
  cupy/cuda/__init__.py
  cupy/cuda/nvtx.py
  cupy_backends/cuda/libs/nvtx.pyx
  cupy_backends/cupy_tx.h
  cupy_backends/stub/cupy_nvtx.h
  cupy_setup_build.py
Labels: backport, cat:enhancement, prio:medium

#5029 [backport] Document `cupy.cuda.runtime.getDeviceProperties`
  docs/source/reference/cuda.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5030 [backport] Doc: Add links to Anaconda, Gitter, StackOverflow
  README.md
  docs/source/contribution.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#4592 CUDA 11.2: Add `MemoryAsyncPool` to support `malloc_async`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_common.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  docs/source/reference/memory.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:feature, prio:medium, st:test-and-merge, to-be-backported

#5007 HIP: add `-ftz=true`
  cupy/cuda/compiler.py
Labels: cat:hip, prio:high, st:test-and-merge, to-be-backported

#4927 Add poisson distribution to random API
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  cupy_setup_build.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:feature, prio:medium, st:test-and-merge, to-be-backported

#5017 CuPy JIT: Print kernel code
  cupyx/jit/_interface.py
Labels: cat:feature, prio:high, st:test-and-merge, to-be-backported

#5019 More documentation on the supported backends
  docs/source/overview.rst
  docs/source/reference/difference.rst
  docs/source/reference/routines.rst
Labels: cat:document, prio:medium, to-be-backported

#4996 Add hfft2, ihfft2, hfftn, and ihfftn to cupyx.scipy.fft
  cupyx/scipy/fft/_fft.py
  docs/source/reference/scipy_fft.rst
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: cat:feature, prio:medium

#4991 CuPy JIT: Readable compile error messages
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4968 Add cupyx.scipy.sparse.kronsum()
  cupyx/scipy/sparse/__init__.py
  cupyx/scipy/sparse/construct.py
  docs/source/reference/sparse.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
Labels: cat:feature, prio:medium

#5040 Add debug print for flaky test
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:test

#5033 Fix code block in installation guide
  docs/source/install.rst
Labels: cat:document, prio:medium, to-be-backported

#5005 Mark `cupyx.jit.rawkernel` as experimental
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#5038 [backport] CuPy JIT: Print kernel code
  cupyx/jit/_interface.py
Labels: backport, cat:feature, prio:high, st:test-and-merge

#5036 [backport] Add poisson distribution to random API
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  cupy_setup_build.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: backport, cat:feature, prio:medium

#5041 [backport] CuPy JIT: Readable compile error messages
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: backport, cat:enhancement, prio:high

#5039 [backport] More documentation on the supported backends
  docs/source/overview.rst
  docs/source/reference/difference.rst
  docs/source/reference/routines.rst
Labels: backport, cat:document, prio:medium

#5035 [backport] HIP: add `-ftz=true`
  cupy/cuda/compiler.py
Labels: backport, cat:hip, prio:high, st:test-and-merge

#5034 [backport] CUDA 11.2: Add `MemoryAsyncPool` to support `malloc_async`
  cupy/cuda/__init__.py
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_common.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  docs/source/reference/memory.rst
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:feature, prio:medium

#5042 Fix `TestStream` cleanup
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5028 CuPy JIT: Use C++-like typing rule in 'cuda' mode
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupyx/jit/_compile.py
  cupyx/jit/_typerules.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#5051 Use bot mode in automatic backport
  .github/workflows/backport.yml
Labels: cat:other, prio:high, to-be-backported

#5058 [backport] Use bot mode in automatic backport
  .github/workflows/backport.yml
Labels: backport, cat:other, prio:high

#5053 [backport] CuPy JIT: Use C++-like typing rule in 'cuda' mode
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupyx/jit/_compile.py
  cupyx/jit/_typerules.py
Labels: backport, cat:enhancement, prio:high

#5025 Document `CFunctionAllocator` and `ManagedMemory`
  cupy/cuda/__init__.py
  docs/source/reference/cuda.rst
Labels: cat:document, prio:medium, to-be-backported

#5052 [backport] Fix `TestStream` cleanup
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: backport, cat:test, prio:high, st:test-and-merge

#5037 Add PCI Bus ID to show_config
  cupyx/_runtime.py
Labels: cat:enhancement, prio:medium, to-be-backported

#5043 [backport] Fix code block in installation guide
  docs/source/install.rst
Labels: backport, cat:document, prio:medium

#5054 Print cuSPARSELt version in `show_config`
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/stub/cupy_cusparselt.h
  cupyx/_runtime.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5057 [backport] Mark `cupyx.jit.rawkernel` as experimental
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#5061 Mark some memory tests as `testing.slow`
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:test, prio:high, st:test-and-merge, to-be-backported

#5062 [backport] Add PCI Bus ID to show_config
  cupyx/_runtime.py
Labels: backport, cat:enhancement, prio:medium, to-be-backported

#5059 [backport] Document `CFunctionAllocator` and `ManagedMemory`
  cupy/cuda/__init__.py
  docs/source/reference/cuda.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5023 Improve the documentation on interoperability
  docs/source/reference/interoperability.rst
Labels: cat:document, prio:medium, to-be-backported

#4994 [backport] Support cuSPARSELt
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cupy_cusparselt.h
  cupy_backends/stub/cupy_cusparselt.h
  cupy_setup_build.py
  examples/cusparselt/matmul.py
  install/build.py
Labels: backport, blocking, cat:feature, prio:high

#5027 [backport] Document `cupyx.time.repeat`
  cupyx/time.py
  docs/source/reference/prof.rst
Labels: backport, cat:document, prio:high

#5063 [backport] Mark some memory tests as `testing.slow`
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:test, prio:high, st:test-and-merge

#5046 Disable cuFFT plan cache on CUDA 11.1
  cupy/fft/_cache.pyx
Labels: cat:bug, prio:high, to-be-backported

#5064 [backport] Improve the documentation on interoperability
  docs/source/reference/interoperability.rst
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5065 [backport] Print cuSPARSELt version in `show_config`
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/stub/cupy_cusparselt.h
  cupyx/_runtime.py
Labels: backport, cat:enhancement, prio:medium, st:test-and-merge

#5068 [backport] Disable cuFFT plan cache on CUDA 11.1
  cupy/fft/_cache.pyx
Labels: backport, cat:bug, prio:high

#5066 [backport] Fix cuSPARSELt example not to use internal function
  examples/cusparselt/matmul.py
Labels: backport, cat:example, prio:high, st:test-and-merge

#5012 CuPy JIT documentation
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
  docs/source/reference/kernel.rst
  docs/source/tutorial/kernel.rst
  examples/jit/elmentwise_op.py
  examples/jit/reduction_simple.py
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#5076 [backport] CuPy JIT documentation
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
  docs/source/reference/kernel.rst
  docs/source/tutorial/kernel.rst
  examples/jit/elmentwise_op.py
  examples/jit/reduction_simple.py
Labels: backport, cat:document, prio:high

#5004 Use async memcpy in `ndarray.copy`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#5060 Improve comments for memory and stream API usage
  cupy/cuda/memory.pyx
  cupy_backends/cuda/stream.pyx
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5077 CuPy JIT: Fix range type
  cupyx/jit/_compile.py
  examples/jit/reduction_simple.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5078 [backport] Use async memcpy in `ndarray.copy`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: backport, blocking, cat:bug, prio:high

#5072 Support PTDS in CuPy memory pool
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5079 [backport] Improve comments for memory and stream API usage
  cupy/cuda/memory.pyx
  cupy_backends/cuda/stream.pyx
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5081 [backport] CuPy JIT: Fix range type
  cupyx/jit/_compile.py
  examples/jit/reduction_simple.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5082 [backport] Support PTDS in CuPy memory pool
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: backport, cat:bug, prio:high, st:test-and-merge

#4829 Ability to pass structured data types by value as kernel parameters
  cupy/cuda/function.pyx
  docs/source/tutorial/kernel.rst
  examples/custom_struct/README.md
  examples/custom_struct/builtin_vectors.py
  examples/custom_struct/complex_struct.py
  examples/custom_struct/packed_matrix.py
  tests/cupy_tests/core_tests/test_function.py
  tests/example_tests/test_custom_struct.py
Labels: cat:enhancement, prio:medium, st:test-and-merge

#5013 Give gufunc a name
  cupy/_core/_gufuncs.py
Labels: cat:enhancement, prio:high, st:test-and-merge, to-be-backported

#4905 Add gamma distributions to random API
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: blocking, cat:feature, prio:medium, st:test-and-merge, to-be-backported

#5071 Support custom getsource option in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
Labels: cat:enhancement, prio:medium, st:test-and-merge, to-be-backported

#5086 [backport] Add gamma distributions to random API
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
  tests/cupy_tests/random_tests/test_distributions.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: backport, blocking, cat:feature, prio:medium, st:test-and-merge

#5085 [backport] Give gufunc a name
  cupy/_core/_gufuncs.py
Labels: backport, cat:enhancement, prio:high, st:test-and-merge

#5045 Fix DLPack lanes
  cupy/_core/dlpack.pyx
  cupy/_core/include/cupy/dlpack/README.md
  cupy/_core/include/cupy/dlpack/dlpack.h
Labels: cat:bug, prio:high, st:test-and-merge, to-be-backported

#5084 Fix some internal `cpdef` functions to `cdef` in `_kernel.pyx`
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/lib/_routines_poly.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#4870 Add APIs for creating NumPy arrays backed by pinned memory
  cupy/_core/core.pyx
  cupy/_core/internal.pxd
  cupy/_core/internal.pyx
  cupy/_creation/basic.py
  cupyx/__init__.py
  cupyx/_pinned_array.py
  docs/source/reference/ext.rst
  docs/source/reference/memory.rst
  tests/cupyx_tests/test_pinned_array.py
Labels: cat:feature, prio:medium, st:test-and-merge, to-be-backported

#4998 Fix JIT test failures on ROCm
  cupy/_core/core.pyx
  cupy/_core/include/cupy/carray.cuh
  cupy/_core/include/cupy/swap.cuh
  cupy/_core/include/cupy/tuple.cuh
  cupy/_functional/vectorize.py
  cupyx/jit/_interface.py
Labels: cat:enhancement, hip, st:test-and-merge, to-be-backported

#5048 Revert "Add debug print for flaky test"
  tests/cupy_tests/manipulation_tests/test_basic.py
Labels: cat:test, prio:medium, st:test-and-merge

#5098 [backport] Fix some internal `cpdef` functions to `cdef` in `_kernel.pyx`
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/lib/_routines_poly.py
Labels: backport, cat:code-fix, prio:medium, st:test-and-merge

#5100 [backport] Add APIs for creating NumPy arrays backed by pinned memory
  cupy/_core/core.pyx
  cupy/_core/internal.pxd
  cupy/_core/internal.pyx
  cupy/_creation/basic.py
  cupyx/__init__.py
  cupyx/_pinned_array.py
  docs/source/reference/ext.rst
  docs/source/reference/memory.rst
  tests/cupyx_tests/test_pinned_array.py
Labels: backport, cat:feature, prio:medium, st:test-and-merge

#4974 Fix Windows dll loading for Conda
  cupy/_environment.py
Labels: cat:install, prio:high, to-be-backported

#5102 [backport] Refactor random tests
  tests/cupy_tests/random_tests/common_distributions.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: backport, cat:test, prio:medium, st:test-and-merge

#5093 Add user guide
  docs/source/contribution.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/overview.rst
  docs/source/reference/cuda.rst
  docs/source/reference/environment.rst
  docs/source/reference/ext.rst
  docs/source/reference/index.rst
  docs/source/tutorial/index.rst
  docs/source/user_guide/basic.rst
  docs/source/user_guide/compatibility.rst
  docs/source/user_guide/cuda_api.rst
  docs/source/user_guide/difference.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/interoperability.rst
  docs/source/user_guide/kernel.rst
  docs/source/user_guide/memory.rst
  docs/source/user_guide/performance.rst
Labels: blocking, cat:document, prio:high, st:test-and-merge, to-be-backported

#5106 [backport] Fix Windows dll loading for Conda
  cupy/_environment.py
Labels: backport, cat:install, prio:high, st:test-and-merge

#4940 Add SciPy compatible connected_components
  cupy_backends/cuda/libs/cugraph.pyx
  cupy_backends/cupy_cugraph.h
  cupy_backends/stub/cupy_cugraph.h
  cupy_setup_build.py
  cupyx/scipy/sparse/csgraph/__init__.py
  cupyx/scipy/sparse/csgraph/_traversal.py
  install/build.py
  tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py
Labels: blocking, cat:feature, prio:medium, st:test-and-merge, to-be-backported

#5108 Reorganize API reference pages
  docs/source/install.rst
  docs/source/reference/ext.rst
  docs/source/reference/generic.rst
  docs/source/reference/index.rst
  docs/source/reference/kernel.rst
  docs/source/reference/memoize.rst
  docs/source/reference/optimize.rst
  docs/source/reference/routines.rst
Labels: blocking, cat:document, st:test-and-merge, to-be-backported

#5109 [backport] Add user guide
  docs/source/contribution.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/overview.rst
  docs/source/reference/cuda.rst
  docs/source/reference/environment.rst
  docs/source/reference/ext.rst
  docs/source/reference/index.rst
  docs/source/tutorial/index.rst
  docs/source/user_guide/basic.rst
  docs/source/user_guide/compatibility.rst
  docs/source/user_guide/cuda_api.rst
  docs/source/user_guide/difference.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/interoperability.rst
  docs/source/user_guide/kernel.rst
  docs/source/user_guide/memory.rst
  docs/source/user_guide/performance.rst
Labels: backport, blocking, cat:document, prio:high

#5088 Point to the correct numpy random docs
  cupy/random/_generator_api.pyx
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#5103 Adjust PATH when preloading to load cuDNN v8 correctly on Windows
  cupy/_environment.py
Labels: blocking, cat:bug, prio:high, st:test-and-merge, to-be-backported

#5114 [backport] Reorganize API reference pages
  docs/source/install.rst
  docs/source/reference/ext.rst
  docs/source/reference/generic.rst
  docs/source/reference/index.rst
  docs/source/reference/kernel.rst
  docs/source/reference/memoize.rst
  docs/source/reference/optimize.rst
  docs/source/reference/routines.rst
Labels: backport, blocking, cat:document, st:test-and-merge

#5113 [backport] Add SciPy compatible connected_components
  cupy_backends/cuda/libs/cugraph.pyx
  cupy_backends/cupy_cugraph.h
  cupy_backends/stub/cupy_cugraph.h
  cupy_setup_build.py
  cupyx/scipy/sparse/csgraph/__init__.py
  cupyx/scipy/sparse/csgraph/_traversal.py
  install/build.py
  tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py
Labels: backport, blocking, cat:feature, prio:medium

#5116 [backport] Adjust PATH when preloading to load cuDNN v8 correctly on Windows
  cupy/_environment.py
Labels: backport, blocking, cat:bug, prio:high, st:test-and-merge

#5115 [backport] Point to the correct numpy random docs
  cupy/random/_generator_api.pyx
Labels: backport, cat:document, prio:high

#4945 Follow the latest NumPy/SciPy docs style
  cupy/_functional/vectorize.py
  docs/requirements.txt
  docs/source/conf.py
  docs/source/reference/binary.rst
  docs/source/reference/creation.rst
  docs/source/reference/cuda.rst
  docs/source/reference/dtype.rst
  docs/source/reference/ext.rst
  docs/source/reference/fft.rst
  docs/source/reference/fftpack.rst
  docs/source/reference/functional.rst
  docs/source/reference/index.rst
  docs/source/reference/indexing.rst
  docs/source/reference/io.rst
  docs/source/reference/kernel.rst
  docs/source/reference/linalg.rst
  docs/source/reference/logic.rst
  docs/source/reference/manipulation.rst
  docs/source/reference/math.rst
  docs/source/reference/misc.rst
  docs/source/reference/ndarray.rst
  docs/source/reference/ndimage.rst
  docs/source/reference/pad.rst
  docs/source/reference/polynomials.rst
  docs/source/reference/prof.rst
  docs/source/reference/random.rst
  docs/source/reference/routines.rst
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_fft.rst
  docs/source/reference/scipy_linalg.rst
  docs/source/reference/set.rst
  docs/source/reference/signal.rst
  docs/source/reference/sorting.rst
  docs/source/reference/sparse.rst
  docs/source/reference/special.rst
  docs/source/reference/statistics.rst
  docs/source/reference/stats.rst
  docs/source/reference/testing.rst
  docs/source/reference/ufunc.rst
  docs/source/reference/window.rst
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#5107 Add ROCm limitations to docs
  docs/source/install.rst
Labels: blocking, cat:document, prio:high, to-be-backported

#5009 [backport] Update examples for current version of CuPy
  examples/stream/cudnn.py
  examples/stream/curand.py
  examples/stream/map_reduce.py
Labels: backport, blocking, cat:example, prio:high, st:test-and-merge

#5118 [backport] Follow the latest NumPy/SciPy docs style
  cupy/_functional/vectorize.py
  docs/requirements.txt
  docs/source/conf.py
  docs/source/reference/binary.rst
  docs/source/reference/creation.rst
  docs/source/reference/cuda.rst
  docs/source/reference/dtype.rst
  docs/source/reference/ext.rst
  docs/source/reference/fft.rst
  docs/source/reference/fftpack.rst
  docs/source/reference/functional.rst
  docs/source/reference/index.rst
  docs/source/reference/indexing.rst
  docs/source/reference/io.rst
  docs/source/reference/kernel.rst
  docs/source/reference/linalg.rst
  docs/source/reference/logic.rst
  docs/source/reference/manipulation.rst
  docs/source/reference/math.rst
  docs/source/reference/misc.rst
  docs/source/reference/ndarray.rst
  docs/source/reference/ndimage.rst
  docs/source/reference/pad.rst
  docs/source/reference/polynomials.rst
  docs/source/reference/prof.rst
  docs/source/reference/random.rst
  docs/source/reference/routines.rst
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_fft.rst
  docs/source/reference/scipy_linalg.rst
  docs/source/reference/set.rst
  docs/source/reference/signal.rst
  docs/source/reference/sorting.rst
  docs/source/reference/sparse.rst
  docs/source/reference/special.rst
  docs/source/reference/statistics.rst
  docs/source/reference/stats.rst
  docs/source/reference/testing.rst
  docs/source/reference/ufunc.rst
  docs/source/reference/window.rst
Labels: backport, blocking, cat:document, prio:high

#5119 [backport] Add ROCm limitations to docs
  docs/source/install.rst
Labels: backport, blocking, cat:document, prio:high

#5123 [backport] Revise ROCm doc
  docs/source/install.rst
Labels: backport, cat:document

#5125 Bugfix for typing rule of CuPy JIT
  cupyx/jit/_typerules.py
Labels: blocking, cat:bug, prio:high, to-be-backported

#5128 [backport] Bugfix for typing rule of CuPy JIT
  cupyx/jit/_typerules.py
Labels: backport, blocking, cat:bug, prio:high

#5126 [v9] Bump version to 9.0.0
  cupy/_version.py
Labels: blocking, cat:install

#5089 [backport] Support custom getsource option in CuPy JIT
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
Labels: backport, cat:enhancement, prio:medium

#5131 Mention baseline API change in upgrade guide
  docs/source/upgrade.rst
Labels: cat:document, prio:high, st:test-and-merge, to-be-backported

#5132 [backport] Mention baseline API change in upgrade guide
  docs/source/upgrade.rst
Labels: backport, cat:document, prio:high

#5121 Remove `cupy.cupy`
  cupy/__init__.py
  cupy/_core/__init__.py
  cupy/_core/_codeblock.py
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_fusion_op.py
  cupyx/jit/_compile.py
Labels: cat:code-fix, prio:medium, to-be-backported

#5137 [backport] Remove `cupy.cupy`
  cupy/__init__.py
  cupy/_core/__init__.py
  cupy/_core/_codeblock.py
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_fusion_op.py
  cupyx/jit/_compile.py
Labels: backport, cat:code-fix, prio:medium

#5139 Update coo.py
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5083 Make cupy.cuda.Device context manager interface thread safe
  cupy/cuda/device.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: cat:enhancement, no-compat, prio:medium

#5099 Adjust testing tolerance for `hfftn` for HIP/ROCm
  tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Labels: hip, prio:medium, st:test-and-merge, to-be-backported

#5101 [backport] Fix JIT test failures on ROCm
  cupy/_core/core.pyx
  cupy/_core/include/cupy/carray.cuh
  cupy/_core/include/cupy/swap.cuh
  cupy/_core/include/cupy/tuple.cuh
  cupy/_functional/vectorize.py
  cupyx/jit/_interface.py
Labels: backport, cat:enhancement, hip, st:test-and-merge

#5144 Fix docs in `stream.pyx`
  cupy/cuda/stream.pyx
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5127 Use current device in tests
  tests/cupy_tests/cuda_tests/test_device.py
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/fft_tests/test_cache.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:test, prio:high, to-be-backported

#5141 [backport] Fix docstring in `coo.py`
  cupyx/scipy/sparse/coo.py
  cupyx/scipy/sparse/csc.py
  cupyx/scipy/sparse/csr.py
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5129 Fix docs of scatter_add
  cupyx/_scatter.py
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5133 Fix ROCm wheel install steps
  docs/source/install.rst
Labels: cat:document, prio:medium, st:test-and-merge, to-be-backported

#5153 [backport] Fix docs of scatter_add
  cupyx/_scatter.py
Labels: backport, cat:document, prio:medium, st:test-and-merge

#5151 [backport] Use current device in tests
  tests/cupy_tests/cuda_tests/test_device.py
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_memory.py
  tests/cupy_tests/fft_tests/test_cache.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: backport, cat:test, prio:high, st:test-and-merge

#5150 [backport] Fix docs in `stream.pyx`
  cupy/cuda/stream.pyx
Labels: backport, cat:document, prio:medium

#5154 [backport] Fix ROCm wheel install steps
  docs/source/install.rst
Labels: backport, cat:document, prio:medium

#5094 [backport] Fix DLPack lanes
  cupy/_core/dlpack.pyx
  cupy/_core/include/cupy/dlpack/README.md
  cupy/_core/include/cupy/dlpack/dlpack.h
Labels: backport, cat:bug, prio:high, st:test-and-merge

#5091 Fix stream usage on D2D copy test under HIP
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:test, hip, prio:high, st:test-and-merge, to-be-backported

#5149 Cosmetic change in cuSPARSELt stub header
  cupy_backends/stub/cupy_cusparselt.h
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#5157 [backport] Fix stream usage on D2D copy test under HIP
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: backport, cat:test, hip, prio:high, st:test-and-merge

#5140 Fix TypeError in `svds`
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:bug, prio:medium, st:test-and-merge, to-be-backported

#5152 Cosmetic changes of CuPy JIT implementation
  cupy/_functional/vectorize.py
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_interface.py
  cupyx/jit/_internal_types.py
Labels: cat:code-fix, prio:medium, st:test-and-merge, to-be-backported

#5147 [backport] Make cupy.cuda.Device context manager interface thread safe
  cupy/cuda/device.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: backport, cat:enhancement, no-compat, prio:medium, st:test-and-merge

#5159 Mention PTDS in ROCm Limitation
  docs/source/install.rst
Labels: cat:document, st:test-and-merge, to-be-backported

#5166 [backport] Mention PTDS in ROCm Limitation
  docs/source/install.rst
Labels: backport, cat:document

#5164 Fix for updated FlexCI base image
  .pfnci/script.sh
Labels: cat:test, prio:high, to-be-backported

#5167 [backport] Fix for updated FlexCI base image
  .pfnci/script.sh
Labels: backport, cat:test, prio:high
