Repository cupy/cupy, pull requests merged in 2022-08, with the labels that each got.

#6890 [special] add `cupyx.scipy.special.softmax`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_softmax.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_softmax.py
Labels: cat:feature, prio:medium

#6892 Add dtype, fweights, aweights to cupy.cov
  cupy/_statistics/correlation.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: cat:feature, takeover, prio:medium

#6939 Make matrix in CG example positive definite
  examples/cg/cg.py
Labels: cat:example, prio:medium

#6869 [complex] add complex support for `nanvar` and `nanstd`
  cupy/_core/_routines_statistics.pyx
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: cat:enhancement, prio:medium

#6910 CI: Show all errors when doc build fail
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported, prio:medium

#6945 [backport] CI: Show all errors when doc build fail
  .github/workflows/pretest.yml
Labels: cat:test, backport, prio:medium

#6879 Remove proxy functions for softlink
  cupy_backends/cuda/_softlink.pxd
  cupy_backends/cuda/_softlink.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: to-be-backported, prio:medium, cat:code-fix

#6876 Add CC 8.7 for Jetson Orin
  cupy/cuda/compiler.py
Labels: cat:enhancement, to-be-backported, prio:high

#6872 Accept `kind` in `sort`/`argsort` and fix `cupy.array_api.{sort,argsort}` accordingly
  cupy/_sorting/sort.py
  cupy/array_api/_sorting_functions.py
  tests/cupy_tests/array_api_tests/test_sorting_functions.py
Labels: cat:enhancement, to-be-backported, prio:medium, array-api

#6883 Expand breaking change & best practice on device management
  docs/source/upgrade.rst
  docs/source/user_guide/interoperability.rst
Labels: cat:document, to-be-backported, prio:medium

#6946 [backport] Remove proxy functions for softlink
  cupy_backends/cuda/_softlink.pxd
  cupy_backends/cuda/_softlink.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: backport, prio:medium, cat:code-fix

#6920 Fix `cupy.clip` to match numpy
  cupy/_core/_routines_math.pyx
  cupy/_math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:bug, no-compat, prio:high

#6952 [backport] Expand breaking change & best practice on device management
  docs/source/upgrade.rst
  docs/source/user_guide/interoperability.rst
Labels: cat:document, backport, prio:medium

#6950 [backport] Add CC 8.7 for Jetson Orin
  cupy/cuda/compiler.py
Labels: cat:enhancement, backport, prio:high

#6894 Fix `XFAIL` for `tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py` when `scipy>=1.9.0rc2`
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:test, to-be-backported, prio:high

#6844 Fix augassign target is evaluated twice in JIT
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_device_function.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6954 Suppress nvcc warning
  cupy/_core/include/cupy/complex/complex.h
Labels: prio:medium, cat:code-fix

#6964 [backport] Fix augassign target is evaluated twice in JIT
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_device_function.py
Labels: cat:enhancement, backport, prio:medium

#6929 [backport] Update `cupy.array_api`
  cupy/array_api/_array_object.py
  cupy/array_api/_data_type_functions.py
  cupy/array_api/_sorting_functions.py
  cupy/array_api/linalg.py
  tests/cupy_tests/array_api_tests/test_array_object.py
Labels: cat:enhancement, backport, prio:medium, array-api

#6899 [backport] Document matmul supports out
  cupy/_core/_routines_linalg.pyx
  cupy/linalg/_product.py
Labels: cat:document, backport

#6932 Update `cupy.array_api` (cont'd)
  cupy/array_api/_set_functions.py
  cupy/array_api/linalg.py
Labels: cat:enhancement, prio:medium

#6955 Fix docs build failure
  docs/source/conf.py
Labels: cat:document, to-be-backported, blocking, prio:high

#6859 JIT: Add type annotation in _compile.py
  cupy/_core/_codeblock.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_internal_types.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6947 Fix SciPy dependency leak
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/scipy/linalg/_uarray.py
  docs/source/install.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py
  tests/cupyx_tests/scipy_tests/special_tests/test_softmax.py
  tests/cupyx_tests/scipy_tests/special_tests/test_sph_harm.py
  tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py
Labels: cat:bug, to-be-backported, prio:high

#6960 Fix CUB reduction with zero-size arrays
  cupy/cuda/cub.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: cat:bug, to-be-backported, prio:high

#6967 [backport] Fix docs build failure
  docs/source/conf.py
Labels: cat:document, backport, blocking, prio:high

#6968 [backport] Fix CUB reduction with zero-size arrays
  cupy/cuda/cub.pyx
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
Labels: cat:bug, backport, prio:high

#6953 Efficiency improvements in `cupyx.scipy.ndimage` utilities
  cupyx/scipy/ndimage/_filters.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_fourier.py
  cupyx/scipy/ndimage/_util.py
Labels: cat:performance, prio:medium

#6963 [backport] Fix `XFAIL` for `tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py` when `scipy>=1.9.0rc2`
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:test, backport, prio:high

#6855 [stats] add `cupyx.scipy.stats.{zmap, zscore}`
  cupyx/scipy/stats/__init__.py
  cupyx/scipy/stats/_stats_py.py
  docs/source/reference/scipy_stats.rst
  tests/cupyx_tests/scipy_tests/stats_tests/test_stats.py
Labels: cat:feature, prio:medium

#6934 Fix cuTensorNet shim layer
  cupy/linalg/_einsum_cutn.py
Labels: cat:bug, to-be-backported, prio:high

#6911 Reorganize build scripts: define compile options declaratively
  install/cupy_builder/__init__.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/_context.py
  install/cupy_builder/_features.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  install/cupy_builder/install_utils.py
  tests/install_tests/test_build.py
  tests/install_tests/test_cupy_builder/test_features.py
Labels: cat:install, prio:low

#6971 Added ``scipy.special.cosm1`` to cupyx
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_basic.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
Labels: cat:feature, prio:medium

#6962 Support SciPy 1.9
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6930 [backport] Bump documentation build requirements
  docs/requirements.txt
  docs/source/conf.py
Labels: cat:document, backport, prio:medium

#6928 Make sure that uniform sampling respects broadcasting
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:enhancement, prio:medium

#6970 [backport] Suppress nvcc warning
  cupy/_core/include/cupy/complex/complex.h
Labels: backport, prio:medium, cat:code-fix

#6991 [backport] Enhance JIT error message when __device__ option is missing
  cupyx/jit/_compile.py
Labels: cat:enhancement, backport, prio:medium

#6992 [backport] Use ubuntu-22.04 as GitHub Actions runner image
  .github/workflows/auto-cc.yml
  .github/workflows/backport.yml
  .github/workflows/docker.yml
  .github/workflows/flexci.yml
  .github/workflows/pretest-rocm-test.sh
  .github/workflows/pretest.yml
Labels: cat:test, backport

#6995 Revert comment fix
  .github/workflows/pretest-rocm-test.sh
Labels: cat:test, to-be-backported

#6996 [backport] Revert comment fix
  .github/workflows/pretest-rocm-test.sh
Labels: cat:test, backport

#6942 Fix occasional hang in sparse distributed
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/run.sh
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda102.multi.sh
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda110.multi.sh
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda111.multi.sh
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda112.multi.sh
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda113.multi.sh
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda114.multi.sh
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda115.multi.sh
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda116.multi.sh
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda117.multi.sh
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:bug, to-be-backported, prio:high

#6980 [backport] Fix SciPy dependency leak
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/scipy/linalg/_uarray.py
  docs/source/install.rst
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_sph_harm.py
Labels: cat:bug, backport, prio:high

#6997 [backport] Fix occasional hang in sparse distributed
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/run.sh
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda102.multi.sh
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda110.multi.sh
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda111.multi.sh
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda112.multi.sh
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda113.multi.sh
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda114.multi.sh
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda115.multi.sh
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda116.multi.sh
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda117.multi.sh
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:bug, backport, prio:high

#6993 [backport] JIT: Add type annotation in _compile.py
  cupy/_core/_codeblock.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_internal_types.py
Labels: cat:enhancement, backport, prio:medium

#6904 [backport] Support `equal_nan` parameter for `unique`
  cupy/_manipulation/add_remove.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: backport, cat:numpy-compat, prio:high

#7000 Filter warnings from setuptools 65
  setup.cfg
Labels: cat:test, to-be-backported, prio:high

#7004 [backport] Filter warnings from setuptools 65
  setup.cfg
Labels: cat:test, backport, prio:high

#7006 Remove use of `distutils.utils`
  install/cupy_builder/install_build.py
Labels: cat:install, to-be-backported, prio:medium

#6984 Make testing decorators able to use with `@pytest.mark.parametrize` in some cases
  cupy/testing/_loops.py
  tests/cupy_tests/testing_tests/test_loops.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6979 [backport] Fix cuTensorNet shim layer
  cupy/linalg/_einsum_cutn.py
Labels: cat:bug, backport, prio:high

#6975 Parallelize Cythonize
  install/cupy_builder/_command.py
  install/cupy_builder/cupy_setup_build.py
Labels: cat:install, prio:medium

#6958 [interpolate] add `cupyx.scipy.interpolate.BarycentricInterpolator`
  cupyx/scipy/_lib/__init__.py
  cupyx/scipy/_lib/_util.py
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_polyint.py
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/__init__.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
Labels: cat:feature, prio:medium

#6921 Let argpartition use the kth argument properly
  cupy/_core/_routines_sorting.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:bug, to-be-backported, prio:medium

#7010 [backport] Make testing decorators able to use with `@pytest.mark.parametrize` in some cases
  cupy/testing/_loops.py
  tests/cupy_tests/testing_tests/test_loops.py
Labels: cat:enhancement, backport, prio:medium

#7020 [backport] Let argpartition use the kth argument properly
  cupy/_core/_routines_sorting.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:bug, backport, prio:medium

#7022 CI: bump CUDA version used in cuda-python test
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, blocking, prio:high

#6973 [backport] Update `cupy.array_api` (cont'd)
  cupy/array_api/_set_functions.py
  cupy/array_api/linalg.py
Labels: cat:enhancement, backport, prio:medium

#6951 [backport] Accept `kind` in `sort`/`argsort` and fix `cupy.array_api.{sort,argsort}` accordingly
  cupy/_sorting/sort.py
  cupy/array_api/_sorting_functions.py
  tests/cupy_tests/array_api_tests/test_sorting_functions.py
Labels: cat:enhancement, backport, prio:medium, array-api

#6897 [backport] Support `keepdims` parameter for `average`
  cupy/_statistics/meanvar.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: backport, cat:numpy-compat, prio:high

#6966 [backport] [special] add `cupyx.scipy.special.log_softmax`
  cupy/_core/include/cupy/complex/arithmetic.h
  cupy/_core/include/cupy/complex/math_private.h
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_logsoftmax.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py
Labels: cat:feature, backport, prio:medium

#6981 [backport] Support SciPy 1.9
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, backport, prio:medium

#7023 [backport] CI: bump CUDA version used in cuda-python test
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
Labels: cat:test, backport, blocking, prio:high
