Repository cupy/cupy, pull requests merged in 2022-04, with the labels that each got.

#6607 [backport] Documentation update for ROCm 5.0
  README.md
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:medium

#6612 Add `--pre` option to instructions installing pre-releases
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:high

#6614 [backport] Add `--pre` option to instructions installing pre-releases
  README.md
  docs/source/install.rst
Labels: cat:document, backport, prio:high

#6613 Implement `flatten(order)`
  cupy/_core/_routines_manipulation.pxd
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  cupy/_manipulation/shape.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/manipulation_tests/test_shape.py
Labels: cat:enhancement, prio:medium

#6598 Run daily benchmark with head branch against latest release
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/actions/benchmark.sh
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/benchmark.head.sh
  .pfnci/matrix.yaml
Labels: cat:test, prio:medium

#6621 Add missing `cudaDevAttrMemoryPoolsSupported` to hip
  cupy_backends/cuda/api/_runtime_enum.pxd
Labels: cat:enhancement, to-be-backported

#6624 Define float16::operator-() only for ROCm 5.0+
  cupy/_core/include/cupy/carray.cuh
  tests/cupy_tests/core_tests/test_include.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#6629 [backport] Define float16::operator-() only for ROCm 5.0+
  cupy/_core/include/cupy/carray.cuh
  tests/cupy_tests/core_tests/test_include.py
Labels: cat:bug, backport, blocking, prio:high

#6619 JIT: Avoid calling default constructor if possible
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
Labels: cat:enhancement, prio:medium

#6630 [hotfix-v10.3.1] [backport] Define float16::operator-() only for ROCm 5.0+
  cupy/_core/include/cupy/carray.cuh
  tests/cupy_tests/core_tests/test_include.py
Labels: cat:bug, backport, blocking, prio:high

#6632 Remove `jenkins` requirements
  .pfnci/windows/test.ps1
  setup.py
Labels: cat:test, to-be-backported, prio:low

#6625 CI: Trigger FlexCI for hotfix branches
  .github/workflows/flexci.yml
Labels: cat:test, to-be-backported, prio:high

#6635 [hotfix-v10.3.1] Bump version in Dockerfile to v10.3.1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install, prio:high

#6636 [backport] CI: Trigger FlexCI for hotfix branches
  .github/workflows/flexci.yml
Labels: cat:test, backport, prio:high

#6617 Implemented a __repr__ for cupyx.profiler._time._PerfCaseResult
  cupyx/profiler/_time.py
Labels: cat:enhancement, prio:medium

#6639 JIT: fix access to cached codes
  cupyx/jit/_interface.py
Labels: cat:bug, to-be-backported, prio:high

#6643 Add kernel.cached_code test
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, prio:medium

#6620 Support cooperative group in JIT compiler
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_interface.py
  cupyx/jit/_internal_types.py
  cupyx/jit/cg.py
  docs/source/conf.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_cooperative_groups.py
Labels: cat:feature, prio:medium

#6634 [backport] Remove `jenkins` requirements
  .pfnci/windows/test.ps1
  setup.py
Labels: cat:test, backport, prio:low

#6181 Improve copy and assign operation
  cupy/_core/_gufuncs.py
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_creation/basic.py
  cupy/_functional/piecewise.py
  cupy/_manipulation/tiling.py
  cupy/cublas.py
  cupy/cuda/cub.pyx
  cupy/cudnn.pyx
  cupy/cusparse.py
  cupy/random/_generator_api.pyx
  cupyx/scipy/ndimage/_filters.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_fourier.py
  cupyx/scipy/ndimage/_interpolation.py
  cupyx/scipy/ndimage/_measurements.py
  cupyx/scipy/ndimage/_morphology.py
  cupyx/scipy/sparse/_base.py
  cupyx/scipy/sparse/_coo.py
  cupyx/scipy/sparse/_csr.py
Labels: cat:performance, prio:medium

#6631 Add CC 3.2 to Tegra arch list
  cupy/cuda/compiler.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6646 Fix `TestIncludesCompileCUDA` for HEAD tests
  tests/cupy_tests/core_tests/test_include.py
Labels: cat:test, to-be-backported, prio:high

#6626 [backport] Add missing `cudaDevAttrMemoryPoolsSupported` to hip
  cupy_backends/cuda/api/_runtime_enum.pxd
Labels: cat:enhancement, backport

#6604 Add a few driver/runtime/nvrtc API wrappers
  cupy/cuda/compiler.py
  cupy_backends/cuda/api/_driver_enum.pxd
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/nvrtc.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/hip/cupy_hip.h
  cupy_backends/hip/cupy_hiprtc.h
  cupy_backends/stub/cupy_cuda.h
  cupy_backends/stub/cupy_nvrtc.h
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_runtime.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6652 Fix cuda python CI
  cupy_backends/cuda/api/runtime.pxd
  tests/cupyx_tests/jit_tests/test_cooperative_groups.py
Labels: cat:bug, prio:high

#6650 [backport] Fix `TestIncludesCompileCUDA` for HEAD tests
  tests/cupy_tests/core_tests/test_include.py
Labels: cat:test, backport, prio:high

#6655 [backport] Trigger CUDA Python tests with `/test mini`
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, backport

#6654 [v10] Fix Mempool attr for Cuda Python
  cupy_backends/cuda/api/runtime.pxd
Labels: cat:bug, prio:high

#6657 Fix Typo
  docs/source/user_guide/performance.rst
Labels: cat:document

#6648 JIT: fix function signatures in the docs
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_internal_types.py
  docs/source/conf.py
  docs/source/reference/kernel.rst
Labels: cat:document, to-be-backported, prio:medium

#6659 [backport] Fix typo in performance guide
  docs/source/user_guide/performance.rst
Labels: cat:document, backport, prio:medium

#6660 [backport] JIT: fix function signatures in the docs
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_internal_types.py
  docs/source/conf.py
  docs/source/reference/kernel.rst
Labels: cat:document, backport, prio:medium

#6640 JIT: Add more cooperative group APIs
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/cg.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_cooperative_groups.py
Labels: cat:enhancement, prio:medium

#6664 Fix int64 overflow in `cupy.polyval`
  cupy/lib/_routines_poly.py
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:bug, to-be-backported, prio:high

#6666 [backport] Fix int64 overflow in `cupy.polyval`
  cupy/lib/_routines_poly.py
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:bug, backport, prio:high

#6649 JIT: Support compile-time for-loop unrolling
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_internal_types.py
  docs/source/reference/kernel.rst
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, takeover, prio:medium

#6669 Improve warning message in sparse
  cupyx/scipy/sparse/_compressed.py
Labels: cat:enhancement, prio:medium

#6651 [backport] Add a few driver/runtime/nvrtc API wrappers
  cupy/cuda/compiler.py
  cupy_backends/cuda/api/_driver_enum.pxd
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/nvrtc.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/hip/cupy_hip.h
  cupy_backends/hip/cupy_hiprtc.h
  cupy_backends/stub/cupy_cuda.h
  cupy_backends/stub/cupy_nvrtc.h
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_driver.py
  tests/cupy_tests/cuda_tests/test_runtime.py
Labels: cat:enhancement, backport, prio:medium

#6671 JIT: Disable `memcpy_async` on CUDA 11.0
  cupyx/jit/cg.py
  tests/cupyx_tests/jit_tests/test_cooperative_groups.py
Labels: cat:bug, prio:medium

#6668 JIT: Support `.shape` and `.strides`
  cupy/_core/include/cupy/carray.cuh
  cupy/_core/include/cupy/tuple/tuple.h
  cupy/_functional/vectorize.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:feature, prio:medium

#6679 [backport] Fix missing f prefix on f-strings fix
  .github/workflows/flexci_dispatcher.py
Labels: cat:test, backport

#6647 [backport] Add CC 3.2 to Tegra arch list
  cupy/cuda/compiler.py
Labels: cat:enhancement, backport, prio:medium

#6628 Add support for sparse matrices in `cupyx.distributed`
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:feature, blocking

#6012 Add universal CuPy package
  .github/workflows/pretest.yml
  .gitignore
  install/universal_pkg/RELEASE.md
  install/universal_pkg/__init__.py
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/__init__.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:install, to-be-backported, blocking, prio:medium

#6683 [backport] Add universal CuPy package
  .github/workflows/pretest.yml
  .gitignore
  install/universal_pkg/RELEASE.md
  install/universal_pkg/__init__.py
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/__init__.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:install, backport, blocking, prio:medium

#6684 Bump version to v11.0.0b2
  cupy/_version.py
Labels: cat:other

#6685 Bump version to v10.4.0
  cupy/_version.py
Labels: cat:other

#6687 Bump version in Dockerfile for v10.4.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#6686 Bump version in Dockerfile for v11.0.0b2
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other
