Repository cupy/cupy, pull requests merged in 2022-07, with the labels that each got.

#6847 Bump stable branch to v11
  .pfnci/BRANCH_STABLE
Labels: cat:other, prio:high

#6845 [v11] Bump branch version to v11
  .pfnci/BRANCH
  .pfnci/BRANCH_STABLE
Labels: cat:other, prio:high

#6848 Relaxed C-contiguous requirement for changing dtype of different size
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#6846 Fix ROCm supported versions in compat matrix
  docs/source/upgrade.rst
Labels: cat:document, to-be-backported, prio:medium

#6851 [backport] Fix ROCm supported versions in compat matrix
  docs/source/upgrade.rst
Labels: cat:document, backport, prio:medium

#6850 [backport] Relaxed C-contiguous requirement for changing dtype of different size
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: backport, cat:numpy-compat, prio:high

#6798 add `cupy.heaviside` api.
  cupy/__init__.py
  cupy/_math/misc.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:feature, prio:medium

#6836 Reverting to v10 installation instruction until v11 stable release
  README.md
Labels: cat:document, to-be-backported, prio:high

#6857 Generate docs for private classes in one location
  cupyx/jit/cg.py
  docs/source/reference/_deprecated.rst
  docs/source/reference/_private.rst
  docs/source/reference/fft.rst
  docs/source/reference/kernel.rst
  docs/source/reference/perf_result.rst
  docs/source/reference/plan_cache.rst
Labels: cat:document, to-be-backported, prio:medium

#6814 Update tags for FlexCI projects
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, prio:medium

#6837 Enhance JIT error message when __device__ option is missing
  cupyx/jit/_compile.py
Labels: cat:enhancement, prio:medium

#6828 CI: Add ROCm 5.1 and 5.2
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-1.sh
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/linux/tests/rocm-5-2.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:medium

#6861 [backport] CI: Add ROCm 5.1 and 5.2
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-5-1.Dockerfile
  .pfnci/linux/tests/rocm-5-1.sh
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/linux/tests/rocm-5-2.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, backport, prio:medium

#6860 [backport] Update tags for FlexCI projects
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, backport, prio:medium

#6858 [backport] Generate docs for private classes in one location
  cupyx/jit/cg.py
  docs/source/reference/_deprecated.rst
  docs/source/reference/_private.rst
  docs/source/reference/fft.rst
  docs/source/reference/kernel.rst
  docs/source/reference/perf_result.rst
  docs/source/reference/plan_cache.rst
Labels: cat:document, backport, prio:medium

#6849 [stats] add `cupyx.scipy.stats.boxcox_llf`
  cupyx/scipy/stats/__init__.py
  cupyx/scipy/stats/_morestats.py
  docs/source/reference/scipy_stats.rst
  tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py
Labels: cat:feature, prio:medium

#6877 Fix function names
  cupy/cuda/device.pyx
Labels: to-be-backported, prio:medium, cat:code-fix

#6875 Generate CUBIN for all supported GPUs at build time
  install/cupy_builder/_compiler.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#6878 [backport] Fix function names
  cupy/cuda/device.pyx
Labels: backport, prio:medium, cat:code-fix

#6881 [backport] Generate CUBIN for all supported GPUs at build time
  install/cupy_builder/_compiler.py
Labels: cat:bug, backport, blocking, prio:high

#6884 Fix `boxcox_llf`
  cupyx/scipy/stats/_morestats.py
  tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py
Labels: cat:bug, to-be-backported, prio:high

#6880 Add config for `cupy.win.cuda117`
  .pfnci/config.pbtxt
  .pfnci/windows/_flexci.ps1
Labels: cat:test, to-be-backported, prio:high

#6885 [backport] Add config for `cupy.win.cuda117`
  .pfnci/config.pbtxt
  .pfnci/windows/_flexci.ps1
Labels: cat:test, backport, prio:high

#6852 Support `keepdims` parameter for `average`
  cupy/_statistics/meanvar.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#6853 Support `equal_nan` parameter for `unique`
  cupy/_manipulation/add_remove.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#6896 Fix real and imag in subclass
  cupy/_core/_routines_math.pyx
Labels: cat:bug, to-be-backported, blocking, prio:high

#6905 Support `deg` in `cupy.angle`
  cupy/_core/__init__.py
  cupy/_core/_routines_math.pyx
  cupy/_math/arithmetic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:enhancement, to-be-backported, blocking, prio:medium

#6909 [backport] Support `deg` in `cupy.angle`
  cupy/_core/__init__.py
  cupy/_core/_routines_math.pyx
  cupy/_math/arithmetic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:enhancement, backport, blocking, prio:medium

#6903 Update cupy-wheel for v11
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#6915 Bump version to v11.0.0
  cupy/_version.py
Labels: cat:install, blocking

#6913 [backport] Update cupy-wheel for v11
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:enhancement, backport, blocking, prio:high

#6888 Update installation guide for v11 (aarch64)
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#6917 [backport] Update installation guide for v11 (aarch64)
  README.md
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:high

#6889 Update install instructions on README
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#6924 Bump version for Docker image v11.0.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#6925 [v11] Update install instructions on README
  README.md
  docs/source/install.rst
Labels: cat:document, prio:high

#6871 Update `cupy.array_api`
  cupy/array_api/_array_object.py
  cupy/array_api/_data_type_functions.py
  cupy/array_api/_sorting_functions.py
  cupy/array_api/linalg.py
  tests/cupy_tests/array_api_tests/test_array_object.py
Labels: cat:enhancement, to-be-backported, prio:medium, array-api

#6825 Bump documentation build requirements
  docs/requirements.txt
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:medium
