Repository cupy/cupy, pull requests merged in 2022-06, with the labels that each got.

#6759 Fix `cupy.median` for NaN inputs
  cupy/_core/_routines_statistics.pyx
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: cat:bug, to-be-backported, prio:high

#6760 [backport] Fix `cupy.median` for NaN inputs
  cupy/_core/_routines_statistics.pyx
  tests/cupy_tests/statistics_tests/test_meanvar.py
Labels: cat:bug, backport, prio:high

#6758 Add sparse `broadcast`
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:feature, prio:medium

#6761 Add sparse `reduce`
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:feature, prio:medium

#6762 Add sparse `all_reduce` and minor fixes
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:feature, prio:medium

#6725 Fix batched matmul for integral numbers
  cupy/_core/_routines_linalg.pyx
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:bug, to-be-backported, prio:medium

#6721 Fix polynomial tests
  cupy/lib/_routines_poly.py
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:bug, prio:medium

#6733 [backport] Xfail a test of LOBPCG on ROCm 5.0+
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, backport, prio:high

#6675 [backport] Improve warning message in sparse
  cupyx/scipy/sparse/compressed.py
Labels: cat:enhancement, backport, prio:medium

#6777 [backport] Fix batched matmul for integral numbers
  cupy/_core/_routines_linalg.pyx
  tests/cupy_tests/core_tests/test_raw.py
  tests/cupy_tests/math_tests/test_matmul.py
Labels: cat:bug, backport, prio:medium

#6746 Subclass rename
  cupy/_core/__init__.py
  cupy/_core/_cub_reduction.pxd
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_fusion_trace.pyx
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/_core/_memory_range.pxd
  cupy/_core/_memory_range.pyx
  cupy/_core/_reduction.pxd
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_indexing.pxd
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pxd
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_logic.pxd
  cupy/_core/_routines_logic.pyx
  cupy/_core/_routines_manipulation.pxd
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pxd
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_sorting.pxd
  cupy/_core/_routines_sorting.pyx
  cupy/_core/_routines_statistics.pxd
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  cupy/_core/dlpack.pxd
  cupy/_core/dlpack.pyx
  cupy/_core/internal.pyx
  cupy/cuda/cub.pxd
  cupy/cuda/cub.pyx
  cupy/cuda/function.pyx
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  cupy/cudnn.pyx
  cupy/cusolver.pyx
  cupy/cutensor.pyx
  cupy/fft/_callback.pyx
  cupy/lib/_polynomial.pyx
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  docs/source/conf.py
  tests/cupy_tests/core_tests/test_core.py
Labels: prio:medium, cat:code-fix

#6781 CI: Fix prep script to show build failure details
  .pfnci/linux/main-flexci-prep.sh
Labels: cat:test, to-be-backported, prio:medium

#6774 Improved NVTX documentation
  cupy_backends/cuda/libs/nvtx.pyx
Labels: cat:document, prio:medium

#6784 [backport] CI: Fix prep script to show build failure details
  .pfnci/linux/main-flexci-prep.sh
Labels: cat:test, backport, prio:medium

#6770 Use fast convolution algorithm in `cupy.poly1d.__pow__`
  cupy/lib/_routines_poly.py
  cupyx/scipy/special/__init__.py
Labels: cat:performance, prio:medium

#6518 [backport] Fix Dockerfile broken for array-api tests
  .pfnci/linux/tests/array-api.Dockerfile
Labels: cat:test, backport, prio:medium

#6726 Add type annotation in `_cuda_types.py`
  cupyx/jit/_cuda_types.py
Labels: prio:medium, cat:code-fix

#6736 Fix to return correct CUDA version when in CUDA Python mode
  cupy_backends/cuda/api/runtime.pyx
  tests/cupy_tests/cuda_tests/test_runtime.py
Labels: cat:enhancement, no-compat, prio:high

#6703 Improved integer matrix multiplication performance by modifying tuning parameters
  cupy/_core/_routines_linalg.pyx
Labels: cat:performance, prio:medium

#6730 Utilize CUDA Enhanced Compatibility
  cupy_backends/cuda/_softlink.pxd
  cupy_backends/cuda/_softlink.pyx
  cupy_backends/cuda/cupy_nvrtc.h
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/hip/cupy_hiprtc.h
  cupy_backends/stub/cupy_nvrtc.h
  install/cupy_builder/_modules.py
Labels: cat:enhancement, no-compat, prio:high

#6763 Add sparse `gather` `scatter` `all_gather`
  cupyx/distributed/_nccl_comm.py
  tests/cupyx_tests/distributed_tests/comm_runner.py
  tests/cupyx_tests/distributed_tests/test_comm.py
Labels: cat:feature, prio:medium

#6782 Fix docs to hide `ndarray_base`
  cupy/_core/core.pyx
  docs/source/conf.py
Labels: cat:document, prio:medium

#6776 [special] Add `cupyx.scipy.special.log_ndtr`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_stats_distributions.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:feature

#6788 [backport] Fix a potential variable misuse bug
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:test, backport, prio:medium

#6778 Add type annotation to JIT internal types
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_internal_types.py
Labels: prio:medium, cat:code-fix

#6791 Make the warning for cupy.array_api say "cupy" instead of "numpy"
  cupy/array_api/__init__.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6795 [backport] Make the warning for cupy.array_api say "cupy" instead of "numpy"
  cupy/array_api/__init__.py
Labels: cat:enhancement, backport, prio:medium

#6768 Add CUDA 11.7 on documents
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:high

#6802 Bump base Docker image to the latest supported one
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:enhancement, no-compat, blocking, prio:high

#6690 Add initial cupyx.spatial.distance support from pylibraft
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
  .pfnci/linux/tests/cuda-rapids.Dockerfile
  .pfnci/linux/tests/cuda-rapids.sh
  cupyx/scipy/spatial/__init__.py
  cupyx/scipy/spatial/distance.py
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_spatial.rst
  docs/source/reference/scipy_spatial_distance.rst
  tests/cupyx_tests/scipy_tests/spatial_tests/__init__.py
  tests/cupyx_tests/scipy_tests/spatial_tests/test_distance.py
Labels: cat:feature, prio:medium

#6799 Utilize CUDA Enhanced Compatibility in all wrappers
  cupy_backends/cuda/cupy_cusparse.h
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/hip/cupy_hiprtc.h
  cupy_backends/stub/cupy_cusparse.h
  cupy_backends/stub/cupy_nvrtc.h
Labels: cat:enhancement, blocking, prio:high

#6800 Add support for `cupy-cuda11x` wheel
  cupy/_environment.py
  cupyx/tools/install_library.py
Labels: cat:enhancement, blocking, prio:high

#6806 Fix required cusparse symbol not loaded in CUDA 11.1.1
  cupy_backends/cuda/cupy_cusparse.h
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:bug, prio:high

#6804 Fix CI Docker image build failing in head test
  .pfnci/coverage.rst
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/update-cuda-driver.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:high

#6720 Support cupy.ndarray subclassing - Part 2 - View casting
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  cupy/_core/internal.pyx
  cupy/cusolver.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:feature, prio:high

#6808 [backport] Fix CI Docker image build failing in head test
  .pfnci/coverage.rst
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/update-cuda-driver.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, backport, prio:high

#6809 Tiny clean up in CI script
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
  .pfnci/linux/tests/cuda-rapids.Dockerfile
  .pfnci/linux/tests/cuda-rapids.sh
Labels: cat:test

#6775 Subclass cupy.ndarray subclassing - Part 3 - New from template (ufunc)
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/_core/_reduction.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  cupy/cutensor.pyx
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:feature, prio:high

#6591 Fix mempool tests
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:test, to-be-backported, prio:medium

#6790 [special] Add `cupyx.scipy.special.expn`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_expn.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_expn.py
Labels: cat:feature

#6803 Update docs for `cupy-cuda11x` wheel
  README.md
  docs/source/install.rst
Labels: cat:document, blocking, prio:high

#6810 Remove `CUPY_CUDA_VERSION` as much as possible
  cupy/cuda/memory.pyx
  cupy/fft/_callback.pyx
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cuda_runtime.h
  cupy_backends/cuda/libs/nvrtc.pyx
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_common.h
  cupy_backends/stub/cupy_cuda_runtime.h
Labels: cat:enhancement, blocking, prio:high

#6807 Fix for NumPy 1.23
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pyx
  cupy/_core/internal.pxd
  cupy/_core/internal.pyx
  cupyx/jit/_cuda_typerules.py
  tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:numpy-compat, blocking, prio:high

#6820 Support NumPy 1.23
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, prio:high

#6824 Bump NumPy version used in docs
  docs/requirements.txt
Labels: cat:document

#6826 Add upgrade guide for CuPy v11
  docs/source/upgrade.rst
Labels: cat:document, blocking, prio:high

#6818 Raise UserWarning in `cupy.cuda.compile_with_cache`
  cupy/cuda/compiler.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: cat:enhancement, blocking, prio:high

#6819 cupy-wheel: Use NVRTC to infer the toolkit version
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:enhancement, to-be-backported, prio:high

#6831 [backport] cupy-wheel: Use NVRTC to infer the toolkit version
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:enhancement, backport, prio:high

#6832 Fix docker workflow to push to latest image
  .github/workflows/docker.yml
Labels: cat:other, prio:high

#6841 [backport] Fix docker workflow to push to latest image
  .github/workflows/docker.yml
Labels: cat:other, backport, prio:high

#6838 Bump cupy-wheel version
  install/universal_pkg/setup.py
Labels: cat:enhancement, to-be-backported

#6840 Bump version for Docker image v10.6.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6839 Bump version for Docker image v11.0.0rc1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6843 [backport] Bump cupy-wheel version
  install/universal_pkg/setup.py
Labels: cat:enhancement, backport
