Repository cupy/cupy, pull requests merged in 2022-01, with the labels that each got.

#6281 Fix cache key for github actions
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported

#6285 Make streams hashable
  cupy/cuda/stream.pyx
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:enhancement, prio:medium

#6278 Cublas extension
  .gitignore
  cupy/cublas.py
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/stub/cupy_cublas.h
  tests/cupy_tests/test_cublas.py
Labels: cat:feature, prio:medium

#6267 [backport] Fixing index calculation for random constructor
  cupyx/scipy/sparse/construct.py
Labels: cat:bug, backport, prio:high

#6286 [backport] Fix cache key for github actions
  .github/workflows/pretest.yml
Labels: cat:test, backport

#6212 Alias NumPy error classes
  cupy/__init__.py
  cupy/linalg/__init__.py
  tests/cupy_tests/test_init.py
Labels: cat:enhancement, prio:medium

#4567 Support stream capture
  cupy/cuda/__init__.py
  cupy/cuda/graph.pxd
  cupy/cuda/graph.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/curand.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  docs/source/reference/cuda.rst
  install/cupy_builder/_modules.py
  tests/cupy_tests/cuda_tests/test_graph.py
Labels: cat:feature, prio:medium

#6287 Check isinstance before comparison in ``__eq__``
  cupy/cuda/stream.pyx
Labels: cat:enhancement, prio:high

#6283 more clear warning message
  cupyx/scipy/ndimage/measurements.py
Labels: cat:enhancement, prio:medium

#6289 BUG: Fix the .T attribute in the `array_api` namespace
  cupy/array_api/_array_object.py
  tests/cupy_tests/array_api_tests/test_array_object.py
Labels: cat:bug, to-be-backported, array-api

#6266 Fix `eigsh` doc
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:document, to-be-backported, prio:medium

#6279 Add `cupy.vander` API.
  cupy/__init__.py
  cupy/_creation/matrix.py
  docs/source/reference/creation.rst
  tests/cupy_tests/creation_tests/test_matrix.py
Labels: cat:feature, prio:medium

#6292 [backport] Fix `eigsh` doc
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:document, backport, prio:medium

#6291 [backport] BUG: Fix the .T attribute in the `array_api` namespace
  cupy/array_api/_array_object.py
  tests/cupy_tests/array_api_tests/test_array_object.py
Labels: cat:bug, backport, array-api

#6250 Support comparison with more objects
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Labels: cat:enhancement, prio:medium

#6259 Remove XFAIL for XPASS tests on ROCm
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: cat:test, to-be-backported, prio:medium

#6303 Use NVIDIA docker images for CUDA 11.5
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda115.sh
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, prio:high

#6296 Fix stream capture in ROCm
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/curand.pyx
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:bug, blocking, prio:high

#6280 Add `cupy.ediff1d` API.
  cupy/__init__.py
  cupy/_math/sumprod.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:feature, prio:medium

#6294 Add doc issue template
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: cat:other, prio:medium

#6304 [backport] Use NVIDIA docker images for CUDA 11.5
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda115.sh
  .pfnci/matrix.yaml
Labels: cat:test, backport, prio:high

#6282 Add `cupy.fabs` API.
  cupy/__init__.py
  cupy/_math/misc.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:feature, prio:medium

#6288 add discrete cosine and sine transforms to cupyx.scipy.fft
  cupyx/scipy/fft/__init__.py
  cupyx/scipy/fft/_fft.py
  cupyx/scipy/fft/_realtransforms.py
  docs/source/reference/scipy_fft.rst
  tests/cupyx_tests/scipy_tests/fft_tests/test_realtransforms.py
Labels: cat:feature, prio:medium

#6310 Tentatively pin to CUDA Driver 495
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:high

#6311 [backport] Tentatively pin to CUDA Driver 495
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:high

#5687 add additional special functions (spherical harmonics, Legendre, Gamma functions)
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_gammainc.py
  cupyx/scipy/special/_gammasgn.py
  cupyx/scipy/special/_lpmv.py
  cupyx/scipy/special/_poch.py
  cupyx/scipy/special/_sph_harm.py
  docs/source/reference/scipy_special.rst
  docs/source/reference/special.rst
  setup.cfg
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gammainc.py
  tests/cupyx_tests/scipy_tests/special_tests/test_sph_harm.py
Labels: cat:feature, prio:medium

#6301 add xlogy and xlog1py to cupyx.scipy.special
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_xlogy.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
Labels: cat:feature, prio:medium

#6305 Add `tril_indices` and `tril_indices_from` API.
  cupy/__init__.py
  cupy/_indexing/generate.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:feature, prio:medium

#6297 [backport] Remove XFAIL for XPASS tests on ROCm
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: cat:test, backport, prio:medium

#6322 Remove unused dtype parameterizing in `tril_indices` test
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:test, prio:medium

#6308 added `cupy.format_float_positional`
  cupy/__init__.py
  cupy/_io/formatting.py
  docs/source/reference/io.rst
  tests/cupy_tests/io_tests/test_formatting.py
Labels: cat:feature, prio:medium

#6316 Add `triu_indices` and `triu_indices_from` API.
  cupy/__init__.py
  cupy/_indexing/generate.py
  docs/source/reference/indexing.rst
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:feature, prio:medium

#6234 JIT: Fix if expr typing rule
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:medium

#6300 add logit, expit and log_expit to cupyx.scipy.special
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_statistics.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:feature, prio:medium

#6314 Support cuDNN 8.3.2
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6187 Support cuTENSOR 1.4.0
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/cutensor.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, st:awaiting-author, prio:medium

#6166 Support CUDA 11.5.1
  cupy/cuda/compiler.py
  cupy/fft/_callback.pyx
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, to-be-backported, prio:medium

#6265 JIT: Support `__device__` function
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_interface.py
  tests/cupyx_tests/jit_tests/test_device_function.py
Labels: cat:enhancement, prio:medium

#6312 Add `cupy.row_stack` API.
  cupy/__init__.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: cat:feature, prio:medium

#6333 Use `get_include` instead of `array_equiv` for fallback test
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:test, prio:medium

#6254 Add array_equiv API.
  cupy/__init__.py
  cupy/_creation/from_data.py
  cupy/_logic/comparison.py
  cupy/_manipulation/kind.py
  docs/source/reference/logic.rst
  tests/cupy_tests/logic_tests/test_comparison.py
Labels: cat:feature, prio:medium

#6337 Fix cuDNN installer not working
  cupyx/tools/install_library.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#6335 CI: Add `cuda-slow` test in FlexCI
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
Labels: cat:test, to-be-backported, prio:high

#6339 [backport] CI: Add `cuda-slow` test in FlexCI
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
Labels: cat:test, backport, prio:high

#6342 Fix for cuDNN directory structure in Windows
  cupyx/tools/install_library.py
Labels: to-be-backported, blocking, prio:high

#6348 Install lib directory on Windows in cuDNN installer
  cupyx/tools/install_library.py
Labels: cat:install, to-be-backported

#6351 Bump version in Dockerfiles for v11.0.0a1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6352 Bump version in Dockerfile for v10.1.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6323 Support NumPy 1.22
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/linalg/_decomposition.py
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, to-be-backported

#6329 Fix JIT to support notebook environment
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
  docs/source/user_guide/kernel.rst
Labels: cat:bug, to-be-backported, prio:high

#6315 Use CUDA's log1p for cupyx.scipy.special.log1p
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_basic.py
  cupyx/scipy/special/_gammainc.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
Labels: cat:feature, prio:medium

#6249 Fix CI failure to support SciPy 1.8.0
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement, to-be-backported, prio:high

#6331 [backport] Support CUDA 11.5.1
  cupy/cuda/compiler.py
  cupy/fft/_callback.pyx
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, backport, prio:medium

#6363 Avoid empty notification message for scheduled tests
  .pfnci/flexci_notify.py
Labels: cat:test, to-be-backported

#6275 Add `asarray_chkfinite` API.
  cupy/__init__.py
  cupy/_manipulation/kind.py
  docs/source/reference/manipulation.rst
  tests/cupy_tests/manipulation_tests/test_kind.py
Labels: cat:feature, prio:medium

#6354 [backport] Support NumPy 1.22
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/linalg/_decomposition.py
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, backport

#6364 [backport] Avoid empty notification message for scheduled tests
  .pfnci/flexci_notify.py
Labels: cat:test, backport

#6341 Make scipy.special ufuncs work with CuPy inputs
  cupy/_core/core.pyx
  tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py
Labels: cat:enhancement, prio:medium

#6328 [backport] Support cuDNN 8.3.2
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:medium

#6368 [backport] Fix cuDNN installer not working
  cupyx/tools/install_library.py
Labels: cat:bug, backport, blocking, prio:high

#6369 [backport] Fix for cuDNN directory structure in Windows
  cupyx/tools/install_library.py
Labels: cat:install, backport, blocking, prio:high

#6370 [backport] Install lib directory on Windows in cuDNN installer
  cupyx/tools/install_library.py
Labels: cat:install, backport

#6356 [backport] Fix JIT to support notebook environment
  cupyx/jit/__init__.py
  cupyx/jit/_compile.py
  docs/source/user_guide/kernel.rst
Labels: cat:bug, backport, prio:high

#6338 [backport] CI: use CUDA docker images for CUDA Python CI
  .pfnci/config.pbtxt
  .pfnci/coverage.md
  .pfnci/generate.py
  .pfnci/linux/README.md
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, backport, prio:medium

#6269 CI: allow discarding docker image cache manually
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/run.sh
Labels: cat:test, to-be-backported, prio:medium

#6273 Avoid monkeypatching distutils
  .github/workflows/pretest.yml
  .pfnci/windows/test.ps1
  install/cupy_builder/__init__.py
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/cupy_setup_build.py
  setup.py
Labels: cat:install, to-be-backported, prio:medium

#6372 [backport] CI: allow discarding docker image cache manually
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/run.sh
Labels: cat:test, backport, prio:medium

#6343 Parameterize library installer tests
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: cat:test, to-be-backported, prio:high

#6373 [backport] Avoid monkeypatching distutils
  .github/workflows/pretest.yml
  .pfnci/windows/test.ps1
  install/cupy_builder/__init__.py
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/cupy_setup_build.py
  setup.py
Labels: cat:install, backport, prio:medium

#6347 Fix tests for eigh() for CUDA 11.6
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:test, to-be-backported, prio:medium

#6321 avoid DeprecationWarning from SciPy 1.8 (`cupyx.scipy.sparse`)
  cupyx/scipy/sparse/_index.py
Labels: cat:enhancement, prio:medium

#6376 [backport] Fix tests for eigh() for CUDA 11.6
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:test, backport, prio:medium

#6327 Remove batched QR solver's experimental mark
  cupy/linalg/_decomposition.py
  tests/cupy_tests/linalg_tests/test_decomposition.py
Labels: cat:enhancement, prio:medium

#6332 DOC: Use `cupy.__version__` instead of `pkg_resources`
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:low

#6380 [backport] DOC: Use `cupy.__version__` instead of `pkg_resources`
  docs/source/conf.py
Labels: cat:document, backport, prio:low

#6330 [backport] Support cuTENSOR 1.4.0
  .pfnci/coverage.md
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/cutensor.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#6362 [backport] Fix CI failure to support SciPy 1.8.0
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:enhancement, backport, prio:high

#6357 Add `cupy.union1d` API.
  cupy/__init__.py
  cupy/_logic/truth.py
  docs/source/reference/logic.rst
  tests/cupy_tests/logic_tests/test_truth.py
Labels: cat:feature, prio:medium

#6379 [backport] avoid DeprecationWarning from SciPy 1.8 (`cupyx.scipy.sparse`)
  cupyx/scipy/sparse/_index.py
Labels: cat:enhancement, backport, prio:medium

#6381 Add `cupy.testing.installed`
  cupy/testing/__init__.py
  cupy/testing/_helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, prio:medium

#6346 Fix thrust related build issue with CUDA 11.6
  cupy/cuda/cupy_thrust.cu
Labels: cat:enhancement, to-be-backported, st:blocked-by-another-pr, prio:medium

#6298 implement overwrite_input in cupy.{percentile,quantile}
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:enhancement, prio:medium

#6386 [backport] Fix thrust related build issue with CUDA 11.6
  cupy/cuda/cupy_thrust.cu
Labels: cat:enhancement, backport, prio:medium

#6387 [backport] Add `cupy.testing.installed`
  cupy/testing/__init__.py
  cupy/testing/_helper.py
  tests/cupy_tests/testing_tests/test_helper.py
Labels: cat:test, backport, prio:medium

#6388 Fix verbose LOBPCG for SciPy 1.8
  cupyx/scipy/sparse/linalg/_lobpcg.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#6382 Fix type annotations in installer
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  install/cupy_builder/install_utils.py
  install/mypy.ini
Labels: cat:enhancement, to-be-backported, prio:medium

#6385 Mark XFAIL for SciPy 1.8 release candidate
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:test, to-be-backported, prio:high

#6395 [backport] Fix type annotations in installer
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  install/cupy_builder/install_utils.py
  install/mypy.ini
Labels: cat:enhancement, backport, prio:medium

#6391 Remove global `use_hip` flag in setup
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  tests/install_tests/test_build.py
Labels: to-be-backported, prio:medium, cat:code-fix

#6389 Eliminate unnecessary configuration pass in setup
  install/cupy_builder/_command.py
  install/cupy_builder/cupy_setup_build.py
  setup.py
  tests/install_tests/test_cupy_builder/test_command.py
Labels: cat:install, to-be-backported, prio:medium

#6396 [backport] Mark XFAIL for SciPy 1.8 release candidate
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:test, backport, prio:high

#6340 Add slow tests for stable branch
  .pfnci/BRANCH_STABLE
  .pfnci/config.pbtxt
  .pfnci/linux/main-flexci-stable.sh
Labels: cat:test, prio:high

#6399 [backport] Eliminate unnecessary configuration pass in setup
  install/cupy_builder/_command.py
  install/cupy_builder/cupy_setup_build.py
  setup.py
  tests/install_tests/test_cupy_builder/test_command.py
Labels: cat:install, backport, prio:medium

#6398 [backport] Remove global `use_hip` flag in setup
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  tests/install_tests/test_build.py
Labels: backport, prio:medium, cat:code-fix

#6251 Add `cupy.typing`
  cupy/_core/core.pyx
  cupy/typing/__init__.py
  cupy/typing/_generic_alias.py
  tests/cupy_tests/test_typing.py
Labels: cat:feature, prio:high

#6394 [backport] Fix verbose LOBPCG for SciPy 1.8
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: backport, cat:numpy-compat, prio:high

#6317 Add special functions from the CUDA Math API
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_basic.py
  cupyx/scipy/special/_bessel.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
Labels: cat:feature, prio:medium

#6302 add Box-Cox transformations to cupyx.scipy.special
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_statistics.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:feature, prio:medium

#6371 added api for `cupy.float_power`
  cupy/__init__.py
  cupy/_math/arithmetic.py
  docs/source/reference/math.rst
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: cat:feature, prio:medium

#6392 Reduce memory usage in `cupy.sort`
  cupy/_core/_routines_sorting.pyx
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:performance, prio:medium
