Repository cupy/cupy, pull requests merged in 2022-10, with the labels that each got.

#7036 Adds `scipy.special.k0`, `scipy.special.k1`, `scipy.special.k0e`, `scipy.special.k1e`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_gamma.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
Labels: cat:feature, prio:medium

#7070 Add wrapper for `cutensorPermutation`
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/stub/cupy_cutensor.h
Labels: cat:enhancement, to-be-backported, prio:medium

#7081 Fix bessel test to pass ROCm CI
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
Labels: cat:bug, blocking, prio:high

#7084 Bump version to v12.0.0a2
  cupy/_version.py
  install/universal_pkg/setup.py
Labels: cat:install

#7085 Bump version to v11.2.0
  cupy/_version.py
  install/universal_pkg/setup.py
Labels: cat:install

#7087 Bump Dockerfile version to v12.0.0a2
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#7090 Support force-overwriting Docker image via workflow
  .github/workflows/docker.yml
Labels: cat:install

#7091 [backport] Support force-overwriting Docker image via workflow
  .github/workflows/docker.yml
Labels: cat:install, backport

#7051 Allow randint to support array bounds
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:enhancement

#6874 Make sure that cupy (array-api) Array objects can be composed using asarray
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pyx
  tests/cupy_tests/array_api_tests/test_creation_functions.py
Labels: cat:bug, to-be-backported, prio:high

#7076 JIT: Fix compile error for `op.routine` including `in0_type`
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug, to-be-backported, prio:high

#7096 [backport] JIT: Fix compile error for `op.routine` including `in0_type`
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug, backport, prio:high

#7095 [backport] Make sure that cupy (array-api) Array objects can be composed using asarray
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/core.pyx
  tests/cupy_tests/array_api_tests/test_creation_functions.py
Labels: cat:bug, backport, prio:high

#7083 [backport] Add wrapper for `cutensorPermutation`
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/stub/cupy_cutensor.h
Labels: cat:enhancement, backport, prio:medium

#7055 [backport] Make sure weibull distribution support ndarrays
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:bug, backport, prio:high

#7077 Support `add.at`, `maximum.at`, `minimum.at`
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_indexing.pxd
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pyx
  cupy/_math/misc.py
  tests/cupy_tests/core_tests/test_ufunc_methods.py
Labels: cat:feature, prio:high

#6797 add `axis` to `cupy.logspace`
  cupy/_creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
Labels: cat:feature, prio:medium

#6989 Don't use `__del__` in `TCPStore`
  cupyx/distributed/_store.py
Labels: cat:bug, to-be-backported, prio:medium

#7103 Docs: Add missing functions
  docs/source/reference/ufunc.rst
Labels: cat:document, to-be-backported, prio:medium

#7112 [backport] Docs: Add missing functions
  docs/source/reference/ufunc.rst
Labels: cat:document, backport, prio:medium

#7104 Docs: ufunc methods
  docs/source/reference/ufunc.rst
Labels: cat:document, prio:medium

#7111 [backport] Don't use `__del__` in `TCPStore`
  cupyx/distributed/_store.py
Labels: cat:bug, backport, prio:medium

#7105 Add `ufunc.reduce` and `ufunc.accumulate`
  cupy/_core/_kernel.pyx
  tests/cupy_tests/core_tests/test_ufunc_methods.py
Labels: cat:feature, prio:medium

#7099 Support `subtract.at`, `bitwise_and.at`, `bitwise_or.at`, `bitwise_xor.at`
  cupy/_core/_routines_binary.pyx
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_math.pyx
  tests/cupy_tests/core_tests/test_ufunc_methods.py
Labels: cat:feature, prio:high

#7078 Add pdist implementation to distance functions
  cupyx/scipy/spatial/distance.py
  docs/source/reference/scipy_spatial_distance.rst
  tests/cupyx_tests/scipy_tests/spatial_tests/test_distance.py
Labels: cat:feature, prio:medium

#7097 Deprecate `ndarray.scatter_{add, max, min}`
  cupy/_core/core.pyx
  cupyx/scipy/sparse/_compressed.py
  tests/cupy_tests/core_tests/test_ndarray_scatter.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/test_scatter.py
Labels: cat:enhancement, no-compat, prio:medium

#7124 CI: Add ROCm 5.3
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/linux/tests/rocm-5-2.sh
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/linux/tests/rocm-5-3.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:high

#7125 [backport] CI: Add ROCm 5.3
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-5-2.Dockerfile
  .pfnci/linux/tests/rocm-5-2.sh
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/linux/tests/rocm-5-3.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, backport, prio:high

#7116 Remove `_ufunc_method` directory
  cupy/_core/_kernel.pyx
  cupy/_ufunc_method/__init__.py
  cupy/_ufunc_method/outer.py
Labels: prio:high, cat:code-fix

#7122 Fix compile error from `inf`/`nan` in cupy.fuse
  cupy/_core/_scalar.pxd
  cupy/_core/_scalar.pyx
  cupy/_core/core.pyx
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Labels: cat:enhancement, prio:medium

#7113 Fusion `TypeError` in `cupy._core.fusion._call_ufunc()`
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
Labels: cat:bug, to-be-backported, prio:high

#7126 CI: Allow `/test jenkins` to trigger Jenkins only
  .github/workflows/flexci.yml
  .github/workflows/flexci_dispatcher.py
Labels: cat:test, to-be-backported, prio:medium

#7129 [backport] CI: Allow `/test jenkins` to trigger Jenkins only
  .github/workflows/flexci.yml
  .github/workflows/flexci_dispatcher.py
Labels: cat:test, backport, prio:medium

#7128 [backport] Fix compile error from `inf`/`nan` in cupy.fuse
  cupy/_core/_scalar.pxd
  cupy/_core/_scalar.pyx
  cupy/_core/core.pyx
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Labels: cat:enhancement, backport, prio:medium

#7130 [backport] Fusion `TypeError` in `cupy._core.fusion._call_ufunc()`
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
Labels: cat:bug, backport, prio:high

#7115 Add `cupy.add.reduceat`
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_indexing.pxd
  cupy/_core/_routines_indexing.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  docs/source/reference/ufunc.rst
  tests/cupy_tests/core_tests/test_ufunc_methods.py
Labels: cat:feature, prio:high

#7132 [backport] CI: use pre-commit in GitHub Actions
  .github/workflows/pretest.yml
  .pfnci/generate.py
  .pfnci/trim_cupy_kernel_cache.py
  .pre-commit-config.yaml
  setup.py
Labels: cat:other, backport, prio:medium

#7054 Support `thrust::count, device` in CuPy JIT
  cupy/_core/include/cupy/carray.cuh
  cupy/_core/include/cupy/pair.cuh
  cupy/_core/include/cupy/tuple/pair.h
  cupy/_core/include/cupy/tuple/tuple.h
  cupy/_core/include/cupy/tuple/type_traits.h
  cupy/_functional/vectorize.py
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_interface.py
  cupyx/jit/_internal_types.py
  cupyx/jit/cg.py
  cupyx/jit/thrust.py
  tests/cupyx_tests/jit_tests/test_thrust.py
Labels: cat:feature, prio:medium

#7137 Install zlib for CUDA 11.8 Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test

#7138 [backport] Install zlib for CUDA 11.8 Windows CI
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#7136 Implement `cupy.min_scalar_type`
  cupy/__init__.py
  cupy/_core/core.pyx
  docs/source/reference/dtype.rst
  tests/cupy_tests/core_tests/test_core.py
Labels: cat:feature, prio:medium

#7119 Add CUDA 11.8 on documents
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:high

#7147 Fix for pytest 7.2
  setup.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/testing_tests/test_parameterized.py
Labels: cat:test, to-be-backported, prio:medium

#7143 Fix indexing sparse matrix with empty index arguments
  cupyx/scipy/sparse/_compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: to-be-backported, cat:numpy-compat, prio:high
