Repository cupy/cupy, pull requests merged in 2022-05, with the labels that each got.

#6708 CI: Update repo for libcudnn7 in cuda10.2
  .pfnci/generate.py
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
Labels: cat:test, to-be-backported, prio:high

#6710 Bump pinned mypy version
  .github/workflows/pretest.yml
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  setup.py
Labels: cat:test, prio:high

#6701 Accelerate `bincount`, `histogram2d`, `histogramdd` with CUB
  cupy/_statistics/histogram.py
  cupy/cuda/cub.pyx
  cupy/cuda/cupy_cub.cu
  cupy/cuda/cupy_cub.h
Labels: cat:performance, prio:medium

#6706 Minor improvement on the array API docs
  docs/source/conf.py
  docs/source/reference/array_api.rst
  docs/source/user_guide/difference.rst
Labels: cat:document, to-be-backported, prio:medium

#6711 [v10] Pin mypy version in setup.py
  .github/workflows/pretest.yml
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  setup.py
Labels: cat:test, prio:high

#6709 [backport] CI: Update repo for libcudnn7 in cuda10.2
  .pfnci/generate.py
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
Labels: cat:test, backport, prio:high

#6696 Fix imports of `scatter_add` example
  cupyx/_scatter.py
Labels: cat:document, prio:medium

#6670 JIT: Use C++14
  cupy/_functional/vectorize.py
  cupyx/jit/_interface.py
Labels: cat:enhancement, prio:medium

#6714 [backport] Minor improvement on the array API docs
  docs/source/conf.py
  docs/source/reference/array_api.rst
  docs/source/user_guide/difference.rst
Labels: cat:document, backport, prio:medium

#6665 Support cuTENSOR 1.5.0
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/cupy_cutensor.h
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/cupy_cutensor.h
  cupy_backends/stub/cupy_cutensor.h
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#6697 Add `cupy.poly`
  cupy/__init__.py
  cupy/_math/misc.py
  cupy/lib/_polynomial.pyx
  cupy/lib/_routines_poly.py
  docs/source/reference/polynomials.rst
  tests/cupy_tests/lib_tests/test_polynomial.py
Labels: cat:feature, takeover, prio:medium

#6677 Support cuTensorNet (from cuQuantum) as an `einsum` backend
  cupy/_core/_accelerator.pxd
  cupy/_core/_accelerator.pyx
  cupy/linalg/_einsum.py
  cupy/linalg/_einsum_cutn.py
  docs/source/conf.py
  docs/source/reference/environment.rst
Labels: cat:feature, prio:medium

#6644 JIT: Cosmetic change of `Dim3` class
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_interface.py
  cupyx/jit/_internal_types.py
  cupyx/jit/cg.py
Labels: prio:medium, cat:code-fix

#6722 [backport] Support cuTENSOR 1.5.0
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/cupy_cutensor.h
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/cupy_cutensor.h
  cupy_backends/stub/cupy_cutensor.h
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#6718 Use exposed name in user guide
  docs/source/user_guide/difference.rst
Labels: cat:document, prio:high

#6727 Follow scipy==1.8.1 sparse dot bugfix
  cupyx/scipy/sparse/_base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: to-be-backported

#6716 Support cupy.ndarray subclassing - Part 1 - Direct constructor call
  cupy/_core/__init__.py
  cupy/_core/_fusion_trace.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_sorting.pyx
  cupy/_core/core.pyx
  cupy/_core/dlpack.pyx
  cupy/cuda/cub.pyx
  cupy/cudnn.pyx
  cupy/random/_generator_api.pyx
  tests/cupy_tests/core_tests/test_core.py
  tests/cupy_tests/core_tests/test_ndarray.py
Labels: cat:feature, prio:high

#6704 Fix memory leak in the FFT plan cache during multi-threading
  cupy/fft/_cache.pyx
Labels: cat:bug, to-be-backported, prio:high

#6603 Xfail a test of LOBPCG on ROCm 5.0+
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, to-be-backported, prio:high

#6728 [backport] Follow scipy==1.8.1 sparse dot bugfix
  cupyx/scipy/sparse/base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:test, backport

#6641 Support cuDNN 8.4
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#6731 Support testing CUDA 11.6+ in FlexCI
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:medium

#6737 [backport] Support testing CUDA 11.6+ in FlexCI
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:medium

#6735 Drop support for NumPy 1.18/1.19 and SciPy 1.4/1.5 in CuPy v11
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, no-compat, blocking

#6739 Fix compilation warning caused by ifdef
  cupy/_core/include/cupy/carray.cuh
Labels: cat:enhancement, to-be-backported, prio:high

#6738 Fix GPG key issue in FlexCI base image
  .pfnci/linux/main-flexci.sh
Labels: cat:test, to-be-backported, prio:high

#6743 [backport] Fix GPG key issue in FlexCI base image
  .pfnci/linux/main-flexci.sh
Labels: cat:test, backport, prio:high

#6741 [backport] Support cuDNN 8.4
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#6732 [backport] Fix memory leak in the FFT plan cache during multi-threading
  cupy/fft/_cache.pyx
Labels: cat:bug, backport, prio:high

#6740 [backport] Fix compilation warning caused by ifdef
  cupy/_core/include/cupy/carray.cuh
Labels: cat:enhancement, backport, prio:high

#6742 [backport] Document the returned benchmark object
  cupyx/profiler/_time.py
  cupyx/time.py
  docs/source/reference/perf_result.rst
Labels: cat:document, backport, prio:medium

#6750 Fix ifdef for ROCm >= 4.2
  cupy/_core/include/cupy/carray.cuh
Labels: cat:bug, blocking, prio:high

#6751 [backport] Fix ifdef for ROCm >= 4.2
  cupy/_core/include/cupy/carray.cuh
Labels: cat:bug, backport, blocking, prio:high

#6734 Drop support for ROCm 4.2 in CuPy v11
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-4-2.Dockerfile
  .pfnci/linux/tests/rocm-4-2.sh
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  README.md
  docs/source/install.rst
Labels: cat:enhancement, no-compat, blocking

#6676 [v10] Skip `ndimage.filter` tests for ROCm 4.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:test, prio:medium, hip

#6582 add `cupy.setxor1d` api
  cupy/__init__.py
  cupy/_logic/truth.py
  docs/source/reference/set.rst
  tests/cupy_tests/logic_tests/test_truth.py
Labels: cat:feature, prio:medium
