Repository cupy/cupy, pull requests merged in 2022-09, with the labels that each got.

#7030 Bump Dockerfile version to v11.0.0a1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install, prio:high

#7031 Bump Dockerfile version to v11.1.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install, prio:high

#7015 Add `cupy.byte_bounds`
  cupy/__init__.py
  cupy/_misc/byte_bounds.py
  docs/source/reference/misc.rst
  tests/cupy_tests/misc_tests/test_byte_bounds.py
Labels: cat:feature, prio:medium

#7024 CI: Create a status for FlexCI dashboard
  .github/workflows/flexci_dispatcher.py
Labels: cat:test, to-be-backported, prio:medium

#6990 [interpolate] add `cupyx.scipy.interpolate.KroghInterpolator`
  cupyx/scipy/_lib/_util.py
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_polyint.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
Labels: cat:feature, prio:medium

#7034 [backport] CI: Create a status for FlexCI dashboard
  .github/workflows/flexci_dispatcher.py
Labels: cat:test, backport, prio:medium

#6998 Fixes docstring for interpolation prefiltering
  cupyx/scipy/ndimage/_interpolation.py
Labels: cat:document, to-be-backported, prio:medium

#6773 [special] add `cupyx.scipy.special.logsumexp`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_logsumexp.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
Labels: cat:feature, prio:medium

#7037 [backport] Fixes docstring for interpolation prefiltering
  cupyx/scipy/ndimage/_interpolation.py
Labels: cat:document, backport, prio:medium

#7014 Add `scipy.special.expi` and `scipy.special.exp1`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_exp1.py
  cupyx/scipy/special/_expi.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_exp1.py
  tests/cupyx_tests/scipy_tests/special_tests/test_expi.py
Labels: cat:feature, prio:medium

#7039 Fix `csrsm2` memory leak
  cupy/cusparse.py
Labels: cat:bug, to-be-backported, prio:high

#6948 Fix JIT for scalar argument
  cupyx/jit/_interface.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:bug, to-be-backported, prio:high

#7041 [backport] Fix `csrsm2` memory leak
  cupy/cusparse.py
Labels: cat:bug, backport, prio:high

#7043 [backport] Fix JIT for scalar argument
  cupyx/jit/_interface.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:bug, backport, prio:high

#7045 Typo fix
  docs/source/reference/array_api_array.rst
Labels: cat:document, to-be-backported, prio:medium

#7048 Make sure weibull distribution support ndarrays
  cupy/random/_generator.py
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:bug, to-be-backported, prio:high

#7049 Add `ufunc.outer`
  cupy/_core/_kernel.pyx
  cupy/_ufunc_method/__init__.py
  cupy/_ufunc_method/outer.py
  tests/cupy_tests/core_tests/test_ufunc_methods.py
Labels: cat:feature, prio:medium

#7053 Cosmetic change in _routine_indexing.pyx
  cupy/_core/_routines_indexing.pyx
Labels: to-be-backported, prio:medium, cat:code-fix

#6976 Make sparse argmin/max return a scalar array containing the index
  cupyx/scipy/sparse/_data.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:bug, to-be-backported, prio:high

#7056 [backport] Cosmetic change in _routine_indexing.pyx
  cupy/_core/_routines_indexing.pyx
Labels: backport, prio:medium, cat:code-fix

#7047 [backport] Typo fix
  docs/source/reference/array_api_array.rst
Labels: cat:document, backport, prio:medium

#7057 [backport] Make sparse argmin/max return a scalar array containing the index
  cupyx/scipy/sparse/_data.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:bug, backport, prio:high

#7064 CI: Migrate to GAR from GCR
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
Labels: cat:test, to-be-backported, prio:high

#7066 [backport] CI: Migrate to GAR from GCR
  .pfnci/linux/main-flexci-prep.sh
  .pfnci/linux/main-flexci.sh
  .pfnci/linux/run.sh
Labels: cat:test, backport, prio:high

#6987 [RFC] Introduce pre-commit
  .flake8.cython
  .pre-commit-config.yaml
  setup.cfg
Labels: cat:other, to-be-backported, prio:medium

#7067 [backport] [RFC] Introduce pre-commit
  .flake8.cython
  .pre-commit-config.yaml
  setup.cfg
Labels: cat:other, backport, prio:medium

#6534 Support NCCL 2.12 ~ 2.14
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#7009 [backport] Remove use of `distutils.utils`
  install/cupy_builder/install_build.py
Labels: cat:install, backport, prio:medium

#7008 Support cuDNN 8.5
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:medium

#7069 [backport] Support NCCL 2.12 ~ 2.14
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#7071 [backport] Support cuDNN 8.5
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/tools/install_library.py
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:medium

#7068 Fix `cupy.apply_along_axis` for tuple retval
  cupy/lib/_shape_base.py
  tests/cupy_tests/lib_tests/test_shape_base.py
Labels: cat:enhancement, prio:medium

#7063 Expose pairwise distance functions
  cupyx/scipy/spatial/distance.py
  docs/source/reference/scipy_spatial_distance.rst
  tests/cupyx_tests/scipy_tests/spatial_tests/test_distance.py
Labels: cat:feature, prio:medium

#7072 CI: tentatively fix hypothesis version
  setup.py
Labels: cat:test, to-be-backported, prio:high, array-api
