Repository cupy/cupy, pull requests merged in 2022-11, with the labels that each got.

#7149 [backport] Fix for pytest 7.2
  setup.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/testing_tests/test_parameterized.py
Labels: cat:test, backport, prio:medium

#7148 [backport] Add CUDA 11.8 on documents
  docs/source/install.rst
Labels: cat:enhancement, backport, prio:high

#7133 Raise `TypeError` instead of `ValueError` in `cupy.from_dlpack` when CPU tensor is passed
  cupy/_core/dlpack.pyx
Labels: cat:enhancement, no-compat, prio:medium

#7139 JIT: Support more thrust functions
  cupy/_core/include/cupy/carray.cuh
  cupyx/jit/_cuda_types.py
  cupyx/jit/thrust.py
  tests/cupyx_tests/jit_tests/test_thrust.py
Labels: cat:feature, prio:medium

#7141 CI: improve use of cache in GitHub Actions
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported, prio:medium

#7156 [backport] CI: improve use of cache in GitHub Actions
  .github/workflows/pretest.yml
Labels: cat:test, backport, prio:medium

#7155 [backport] Fix indexing sparse matrix with empty index arguments
  cupyx/scipy/sparse/_compressed.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: backport, cat:numpy-compat, prio:high

#7153 Support NCCL 2.15
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:high

#7100 Support CUDA 11.8 H100 GPUs
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/include/cupy/cuda_workaround.h
  cupy/cuda/compiler.py
  cupy/fft/_callback.pyx
  cupy_backends/cuda/cupy_cublas.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/stub/cupy_cublas.h
  install/cupy_builder/_compiler.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, to-be-backported, prio:high

#7162 JIT: Skip HIP `thrust::sort` test
  tests/cupyx_tests/jit_tests/test_thrust.py
Labels: cat:test, to-be-backported, prio:medium

#7160 [backport] Support NCCL 2.15
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:high

#7161 CI: Add support for the latest FlexCI Windows image
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, blocking, prio:high

#7167 JIT: Fix compile error of minmax function
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug, to-be-backported, prio:high

#7163 Fix a typo
  cupy/cusparse.py
Labels: cat:bug, blocking, prio:high

#7170 Add missing base type to cdef declarations
  cupy/random/_generator_api.pyx
  cupyx/cudnn.pyx
Labels: prio:medium, cat:code-fix

#7169 [backport] Support CUDA 11.8 H100 GPUs
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/include/cupy/cuda_workaround.h
  cupy/cuda/compiler.py
  cupy/fft/_callback.pyx
  cupy_backends/cuda/cupy_cublas.h
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/stub/cupy_cublas.h
  install/cupy_builder/_compiler.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, backport, prio:high

#7172 [backport] CI: Add support for the latest FlexCI Windows image
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, backport, blocking, prio:high

#7174 [backport] JIT: Fix compile error of minmax function
  cupyx/jit/_compile.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:bug, backport, prio:high

#7176 Improve benchmark documentation
  cupyx/profiler/_time.py
Labels: cat:document, prio:medium

#7159 Support Python 3.11
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
  setup.py
  tests/cupy_tests/io_tests/test_formatting.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupyx_tests/profiler_tests/test_profile.py
Labels: cat:enhancement, to-be-backported, blocking, prio:medium

#7181 Bump version to v12.0.0b1
  cupy/_version.py
  install/universal_pkg/setup.py
Labels: cat:install

#7182 Bump version to v11.3.0
  cupy/_version.py
  install/universal_pkg/setup.py
Labels: cat:install

#7184 Bump Dockerfile version to v11.3.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#7145 JIT: Support `cub::WarpReduce` and `cub::BlockReduce`
  cupyx/jit/__init__.py
  cupyx/jit/_builtin_funcs.py
  cupyx/jit/_compile.py
  cupyx/jit/_cuda_typerules.py
  cupyx/jit/_cuda_types.py
  cupyx/jit/_internal_types.py
  cupyx/jit/cub.py
  tests/cupyx_tests/jit_tests/test_cub.py
Labels: cat:feature, prio:medium

#7175 CI: Generate coverage count just after the parameter axis in table
  .pfnci/coverage.rst
  .pfnci/generate.py
Labels: cat:test, to-be-backported, prio:low

#7188 [backport] CI: Generate coverage count just after the parameter axis in table
  .pfnci/coverage.rst
  .pfnci/generate.py
Labels: cat:test, backport, prio:low

#7152 Improve `_PerfCaseResult.to_str` format
  cupyx/profiler/_time.py
  tests/cupyx_tests/profiler_tests/test_benchmark.py
  tests/cupyx_tests/test_time.py
Labels: cat:enhancement, prio:low

#7178 Fix 1-dim lexsort
  cupy/_sorting/sort.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:bug, no-compat, to-be-backported, prio:high

#7191 [backport] Fix 1-dim lexsort
  cupy/_sorting/sort.py
  tests/cupy_tests/sorting_tests/test_sort.py
Labels: cat:bug, no-compat, backport, prio:high

#7194 Fix wrong argument in warnings.warn()
  cupy/_core/core.pyx
Labels: cat:bug, to-be-backported, prio:medium

#7052 Use cuSPARSE Generic API instead of older one documented to be removed
  cupy_backends/cuda/cupy_cusparse.h
  cupy_backends/cuda/libs/cusparse.pxd
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/hip/cupy_hipsparse.h
  cupy_backends/stub/cupy_cusparse.h
  cupyx/cusparse.py
  cupyx/scipy/sparse/_csc.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
  tests/cupyx_tests/test_cusparse.py
Labels: cat:enhancement, to-be-backported, prio:high

#7192 Fix cupyx.scipy.ndimage.zoom for outputs of size 1 when mode is 'opencv'
  cupyx/scipy/ndimage/_interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, to-be-backported, prio:high

#7173 Split inputs to random routines
  cupy/random/_generator_api.pyx
Labels: cat:bug, to-be-backported, prio:high

#7207 [backport] Split inputs to random routines
  cupy/random/_generator_api.pyx
Labels: cat:bug, backport, prio:high

#7086 Add 1-D BSpline to interpolate module
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_bspline.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline.py
Labels: cat:feature, prio:medium

#7203 Use list(kwargs) instead of list(kwargs.keys)
  cupy/linalg/_einsum.py
Labels: cat:bug, to-be-backported, prio:high

#7213 [backport] Use list(kwargs) instead of list(kwargs.keys)
  cupy/linalg/_einsum.py
Labels: cat:bug, backport, prio:high

#7215 Expose splder and splantider
  cupyx/scipy/interpolate/__init__.py
  docs/source/reference/scipy_interpolate.rst
Labels: cat:feature, prio:medium

#7202 [backport] Fix cupyx.scipy.ndimage.zoom for outputs of size 1 when mode is 'opencv'
  cupyx/scipy/ndimage/_interpolation.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Labels: cat:bug, backport, prio:high

#7190 Add `cupyx.scipy.interpolate.RBFInterpolator`
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_rbfinterp.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
Labels: cat:feature, prio:medium
