Repository cupy/cupy, pull requests merged in 2023-12, with the labels that each got.

#7994 Softlink CUDA Driver
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_driver_typedef.pxi
  cupy_backends/cuda/api/_runtime_typedef.pxi
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/cupy_cuda.h
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/cuda/libs/nccl.pyx
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/stub/cupy_cuda.h
  cupy_backends/stub/cupy_cuda_common.h
  install/cupy_builder/_features.py
Labels: cat:enhancement, blocking, prio:high

#8015 Bump version to v13.0.0rc1
  cupy/_version.py
Labels: cat:other, prio:medium

#8016 [v12] Bump version to v12.3.0
  cupy/_version.py
  install/universal_pkg/setup.py
Labels: cat:other, prio:medium

#8023 [backport] Add upgrade guide for v13
  docs/source/upgrade.rst
Labels: cat:document, backport

#8026 [v13] Bump stable branch to v13
  .pfnci/BRANCH
  .pfnci/BRANCH_STABLE
Labels: cat:test

#8024 Bump stable branch to v13
  .pfnci/BRANCH_STABLE
Labels: cat:test, prio:medium

#8010 Support for break and continue keywords
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, prio:medium

#8034 Fix lfilter_zi and sosfilt_zi when any IIR coefficient is zero
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:bug, to-be-backported, prio:high

#8031 Fix argmax/argmin for large reduction axis
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_fusion_op.py
  cupy/_core/_kernel.pxd
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_statistics.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, to-be-backported, prio:high

#8017 Speed up cupy environment duplicate detection
  cupy/_environment.py
Labels: to-be-backported, cat:performance, prio:medium

#6137 Generate signature for ufunc documentation
  cupy/__init__.py
  cupy/_core/_kernel.pyx
  docs/source/conf.py
Labels: cat:document, to-be-backported, prio:medium

#8039 [backport] Add `cupyx.signal.pulse_compression` from cuSignal's non SciPy-compat API
  cupyx/signal/__init__.py
  cupyx/signal/radartools/__init__.py
  cupyx/signal/radartools/_radartools.py
  docs/source/reference/ext.rst
  tests/cupyx_tests/signal_tests/__init__.py
  tests/cupyx_tests/signal_tests/radartools_tests/__init__.py
  tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Labels: cat:feature, backport, prio:medium

#8036 [backport] Fix lfilter_zi and sosfilt_zi when any IIR coefficient is zero
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:bug, backport, prio:high

#7988 Use modern dlpack interface in torch interoperability document
  docs/source/user_guide/interoperability.rst
Labels: cat:document, to-be-backported, prio:medium

#8048 [backport] Use modern dlpack interface in torch interoperability document
  docs/source/user_guide/interoperability.rst
Labels: cat:document, backport, prio:medium

#8004 Add a note on accelerating CI/CD
  docs/source/user_guide/performance.rst
Labels: cat:document, prio:medium

#8025 Update Compatibility Matrix
  docs/source/upgrade.rst
Labels: cat:test, prio:medium

#8041 [backport] Fix argmax/argmin for large reduction axis
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_fusion_op.py
  cupy/_core/_kernel.pxd
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_statistics.pyx
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, backport, prio:high

#8042 [backport] Speed up cupy environment duplicate detection
  cupy/_environment.py
Labels: backport, cat:performance, prio:medium

#8044 [backport] Generate signature for ufunc documentation
  cupy/__init__.py
  cupy/_core/_kernel.pyx
  docs/source/conf.py
Labels: cat:document, backport, prio:medium

#8053 [backport] Make `cupyx.signal.radartools` private
  cupyx/signal/__init__.py
  cupyx/signal/_radartools/__init__.py
  cupyx/signal/_radartools/_radartools.py
  cupyx/signal/radartools/__init__.py
Labels: cat:enhancement, backport, prio:medium

#8037 Add `cupyx.signal.convolve1d3o` from cuSignal's non SciPy-compat API
  cupyx/signal/__init__.py
  cupyx/signal/_convolution/__init__.py
  cupyx/signal/_convolution/_convolution_utils.py
  cupyx/signal/_convolution/_convolve.py
  docs/source/reference/ext.rst
  tests/cupyx_tests/signal_tests/convolution_tests/__init__.py
  tests/cupyx_tests/signal_tests/convolution_tests/test_convolve.py
Labels: cat:feature, to-be-backported, prio:medium

#8067 [backport] Add `cupyx.signal.convolve1d3o` from cuSignal's non SciPy-compat API
  cupyx/signal/__init__.py
  cupyx/signal/_convolution/__init__.py
  cupyx/signal/_convolution/_convolution_utils.py
  cupyx/signal/_convolution/_convolve.py
  docs/source/reference/ext.rst
  tests/cupyx_tests/signal_tests/convolution_tests/__init__.py
  tests/cupyx_tests/signal_tests/convolution_tests/test_convolve.py
Labels: cat:feature, backport, prio:medium

#8057 add `cupyx.signal.{pulse_doppler, cfar_alpha}`
  cupyx/signal/__init__.py
  cupyx/signal/_radartools/__init__.py
  cupyx/signal/_radartools/_radartools.py
  tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Labels: cat:feature, to-be-backported, prio:medium

#8069 [backport] add `cupyx.signal.{pulse_doppler, cfar_alpha}`
  cupyx/signal/__init__.py
  cupyx/signal/_radartools/__init__.py
  cupyx/signal/_radartools/_radartools.py
  tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Labels: cat:feature, backport, prio:medium
