Repository cupy/cupy, pull requests merged in 2023-06, with the labels that each got.

#7594 update badges
  README.md
Labels: cat:document, to-be-backported, prio:medium

#7600 [backport] update badges
  README.md
Labels: cat:document, backport, prio:medium

#7601 Fix command in issue template for Windows
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cat:other

#7602 Fix flake8-cython not working
  .flake8.cython
  .pre-commit-config.yaml
  cupy/_core/core.pyx
Labels: cat:other, to-be-backported, prio:high

#7606 [backport] Fix flake8-cython not working
  .flake8.cython
  .pre-commit-config.yaml
  cupy/_core/core.pyx
Labels: cat:other, backport, prio:high

#7487 Let the user specify a starting vector for eigsh.
  cupyx/scipy/sparse/linalg/_eigen.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, prio:medium

#7413 Add Euclidean distance transform (scipy.ndimage.distance_transform_edt)
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/_distance_transform.py
  cupyx/scipy/ndimage/_pba_2d.py
  cupyx/scipy/ndimage/_pba_3d.py
  cupyx/scipy/ndimage/cuda/LICENSE
  cupyx/scipy/ndimage/cuda/pba_kernels_2d.h
  cupyx/scipy/ndimage/cuda/pba_kernels_3d.h
  docs/source/reference/scipy_ndimage.rst
  setup.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_distance_transform.py
Labels: cat:feature, prio:medium

#7410 Add cupyx.scipy.ndimage.value_indices
  cupyx/scipy/ndimage/__init__.py
  cupyx/scipy/ndimage/_measurements.py
  docs/source/reference/scipy_ndimage.rst
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Labels: cat:feature, prio:medium

#7508 Introduce `cython-lint`
  .pre-commit-config.yaml
  cupy/_core/_carray.pyx
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/_memory_range.pyx
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_binary.pyx
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pyx
  cupy/_core/dlpack.pyx
  cupy/_core/fusion.pyx
  cupy/_core/internal.pyx
  cupy/_core/new_fusion.pyx
  cupy/_core/raw.pyx
  cupy/_util.pyx
  cupy/cuda/cub.pyx
  cupy/cuda/cufft.pyx
  cupy/cuda/function.pyx
  cupy/cuda/jitify.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  cupy/cuda/texture.pyx
  cupy/cuda/thrust.pyx
  cupy/fft/_cache.pyx
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupyx/cudnn.pyx
  cupyx/cusolver.pyx
  cupyx/cutensor.pyx
Labels: to-be-backported, prio:medium, cat:code-fix

#7610 Fix build-cuda test `restore-keys` not working
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported

#7543 cupyx.scipy.signal: add CZT and ZoomFFT
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_czt.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_czt.py
Labels: cat:feature, prio:medium

#7552 Add sosfilt_zi to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7612 [backport] Introduce `cython-lint`
  .pre-commit-config.yaml
  cupy/_core/_carray.pyx
  cupy/_core/_cub_reduction.pyx
  cupy/_core/_fusion_kernel.pyx
  cupy/_core/_kernel.pyx
  cupy/_core/_memory_range.pyx
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_binary.pyx
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_linalg.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/core.pyx
  cupy/_core/dlpack.pyx
  cupy/_core/fusion.pyx
  cupy/_core/internal.pyx
  cupy/_core/new_fusion.pyx
  cupy/_core/raw.pyx
  cupy/_util.pyx
  cupy/cuda/cub.pyx
  cupy/cuda/cufft.pyx
  cupy/cuda/function.pyx
  cupy/cuda/jitify.pyx
  cupy/cuda/memory.pyx
  cupy/cuda/stream.pyx
  cupy/cuda/texture.pyx
  cupy/cuda/thrust.pyx
  cupy/fft/_cache.pyx
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/nvrtc.pyx
  cupyx/cudnn.pyx
  cupyx/cusolver.pyx
  cupyx/cutensor.pyx
Labels: backport, prio:medium, cat:code-fix

#7614 [backport] Fix build-cuda test `restore-keys` not working
  .github/workflows/pretest.yml
Labels: cat:test, backport

#7613 Fix returned CUDA statuses not being checked
  cupy/_core/new_fusion.pyx
  cupy/_core/raw.pyx
  cupy/cuda/cufft.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
Labels: cat:bug, to-be-backported, prio:high

#7618 [backport] Fix returned CUDA statuses not being checked
  cupy/_core/new_fusion.pyx
  cupy/_core/raw.pyx
  cupy/cuda/cufft.pyx
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/cuda/libs/cudnn.pyx
Labels: cat:bug, backport, prio:high

#7607 ENH: cupyx.scipy.signal: add hilbert and hilbert2
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7597 Fix `cupy-wheel` package installation fails with pip 23.1+
  install/universal_pkg/setup.py
Labels: cat:install, to-be-backported, prio:high

#7558 Add sosfiltfilt to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7591 add iirfilter and related filter design functions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_iir_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py
Labels: cat:feature, prio:medium

#7608 cupy.kron can accept numeric arguments, replicating numpy.kron behavior
  cupy/linalg/_product.py
  tests/cupy_tests/linalg_tests/test_product.py
Labels: cat:enhancement, prio:medium

#7619 Fix `hilbert` and `hilbert2` test condition
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, prio:medium

#7626 Change test pass condition for TestChoiceChi::test_goodness_of_fit
  tests/cupy_tests/random_tests/test_generator.py
Labels: cat:test, prio:medium

#7625 [hotfix] [backport] Fix `cupy-wheel` package installation fails with pip 23.1+
  install/universal_pkg/setup.py
Labels: cat:install, backport, prio:high

#7622 Avoid overflow warnings in test_astype_strides
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:numpy-compat, prio:medium

#7623 Deprecate `cupy.round_`
  cupy/__init__.py
  cupy/_math/rounding.py
  cupyx/scipy/special/__init__.py
  tests/cupy_tests/core_tests/fusion_tests/test_routines.py
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py
Labels: cat:numpy-compat, prio:medium

#7631 Add workflow to automatically updating Pull-Request dashboard project
  .github/workflows/pr-project.yml
  .github/workflows/pr-updated.yml
Labels: cat:other, prio:medium

#7507 Add `cupy.scipy.linalg.bandwidth` functionality
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/_array_utils.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_array_utils.py
Labels: cat:feature, prio:medium

#7637 ENH: cupyx/scipy/signal: add abcd_normalize
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_lti_conversion.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
Labels: cat:feature, prio:medium

#7650 Do not trigger on closed pull-requests and fix to work with `issue_comment` trigger
  .github/workflows/pr-updated.yml
Labels: cat:other, prio:medium

#7537 ENH: signal: add firls and freqz, freqz_zpk, sosfreqz
  cupy/polynomial/polynomial.py
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_filter_design.py
  cupyx/scipy/signal/_fir_filter_design.py
  docs/source/reference/polynomials.rst
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:feature, prio:medium

#7653 Ignore `pkg_resources` deprecation warning on import
  setup.cfg
Labels: cat:test, to-be-backported, prio:high

#7655 Fix small typos in docstrings
  cupyx/jit/thrust.py
Labels: cat:document, to-be-backported, prio:medium

#7656 [backport] Ignore `pkg_resources` deprecation warning on import
  setup.cfg
Labels: cat:test, backport, prio:high

#7627 cupyx/signal: skip tests against older SciPy versions, adjust test tolerances
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py
Labels: cat:test, prio:medium

#7658 Fix project automation to skip when pull-request is already closed
  .github/workflows/pr-project.yml
  .github/workflows/pr-updated.yml
Labels: cat:other, prio:medium

#7638 ENH: add `cupyx.scipy.signal.minimum_phase`
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_fir_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:feature, prio:medium

#7642 [v12] Require numpy<1.25 for `round_` tests
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py
Labels: cat:test, prio:high

#7657 [backport] Fix small typos in docstrings
  cupyx/jit/thrust.py
Labels: cat:document, backport, prio:medium

#7659 Implement `scipy.linalg.khatri_rao`
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/_matfuncs.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py
Labels: cat:feature, prio:medium

#7644 ENH: cupyx/scipy/signal: add unique_roots, invres{z}, residue{z}
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_polyutils.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/__init__.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_polyutils.py
Labels: cat:feature, prio:medium

#7641 ENH: add cupyx.signal.{freqs, freqs_zpk, findfreqs}
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
Labels: cat:feature, prio:medium

#7669 Skip `TestLOBPCG::test_maxit_None` in CUDA 12.1.1 & cuSOVLER 11.4.5
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, to-be-backported, prio:high

#7645 Deprecate `product`, `cumproduct`, `alltrue` and `sometrue`
  cupy/__init__.py
  cupy/_indexing/insert.py
  cupy/_logic/truth.py
  cupy/_math/sumprod.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: no-compat, cat:numpy-compat

#7670 [backport] Skip `TestLOBPCG::test_maxit_None` in CUDA 12.1.1 & cuSOVLER 11.4.5
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, backport, prio:high

#7647 Deprecate support for out-dated platforms in CuPy v13
  .github/workflows/pretest-rocm-test.sh
  .github/workflows/pretest.yml
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-rapids.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda102.multi.sh
  .pfnci/linux/tests/cuda102.sh
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda110.multi.sh
  .pfnci/linux/tests/cuda110.sh
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda111.multi.sh
  .pfnci/linux/tests/cuda111.sh
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  .readthedocs.yaml
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, no-compat, prio:high
