Repository cupy/cupy, pull requests merged in 2023-09, with the labels that each got.

#7694 Port argrel{extrema, max, min} to cupyx.scipy.signal from cusignal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_peak_finding.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py
Labels: cat:feature, prio:medium

#7840 Remove `cusolver_enabled`, `cub_enabled`, `thrust_enabled` flags
  cupy/cuda/__init__.py
  cupy/cuda/device.pyx
Labels: cat:enhancement, no-compat, prio:medium

#7842 Fix nvrtc initialize not inlined for CUDA Python
  cupy_backends/cuda/libs/nvrtc.pyx
Labels: prio:medium, cat:code-fix

#7844 Fix coding style
  cupy/cuda/texture.pyx
  cupy_backends/cuda/libs/nvrtc.pyx
  tests/cupy_tests/random_tests/common_distributions.py
Labels: to-be-backported, prio:medium, cat:code-fix

#7843 Lazy import cuSOLVER
  .github/workflows/pretest.yml
  cupy/cuda/__init__.py
  cupy/cuda/device.pyx
  cupy/linalg/_decomposition.py
  cupy/linalg/_eigenvalue.py
  cupyx/lapack.py
  cupyx/linalg/sparse/_solve.py
  cupyx/scipy/linalg/_decomp_lu.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:enhancement, blocking, prio:medium

#7846 [backport] Fix coding style
  cupy/cuda/texture.pyx
  tests/cupy_tests/random_tests/common_distributions.py
Labels: backport, prio:medium, cat:code-fix

#7810 [backport] Avoid using `numpy.find_common_type`
  cupy/_indexing/generate.py
  cupyx/scipy/linalg/_special_matrices.py
  cupyx/scipy/sparse/_sputils.py
  cupyx/scipy/sparse/linalg/_interface.py
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: backport, cat:numpy-compat, prio:high

#7815 Fix handling of scalars in cupy.r_
  cupy/_indexing/generate.py
  cupyx/scipy/signal/_splines.py
  tests/cupy_tests/indexing_tests/test_generate.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:bug, prio:high

#7847 Lazy import cuSPARSE
  .github/workflows/pretest.yml
  cupy/cuda/__init__.py
  cupy/cuda/device.pyx
  cupyx/scipy/sparse/_compressed.py
  cupyx/scipy/sparse/_coo.py
  cupyx/scipy/sparse/_csc.py
  cupyx/scipy/sparse/_csr.py
  cupyx/scipy/sparse/_index.py
  cupyx/scipy/sparse/linalg/_eigen.py
  cupyx/scipy/sparse/linalg/_iterative.py
  cupyx/scipy/sparse/linalg/_solve.py
Labels: cat:enhancement, blocking

#7696 Port waveforms from cusignal to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_waveforms.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_waveforms.py
Labels: cat:feature, prio:medium

#7808 [backport] Fix csr2dense to avoid race conditions
  cupyx/scipy/sparse/_csr.py
Labels: cat:bug, backport, prio:high

#7836 Execution tests for typing tests passing rows in `typing_tests`
  .github/workflows/pretest.yml
  tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi
  tests/typing_tests/test_run.py
Labels: cat:test, prio:medium

#7850 Static link to CUDA Runtime in CUB module
  install/cupy_builder/_command.py
  install/cupy_builder/_features.py
  install/cupy_builder/cupy_setup_build.py
Labels: cat:enhancement, blocking, prio:high

#7721 Add 2D signal b-splines to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_bsplines.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_splines.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
Labels: cat:feature, prio:medium

#7775 Add timeout to Windows CI
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:high

#7859 [backport] Add timeout to Windows CI
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#7857 CI: Remove path length limitation on Windows CI image
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:high

#7860 [backport] CI: Remove path length limitation on Windows CI image
  .pfnci/windows/_flexci.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#7861 Avoid triggering Project Updates for updates from assignees
  .github/workflows/pr-updated.yml
Labels: cat:other, prio:medium

#7564 Port periodogram, welch and csd from CuSignal to cupyx.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_arraytools.py
  cupyx/scipy/signal/_spectral.py
  cupyx/scipy/signal/_spectral_impl.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Labels: cat:feature, prio:medium

#7862 Fix Windows CI failures
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:high

#7865 [backport] Fix Windows CI failures
  .pfnci/windows/_error_handler.ps1
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#7675 Add check_{NOLA, COLA} to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_spectral.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Labels: cat:feature, prio:medium

#7849 Lazy import cuFFT
  .github/workflows/pretest.yml
  cupy/fft/_cache.pyx
  cupy/fft/_callback.pyx
  cupy/fft/_fft.py
  cupyx/_runtime.py
  cupyx/scipy/fft/_fft.py
  cupyx/scipy/fftpack/_fft.py
Labels: cat:enhancement, blocking

#7837 Port gauss_spline from CuSignal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_bsplines.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
Labels: cat:feature, prio:medium

#7764 Support boolean COO sparse matrix
  cupyx/cusparse.py
  cupyx/scipy/sparse/_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:feature, prio:medium

#7868 Clarify sparse .transpose() return type in docstrings
  cupyx/scipy/sparse/_csc.py
  cupyx/scipy/sparse/_csr.py
Labels: cat:document, prio:medium

#7700 Port wavelets module from cusignal to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_wavelets.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_wavelets.py
Labels: cat:feature, prio:medium

#7885 Add optional argument `device_id=-1` to `get_current_stream`
  cupy/cuda/stream.pxd
  cupy/cuda/stream.pyx
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:enhancement, prio:medium
