Repository cupy/cupy, pull requests merged in 2023-07, with the labels that each got.

#7682 Bump CUDA minor versions used in CI
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:high

#7683 [backport] Bump CUDA minor versions used in CI
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/schema.yaml
Labels: cat:test, backport, prio:high

#7680 Fix cuSPARSE error message
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/hip/cupy_hipsparse.h
  cupy_backends/stub/cupy_cusparse.h
  tests/cupy_tests/cuda_tests/test_cusparse.py
Labels: cat:bug, to-be-backported, prio:high

#7679 Fix memory pool to try resolve fragmentation when limit is set
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:bug, to-be-backported, prio:high

#7633 Add gammatone, group_delay to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
Labels: cat:feature, prio:medium

#7643 Fix `test_fht` not to feed `cupy.ndarray` to `scipy.fft.fhtoffset`
  tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py
Labels: cat:test, to-be-backported, prio:high

#7685 [backport] Fix memory pool to try resolve fragmentation when limit is set
  cupy/cuda/memory.pyx
  tests/cupy_tests/cuda_tests/test_memory.py
Labels: cat:bug, backport, prio:high

#7684 [backport] Fix cuSPARSE error message
  cupy_backends/cuda/libs/cusparse.pyx
  cupy_backends/hip/cupy_hipsparse.h
  cupy_backends/stub/cupy_cusparse.h
  tests/cupy_tests/cuda_tests/test_cusparse.py
Labels: cat:bug, backport, prio:high

#7692 Fix type/exception annotations in cuSPARSE binding
  cupy_backends/cuda/libs/cusparse.pxd
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:bug, to-be-backported, prio:high

#7693 Update pylibcugraph weakly connected components call
  .pfnci/linux/tests/cuda-rapids.Dockerfile
  cupyx/scipy/sparse/csgraph/_traversal.py
  tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py
Labels: cat:bug, to-be-backported, prio:high

#7704 [backport] Update pylibcugraph weakly connected components call
  .pfnci/config.pbtxt
  .pfnci/linux/tests/cuda-rapids.Dockerfile
  cupyx/scipy/sparse/csgraph/_traversal.py
  tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py
Labels: cat:bug, backport, prio:high

#7689 Allow specifying Docker repository for CI images
  .pfnci/generate.py
  .pfnci/schema.yaml
Labels: cat:test, prio:high

#7690 [v12] Allow specifying Docker repository for CI images
  .pfnci/generate.py
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/schema.yaml
Labels: cat:test, prio:high

#7703 [backport] Fix type/exception annotations in cuSPARSE binding
  cupy_backends/cuda/libs/cusparse.pxd
  cupy_backends/cuda/libs/cusparse.pyx
Labels: cat:bug, backport, prio:high

#7663 Add mixed precision (FP16) support for ROCm
  cupy/_core/_routines_linalg.pyx
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
Labels: cat:enhancement, prio:medium

#7640 Add find_peaks, peak_prominences, peak_widths to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_peak_finding.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py
Labels: cat:feature, prio:medium

#7635 add kaiser{ord,_beta,_atten} functions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_fir_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:feature, prio:medium

#7705 Use "/test" tag configuration from pull-request base branch
  .github/workflows/flexci.yml
Labels: cat:test, to-be-backported, prio:high

#7706 [backport] Use "/test" tag configuration from pull-request base branch
  .github/workflows/flexci.yml
Labels: cat:test, backport, prio:high

#7709 Improve detection for package installation source on Windows
  cupy/_environment.py
Labels: cat:bug, to-be-backported, prio:high

#7711 [backport] Improve detection for package installation source on Windows
  cupy/_environment.py
Labels: cat:bug, backport, prio:high

#7708 Temporarily disable CUB histogram
  cupy/_statistics/histogram.py
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:bug, to-be-backported, prio:high

#7632 cupyx/scipy.signal: port *ord filter design functions from scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_filter_design.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_iir_filter_design.py
  cupyx/scipy/signal/_optimize.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py
Labels: cat:feature, prio:medium

#7701 fix a typo in `cupy.cov`
  cupy/_statistics/correlation.py
Labels: cat:bug, to-be-backported, prio:medium

#7716 [backport] Temporarily disable CUB histogram
  cupy/_statistics/histogram.py
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:bug, backport, prio:high

#7691 Add env var to disable RPATH
  install/cupy_builder/_context.py
Labels: cat:other, to-be-backported, prio:medium

#7707 ENH: cupyx/scipy/signal: add correlation_lags
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7688 XFAIL known test failures in cuSPARSE module
  cupyx/cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/test_cusparse.py
Labels: cat:test, to-be-backported, prio:high

#7725 [backport] XFAIL known test failures in cuSPARSE module
  cupyx/cusparse.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/test_cusparse.py
Labels: cat:test, backport, prio:high

#7729 CI: remove explicit Cython installation
  .github/workflows/pretest-rocm-test.sh
  .github/workflows/pretest.yml
Labels: cat:test, prio:medium

#7723 Minor updates for cuQuantum/cuTensorNet support
  cupy/linalg/_einsum_cutn.py
  docs/source/conf.py
Labels: cat:enhancement, to-be-backported, prio:medium

#7731 [backport] CI: remove explicit Cython installation
  .github/workflows/pretest-rocm-test.sh
  .github/workflows/pretest.yml
Labels: cat:test, backport, prio:medium

#7730 [backport] Minor updates for cuQuantum/cuTensorNet support
  cupy/linalg/_einsum_cutn.py
  docs/source/conf.py
Labels: cat:enhancement, backport, prio:medium

#7734 Remove `cupy.cuda.compile_with_cache`
  cupy/cuda/__init__.py
  cupy/cuda/compiler.py
  tests/cupy_tests/cuda_tests/test_compiler.py
Labels: no-compat, prio:high, cat:code-fix

#7728 [backport] Fix `test_fht` not to feed `cupy.ndarray` to `scipy.fft.fhtoffset`
  tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py
Labels: cat:test, backport, prio:high

#7634 add iir{notch,comb,peak} design functions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_design.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py
Labels: cat:feature, prio:medium

#7652 ENH: cupyx/scipy/signal: add missing LTI format conversions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_polyutils.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
Labels: cat:feature, prio:medium

#7736 [backport] Bump mypy version to 1.4.1
  .pre-commit-config.yaml
  setup.py
Labels: cat:enhancement, backport

#7740 MAINT: centralize np.roots calls
  cupyx/scipy/signal/_filter_design.py
  cupyx/scipy/signal/_polyutils.py
Labels: prio:medium, cat:code-fix

#7738 Cosmetic changes of cupy/typing
  cupy/_core/core.pyx
  cupy/typing/__init__.py
  cupy/typing/_generic_alias.py
  cupy/typing/_types.py
Labels: prio:medium, cat:code-fix

#7745 Remove `cupy-wheel` package
  install/universal_pkg/RELEASE.md
  install/universal_pkg/__init__.py
  install/universal_pkg/setup.py
  tests/install_tests/test_universal_pkg/__init__.py
  tests/install_tests/test_universal_pkg/test_setup.py
Labels: cat:install, blocking, prio:high

#7748 Support CUDA 12.2
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda122.multi.sh
  .pfnci/linux/tests/cuda122.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  .pfnci/windows/_flexci.ps1
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-10.2/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-10.2/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-11.1/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-11.1/cuda_fp16.hpp
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#7752 [backport] Support CUDA 12.2
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda122.multi.sh
  .pfnci/linux/tests/cuda122.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  .pfnci/windows/_flexci.ps1
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, backport, blocking, prio:high

#7753 Add CUDA 12.2 to list of supported CUDA
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking

#7756 [backport] Add CUDA 12.2 to list of supported CUDA
  docs/source/install.rst
Labels: cat:document, backport, blocking

#7746 Remove incorrect `cupyx.distributed.NCCLBackend.all_gather` comment
  cupyx/distributed/_nccl_comm.py
Labels: cat:document, to-be-backported, prio:medium

#7763 Fix test_sum_duplicates_incompatibility for SciPy 1.11
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:test, to-be-backported, prio:medium

#7765 [backport] Remove incorrect `cupyx.distributed.NCCLBackend.all_gather` comment
  cupyx/distributed/_nccl_comm.py
Labels: cat:document, backport, prio:medium

#7767 Fix Note highlight sections in README
  README.md
Labels: cat:document, to-be-backported, prio:medium

#7770 [backport] Fix Note highlight sections in README
  README.md
Labels: cat:document, backport, prio:medium
