Repository cupy/cupy, pull requests merged in 2023-08, with the labels that each got.

#7744 add the matrix exponential, `expm`
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/_matfuncs.py
  docs/source/reference/scipy_linalg.rst
  tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py
Labels: cat:feature, prio:medium

#7768 [backport] Fix test_sum_duplicates_incompatibility for SciPy 1.11
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Labels: cat:test, backport, prio:medium

#7715 Add 1D signal b-splines to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_bsplines.py
  cupyx/scipy/signal/_iir_utils.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
Labels: cat:feature, prio:medium

#7660 ENH: add LTI class hierarchy and lti/dlti related functions
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_ltisys.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_cont2discrete.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_dltisys.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
Labels: cat:feature, prio:medium

#7771 Note device sync on some cupyx.scipy.signal API documents
  cupyx/scipy/signal/_filter_design.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_polyutils.py
Labels: cat:document, prio:medium

#7758 Revert FP16 headers from CUDA 12.2.0 to CUDA 12.1.1
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp
Labels: cat:bug, to-be-backported, blocking

#7773 [backport] Revert FP16 headers from CUDA 12.2.0 to CUDA 12.1.1
  cupy/_core/include/cupy/_cuda/README.md
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp
Labels: cat:bug, backport, blocking

#7777 Add notes for CUDA 12.2 on Windows support
  docs/source/install.rst
Labels: to-be-backported, blocking, prio:high

#7778 [backport] Add notes for CUDA 12.2 on Windows support
  docs/source/install.rst
Labels: backport, blocking, prio:high

#7779 Add workflow to publish to PyPI
  .github/workflows/publish.yml
Labels: cat:other, to-be-backported, prio:high

#7782 [v12] Bump universal package version to v12.2.0
  install/universal_pkg/setup.py
Labels: blocking

#7781 Fix CUDA 12.2 for Windows notes
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#7786 Improve publish workflow
  .github/workflows/publish.yml
Labels: cat:other

#7785 [backport] Fix CUDA 12.2 for Windows notes
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:high

#7788 Fix publish workflow permission and output for review
  .github/workflows/publish.yml
Labels: cat:other

#7789 Fix publish workflow
  .github/workflows/publish.yml
Labels: cat:other

#7793 Add postcheck step to publish workflow
  .github/workflows/publish.yml
Labels: cat:other

#7794 Bump version in Dockerfile to v13.0.0b1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#7795 [v12] Bump version in Dockerfile to v12.2.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#6886 Implement axis parameter on cupy.unique
  cupy/_manipulation/add_remove.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: cat:enhancement, prio:medium

#7797 Fix ROCm Dockerfile not working
  docker/rocm/Dockerfile
Labels: cat:install, no-compat, prio:medium

#7575 Add `cupy.lib.stride_tricks.sliding_window_view`
  cupy/lib/stride_tricks.py
  tests/cupy_tests/lib_tests/test_strided_tricks.py
Labels: cat:feature, prio:high

#7800 ENH: Remove `NINF`, `PINF`, `Inf`,... usages
  cupy/__init__.py
  cupy/linalg/_norms.py
  cupyx/scipy/sparse/linalg/_norm.py
  cupyx/scipy/sparse/linalg/_solve.py
  examples/gmm/gmm.py
  tests/cupy_tests/linalg_tests/test_norms.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: to-be-backported, cat:numpy-compat, prio:medium

#7803 Add `-U` to pre-release installation command
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:medium

#7799 [v12] Fix ROCm Dockerfile not working
  docker/rocm/Dockerfile
Labels: cat:install, prio:medium

#7806 [backport] Add `-U` to pre-release installation command
  README.md
  docs/source/install.rst
Labels: cat:document, backport, prio:medium

#7792 Avoid warning when uploading packages
  install/cupy_builder/_context.py
  setup.py
Labels: cat:install, to-be-backported, prio:medium

#7724 Fix csr2dense to avoid race conditions
  cupyx/scipy/sparse/_csr.py
Labels: cat:bug, to-be-backported, prio:high

#7807 [backport] Avoid warning when uploading packages
  install/cupy_builder/_context.py
  setup.py
Labels: cat:install, backport, prio:medium

#7651 Avoid using `numpy.find_common_type`
  cupy/_indexing/generate.py
  cupyx/scipy/linalg/_special_matrices.py
  cupyx/scipy/sparse/_sputils.py
  cupyx/scipy/sparse/linalg/_interface.py
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#7814 Fix cuTENSOR contraction descriptor cache
  cupyx/cutensor.pyx
  tests/cupyx_tests/test_cutensor.py
Labels: cat:bug, to-be-backported

#7714 MNT: suppress compiler warning from `cupyx.cusolver`
  cupyx/cusolver.pyx
Labels: prio:medium, cat:code-fix

#7816 Add cuSignal license
  MANIFEST.in
  README.md
  docs/LICENSE_THIRD_PARTY
  docs/source/license.rst
Labels: cat:install, prio:high

#7739 Add type annotation in _creation.basic
  .github/workflows/pretest.yml
  cupy/_creation/basic.py
  cupy/typing/_types.py
  docs/source/conf.py
  tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi
  tests/typing_tests/mypy.ini
  tests/typing_tests/test_typing.py
Labels: prio:medium, cat:code-fix

#7563 Port lombscargle from CuSignal to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_spectral.py
  cupyx/scipy/signal/_spectral_impl.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Labels: cat:feature, prio:medium

#7823 Add a property to get access to the nccl handle.
  cupy_backends/cuda/libs/nccl.pyx
Labels: to-be-backported

#7819 [backport] MNT: suppress compiler warning from `cupyx.cusolver`
  cupyx/cusolver.pyx
Labels: backport, prio:medium, cat:code-fix

#7824 [backport] Add a property to get access to the nccl handle.
  cupy_backends/cuda/libs/nccl.pyx
Labels: cat:enhancement, backport, prio:medium

#7831 Fix backport workflow
  .github/workflows/backport.yml
Labels: cat:other, to-be-backported, prio:low

#7833 [backport] Fix backport workflow
  .github/workflows/backport.yml
Labels: cat:other, backport, prio:low

#7832 Fix mypy not installed in pre-review test
  .github/workflows/pretest.yml
  cupyx/jit/_compile.py
Labels: cat:test, prio:high

#7568 Port cusignal windows module to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/windows/__init__.py
  cupyx/scipy/signal/windows/_windows.py
  docs/source/reference/scipy.rst
  docs/source/reference/scipy_signal.rst
  docs/source/reference/scipy_signal_windows.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_windows.py
Labels: cat:feature, prio:medium

#7827 Fix `cupy.empty_like` parameter name to `prototype`
  cupy/_creation/basic.py
  tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi
Labels: no-compat, cat:numpy-compat, prio:medium

#7829 Make `stream` kwonly argument in `ndarray.__dlpack__`
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: no-compat, cat:numpy-compat, prio:medium

#7817 [backport] Fix cuTENSOR contraction descriptor cache
  cupyx/cutensor.pyx
  tests/cupyx_tests/test_cutensor.py
Labels: cat:bug, backport
