Repository cupy/cupy, pull requests merged in 2023-04, with the labels that each got.

#7463 Added `scipy.special.binom` functionality to CuPy
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_binom.py
  tests/cupyx_tests/scipy_tests/special_tests/test_binom.py
Labels: cat:feature, prio:medium

#7497 Use `-Xfatbin=-compress-all`
  install/cupy_builder/_compiler.py
Labels: cat:install, to-be-backported, prio:medium

#7505 [backport] Use `-Xfatbin=-compress-all`
  install/cupy_builder/_compiler.py
Labels: cat:install, backport, prio:medium

#7357 Add NdPPoly to cupyx.scipy.interpolate
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_interpolate.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
Labels: cat:feature, prio:medium

#7442 Add lfilter/IIR utilities to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_utils.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7432 add array_api.take function
  cupy/array_api/__init__.py
  cupy/array_api/_indexing_functions.py
  tests/cupy_tests/array_api_tests/test_indexing_functions.py
Labels: cat:feature, to-be-backported, prio:medium, array-api

#7513 [backport] add array_api.take function
  cupy/array_api/__init__.py
  cupy/array_api/_indexing_functions.py
  tests/cupy_tests/array_api_tests/test_indexing_functions.py
Labels: cat:feature, backport, prio:medium, array-api

#7469 ENH: cupyx/scipy/signal: add savgol_coeffs and savgol_filter
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_arraytools.py
  cupyx/scipy/signal/_savitzky_golay.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_savitzky_golay.py
Labels: cat:feature, prio:medium

#7481 Support NumPy 1.24: Adding `strict` option to `testing.assert_array_equal`
  cupy/testing/_array.py
Labels: cat:numpy-compat, prio:medium

#7477 Add lfiltic and lfilter_zi to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7511 Add symiirorder1 to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_splines.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
Labels: cat:feature, prio:medium

#7518 Add symiirorder2 to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_splines.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
Labels: cat:feature, prio:medium

#7474 add `cupyx.scipy.special.exprel`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_basic.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
Labels: cat:feature, prio:medium

#7490 Support NumPy 1.24: `dtype` and `casting` keyword arguments for `hstack`, `vstack`, `stack`
  cupy/_manipulation/join.py
  tests/cupy_tests/manipulation_tests/test_join.py
Labels: cat:enhancement, prio:medium

#7521 Fix TestBSpline::test_design_matrix_same_as_BSpline_call
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline.py
Labels: cat:test, to-be-backported, prio:medium

#7522 Replace concatenate by slice manipulation in lfilter
  cupyx/scipy/signal/_arraytools.py
  cupyx/scipy/signal/_signaltools.py
Labels: cat:enhancement, prio:medium

#7520 Add `scipy.special.spherical_yn`
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_spherical_bessel.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py
Labels: cat:feature, prio:medium

#7523 Mark scipy required in a test
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
Labels: cat:test, prio:high

#7470 Add `scipy.special.zetac` to cupyx
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_zetac.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/special_tests/test_zetac.py
Labels: cat:feature, prio:medium

#7531 Import SciPy in tests
  tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
Labels: cat:test, prio:medium

#7524 Require newer SciPy in a test
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
Labels: cat:test, prio:high

#7526 Improve symiirorder2 performance
  cupyx/scipy/signal/_splines.py
Labels: cat:performance, prio:medium
