Repository cupy/cupy, pull requests merged in 2023-02, with the labels that each got.

#7356 Imporves stability of orthogonization step in ```cupyx.scipy.sparse.eigsh```
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:bug, to-be-backported, prio:high

#7338 Avoid int8 overflow warning in `TestRoundHalfway`
  tests/cupy_tests/core_tests/test_ndarray_math.py
Labels: cat:test, to-be-backported, prio:medium

#7361 [backport] Imporves stability of orthogonization step in ```cupyx.scipy.sparse.eigsh```
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:bug, backport, prio:high

#7364 Filter SQLAlchemy 2.0 warnings raised from Optuna v2
  setup.cfg
Labels: cat:test, to-be-backported, prio:high

#7363 Drop support for Optuna v2
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
Labels: cat:test, to-be-backported, prio:medium

#7334 Enable spline methods on RegularGridInterpolator
  cupyx/scipy/interpolate/_rgi.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rgi.py
Labels: cat:feature, prio:medium

#7365 [backport] Filter SQLAlchemy 2.0 warnings raised from Optuna v2
  setup.cfg
Labels: cat:test, backport, prio:high

#7368 Do not test NumPy version for private APIs
  cupy/typing/_generic_alias.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#7370 [backport] Do not test NumPy version for private APIs
  cupy/typing/_generic_alias.py
Labels: cat:bug, backport, blocking, prio:high

#7349 Add CI for CUDA 12.0 on Windows
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, prio:high

#7369 Fix pre-commit configuration error
  .pre-commit-config.yaml
Labels: cat:test, to-be-backported, prio:low

#7265 Add `cached_code` to `ElementwiseKernel` and `ReductionKernel`
  cupy/_core/_kernel.pyx
  cupy/_core/_reduction.pxd
  cupy/_core/_reduction.pyx
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/core_tests/test_userkernel.py
Labels: cat:feature, prio:medium

#7343 Add BPoly to cupyx.scipy.interpolate module
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_interpolate.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
Labels: cat:feature, prio:medium

#7371 [backport] Add CI for CUDA 12.0 on Windows
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, backport, prio:high

#7373 [backport] Fix pre-commit configuration error
  .pre-commit-config.yaml
Labels: cat:test, backport, prio:low

#7362 [backport] Avoid int8 overflow warning in `TestRoundHalfway`
  tests/cupy_tests/core_tests/test_ndarray_math.py
Labels: cat:test, backport, prio:medium

#7040 Initial experimental & private `cupyx.distributed._array` implementation
  cupy/_core/_kernel.pyx
  cupy/cuda/memory.pxd
  cupyx/distributed/_array.py
  tests/cupyx_tests/distributed_tests/test_array.py
Labels: cat:feature, prio:medium

#7307 Update DLPack to v0.8 to support bool arrays
  cupy/_core/dlpack.pyx
  cupy/_core/include/cupy/dlpack/README.md
  cupy/_core/include/cupy/dlpack/dlpack.h
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:enhancement, to-be-backported, prio:medium

#7308 Remove texture reference completely
  cupy/_core/raw.pyx
  cupy/cuda/function.pxd
  cupy/cuda/function.pyx
  cupy/cuda/texture.pxd
  cupy/cuda/texture.pyx
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_driver_typedef.pxi
  cupy_backends/cuda/api/driver.pxd
  cupy_backends/cuda/api/driver.pyx
  cupy_backends/hip/cupy_hip.h
  cupy_backends/hip/cupy_hip_common.h
  cupy_backends/stub/cupy_cuda.h
  cupy_backends/stub/cupy_cuda_common.h
  docs/source/reference/cuda.rst
  docs/source/user_guide/kernel.rst
  tests/cupy_tests/cuda_tests/test_texture.py
Labels: cat:enhancement, prio:medium

#7376 [backport] Update DLPack to v0.8 to support bool arrays
  cupy/_core/dlpack.pyx
  cupy/_core/include/cupy/dlpack/README.md
  cupy/_core/include/cupy/dlpack/dlpack.h
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:enhancement, backport, prio:medium

#7377 Mark `cupy.cuda.profiler.initialize` deprecated as it is removed in CUDA 12
  cupy_backends/cuda/libs/profiler.pyx
Labels: cat:enhancement, to-be-backported, prio:medium

#7375 Doc: downgrade pydata-sphinx-theme to v0.11.0
  docs/requirements.txt
Labels: cat:document, to-be-backported, prio:high

#7305 Add `CUPY_INCLUDE_PATH` and `CUPY_LIBRARY_PATH` env vars
  install/cupy_builder/_context.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
  tests/install_tests/test_build.py
  tests/install_tests/test_cupy_builder/test_context.py
  tests/install_tests/test_cupy_builder/test_features.py
Labels: cat:install, to-be-backported, prio:low

#7341 Avoid casting nan value to integer type in `nanargmin/max` tests
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:test, to-be-backported, prio:medium

#7339 Avoid int8 overflow in some tests
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/functional_tests/test_piecewise.py
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/logic_tests/test_comparison.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
  tests/cupy_tests/polynomial_tests/test_polyutils.py
  tests/cupy_tests/testing_tests/test_loops.py
  tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
Labels: cat:test, to-be-backported, prio:medium

#7340 Fix int8 overflow in vectorize tests
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:test, to-be-backported, prio:medium

#7382 [backport] Avoid int8 overflow in some tests
  tests/cupy_tests/core_tests/test_ndarray_unary_op.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/functional_tests/test_piecewise.py
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/logic_tests/test_comparison.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
  tests/cupy_tests/polynomial_tests/test_polyutils.py
  tests/cupy_tests/testing_tests/test_loops.py
  tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py
Labels: cat:test, backport, prio:medium

#7384 [backport] Fix int8 overflow in vectorize tests
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:test, backport, prio:medium

#7381 [backport] Avoid casting nan value to integer type in `nanargmin/max` tests
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:test, backport, prio:medium

#7316 Work around a potential OOM error raised by CUB histogram
  cupy/_statistics/histogram.py
  cupy/cuda/cub.pyx
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:enhancement, prio:medium

#7388 [backport] Work around a potential OOM error raised by CUB histogram
  cupy/_statistics/histogram.py
  cupy/cuda/cub.pyx
  tests/cupy_tests/statistics_tests/test_histogram.py
Labels: cat:enhancement, backport, prio:medium

#7379 [backport] Mark `cupy.cuda.profiler.initialize` deprecated as it is removed in CUDA 12
  cupy_backends/cuda/libs/profiler.pyx
Labels: cat:enhancement, backport, prio:medium

#7395 Fix sumprod test to avoid uint overflow
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:test, to-be-backported, prio:high

#7398 [backport] Fix sumprod test to avoid uint overflow
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:test, backport, prio:high

#7397 Avoid `fillvalue` overflow in `cupyx.scipy.signal` test
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, to-be-backported, prio:high

#7401 [backport] Avoid `fillvalue` overflow in `cupyx.scipy.signal` test
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, backport, prio:high

#7322 Small fixes and refactor of casting related things
  cupy/_core/_dtype.pxd
  cupy/_core/_dtype.pyx
  cupy/_core/_fusion_trace.pyx
  cupy/_core/_gufuncs.py
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/fusion.pyx
  cupyx/jit/_compile.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/math_tests/test_arithmetic.py
Labels: prio:medium, cat:code-fix

#7353 [backport] Use warp size from `runtime.getDeviceProperties`
  cupy/_core/__init__.py
  cupy/_core/_kernel.pyx
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_math.pyx
  cupyx/jit/_interface.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:enhancement, backport, prio:medium

#7394 Fix `arange()` to raise `TypeError` in boolean case
  cupy/_creation/ranges.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: cat:numpy-compat, prio:high

#7399 Change implementation of fftshift and ifftshift
  cupy/fft/_fft.py
Labels: cat:performance, prio:medium

#7387 Avoid int8 overflow in core test
  tests/cupy_tests/core_tests/test_core.py
Labels: cat:test, to-be-backported, prio:high

#7407 [backport] Fix `arange()` to raise `TypeError` in boolean case
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/indexing_tests/test_generate.py
Labels: backport, cat:numpy-compat, prio:high

#7408 [backport] Fix ndarray.fill to raise ComplexWarning
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Labels: cat:test, backport

#7402 fix typo in docstring
  cupy/_functional/vectorize.py
Labels: cat:document, prio:medium

#7417 Tentatively disable cuquantum intersphinx
  docs/source/conf.py
Labels: cat:document, to-be-backported, blocking, prio:high

#7420 [backport] Tentatively disable cuquantum intersphinx
  docs/source/conf.py
Labels: cat:document, backport, blocking, prio:high

#7248 Use NumPy 1.24 in CI and bump baseline API
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, to-be-backported, prio:high

#7421 Revert "Tentatively disable cuquantum intersphinx"
  docs/source/conf.py
Labels: cat:enhancement, prio:high

#7422 Revert "[backport] Tentatively disable cuquantum intersphinx"
  docs/source/conf.py
Labels: cat:document

#7423 [backport] Use NumPy 1.24 in CI and bump baseline API
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:enhancement, backport, prio:high

#7411 Added runtime error if pylibraft unavailable
  cupyx/scipy/spatial/distance.py
Labels: cat:enhancement, prio:medium

#7419 DOC: cupyx.interpolate: document limitations on ROCm
  docs/source/install.rst
Labels: cat:document, prio:medium

#7427 Revert cupy.cuda.Device behavior to v9
  cupy/cuda/device.pyx
  tests/cupy_tests/cuda_tests/test_device.py
Labels: cat:enhancement, no-compat, blocking, prio:high

#7429 Bump docker image to CUDA 11.8.0
  docker/python3/Dockerfile
Labels: cat:install, no-compat, blocking, prio:high

#7430 Add upgrade guide for v12
  docs/source/upgrade.rst
  docs/source/user_guide/interoperability.rst
Labels: cat:document, blocking, prio:high
