Repository cupy/cupy, pull requests merged in 2023-05, with the labels that each got.

#7547 Fix RTD build failure
  .readthedocs.yaml
Labels: cat:document, to-be-backported, prio:high

#7554 [backport] Fix RTD build failure
  .readthedocs.yaml
Labels: cat:document, backport, prio:high

#7525 [backport] Fix TestBSpline::test_design_matrix_same_as_BSpline_call
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline.py
Labels: cat:test, backport, prio:medium

#7496 Add filtfilt to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_arraytools.py
  cupyx/scipy/signal/_signaltools.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7540 Fix cudart errors raised by texture APIs swallowed by Cython
  cupy/cuda/texture.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
Labels: cat:bug, prio:medium

#7517 Fix random module performance regression
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
Labels: cat:performance, prio:medium

#7528 Add sosfilt to cupyx.scipy.signal
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_signaltools.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_utils.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7566 [backport] Fix cudart errors raised by texture APIs swallowed by Cython
  cupy/cuda/texture.pyx
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
Labels: cat:bug, backport, prio:medium

#7541 cupyx.scipy.signal: add bilinear & bilinear_zpk
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
Labels: cat:feature, prio:medium

#7536 ENH: scipy.signal: add detrend
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_signaltools.py
  docs/source/reference/scipy_signal.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:feature, prio:medium

#7567 Try to fix nan value mismatches in filtfilt tests
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, to-be-backported, prio:high

#7546 Reestore GitHub Actions cache with prefix match
  .github/workflows/pretest.yml
Labels: cat:test, to-be-backported, prio:low

#7571 [backport] Reestore GitHub Actions cache with prefix match
  .github/workflows/pretest.yml
Labels: cat:test, backport, prio:low

#7582 [backport] Fix CUDA Python CI failure
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda102.Dockerfile
  .pfnci/linux/tests/cuda102.multi.Dockerfile
  .pfnci/linux/tests/cuda110.Dockerfile
  .pfnci/linux/tests/cuda110.multi.Dockerfile
  .pfnci/linux/tests/cuda111.Dockerfile
  .pfnci/linux/tests/cuda111.multi.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
Labels: cat:test, backport, prio:high

#7572 Dispatch ufunc methods
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:bug, to-be-backported, prio:high

#7578 Fix `_depends.json` not included in wheel
  install/cupy_builder/_command.py
Labels: cat:install, to-be-backported, blocking, prio:high

#7584 [backport] Fix `_depends.json` not included in wheel
  install/cupy_builder/_command.py
Labels: cat:install, backport, blocking, prio:high

#7583 [backport] Dispatch ufunc methods
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray_ufunc.py
Labels: cat:bug, backport, blocking, prio:high

#7367 Support SciPy 1.10
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupyx/scipy/sparse/linalg/_lobpcg.py
  docs/requirements.txt
  docs/source/install.rst
  setup.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, to-be-backported, prio:medium

#7586 [backport] Support SciPy 1.10
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
  setup.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:enhancement, backport, blocking, prio:medium

#7587 Bump version to v13.0.0a1
  install/universal_pkg/setup.py
Labels: cat:install

#7589 Bump Dockerfile version to v13.0.0a1
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:other

#7592 [backport] Fix random module performance regression
  cupy/random/_bit_generator.pyx
  cupy/random/_generator_api.pyx
  cupy/random/cupy_distributions.cu
  cupy/random/cupy_distributions.cuh
Labels: backport, cat:performance, prio:medium

#7595 Bump versions of static checkers
  .pre-commit-config.yaml
  cupy/_indexing/indexing.py
  cupy/_io/formatting.py
  cupy/_manipulation/kind.py
  cupy/_math/arithmetic.py
  cupy/_math/misc.py
  cupy/_statistics/histogram.py
  cupy/cublas.py
  cupy/random/_generator.py
  cupyx/_pinned_array.py
  cupyx/jit/cg.py
  cupyx/profiler/_time.py
  cupyx/scipy/linalg/_decomp_lu.py
  cupyx/scipy/sparse/linalg/_lobpcg.py
  cupyx/scipy/sparse/linalg/_solve.py
  examples/gemm/sgemm.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/random_tests/test_permutations.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, to-be-backported, prio:medium

#7580 Improve README and Installation Guide
  README.md
  docs/source/install.rst
Labels: cat:document, to-be-backported, prio:high

#7598 [backport] Bump versions of static checkers
  .pre-commit-config.yaml
  cupy/_indexing/indexing.py
  cupy/_io/formatting.py
  cupy/_manipulation/kind.py
  cupy/_math/arithmetic.py
  cupy/_math/misc.py
  cupy/_statistics/histogram.py
  cupy/cublas.py
  cupy/random/_generator.py
  cupyx/_pinned_array.py
  cupyx/jit/cg.py
  cupyx/profiler/_time.py
  cupyx/scipy/linalg/_decomp_lu.py
  cupyx/scipy/sparse/linalg/_lobpcg.py
  cupyx/scipy/sparse/linalg/_solve.py
  examples/gemm/sgemm.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/random_tests/test_permutations.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, backport, prio:medium

#7599 [backport] Improve README and Installation Guide
  README.md
  docs/source/install.rst
Labels: cat:document, backport, prio:high

#7553 filter design "prototypes"
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_ellip.py
  docs/source/reference/scipy_special.rst
  tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
  tests/cupyx_tests/scipy_tests/special_tests/test_ellipk.py
Labels: cat:feature, prio:medium
