Repository cupy/cupy, pull requests merged in 2024-06, with the labels that each got.

#8150 Fix overflow indexing ndarray generated with as_strided
  cupy/_core/core.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:bug, to-be-backported, prio:high

#8074 patch for cusparseLt 0.6.1
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/libs/cusparselt.pxd
  cupy_backends/cuda/libs/cusparselt.pyx
  cupy_backends/stub/cupy_cusparselt.h
  examples/cusparselt/matmul.py
Labels: cat:enhancement, prio:high

#8346 make CuPy import under NumPy 2.0
  .github/workflows/pretest.yml
  cupy/__init__.py
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_sorting.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pyx
  cupy/_core/fusion.pyx
  cupy/_core/internal.pyx
  cupy/exceptions/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/_shape_base.py
  cupy/testing/_loops.py
  cupyx/jit/_compile.py
  cupyx/scipy/fft/_realtransforms.py
  cupyx/scipy/interpolate/_bspline2.py
  setup.cfg
  setup.py
  tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
Labels: cat:enhancement, to-be-backported, prio:high

#8345 Fix CUB build error on win-64
  cupy/cuda/cupy_cub.cu
Labels: cat:bug, to-be-backported, prio:high

#8349 [backport] Fix overflow indexing ndarray generated with as_strided
  cupy/_core/core.pyx
  tests/cupy_tests/indexing_tests/test_indexing.py
Labels: cat:bug, backport, prio:high

#8362 Update the version of cusparselt in the installation guide
  docs/source/install.rst
Labels: cat:document, prio:high

#8357 [backport] make CuPy import under NumPy 2.0
  .github/workflows/pretest.yml
  cupy/__init__.py
  cupy/_core/_routines_indexing.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_sorting.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pyx
  cupy/_core/fusion.pyx
  cupy/_core/internal.pyx
  cupy/exceptions/__init__.py
  cupy/lib/_routines_poly.py
  cupy/lib/_shape_base.py
  cupy/testing/_loops.py
  cupyx/jit/_compile.py
  cupyx/scipy/fft/_realtransforms.py
  cupyx/scipy/interpolate/_bspline2.py
  setup.cfg
  setup.py
  tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
Labels: cat:enhancement, backport, prio:high

#8361 [backport] Re-enable NVTX range coloring for NVTX3.
  cupy_backends/cuda/libs/nvtx.pyx
Labels: cat:bug, backport, prio:high

#8358 [backport] Fix CUB build error on win-64
  cupy/cuda/cupy_cub.cu
Labels: cat:bug, backport, prio:high

#8355 [v13] Use the latest NumPy v1 for head CI
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/schema.yaml
Labels: cat:test, prio:high

#8360 Lazy-preload NCCL
  cupy/__init__.py
  cupy/cuda/nccl.py
  cupyx/_runtime.py
Labels: cat:enhancement, to-be-backported, prio:high

#8367 [backport] Lazy-preload NCCL
  cupy/__init__.py
  cupy/cuda/nccl.py
  cupyx/_runtime.py
Labels: cat:enhancement, backport, prio:high

#8368 Add NumPy 2.0 on document
  docs/source/install.rst
Labels: cat:document, to-be-backported, blocking, prio:high

#8370 Update API baseline on document
  docs/source/install.rst
Labels: cat:document, prio:high

#8371 [backport] Add NumPy 2.0 on document
  docs/source/install.rst
Labels: cat:document, backport, blocking, prio:high

#8372 Bump version to v14.0.0a1
  cupy/_version.py
Labels: cat:other

#8373 Bump version to v13.2.0
  cupy/_version.py
Labels: cat:other

#8376 Bump Dockerfile
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install

#8366 Fix pull request project board workflows
  .github/workflows/pr-project.yml
  .github/workflows/pr-updated.yml
Labels: cat:other, prio:medium

#8378 Fix `map_cordinates` recompilation condition
  cupyx/scipy/ndimage/_interp_kernels.py
  cupyx/scipy/ndimage/_interpolation.py
Labels: cat:enhancement, prio:medium

#8365 eigsh doc correction _eigen.py
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:document, to-be-backported

#8383 [backport] eigsh doc correction _eigen.py
  cupyx/scipy/sparse/linalg/_eigen.py
Labels: cat:document, backport

#8343 MAINT: interpolate: update RBF to scipy 1.13
  cupyx/scipy/interpolate/_rbfinterp.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
Labels: cat:enhancement, prio:medium

#8388 Fix spline temp container size in make_interp_spline
  cupyx/scipy/interpolate/_bspline2.py
Labels: cat:bug, to-be-backported, prio:high

#8390 [backport] Fix spline temp container size in make_interp_spline
  cupyx/scipy/interpolate/_bspline2.py
Labels: cat:bug, backport, prio:high
