Repository cupy/cupy, pull requests merged in 2024-03, with the labels that each got.

#8217 [backport] Fix: remove unnecessary include that causes deployment issue
  cupyx/scipy/interpolate/_interpolate.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_max_len_seq.py
  cupyx/scipy/signal/_peak_finding.py
  cupyx/scipy/signal/_spectral_impl.py
  cupyx/scipy/signal/_splines.py
  cupyx/scipy/signal/_waveforms.py
Labels: cat:bug, backport, prio:medium

#8216 [backport] Fix jitify warmup kernel
  cupy/cuda/jitify.pyx
Labels: cat:bug, backport, prio:high

#8229 Fix build system for Thrust detection
  install/cupy_builder/_features.py
Labels: cat:bug, to-be-backported

#8225 Add CuPy Training Materials information to README.md
  README.md
Labels: cat:document, prio:medium

#7996 Add import test without CUDA Toolkit
  .pfnci/linux/tests/cuda-build.sh
  tests/import_tests/test_import.py
Labels: cat:test, to-be-backported, prio:medium

#8230 [backport] Fix build system for Thrust detection
  install/cupy_builder/_features.py
Labels: cat:bug, backport

#7864 Add neighbors option to RbfInterpolator
  cupyx/scipy/interpolate/_rbfinterp.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
Labels: cat:feature, prio:medium

#8035 Add LinearNDInterpolator to cupyx.scipy.interpolate
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_interpnd.py
  cupyx/scipy/spatial/_delaunay.py
  cupyx/scipy/spatial/delaunay_2d/_kernels.py
  cupyx/scipy/spatial/delaunay_2d/_schewchuk.py
  cupyx/scipy/spatial/delaunay_2d/_tri.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_interpnd.py
  tests/cupyx_tests/scipy_tests/spatial_tests/test_delaunay.py
Labels: cat:feature, prio:medium

#8231 [backport] Add import test without CUDA Toolkit
  .pfnci/linux/tests/cuda-build.sh
  tests/import_tests/test_import.py
Labels: cat:test, backport, prio:medium

#8235 Various Jitify improvements
  cupy/cuda/jitify.pyx
  install/cupy_builder/cupy_setup_build.py
Labels: to-be-backported, prio:high

#8237 [backport] Various Jitify improvements
  cupy/cuda/jitify.pyx
  install/cupy_builder/cupy_setup_build.py
Labels: backport, prio:high

#8224 Add the `nearest` method for percentile/quantile estimation
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:enhancement, prio:medium

#8219 add `cudaStreamCreateWithPriority`
  cupy/cuda/stream.pyx
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_stream.py
Labels: cat:enhancement, prio:medium

#8201 Fix: always switch to the submodule dir before checking git tag/commit
  install/cupy_builder/install_build.py
Labels: cat:bug, to-be-backported, prio:medium

#8223 Add NdBSpline to cupyx.scipy.interpolate
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_ndbspline.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_ndbspline.py
Labels: cat:feature, prio:medium

#8240 [backport] Fix: always switch to the submodule dir before checking git tag/commit
  install/cupy_builder/install_build.py
Labels: cat:bug, backport, prio:medium

#8243 Fix overflow of index calculation in random generator API
  cupy/random/cupy_distributions.cu
  tests/cupy_tests/random_tests/test_generator_api.py
Labels: cat:bug, to-be-backported

#8244 Fix Generator API parallelism
  cupy/random/_bit_generator.pyx
Labels: cat:bug, to-be-backported

#8247 [backport] Fix Generator API parallelism
  cupy/random/_bit_generator.pyx
Labels: cat:bug, backport

#8259 BUG: cupyx/scipy/signal: fix mpmath test
  setup.py
  tests/cupyx_tests/scipy_tests/signal_tests/mpsig.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
Labels: cat:test, to-be-backported, prio:high

#8212 Add CutensorMg support
  cupy_backends/cuda/cupy_cutensor.h
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/cuda/stream.pxd
  cupy_backends/cuda/stream.pyx
  cupy_backends/stub/cupy_cutensor.h
  cupyx/cutensor.pyx
  install/cupy_builder/_features.py
  tests/cupyx_tests/test_cutensor.py
Labels: cat:enhancement, prio:medium
