Repository cupy/cupy, pull requests merged in 2024-08, with the labels that each got.

#8444 Fix the size of temporary CUB output space to consider its alignment
  cupy/cuda/cub.pyx
Labels: cat:bug, to-be-backported, prio:high

#8447 [backport] Fix the size of temporary CUB output space to consider its alignment
  cupy/cuda/cub.pyx
Labels: cat:bug, backport, prio:high

#8425 Add Incomplete Elliptic Integrals to special
  cupy/_core/include/cupy/special/cephes/ellie.h
  cupy/_core/include/cupy/special/cephes/ellik.h
  cupy/_core/include/cupy/special/cephes/ellpe.h
  cupy/_core/include/cupy/special/cephes/ellpk.h
  cupy/_core/include/cupy/special/cephes/unity.h
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_ellip.py
  tests/cupyx_tests/scipy_tests/special_tests/test_ellipk.py
Labels: cat:feature, prio:medium

#8295 Add comparison table for `(cupyx.)scipy.sparse.*_matrix classes` class methods
  docs/source/_comparison_generator.py
Labels: cat:document, to-be-backported, prio:medium

#8461 Decrease number of threads to avoid "system error: excessive memory usage is detected"
  .pfnci/linux/tests/actions/build.sh
Labels: cat:test, to-be-backported, prio:high

#8462 [backport] Decrease number of threads to avoid "system error: excessive memory usage is detected"
  .pfnci/linux/tests/actions/build.sh
Labels: cat:test, backport, prio:high

#7603 Patch the build system to better support conda-build
  install/cupy_builder/_environment.py
  install/cupy_builder/_features.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
Labels: cat:install, to-be-backported, prio:high

#8441 Address KeyErrors from importlib_metadata
  cupy/_environment.py
Labels: cat:bug, to-be-backported, prio:high

#8463 CI: skip CUDA 12.1/12.2/12.3/12.4 CI on "mini" trigger
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, prio:medium

#8469 [backport] CI: skip CUDA 12.1/12.2/12.3/12.4 CI on "mini" trigger
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, backport, prio:medium

#8465 [backport] Address KeyErrors from importlib_metadata
  cupy/_environment.py
Labels: cat:bug, backport, prio:high

#8464 [backport] Patch the build system to better support conda-build
  install/cupy_builder/_environment.py
  install/cupy_builder/_features.py
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
Labels: cat:install, backport, prio:high

#8455 Resolve Ruff `NPY` errors
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/indexing_tests/test_iterate.py
  tests/cupy_tests/lib_tests/test_shape_base.py
  tests/cupy_tests/logic_tests/test_content.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/manipulation_tests/test_dims.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_kind.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/padding_tests/test_pad.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/cupy_tests/testing_tests/test_loops.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#8471 [backport] Resolve Ruff `NPY` errors
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
  tests/cupy_tests/core_tests/test_reduction.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/indexing_tests/test_iterate.py
  tests/cupy_tests/lib_tests/test_shape_base.py
  tests/cupy_tests/logic_tests/test_content.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/manipulation_tests/test_dims.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_kind.py
  tests/cupy_tests/manipulation_tests/test_transpose.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/padding_tests/test_pad.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/statistics_tests/test_meanvar.py
  tests/cupy_tests/testing_tests/test_helper.py
  tests/cupy_tests/testing_tests/test_loops.py
Labels: backport, cat:numpy-compat, prio:high

#8467 Avoid using Jitify everywhere inside CuPy
  cupyx/jit/cub.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/signal/_filtering/_filtering.py
Labels: cat:enhancement, to-be-backported, prio:high

#8411 Skip some tests in aarch64 CI
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
Labels: cat:test, to-be-backported, prio:medium

#8476 upfirdn: mode=None -> mode="constant"
  cupyx/scipy/signal/_upfirdn.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py
Labels: cat:bug, no-compat, prio:medium

#8490 [backport] Skip some tests in aarch64 CI
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
Labels: cat:test, backport, prio:medium

#8495 [backport] upfirdn: mode=None -> mode="constant"
  cupyx/scipy/signal/_upfirdn.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py
Labels: cat:bug, backport, prio:medium

#8491 Drop support for Python 3.9, NumPy 1.22 and 1.23, SciPy 1.7, 1.8 and 1.9
  .pfnci/coverage.rst
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  docs/source/install.rst
Labels: cat:enhancement, no-compat, prio:high

#8483 Improving performance of `cupy.random.choice`
  cupy/random/_generator.py
Labels: to-be-backported, cat:performance, prio:high

#8501 [backport] Improving performance of `cupy.random.choice`
  cupy/random/_generator.py
Labels: backport, cat:performance, prio:high

#8489 Search header files from CTK wheel
  cupy/_environment.py
  cupy/cuda/compiler.py
  cupyx/_runtime.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#8504 [backport] Search header files from CTK wheel
  cupy/_environment.py
  cupy/cuda/compiler.py
  cupyx/_runtime.py
Labels: cat:bug, backport, blocking, prio:high

#8499 Remove deprecated `cupyx.scipy.linalg.{tri,tril,triu}`
  cupyx/scipy/linalg/__init__.py
  cupyx/scipy/linalg/_special_matrices.py
  docs/source/reference/scipy_linalg.rst
Labels: cat:enhancement, no-compat, prio:medium

#8505 Fix CUDA version condition to use headers from wheel
  cupy/_environment.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#8507 [backport] Fix CUDA version condition to use headers from wheel
  cupy/_environment.py
Labels: cat:bug, backport, blocking, prio:high

#8323 NEP50
  cupy/_core/_fusion_trace.pyx
  cupy/_core/_fusion_variable.pyx
  cupy/_core/_kernel.pxd
  cupy/_core/_kernel.pyx
  cupy/_core/_reduction.pyx
  cupy/_core/_routines_logic.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_routines_math.pyx
  cupy/_core/_routines_statistics.pyx
  cupy/_core/core.pyx
  cupy/_core/fusion.pyx
  cupy/_core/new_fusion.pyx
  cupy/_sorting/search.py
  cupy/_statistics/correlation.py
  cupy/_statistics/histogram.py
  cupy/cublas.py
  cupy/linalg/_einsum.py
  cupyx/jit/_cuda_typerules.py
  cupyx/scipy/linalg/_solve_triangular.py
  cupyx/scipy/signal/_splines.py
  cupyx/scipy/sparse/linalg/_solve.py
  tests/conftest.py
  tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
  tests/cupy_tests/core_tests/test_elementwise.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/core_tests/test_nep50_examples.py
  tests/cupy_tests/creation_tests/test_ranges.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/indexing_tests/test_indexing.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/linalg_tests/test_product.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_special.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupy_tests/random_tests/test_sample.py
  tests/cupy_tests/statistics_tests/test_histogram.py
  tests/cupyx_tests/jit_tests/test_cooperative_groups.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
Labels: cat:numpy-compat, prio:medium

#8506 [backport] Remove deprecated `cupyx.scipy.linalg.{tri,tril,triu}`
  cupyx/scipy/linalg/_special_matrices.py
Labels: cat:enhancement, no-compat, backport, prio:medium

#8473 [backport] Avoid using Jitify everywhere inside CuPy
  cupyx/jit/cub.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/signal/_filtering/_filtering.py
Labels: cat:enhancement, backport, prio:high

#8517 [backport] Use `.toarray()` instead of `.A` attribute
  cupy/testing/_loops.py
  tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
Labels: cat:enhancement, backport, prio:high

#8516 [v13] Fix deprecation backport
  cupyx/scipy/linalg/_special_matrices.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_uarray.py
Labels: cat:bug, blocking, prio:high

#8519 Extend runtime header search logic to conda
  cupy/_environment.py
  cupy/cuda/compiler.py
  cupyx/_runtime.py
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#8509 Relax `test_firls` atol
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:test, to-be-backported, prio:high

#8510 Support `half` option in `scipy.signal.minimum_phase`
  cupyx/scipy/signal/_fir_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:enhancement, prio:high

#8513 Support CUDA 12.6
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/linux/tests/cuda126.multi.sh
  .pfnci/linux/tests/cuda126.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  .pfnci/windows/_flexci.ps1
  cupy/_core/core.pyx
  cupy/_core/include/cupy/_cuda/cuda-12.6/cuda_fp16.h
  cupy/_core/include/cupy/_cuda/cuda-12.6/cuda_fp16.hpp
  docs/source/install.rst
Labels: cat:enhancement, to-be-backported, prio:high

#8502 Add CUDA graph debug function
  cupy/cuda/graph.pxd
  cupy/cuda/graph.pyx
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/runtime.pxd
  cupy_backends/cuda/api/runtime.pyx
  cupy_backends/cuda/cupy_cuda_runtime.h
  cupy_backends/hip/cupy_hip_runtime.h
  cupy_backends/stub/cupy_cuda_runtime.h
  docs/source/reference/cuda.rst
  tests/cupy_tests/cuda_tests/test_graph.py
Labels: cat:feature, prio:medium

#8520 [backport] Extend runtime header search logic to conda
  cupy/_environment.py
  cupy/cuda/compiler.py
  cupyx/_runtime.py
Labels: cat:enhancement, backport, blocking, prio:high

#8521 [v13] Revert "[backport] Improving performance of `cupy.random.choice`"
  cupy/random/_generator.py
Labels: blocking

#8518 Fallback to system headers for future CUDA 12.x versions
  cupy/_core/core.pyx
Labels: cat:enhancement, to-be-backported, blocking, prio:high

#8529 [backport] Fallback to system headers for future CUDA 12.x versions
  cupy/_core/core.pyx
Labels: cat:enhancement, backport, blocking, prio:high

#8528 Fix ROCm 4.3 binary package build broken
  cupy/_core/include/cupy/complex/namespace.h
Labels: cat:bug, to-be-backported, blocking, prio:high

#8530 Fix cudart header detection for conda
  cupy/_core/core.pyx
Labels: cat:bug, to-be-backported, blocking, prio:high

#8534 [backport] Fix ROCm 4.3 binary package build broken
  cupy/_core/include/cupy/complex/namespace.h
Labels: cat:bug, backport, blocking, prio:high

#8535 [backport] Fix cudart header detection for conda
  cupy/_core/core.pyx
Labels: cat:bug, backport, blocking, prio:high

#8543 Bump version to v13.3.0
  cupy/_version.py
Labels: cat:install, blocking, prio:high

#8548 [v13] Bump version in Dockerfile for v13.3.0
  docker/python3/Dockerfile
  docker/rocm/Dockerfile
Labels: cat:install, blocking

#8526 Fix `sparse.linalg` function signatures following SciPy 1.14
  cupyx/scipy/sparse/linalg/_iterative.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:numpy-compat, prio:high

#8527 Fix `cupyx.scipy.sparse` tests for SciPy 1.14
  tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:test, prio:high

#8532 Fix dtype rule of special functions for SciPy 1.14
  cupyx/scipy/special/_basic.py
  cupyx/scipy/special/_digamma.py
  cupyx/scipy/special/_gamma.py
  cupyx/scipy/special/_loggamma.py
  cupyx/scipy/special/_spherical_bessel.py
  cupyx/scipy/special/_statistics.py
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:numpy-compat, prio:high

#8533 Skip `special.logsumexp` test for empty input
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
Labels: cat:test, prio:medium

#8546 Skip betaincinv test with SciPy 1.14.1
  tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
Labels: cat:test, prio:medium

#8547 Fix dtype rule of `cupy.scipy.stats.entropy` for SciPy 1.14
  cupyx/scipy/stats/_distributions.py
  tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py
Labels: cat:enhancement, prio:medium

#8552 [v13] Fix cupyx.scipy.sparse tests for SciPy 1.14
  tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:numpy-compat, prio:high

#8553 [backport] Skip betaincinv test with SciPy 1.14.1
  tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
Labels: cat:test, backport, prio:medium

#8500 Support SciPy 1.13 and 1.14
  .github/workflows/pretest.yml
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda-doctest.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/install.rst
  setup.py
Labels: cat:test, to-be-backported, blocking, prio:high

#8551 [v13] Skip sparse.linalg.{cg, cgs, gmres} tests for scipy>=1.14
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:numpy-compat, prio:high

#8554 [v13] Skip special tests for SciPy 1.14 dtype rule changes
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:test, prio:high

#8556 [v13] Skip `cupy.scipy.stats.entropy` tessts for SciPy 1.14 dtype rule change
  tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py
Labels: cat:test, prio:medium

#8567 Use `setuptools==73.0.1`
  .github/workflows/pretest.yml
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/windows/test.ps1
  .readthedocs.yaml
  docs/requirements.txt
Labels: cat:test, to-be-backported, prio:high

#8569 [backport] Use `setuptools==73.0.1`
  .github/workflows/pretest.yml
  .pfnci/generate.py
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/windows/test.ps1
  .readthedocs.yaml
  docs/requirements.txt
Labels: cat:test, backport, prio:high

#8566 [backport] add nccl.broadcast 64-bit support
  cupy_backends/cuda/libs/nccl.pyx
Labels: cat:bug, backport, prio:high

#8559 fixed arg order to match NumPy
  cupy/_statistics/histogram.py
Labels: no-compat, cat:numpy-compat, prio:medium

#8564 Revert CI timeout bump
  .pfnci/config.pbtxt
  .pfnci/linux/tests/actions/unittest.sh
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:medium

#8523 [v13] Skip test_homomorphic in scipy>=1.14
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:test, prio:high

#8574 Support building CuPy with setuptools 74
  .github/workflows/pretest.yml
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/_context.py
Labels: cat:bug, to-be-backported, blocking, prio:high

#8577 [backport] Support building CuPy with setuptools 74
  .github/workflows/pretest.yml
  install/cupy_builder/_command.py
  install/cupy_builder/_compiler.py
  install/cupy_builder/_context.py
Labels: cat:bug, backport, blocking, prio:high

#8573 [v13] Missing backport for sparse_array.A removal
  tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Labels: cat:test, prio:high

#8555 [backport] Skip `special.logsumexp` test for empty input
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
Labels: cat:test, backport, prio:medium

#8339 add axes support in ndimage filters module
  cupyx/scipy/ndimage/_filters.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_morphology.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/signal/_bsplines.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
Labels: cat:enhancement, prio:medium
