Repository cupy/cupy, pull requests merged in 2024-05, with the labels that each got.

#8312 improve efficiency of binary morphology functions by accepting a tuple for `footprint`
  cupyx/scipy/ndimage/_filters.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:performance, prio:medium

#8311 Use f-strings in ndimage kernel generation code
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_morphology.py
Labels: prio:medium, cat:code-fix

#8313 ndimage: more efficient testing of binary morphology functions
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:test, prio:medium

#8320 cupyx: cleanup use of deprecated NumPy functionality (NumPy 2.0 compatibility)
  cupy/_manipulation/kind.py
  cupyx/scipy/_lib/_util.py
  cupyx/scipy/interpolate/_bspline.py
  cupyx/scipy/interpolate/_interpolate.py
  cupyx/scipy/interpolate/_polyint.py
  cupyx/scipy/ndimage/_interpolation.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_waveforms.py
Labels: cat:enhancement, to-be-backported, prio:medium

#8325 [backport] cupyx: cleanup use of deprecated NumPy functionality (NumPy 2.0 compatibility)
  cupy/_manipulation/kind.py
  cupyx/scipy/_lib/_util.py
  cupyx/scipy/interpolate/_bspline.py
  cupyx/scipy/interpolate/_interpolate.py
  cupyx/scipy/interpolate/_polyint.py
  cupyx/scipy/ndimage/_interpolation.py
  cupyx/scipy/ndimage/_util.py
  cupyx/scipy/signal/_iir_filter_conversions.py
  cupyx/scipy/signal/_waveforms.py
Labels: cat:enhancement, backport, prio:medium

#8220 Add NearestNDInterpolator to cupyx.scipy.interpolate
  cupyx/scipy/interpolate/__init__.py
  cupyx/scipy/interpolate/_ndgriddata.py
  docs/source/reference/scipy_interpolate.rst
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_ndgriddata.py
Labels: cat:feature, prio:medium

#8341 Bump version in main branch for v14 development
  cupy/_version.py
Labels: cat:install, prio:high

#8333 MAINT: fft, linalg: add __all__ lists
  cupy/fft/__init__.py
  cupy/linalg/__init__.py
Labels: cat:enhancement, prio:medium

#8324 Add wright_bessel function to special
  cupy/_core/include/cupy/special/binom.h
  cupy/_core/include/cupy/special/cephes/chbevl.h
  cupy/_core/include/cupy/special/cephes/const.h
  cupy/_core/include/cupy/special/cephes/gamma.h
  cupy/_core/include/cupy/special/cephes/lanczos.h
  cupy/_core/include/cupy/special/cephes/rgamma.h
  cupy/_core/include/cupy/special/cephes/trig.h
  cupy/_core/include/cupy/special/cephes/zeta.h
  cupy/_core/include/cupy/special/config.h
  cupy/_core/include/cupy/special/digamma.h
  cupy/_core/include/cupy/special/error.h
  cupy/_core/include/cupy/special/lambertw.h
  cupy/_core/include/cupy/special/loggamma.h
  cupy/_core/include/cupy/special/trig.h
  cupy/_core/include/cupy/special/wright_bessel.h
  cupyx/scipy/special/__init__.py
  cupyx/scipy/special/_wright_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_wright_bessel.py
Labels: cat:enhancement, prio:medium

#8329 Add batched solve_triangular
  cupy_backends/cuda/libs/cublas.pxd
  cupy_backends/cuda/libs/cublas.pyx
  cupy_backends/hip/cupy_hipblas.h
  cupy_backends/stub/cupy_cublas.h
  cupyx/scipy/linalg/_solve_triangular.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: cat:feature, prio:medium
