Repository cupy/cupy, pull requests merged in 2024-12, with the labels that each got.

#8787 [backport] Fix race during SoftLink initialization
  cupy_backends/cuda/api/_driver_extern.pxi
  cupy_backends/cuda/api/_runtime_softlink.pxi
  cupy_backends/cuda/libs/_cnvrtc.pxi
Labels: cat:bug, backport, blocking, prio:high

#8783 fix nanargmin and nanargmax's parameter order and pass optional parameters
  cupy/_sorting/search.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, to-be-backported, prio:high

#8791 [backport] fix nanargmin and nanargmax's parameter order and pass optional parameters
  cupy/_sorting/search.py
  tests/cupy_tests/sorting_tests/test_search.py
Labels: cat:bug, backport, prio:high

#8797 Resolve uncaught type warning
  install/cupy_builder/_command.py
Labels: to-be-backported, prio:medium, cat:code-fix

#8799 [backport] [ROCm 6.2.2] Conditionally define CUDA_SUCCESS only if it's not
  cupy_backends/hip/cupy_hip_common.h
Labels: cat:enhancement, backport, prio:high

#8798 [backport] Resolve uncaught type warning
  install/cupy_builder/_command.py
Labels: backport, prio:medium, cat:code-fix

#8768 [backport] Add NumPy 2.x CI for Linux
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/testing/_loops.py
  docs/source/install.rst
  tests/cupy_tests/core_tests/fusion_tests/test_array.py
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
  tests/cupy_tests/core_tests/test_elementwise.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
  tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
  tests/cupy_tests/core_tests/test_ndarray_indexing.py
  tests/cupy_tests/core_tests/test_ndarray_reduction.py
  tests/cupy_tests/creation_tests/test_basic.py
  tests/cupy_tests/creation_tests/test_from_data.py
  tests/cupy_tests/fft_tests/test_callback.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/functional_tests/test_vectorize.py
  tests/cupy_tests/indexing_tests/test_iterate.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/linalg_tests/test_product.py
  tests/cupy_tests/linalg_tests/test_solve.py
  tests/cupy_tests/logic_tests/test_truth.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/manipulation_tests/test_join.py
  tests/cupy_tests/manipulation_tests/test_shape.py
  tests/cupy_tests/math_tests/test_arithmetic.py
  tests/cupy_tests/math_tests/test_misc.py
  tests/cupy_tests/math_tests/test_rounding.py
  tests/cupy_tests/math_tests/test_sumprod.py
  tests/cupy_tests/polynomial_tests/test_polynomial.py
  tests/cupy_tests/sorting_tests/test_sort.py
  tests/cupy_tests/statistics_tests/test_histogram.py
  tests/cupy_tests/test_init.py
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, backport, prio:high

#8790 Fix some NumPy 2.x CI failures (cont.)
  cupy/fft/_fft.py
  cupy/lib/_routines_poly.py
  cupyx/scipy/fft/_fft.py
  cupyx/scipy/special/_gammaln.py
  tests/cupy_tests/fft_tests/test_fft.py
  tests/cupy_tests/lib_tests/test_polynomial.py
  tests/cupy_tests/manipulation_tests/test_basic.py
  tests/cupy_tests/math_tests/test_special.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
Labels: cat:test, prio:medium

#8671 Replace `flake8` with `ruff`
  .flake8.cython
  .github/workflows/scripts/backport_reminder.py
  .pre-commit-config.yaml
  .ruff.toml
  cupy/__init__.py
  cupy/_core/__init__.py
  cupy/linalg/_einsum_opt.py
  cupy/random/__init__.py
  cupyx/distributed/array/_linalg.py
  cupyx/scipy/fft/_realtransforms.py
  cupyx/scipy/interpolate/_ndgriddata.py
  cupyx/scipy/ndimage/_measurements.py
  cupyx/scipy/ndimage/_spline_kernel_weights.py
  cupyx/scipy/sparse/_sputils.py
  setup.cfg
  tests/cupyx_tests/jit_tests/test_raw.py
  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py
Labels: cat:test, to-be-backported, prio:medium

#8808 Fix crashes of quantile and percentile
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:bug, to-be-backported, prio:medium

#8766 Add NumPy 2.x CI for Windows
  .pfnci/config.pbtxt
  cupy/_core/_routines_math.pyx
  cupy/_functional/vectorize.py
  cupy/random/_distributions.py
  cupy/random/_generator.py
  cupyx/jit/_cuda_typerules.py
  tests/cupy_tests/random_tests/test_generator.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_polyutils.py
  tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Labels: cat:test, prio:medium

#8811 [backport] Fix crashes of quantile and percentile
  cupy/_statistics/order.py
  tests/cupy_tests/statistics_tests/test_order.py
Labels: cat:bug, backport, prio:medium

#8810 Switch from `.A` attribute to `.todense()` method
  cupyx/scipy/sparse/linalg/_norm.py
Labels: to-be-backported, prio:medium, cat:code-fix

#8809 Set `numpy._set_promotion_state("weak")` only for test with NumPy 1.x
  tests/conftest.py
Labels: cat:test, prio:high

#8814 [backport] Switch from `.A` attribute to `.todense()` method
  cupyx/scipy/sparse/linalg/_norm.py
Labels: backport, prio:medium, cat:code-fix

#8813 Add `cupy/_core/numpy_allocator.h` to `.gitignore`
  .gitignore
Labels: prio:medium, cat:code-fix

#8816 Remove fallback mode
  cupyx/_ufunc_config.py
  cupyx/fallback_mode/__init__.py
  cupyx/fallback_mode/fallback.py
  cupyx/fallback_mode/notification.py
  tests/cupyx_tests/fallback_mode_tests/__init__.py
  tests/cupyx_tests/fallback_mode_tests/test_fallback.py
  tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Labels: cat:enhancement, no-compat, blocking, prio:high

#8817 Skip some tests incompatible with NumPy 2.2
  cupy/_manipulation/add_remove.py
  cupy/polynomial/polyutils.py
  tests/cupy_tests/manipulation_tests/test_add_remove.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#8830 [backport] Skip some tests incompatible with NumPy 2.2
  tests/cupy_tests/manipulation_tests/test_add_remove.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: backport, cat:numpy-compat, prio:high

#8832 CI: support "skip-ci" label
  .github/workflows/flexci.yml
Labels: cat:test, skip-ci

#8841 [backport] CI: support "skip-ci" label
  .github/workflows/flexci.yml
Labels: cat:test, backport, skip-ci

#8840 CI: Fix FlexCI compatibility
  .github/workflows/scripts/flexci_dispatcher.py
Labels: cat:test, to-be-backported

#8838 Update `pre-commit` hooks
  .pre-commit-config.yaml
Labels: cat:other, to-be-backported, skip-ci

#8842 [backport] CI: Fix FlexCI compatibility
  .github/workflows/scripts/flexci_dispatcher.py
Labels: cat:test, backport, skip-ci

#8815 Add NumPy 2.2 to CI
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:high

#8839 Fix `cupy.cov`
  cupy/_statistics/correlation.py
  tests/cupy_tests/statistics_tests/test_correlation.py
Labels: cat:numpy-compat, prio:medium

#8845 Fix handling of pinned memory
  cupy/_core/core.pyx
  cupy/cuda/pinned_memory.pyx
Labels: cat:bug, to-be-backported, prio:high

#8852 [backport] Fix handling of pinned memory
  cupy/_core/core.pyx
  cupy/cuda/pinned_memory.pyx
Labels: cat:bug, backport, prio:high
