Repository cupy/cupy, pull requests merged in 2025-10, with the labels that each got.

#9383 feat(JIT) Remove CCCL includes dir
  cupy/_core/core.pyx
Labels: cat:enhancement, prio:medium

#9409 Fix return dtype of csr_matrix minmax with scalar
  cupyx/scipy/sparse/_csr.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Labels: cat:numpy-compat

#9406 Drop support of CUDA 11.x and NumPy v1.x
  .pfnci/README.md
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda112.multi.sh
  .pfnci/linux/tests/cuda112.sh
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda113.multi.sh
  .pfnci/linux/tests/cuda113.sh
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda114.multi.sh
  .pfnci/linux/tests/cuda114.sh
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda115.multi.sh
  .pfnci/linux/tests/cuda115.sh
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda116.multi.sh
  .pfnci/linux/tests/cuda116.sh
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda117.multi.sh
  .pfnci/linux/tests/cuda117.sh
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda118.multi.sh
  .pfnci/linux/tests/cuda118.sh
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/linux/tests/rocm-6-2.Dockerfile
  .pfnci/linux/tests/rocm-6-4.Dockerfile
  .pfnci/linux/tests/rocm-7-0.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  README.md
  docs/source/install.rst
Labels: cat:enhancement, no-compat, prio:high

#9398 Enable rocm7
  cupy/_core/_routines_linalg.pyx
  cupy/_core/include/cupy/carray.cuh
  cupy/_core/raw.pyx
  cupy/fft/_callback.pyx
  cupy_backends/cuda/libs/_cnvrtc.pxi
  cupy_backends/hip/cupy_hipblas.h
  cupyx/scipy/interpolate/_bspline.py
  cupyx/scipy/interpolate/_interpolate.py
  cupyx/scipy/ndimage/_filters_core.py
  cupyx/scipy/ndimage/_filters_generic.py
  cupyx/scipy/ndimage/_pba_2d.py
  cupyx/scipy/ndimage/_pba_3d.py
  cupyx/scipy/signal/_bsplines.py
  cupyx/scipy/signal/_fir_filter_design.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_peak_finding.py
  cupyx/scipy/signal/_spectral_impl.py
  cupyx/scipy/signal/_splines.py
  cupyx/scipy/signal/_upfirdn.py
  cupyx/scipy/signal/_waveforms.py
  cupyx/scipy/signal/_wavelets.py
  cupyx/scipy/sparse/_compressed.py
  examples/custom_struct/complex_struct.py
  examples/custom_struct/packed_matrix.py
  tests/cupy_tests/core_tests/test_core.py
  tests/cupy_tests/core_tests/test_function.py
  tests/cupy_tests/functional_tests/test_vectorize.py
Labels: cat:enhancement, prio:high
