Repository cupy/cupy, pull requests merged in 2025-03, with the labels that each got.

#9007 [v13] API: Revert toDlpack() default to the old unversioned one
  cupy/_core/dlpack.pyx
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:bug, prio:high

#9011 [v13.4.1] API: Revert toDlpack() default to the old unversioned one
  cupy/_core/dlpack.pyx
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:bug, backport, prio:high

#9012 [v13] BUG: Hot fix for numpy 2 support in some fusion paths
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
Labels: cat:bug, blocking, prio:high

#9013 TST: Add test for fusion path with constant and scalar
  tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
Labels: cat:test, prio:medium

#9001 [backport] JIT: Support empty return
  cupyx/jit/_compile.py
  tests/cupyx_tests/jit_tests/test_raw.py
Labels: cat:bug, backport, prio:medium

#9022 Fix rocThrust build for ROCm 6.3
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
Labels: cat:enhancement, to-be-backported

#9016 [v13.4.1] BUG: Hot fix for numpy 2 support in some fusion paths
  cupy/_core/fusion.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
Labels: cat:bug, backport, blocking, prio:high

#9023 [backport] Fix rocThrust build for ROCm 6.3
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
Labels: cat:enhancement, backport

#8977 Fix `cupyx.scipy.stats.zscore` for SciPy 1.15
  cupyx/scipy/stats/_stats_py.py
  tests/cupyx_tests/scipy_tests/stats_tests/test_stats.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#8954 ndimage: fix bug in morphology `axes` support when `structure=None`
  cupyx/scipy/ndimage/_morphology.py
  tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
Labels: cat:bug, to-be-backported, prio:high

#9033 [backport] Support system allocated memory
  cupy/_core/_dtype.pxd
  cupy/_core/_dtype.pyx
  cupy/_core/_routines_manipulation.pyx
  cupy/_core/_scalar.pyx
  cupy/_core/core.pxd
  cupy/_core/core.pyx
  cupy/_core/internal.pxd
  cupy/_core/internal.pyx
  cupy/_core/numpy_allocator.pyx
  cupy/cuda/memory.pxd
  cupy/cuda/memory.pyx
  cupy_backends/cuda/api/_runtime_enum.pxd
  cupyx/fallback_mode/fallback.py
  docs/source/user_guide/memory.rst
  install/cupy_builder/_features.py
  install/cupy_builder/cupy_setup_build.py
  tests/conftest.py
  tests/cupy_tests/creation_tests/test_from_data.py
  tests/cupy_tests/test_numpy_interop.py
  tests/cupyx_tests/tools_tests/test_install_library.py
Labels: cat:feature, backport, prio:high

#9030 Allow discovering cuTENSOR using major version
  cupy/_environment.py
  cupyx/tools/_generate_wheel_metadata.py
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:high

#9038 CI: Pin setuptools version on Windows
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:high

#9039 [backport] CI: Pin setuptools version on Windows
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#9037 [backport] Allow discovering cuTENSOR using major version
  cupy/_environment.py
  cupyx/tools/_generate_wheel_metadata.py
  cupyx/tools/install_library.py
Labels: cat:enhancement, backport, prio:high

#9034 Fix compilation error of cupy.inf in fusion2
  cupy/_core/_fusion_variable.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Labels: cat:bug, to-be-backported, prio:high

#9043 [backport] Fix compilation error of cupy.inf in fusion2
  cupy/_core/_fusion_variable.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Labels: cat:bug, to-be-backported, backport, prio:high

#9047 [v13.4.1] CI: Pin setuptools version on Windows
  .pfnci/windows/test.ps1
Labels: cat:test, backport, prio:high

#9044 [v13.4.1] Fix compilation error of cupy.inf in fusion2
  cupy/_core/_fusion_variable.pyx
  tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Labels: cat:bug, backport, prio:high

#9051 Bump version to v13.4.1
  cupy/_version.py
Labels: cat:other, blocking

#9052 Bump to v13.4.1 in Dockerfile
  docker/python3/Dockerfile
Labels: cat:install, blocking

#9053 Support FIPS enabled machines with MD5 hashing
  cupy/fft/_callback.pyx
  cupy/random/_generator.py
Labels: cat:enhancement, to-be-backported, prio:high

#9050 Revert "CI: Pin setuptools version on Windows"
  .pfnci/windows/test.ps1
Labels: cat:test, to-be-backported, prio:low

#9056 [backport] Revert "CI: Pin setuptools version on Windows"
  .pfnci/windows/test.ps1
Labels: cat:test, backport, skip-ci, prio:low

#9045 Update cutensornet accelerator based on cuquantum-python 25.03 deprecation
  cupy/linalg/_einsum_cutn.py
Labels: cat:enhancement, to-be-backported, prio:high

#9058 [backport] Update cutensornet accelerator based on cuquantum-python 25.03 deprecation
  cupy/linalg/_einsum_cutn.py
Labels: cat:enhancement, backport, prio:high

#9054 [backport] Fix get_typename to emit thrust::complex
  cupy/_core/_scalar.pyx
  cupyx/scipy/interpolate/_bspline.py
  cupyx/scipy/interpolate/_interpolate.py
  cupyx/scipy/signal/_iir_utils.py
  cupyx/scipy/signal/_peak_finding.py
  cupyx/scipy/signal/_waveforms.py
  cupyx/signal/_filtering/_filtering.py
Labels: backport, prio:medium, cat:code-fix

#9024 [backport] Fix `cupyx.scipy.stats.zscore` for SciPy 1.15
  tests/cupyx_tests/scipy_tests/stats_tests/test_stats.py
Labels: backport, cat:numpy-compat, prio:high

#8908 Update cupyx.scipy.special functions for SciPy 1.15
  cupyx/scipy/special/_basic.py
  cupyx/scipy/special/_bessel.py
  cupyx/scipy/special/_beta.py
  cupyx/scipy/special/_gamma.py
  cupyx/scipy/special/_gammaln.py
  cupyx/scipy/special/_gammasgn.py
  cupyx/scipy/special/_logsumexp.py
  cupyx/scipy/special/_spherical_bessel.py
  cupyx/scipy/special/_zetac.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
  tests/cupyx_tests/scipy_tests/special_tests/test_binom.py
  tests/cupyx_tests/scipy_tests/special_tests/test_convex_analysis.py
  tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
  tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
  tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
  tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py
  tests/cupyx_tests/scipy_tests/special_tests/test_zeta.py
  tests/cupyx_tests/scipy_tests/special_tests/test_zetac.py
Labels: to-be-backported, cat:numpy-compat, prio:high

#9057 Refactor hashing
  cupy/cuda/compiler.py
Labels: cat:enhancement, to-be-backported, prio:medium

#8984 Mark xfails in some spline tests for SciPy 1.15
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
Labels: cat:test, to-be-backported, prio:high

#8831 Raise user warning in both `{to,from}Dlpack` & Update the Interoperability page
  cupy/_core/core.pyx
  cupy/_core/dlpack.pxd
  cupy/_core/dlpack.pyx
  docs/source/user_guide/interoperability.rst
  tests/cupy_tests/core_tests/test_dlpack.py
Labels: cat:enhancement, no-compat, to-be-backported

#8861 Support SciPy 1.15
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda128.Dockerfile
  .pfnci/linux/tests/cuda128.multi.Dockerfile
  .pfnci/linux/tests/rocm-6-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:medium

#8177 Add `apply_over_axes` API
  cupy/__init__.py
  cupy/lib/_shape_base.py
  docs/source/reference/functional.rst
  tests/cupy_tests/lib_tests/test_shape_base.py
Labels: cat:feature, prio:medium

#9060 [backport] Mark xfails in some spline tests for SciPy 1.15
  tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
Labels: cat:test, backport, prio:high

#9066 Add SciPy 1.15 CI for Windows
  .pfnci/config.pbtxt
Labels: cat:test, prio:medium

#9021 Cast points when computing Delaunay triangulation on dtype != float64
  cupyx/scipy/spatial/delaunay_2d/_tri.py
  tests/cupyx_tests/scipy_tests/spatial_tests/test_delaunay.py
Labels: cat:bug, prio:medium
