Repository cupy/cupy, pull requests merged in 2025-06, with the labels that each got.

#9165 Improve API reference list
  docs/source/_comparison_generator.py
  docs/source/reference/indexing.rst
Labels: cat:document, to-be-backported, prio:medium

#9161 `np.unique_values` may return unsorted data from NumPy 2.3
  tests/cupy_tests/manipulation_tests/test_add_remove.py
Labels: cat:test, to-be-backported, prio:medium

#9166 [v13] Bump NumPy version restriction
  pyproject.toml
Labels: cat:install, skip-ci, blocking, prio:high

#9168 [backport] Fix WARNING: Inline emphasis start-string without end-string
  cupy/_core/raw.pyx
Labels: cat:document, backport, skip-ci, prio:high

#9169 [backport] `np.sum` has numerical change in NumPy 2.3
  tests/cupy_tests/math_tests/test_sumprod.py
Labels: cat:test, backport, prio:medium

#9160 Fix `cp.empty(None)` to raise `TypeError`
  cupy/_core/internal.pyx
  tests/cupy_tests/core_tests/test_internal.py
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/creation_tests/test_basic.py
Labels: to-be-backported, cat:numpy-compat, prio:medium

#9178 CI: NumPy 2.3
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda128.Dockerfile
  .pfnci/linux/tests/cuda128.multi.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, to-be-backported, prio:high

#9136 Make rebuild faster for development
  .gitignore
  install/cupy_builder/_context.py
  install/cupy_builder/cupy_setup_build.py
Labels: cat:install, to-be-backported, prio:medium

#9196 [backport] Make rebuild faster for development
  .gitignore
  install/cupy_builder/_context.py
  install/cupy_builder/cupy_setup_build.py
Labels: cat:install, backport, prio:medium

#9202 [backport] Update pre-commit settings
  .github/workflows/pretest.yml
  .pre-commit-config.yaml
Labels: cat:test, backport, skip-ci, prio:medium

#9197 [backport] Add NumPy 2.3 + windows CI
  .pfnci/config.pbtxt
Labels: cat:test, backport, prio:high

#9201 Support loading NCCL from Pip packages
  cupy/_environment.py
  cupyx/tools/install_library.py
Labels: cat:enhancement, to-be-backported, prio:high

#9213 Add `cupy.win.cuda129` CI
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: to-be-backported, blocking, prio:high

#9215 Fix test trigger phrase for `cupy.win.cuda129` CI
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, to-be-backported, skip-ci, prio:high

#9217 [backport] Fix test trigger phrase for `cupy.win.cuda129` CI
  .pfnci/config.tags.json
  .pfnci/matrix.yaml
Labels: cat:test, backport, skip-ci, prio:high
