Repository cupy/cupy, pull requests merged in 2025-07, with the labels that each got.

#8468 Add short cut for subsetting along the minor axis
  cupyx/scipy/sparse/_compressed.py
Labels: cat:performance, prio:medium

#9222 [backport] Fix buffer protocol to raise TypeError when it is not meant to be supported
  cupy/_core/core.pyx
Labels: cat:bug, backport, blocking, prio:high

#9207 Update cupyx.scipy.special functions for SciPy 1.16
  cupyx/scipy/special/_basic.py
  cupyx/scipy/special/_beta.py
  cupyx/scipy/special/_erf.py
  cupyx/scipy/special/_stats_distributions.py
  cupyx/scipy/special/_xlogy.py
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
  tests/cupyx_tests/scipy_tests/special_tests/test_erf.py
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:enhancement, to-be-backported, prio:high

#9231 [backport] Fix `long_description` missing after `pyproject.toml` migration
  pyproject.toml
  setup.py
Labels: cat:install, backport, skip-ci, blocking, prio:high

#8983 Fix illegal memory access in LinearNDInterpolator
  cupyx/scipy/spatial/delaunay_2d/_kernels.py
Labels: cat:bug, to-be-backported, prio:high

#9225 [v13] Bump verison in Dockerfile to v13.5.1
  docker/python3/Dockerfile
Labels: cat:install, skip-ci, blocking, prio:high

#9245 [backport] Add test cases for batchwise `solve_triangular` (as xfail)
  tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
Labels: cat:test, backport, prio:medium

#9246 [backport] Update cupyx.scipy.special functions for SciPy 1.16
  tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
  tests/cupyx_tests/scipy_tests/special_tests/test_erf.py
  tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Labels: cat:enhancement, backport, prio:high

#9244 Relax tolerance of test_hilbert
  tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
Labels: cat:test, to-be-backported, prio:medium

#9242 Skip some signal q dtype tests
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, to-be-backported, prio:medium

#9243 Fix freqz for complex w
  cupyx/scipy/signal/_filter_design.py
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
Labels: to-be-backported, cat:numpy-compat, prio:medium

#9256 [backport] Skip some signal q dtype tests
  tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Labels: cat:test, backport, prio:medium

#9259 [backport] Fix freqz for complex w
  tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
Labels: backport, cat:numpy-compat, prio:medium

#9261 [backport] Increase CPU memory limit of `linux.cuda{128,129}` CIs
  .pfnci/config.pbtxt
Labels: cat:test, backport, prio:medium

#9253 Add `cupy.bool`, `cupy.long` and `cupy.ulong`
  cupy/__init__.py
Labels: cat:feature, prio:medium

#9240 feat: make `cupy.nan_to_num` broadcast `nan`, `posinf`, and `neginf` kwargs
  cupy/_math/misc.py
  tests/cupy_tests/math_tests/test_misc.py
Labels: cat:numpy-compat, prio:medium

#9265 Support SciPy 1.16 on Windows
  .pfnci/config.pbtxt
Labels: cat:test, to-be-backported, prio:medium

#9273 Fix lsmr type promotion rule for complex dtype
  cupyx/scipy/sparse/linalg/_solve.py
  tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Labels: cat:bug, to-be-backported, prio:high
