Repository cupy/cupy, pull requests merged in 2025-09, with the labels that each got.

#9336 Lazy load the testing module
  cupy/__init__.py
Labels: cat:performance, prio:medium

#9369 Fix syntax error in CI workflow
  .github/workflows/flexci.yml
Labels: cat:test, prio:high

#8860 Fix handling of ROCm self-hosted CIs
  .github/workflows/flexci.yml
  .github/workflows/self-hosted-ci.yml
Labels: cat:test, skip-ci, prio:medium

#9377 Build against `cuda-bindings` 12.x
  .pfnci/config.pbtxt
  .pfnci/config.tags.json
  .pfnci/coverage.rst
  .pfnci/linux/tests/cuda12x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda12x-cuda-python.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy_backends/cuda/api/_runtime_extern.pxi
  cupy_backends/cuda/api/runtime.pyx
Labels: cat:enhancement, prio:high

#9340 Dev/gpinkert/add cuda array interface
  cupy/_core/core.pyx
  tests/cupy_tests/core_tests/test_ndarray.py
  tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
  tests/cupy_tests/creation_tests/test_from_data.py
Labels: cat:enhancement, prio:medium

#9380 feat(CI) ROCm 6.4.3
  .github/workflows/self-hosted-ci.yml
  .pfnci/coverage.rst
  .pfnci/linux/tests/rocm-6-4.Dockerfile
  .pfnci/linux/tests/rocm-6-4.sh
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
Labels: cat:test, skip-ci, prio:medium

#9382 feat(kernels) fix HIPRTC build error ROCm 6/7
  cupyx/scipy/signal/windows/_windows.py
  cupyx/signal/_acoustics/_cepstrum.py
Labels: cat:enhancement, prio:medium

#9385 [backport] Update conda-build support for conda CUDA 13 packages
  install/cupy_builder/cupy_setup_build.py
  install/cupy_builder/install_build.py
Labels: cat:install, backport, skip-ci, prio:high

#9399 Fix cuTENSOR workspace size query
  cupy_backends/cuda/libs/cutensor.pxd
  cupy_backends/cuda/libs/cutensor.pyx
  cupy_backends/stub/cupy_cutensor.h
  cupyx/cutensor.pyx
Labels: cat:performance

#9384 feat(hipCUB) Use c++17 for hipCUB
  cupy/_core/_cub_reduction.pyx
Labels: cat:enhancement, to-be-backported, prio:medium
