Repository cupy/cupy, pull requests merged in 2025-05, with the labels that each got.

#9114 ENH: cupyx/signal: add freqz_sos, a preferred alias for sosfreqz
  cupyx/scipy/signal/__init__.py
  cupyx/scipy/signal/_filter_design.py
  docs/source/reference/scipy_signal.rst
Labels: cat:numpy-compat, prio:high

#9117 BUG: cupyx.scipy.signal: make gammatone return arrays
  cupyx/scipy/signal/_filter_design.py
Labels: cat:bug, to-be-backported, prio:high

#9131 Support Cython 3.1
  .pfnci/coverage.rst
  .pfnci/linux/tests/actions/build.sh
  .pfnci/linux/tests/benchmark.Dockerfile
  .pfnci/linux/tests/benchmark.head.Dockerfile
  .pfnci/linux/tests/cuda-example.Dockerfile
  .pfnci/linux/tests/cuda-head.Dockerfile
  .pfnci/linux/tests/cuda-slow.Dockerfile
  .pfnci/linux/tests/cuda112.Dockerfile
  .pfnci/linux/tests/cuda112.multi.Dockerfile
  .pfnci/linux/tests/cuda113.Dockerfile
  .pfnci/linux/tests/cuda113.multi.Dockerfile
  .pfnci/linux/tests/cuda114.Dockerfile
  .pfnci/linux/tests/cuda114.multi.Dockerfile
  .pfnci/linux/tests/cuda115.Dockerfile
  .pfnci/linux/tests/cuda115.multi.Dockerfile
  .pfnci/linux/tests/cuda116.Dockerfile
  .pfnci/linux/tests/cuda116.multi.Dockerfile
  .pfnci/linux/tests/cuda117.Dockerfile
  .pfnci/linux/tests/cuda117.multi.Dockerfile
  .pfnci/linux/tests/cuda118.Dockerfile
  .pfnci/linux/tests/cuda118.multi.Dockerfile
  .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
  .pfnci/linux/tests/cuda120.Dockerfile
  .pfnci/linux/tests/cuda120.multi.Dockerfile
  .pfnci/linux/tests/cuda121.Dockerfile
  .pfnci/linux/tests/cuda121.multi.Dockerfile
  .pfnci/linux/tests/cuda122.Dockerfile
  .pfnci/linux/tests/cuda122.multi.Dockerfile
  .pfnci/linux/tests/cuda123.Dockerfile
  .pfnci/linux/tests/cuda123.multi.Dockerfile
  .pfnci/linux/tests/cuda124.Dockerfile
  .pfnci/linux/tests/cuda124.multi.Dockerfile
  .pfnci/linux/tests/cuda125.Dockerfile
  .pfnci/linux/tests/cuda125.multi.Dockerfile
  .pfnci/linux/tests/cuda126.Dockerfile
  .pfnci/linux/tests/cuda126.multi.Dockerfile
  .pfnci/linux/tests/cuda128.Dockerfile
  .pfnci/linux/tests/cuda128.multi.Dockerfile
  .pfnci/linux/tests/rocm-4-3.Dockerfile
  .pfnci/linux/tests/rocm-5-0.Dockerfile
  .pfnci/linux/tests/rocm-5-3.Dockerfile
  .pfnci/linux/tests/rocm-6-2.Dockerfile
  .pfnci/matrix.yaml
  .pfnci/schema.yaml
  cupy/_core/_accelerator.pxd
  cupy/_util.pyx
  cupy/cuda/cub.pyx
Labels: cat:bug, to-be-backported, blocking, prio:high

#9130 Fix missing items in API reference
  docs/source/reference/_deprecated.rst
  docs/source/reference/binary.rst
  docs/source/reference/creation.rst
  docs/source/reference/dtype.rst
  docs/source/reference/functional.rst
  docs/source/reference/indexing.rst
  docs/source/reference/io.rst
  docs/source/reference/linalg.rst
  docs/source/reference/logic.rst
  docs/source/reference/manipulation.rst
  docs/source/reference/math.rst
  docs/source/reference/pad.rst
  docs/source/reference/routines.rst
  docs/source/reference/scipy_linalg.rst
  docs/source/reference/scipy_special.rst
  docs/source/reference/set.rst
  docs/source/reference/sorting.rst
  docs/source/reference/statistics.rst
Labels: cat:document, prio:high

#9133 Limit Cython version to 3.0 or 3.1
  docs/source/contribution.rst
  pyproject.toml
Labels: cat:install, to-be-backported, prio:high

#8980 Implement cupy.linalg.eig / cupy.linalg.eigvals clone of PR #8854
  cupy/linalg/__init__.py
  cupy/linalg/_eigenvalue.py
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/hip/cupy_rocsolver.h
  cupy_backends/stub/cupy_cusolver.h
  cupyx/cusolver.pyx
  docs/source/reference/linalg.rst
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:feature, takeover, prio:high

#9142 BUG: fix `cupyx.scipy.linalg.expm`
  cupyx/scipy/linalg/_matfuncs.py
  tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py
Labels: cat:bug, to-be-backported, prio:high

#9146 [backport] Limit Cython version to 3.0 or 3.1
  docs/source/contribution.rst
  pyproject.toml
Labels: cat:install, backport, prio:high

#9147 Fix cuSOLVER feature/version detection for `eig` and `eigvals`
  cupy_backends/cuda/cupy_cusolver.h
  cupy_backends/cuda/libs/cusolver.pxd
  cupy_backends/cuda/libs/cusolver.pyx
  cupy_backends/stub/cupy_cusolver.h
  cupyx/cusolver.pyx
  tests/cupy_tests/linalg_tests/test_eigenvalue.py
Labels: cat:bug, blocking, prio:high
